-- Isolated security regression: workspace scope, protected admin, role changes and retries.
begin;
insert into auth.users(id,email,email_confirmed_at) values('10000000-0000-4000-8000-000000000081','scope-admin@example.test',now()),('10000000-0000-4000-8000-000000000082','scope-teacher@example.test',now());
select public.initialize_academy('scope-admin@example.test','Scope administrator');
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000081',true);
do $$ declare aid uuid;school uuid;coaching uuid;run uuid;batch uuid;teacher uuid;request uuid:=gen_random_uuid();result jsonb;role_revision int;subject uuid;room uuid;session uuid;day_value date:=(now() at time zone 'Asia/Dhaka')::date;teacher_profile uuid:='10000000-0000-4000-8000-000000000082';input jsonb;
begin
 select id into aid from public.academies;
 select id into school from public.operating_divisions where code='SCHOOL';select id into coaching from public.operating_divisions where code='COACHING';
 perform set_config('request.headers',jsonb_build_object('x-sohoj-workspace',school)::text,true);
 select id into run from public.programme_runs where division_id=coaching limit 1;
 result:=public.list_current_programmes(null,'',1);
 if exists(select 1 from jsonb_array_elements(result->'rows') r where (r->>'division_id')::uuid<>school) then raise exception 'Other workspace offerings leaked';end if;
 begin perform public.programme_run_setup(run,1);raise exception 'Other workspace detail allowed';exception when others then if sqlerrm='Other workspace detail allowed' then raise;end if;end;
 begin perform public.save_academic_plan(gen_random_uuid(),jsonb_build_object('target','RUN','id',run,'revision',1,'weekdays','[]'::jsonb,'reason','Wrong workspace fixture'));raise exception 'Other workspace write allowed';exception when insufficient_privilege then null;end;
 insert into public.people(academy_id,full_name) values(aid,'Scope teacher') returning id into teacher;
 insert into public.person_responsibilities values(teacher,aid,'TEACHER',true);
 insert into public.account_profiles(id,academy_id,display_name) values(teacher_profile,aid,'Scope teacher');
 insert into public.person_accounts values(teacher_profile,teacher,aid);
 insert into public.account_roles values(teacher_profile,'TEACHER');
 input:=jsonb_build_object('action','ACCOUNT','id',teacher_profile,'revision',1,'roles',jsonb_build_array('TEACHER'),'workspaces',jsonb_build_array(school),'active',true,'reason','Assigned teacher school workspace');
 result:=public.save_account_access(request,input);perform public.save_account_access(request,input);
 if (select access_revision from public.account_profiles where id=teacher_profile)<>2 then raise exception 'Access retry applied twice';end if;
 
 select greatest(starts_on,day_value) into day_value from public.programme_runs where id=run;
 select id into batch from public.teaching_batches where run_id=run limit 1;
 select subject_id into subject from public.run_subjects where run_id=run and is_active limit 1;
 insert into public.teacher_subject_qualifications values(aid,teacher,subject,true,1);
 insert into public.account_workspaces values(teacher_profile,coaching);
 insert into public.academic_rooms(academy_id,name,capacity) values(aid,'Scope room',100) returning id into room;
 perform set_config('request.headers',jsonb_build_object('x-sohoj-workspace',coaching)::text,true);
 result:=public.academic_command(gen_random_uuid(),jsonb_build_object('action','CREATE','batchId',batch,'subjectId',subject,'teacherId',teacher,'roomId',room,'start',(day_value+time '12:00') at time zone 'Asia/Dhaka','end',(day_value+time '13:00') at time zone 'Asia/Dhaka','confirmAvailability',true,'reason','Coaching scope session fixture'));
 session:=(result->>'id')::uuid;
 if (public.academic_session_register(1)->>'total')::int<>1 then raise exception 'Current workspace session missing';end if;
 perform set_config('request.headers',jsonb_build_object('x-sohoj-workspace',school)::text,true);
 if (public.academic_session_register(1)->>'total')::int<>0 or (public.academic_calendar(day_value::text,day_value::text,1,'')->>'total')::int<>0 then raise exception 'Other workspace sessions leaked';end if;
 begin perform public.academic_session_detail(session);raise exception 'Cross-workspace class detail allowed';exception when others then if sqlerrm='Cross-workspace class detail allowed' then raise;end if;end;
 begin perform public.academic_command(gen_random_uuid(),jsonb_build_object('action','CANCEL','id',session,'revision',1,'reason','Invalid scope cancellation fixture'));raise exception 'Cross-workspace cancellation allowed';exception when insufficient_privilege then null;end;
 delete from public.account_workspaces where profile_id=teacher_profile and division_id=coaching;
 if not exists(select 1 from public.activity_events where action='UPDATE_ACCOUNT_ACCESS' and actor_profile_id=auth.uid() and request_id=request) then raise exception 'Access actor audit missing';end if;
 begin perform public.save_account_access(gen_random_uuid(),jsonb_build_object('action','ROLE','role','ADMIN','revision',1,'permissions','[]'::jsonb,'reason','Invalid removal fixture'));raise exception 'Admin role editable';exception when others then if sqlerrm='Admin role editable' then raise;end if;end;
 select revision into role_revision from public.access_roles where code='TEACHER';
 perform public.save_account_access(gen_random_uuid(),jsonb_build_object('action','ROLE','role','TEACHER','revision',role_revision,'permissions',jsonb_build_array('academics.view'),'reason','Teacher viewing only fixture'));
 perform set_config('request.jwt.claim.sub',teacher_profile::text,true);
 result:=public.academy_account_context();if jsonb_array_length(result->'divisions')<>1 or result->'divisions'->0->>'id'<>school::text then raise exception 'Unassigned workspace in switcher';end if;
 if public.can_operate('academics.teach') then raise exception 'Removed teacher action remains allowed';end if;
 begin perform public.save_academic_session_work(gen_random_uuid(),jsonb_build_object('action','DRAFT','id',session));raise exception 'Removed report action allowed';exception when insufficient_privilege then null;end;
 begin perform public.account_access_settings('',1);raise exception 'Teacher access settings allowed';exception when insufficient_privilege then null;end;
 perform set_config('request.headers',jsonb_build_object('x-sohoj-workspace',coaching)::text,true);
 begin perform public.academic_session_register(1);raise exception 'Unassigned workspace selectable';exception when insufficient_privilege then null;end;
 perform set_config('request.headers',jsonb_build_object('x-sohoj-workspace',school)::text,true);
 if has_function_privilege('authenticated','public.academy_unscoped_command(uuid,jsonb)','EXECUTE') or has_table_privilege('authenticated','public.workspace_sessions','SELECT') or has_table_privilege('authenticated','public.account_workspaces','INSERT') then raise exception 'Internal scope bypass exposed';end if;
end $$;
rollback;
