begin;
insert into auth.users(id,email,email_confirmed_at) values('10000000-0000-4000-8000-000000000091','admission-admin@example.test',now());
select public.initialize_academy('admission-admin@example.test','Admission administrator');
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000091',true);
do $$declare aid uuid;workspace uuid;run uuid;batch uuid;relationship uuid;draft uuid;invoice uuid;receipt uuid;request uuid;payload jsonb;result jsonb;before_count int;day_value date:=(now() at time zone 'Asia/Dhaka')::date;
begin
 select id into aid from public.academies;select id into workspace from public.operating_divisions where code='COACHING';
 perform set_config('request.headers',jsonb_build_object('x-sohoj-workspace',workspace)::text,true);
 select id into run from public.programme_runs where division_id=workspace limit 1;select id into batch from public.teaching_batches where run_id=run limit 1;
 update public.programme_runs set starts_on=day_value,ends_on=day_value+365 where id=run;
 select id into relationship from public.directory_entries where kind='RELATIONSHIP' limit 1;
 select count(*) into before_count from public.enquiries;
 result:=public.save_admission_draft(gen_random_uuid(),jsonb_build_object('runId',run,'batchId',batch,'details',jsonb_build_object('studentName','Admission student','dateOfBirth','2015-01-01','guardianName','Admission guardian','guardianMobile','01775804072','relationshipId',relationship,'enrollmentDate',day_value,'newStudentConfirmed',true,'newGuardianConfirmed',true,'sourceVerified',true),'reason','Staff assisted admission fixture'));draft:=(result->>'id')::uuid;
 if (select count(*) from public.enquiries)<>before_count then raise exception 'Direct admission fabricated enquiry';end if;
 request:=gen_random_uuid();payload:=jsonb_build_object('id',draft,'revision',1,'reviewed',true,'paperReceived',true,'reason','Reviewed application fixture');
 result:=public.finalize_admission(request,payload);invoice:=(result->>'invoiceId')::uuid;perform public.finalize_admission(request,payload);
 if (select count(*) from public.student_invoices where admission_id=draft)<>1 or (select count(*) from public.academic_batch_enrollments)<>1 then raise exception 'Confirmation retry duplicated enrollment/invoice';end if;
 if (public.admission_case(draft)->>'studentNumber') is null then raise exception 'Student ID missing';end if;
 if (public.invoice_balance(invoice)->>'due')::numeric<=0 then raise exception 'Unpaid invoice due missing';end if;
 request:=gen_random_uuid();payload:=jsonb_build_object('action','PAYMENT','admissionId',draft,'invoiceId',invoice,'amount',100,'method','CASH','receivedOn',day_value,'reason','Received part payment fixture');
 result:=public.student_billing_command(request,payload);receipt:=(result->>'id')::uuid;perform public.student_billing_command(request,payload);
 if (select count(*) from public.student_payments)<>1 then raise exception 'Payment retry duplicated receipt';end if;
 perform public.student_billing_command(gen_random_uuid(),jsonb_build_object('action','SCHOLARSHIP','admissionId',draft,'invoiceId',invoice,'amount',50,'reason','Scholarship reduction fixture'));
 perform public.student_billing_command(gen_random_uuid(),jsonb_build_object('action','REFUND','admissionId',draft,'invoiceId',invoice,'paymentId',receipt,'amount',20,'reason','Returned collected money fixture'));
 if (public.invoice_balance(invoice)->>'paid')::numeric<>100 or (public.invoice_balance(invoice)->>'refunded')::numeric<>20 or (public.invoice_balance(invoice)->>'reductions')::numeric<>50 then raise exception 'Payment adjustment totals incorrect';end if;
 begin perform public.student_billing_command(gen_random_uuid(),jsonb_build_object('action','PAYMENT','admissionId',draft,'invoiceId',invoice,'amount',999999,'method','CASH','receivedOn',day_value,'reason','Invalid overpayment fixture'));raise exception 'Overpayment accepted';exception when others then if sqlerrm='Overpayment accepted' then raise;end if;end;
 perform public.student_billing_command(gen_random_uuid(),jsonb_build_object('action','NEXT_INVOICE','admissionId',draft,'reason','Next monthly tuition fixture'));
 if (select count(*) from public.student_invoices where admission_id=draft)<>2 then raise exception 'Next tuition missing';end if;
 select id into workspace from public.operating_divisions where code='SCHOOL';perform set_config('request.headers',jsonb_build_object('x-sohoj-workspace',workspace)::text,true);
 begin perform public.admission_billing(draft);raise exception 'Cross workspace billing leaked';exception when others then if sqlerrm='Cross workspace billing leaked' then raise;end if;end;
 if has_table_privilege('authenticated','public.student_payments','INSERT') or has_function_privilege('authenticated','public.invoice_balance(uuid)','EXECUTE') then raise exception 'Financial bypass exposed';end if;
end $$;
rollback;
