begin;
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values('96000000-0000-0000-0000-000000000001','credit-admin@example.test',now(),'{"full_name":"Credit Admin"}');select public.bootstrap_admin('credit-admin@example.test','Credit Admin');select set_config('request.jwt.claim.sub','96000000-0000-0000-0000-000000000001',true);
do $test$ declare vendor uuid;category uuid;cash uuid;purchase uuid;adjustment uuid;payload jsonb;e public.finance_expenses;rejected boolean:=false;begin
 vendor:=(public.purchase_command(jsonb_build_object('action','CREATE_VENDOR','request_id',gen_random_uuid(),'name','Credit Supplier','reason','Verified credit note supplier'))->>'id')::uuid;select id into category from public.finance_expense_categories where is_active limit 1;select id into cash from public.finance_accounts where account_subtype='CASH' and is_active limit 1;
 purchase:=(public.purchase_command(jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'vendor_id',vendor,'category_id',category,'description','Credit fixture purchase','items',jsonb_build_array(jsonb_build_object('name','Supplies','quantity',3,'price',125)),'reason','Preparing credited purchase'))->>'id')::uuid;
 perform public.purchase_command(jsonb_build_object('action','RECEIVE','request_id',gen_random_uuid(),'id',purchase,'revision',1,'received_on',current_date,'invoice_reference','ORIG-01','confirmed_received',true,'payment_mode','ON_ACCOUNT','reason','Verified full goods receipt'));
 perform public.purchase_command(jsonb_build_object('action','PAY','request_id',gen_random_uuid(),'id',purchase,'revision',2,'amount',100,'payment_account_id',cash,'external_reference','PAID-01','reason','Partial supplier payment made'));
 payload:=jsonb_build_object('action','ADJUST','request_id',gen_random_uuid(),'purchase_id',purchase,'kind','RETURN','confirmed',true,'amount',300,'cash_refund',0,'date',current_date,'reference','CREDIT-01','reason','Goods returned and credit verified');adjustment:=(public.purchase_adjustment_command(payload)->>'id')::uuid;perform public.purchase_adjustment_command(payload);
 if (select payable_credit from public.purchase_adjustments where id=adjustment)<>275 or (select refund_due from public.purchase_adjustments where id=adjustment)<>25 then raise exception 'Credit/refund split incorrect.';end if;
 select * into e from public.finance_expenses where id=(select expense_id from public.finance_purchases where id=purchase);if e.amount<>375 then raise exception 'Original expense rewritten.';end if;
 if (select sum(amount) from public.finance_payable_settlements where payable_id=e.payable_id and settlement_kind='PAYMENT')<>100 then raise exception 'Credit was labelled cash payment.';end if;
 payload:=jsonb_build_object('action','COLLECT_REFUND','request_id',gen_random_uuid(),'adjustment_id',adjustment,'amount',20,'date',current_date,'payment_account_id',cash,'reference','REFUND-01','reason','Actually received supplier refund');perform public.purchase_adjustment_command(payload);perform public.purchase_adjustment_command(payload);
 if (select sum(amount) from public.purchase_refund_receipts where adjustment_id=adjustment)<>20 then raise exception 'Refund retry duplicated.';end if;
 payload:=jsonb_set(payload,'{request_id}',to_jsonb(gen_random_uuid()));payload:=jsonb_set(payload,'{amount}','6');begin perform public.purchase_adjustment_command(payload);exception when others then rejected:=true;end;if not rejected then raise exception 'Excess supplier refund accepted.';end if;
end $test$;rollback;
