begin;
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values('97000000-0000-0000-0000-000000000001','claim-admin@example.test',now(),'{"full_name":"Claim Admin"}'),('97000000-0000-0000-0000-000000000002','claim-teacher@example.test',now(),'{"full_name":"Claim Teacher"}');select public.bootstrap_admin('claim-admin@example.test','Claim Admin');
select set_config('request.jwt.claim.sub','',true);select public.request_staff_access('{"full_name":"Claim Teacher","email":"claim-teacher@example.test","mobile":"01712345688","requested_role":"TEACHER","purpose":"Teach assigned classes"}');select set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000001',true);
do $test$ declare id_value uuid;begin select id into id_value from public.staff_access_requests where email='claim-teacher@example.test';perform public.review_staff_access(jsonb_build_object('id',id_value,'action','VERIFY','assigned_role','TEACHER','reason','Verified teacher identity'));perform public.review_staff_access(jsonb_build_object('id',id_value,'action','COMPLETE_INVITATION','reason','Account setup completed'));end $test$;
select set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000002',true);
do $test$ declare category uuid;claim uuid;payload jsonb;doc uuid:=gen_random_uuid();prepared jsonb;rejected boolean:=false;begin
 select id into category from public.finance_expense_categories where is_active limit 1;
 payload:=jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'category_id',category,'expense_date',current_date,'amount',200,'description','Teaching supplies personally paid','receipt_reference','TEACHER-001','reason','Claim for personal classroom spend');claim:=(public.reimbursement_command(payload)->>'id')::uuid;
 payload:=jsonb_build_object('action','SUBMIT','request_id',gen_random_uuid(),'id',claim,'revision',1,'own_funds',true,'reason','Confirmed personal funds spent');begin perform public.reimbursement_command(payload);exception when others then rejected:=true;end;if not rejected then raise exception 'Claim submitted without evidence.';end if;
 prepared:=public.finance_document_prepare(jsonb_build_object('request_id',doc,'entity_type','REIMBURSEMENT','entity_id',claim,'original_name','receipt.pdf','mime_type','application/pdf','byte_size',100,'sha256',repeat('b',64),'note','Receipt for personal expense'));insert into storage.objects(bucket_id,name,metadata) values('finance-evidence',prepared->>'path','{"size":100,"mimetype":"application/pdf"}');perform public.finance_document_complete(doc);perform public.reimbursement_command(payload);
 rejected:=false;begin perform public.reimbursement_command(jsonb_build_object('action','POST','request_id',gen_random_uuid(),'id',claim,'revision',2,'reason','Teacher attempts self posting'));exception when others then rejected:=true;end;if not rejected then raise exception 'Teacher self posting allowed.';end if;
end $test$;
select set_config('request.jwt.claim.sub','97000000-0000-0000-0000-000000000001',true);
do $test$ declare claim uuid;cash uuid;payload jsonb;begin select id into claim from public.staff_reimbursements where receipt_reference='TEACHER-001';select id into cash from public.finance_accounts where account_subtype='CASH' and is_active limit 1;
 payload:=jsonb_build_object('action','POST','request_id',gen_random_uuid(),'id',claim,'revision',2,'reason','Verified receipt and beneficiary');perform public.reimbursement_command(payload);perform public.reimbursement_command(payload);
 payload:=jsonb_build_object('action','PAY','request_id',gen_random_uuid(),'id',claim,'revision',3,'amount',75,'payment_account_id',cash,'reference','CLAIM-PAY-001','reason','Reimbursed actual personal expense');perform public.reimbursement_command(payload);perform public.reimbursement_command(payload);
 if (select (r->>'remaining')::numeric from jsonb_array_elements(public.reimbursement_workspace()->'rows')r where r->>'id'=claim::text)<>125 then raise exception 'Claim payment balance incorrect.';end if;
end $test$;rollback;
