begin;
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values('98000000-0000-0000-0000-000000000001','asset-admin@example.test',now(),'{"full_name":"Asset Admin"}'),('98000000-0000-0000-0000-000000000002','asset-teacher@example.test',now(),'{"full_name":"Asset Teacher"}');select public.bootstrap_admin('asset-admin@example.test','Asset Admin');select set_config('request.jwt.claim.sub','',true);select public.request_staff_access('{"full_name":"Asset Teacher","email":"asset-teacher@example.test","mobile":"01712345689","requested_role":"TEACHER","purpose":"Teach assigned classes"}');select set_config('request.jwt.claim.sub','98000000-0000-0000-0000-000000000001',true);
do $test$ declare id_value uuid;begin select id into id_value from public.staff_access_requests where email='asset-teacher@example.test';perform public.review_staff_access(jsonb_build_object('id',id_value,'action','VERIFY','assigned_role','TEACHER','reason','Verified teacher identity'));perform public.review_staff_access(jsonb_build_object('id',id_value,'action','COMPLETE_INVITATION','reason','Account setup completed'));end $test$;
do $test$ declare vendor uuid;account uuid;cash uuid;sid uuid;asset uuid;payload jsonb;month_value date:=(date_trunc('month',now() at time zone 'Asia/Dhaka')-interval '1 month')::date;rejected boolean:=false;begin
 vendor:=(public.purchase_command(jsonb_build_object('action','CREATE_VENDOR','request_id',gen_random_uuid(),'name','Asset Supplier','reason','Verified equipment supplier'))->>'id')::uuid;select id into account from public.finance_accounts where account_subtype='FIXED_ASSET' and is_active limit 1;select id into cash from public.finance_accounts where account_subtype='CASH' and is_active limit 1;select id into sid from public.staff where profile_id='98000000-0000-0000-0000-000000000002';
 payload:=jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'name','Classroom projector','location','Room A','vendor_id',vendor,'asset_account_id',account,'cost',1200,'residual',0,'life_months',12,'acquired_on',month_value,'in_service_on',month_value,'depreciation_start',month_value,'invoice_reference','ASSET-INV-001','reason','Prepared verified projector acquisition');asset:=(public.asset_command(payload)->>'id')::uuid;
 payload:=jsonb_build_object('action','ACQUIRE','request_id',gen_random_uuid(),'id',asset,'revision',1,'date',month_value,'payment_mode','ON_ACCOUNT','confirmed',true,'reason','Equipment received and capitalized');perform public.asset_command(payload);perform public.asset_command(payload);
 payload:=jsonb_build_object('action','DEPRECIATE','request_id',gen_random_uuid(),'id',asset,'revision',2,'month',month_value,'reason','Post complete monthly depreciation');perform public.asset_command(payload);perform public.asset_command(payload);
 if (select sum(amount) from public.asset_depreciation_entries where asset_id=asset)<>100 then raise exception 'Depreciation incorrect or duplicated.';end if;
 perform public.asset_command(jsonb_build_object('action','TRANSFER','request_id',gen_random_uuid(),'id',asset,'revision',2,'custodian_id',sid,'location','Room A','reason','Transferred projector to teacher'));
 perform public.asset_command(jsonb_build_object('action','PAY','request_id',gen_random_uuid(),'id',asset,'revision',3,'amount',200,'payment_account_id',cash,'reference','ASSET-PAY-001','reason','Actual supplier installment paid'));
 begin update public.academy_assets set cost=1100 where id=asset;exception when others then rejected:=true;end;if not rejected then raise exception 'Capitalized cost mutable.';end if;
end $test$;
select set_config('request.jwt.claim.sub','98000000-0000-0000-0000-000000000002',true);
do $test$ declare asset uuid;transfer uuid;rejected boolean:=false;begin
 if jsonb_array_length(public.asset_workspace()->'rows')<>1 then raise exception 'Own custodian asset unavailable.';end if;select id into asset from public.academy_assets where invoice_reference='ASSET-INV-001';select id into transfer from public.asset_events where asset_id=asset and action='TRANSFER';perform public.asset_command(jsonb_build_object('action','ACKNOWLEDGE','request_id',gen_random_uuid(),'id',asset,'transfer_id',transfer,'reason','Received assigned projector in good order'));
 begin perform public.asset_command(jsonb_build_object('action','MARK_INACTIVE','request_id',gen_random_uuid(),'id',asset,'revision',3,'reason','Teacher attempts lifecycle change'));exception when others then rejected:=true;end;if not rejected then raise exception 'Teacher manager action allowed.';end if;
end $test$;
select set_config('request.jwt.claim.sub','98000000-0000-0000-0000-000000000001',true);
do $test$ declare asset uuid;cash uuid;begin select id into asset from public.academy_assets where invoice_reference='ASSET-INV-001';select id into cash from public.finance_accounts where account_subtype='CASH' and is_active limit 1;
 perform public.asset_command(jsonb_build_object('action','DISPOSE','request_id',gen_random_uuid(),'id',asset,'revision',3,'date',current_date,'proceeds',1000,'payment_account_id',cash,'reference','DISP-001','confirmed',true,'reason','Disposed verified equipment and collected proceeds'));
 if (select book_value from public.asset_disposals where asset_id=asset)<>1100 then raise exception 'Disposal book value incorrect.';end if;
 if (select (r->>'remaining')::numeric from jsonb_array_elements(public.asset_workspace()->'rows')r where r->>'id'=asset::text)<>1000 then raise exception 'Disposal erased vendor payable.';end if;
end $test$;
do $test$ declare vendor uuid;category uuid;cash uuid;account uuid;purchase uuid;asset uuid;payload jsonb;month_value date:=(date_trunc('month',now() at time zone 'Asia/Dhaka')-interval '1 month')::date;rejected boolean:=false;begin
 select id into vendor from public.vendors where name='Asset Supplier';select id into category from public.finance_expense_categories where is_active limit 1;select id into cash from public.finance_accounts where account_subtype='CASH' and is_active limit 1;select id into account from public.finance_accounts where account_subtype='FIXED_ASSET' and is_active limit 1;
 purchase:=(public.purchase_command(jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'vendor_id',vendor,'category_id',category,'description','Equipment first recorded as expense','items',jsonb_build_array(jsonb_build_object('name','Equipment','quantity',1,'price',500)),'reason','Prepare equipment purchase source'))->>'id')::uuid;
 perform public.purchase_command(jsonb_build_object('action','RECEIVE','request_id',gen_random_uuid(),'id',purchase,'revision',1,'received_on',month_value,'invoice_reference','SOURCE-INV-001','confirmed_received',true,'payment_mode','PAID_NOW','payment_account_id',cash,'reason','Received equipment and paid once'));
 asset:=(public.asset_command(jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'source_purchase_id',purchase,'asset_account_id',account,'name','Reclassified equipment','location','Office','residual',0,'life_months',24,'in_service_on',month_value,'depreciation_start',(month_value+interval '1 month')::date,'invoice_reference','SOURCE-INV-001','reason','Correct equipment classification'))->>'id')::uuid;
 perform public.asset_command(jsonb_build_object('action','ACQUIRE','request_id',gen_random_uuid(),'id',asset,'revision',1,'date',month_value,'confirmed',true,'reason','Reclassified posted purchase as equipment'));
 if exists(select 1 from public.general_ledger_lines where journal_id=(select acquisition_journal_id from public.academy_assets where id=asset) and account_id=cash) then raise exception 'Source capitalization paid cash twice.';end if;
 begin perform public.purchase_adjustment_command(jsonb_build_object('action','ADJUST','request_id',gen_random_uuid(),'purchase_id',purchase,'kind','RETURN','amount',100,'date',current_date,'reference','WRONG-RETURN','confirmed',true,'reason','Attempt expense reversal after capitalization'));exception when others then rejected:=true;end;if not rejected then raise exception 'Capitalized source expense reversed twice.';end if;
 asset:=(public.asset_command(jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'vendor_id',vendor,'asset_account_id',account,'cost',0.01,'name','Tiny rounding asset','location','Office','residual',0,'life_months',3,'acquired_on',month_value,'in_service_on',month_value,'depreciation_start',month_value,'invoice_reference','TINY-INV-001','reason','Prepare rounding edge case'))->>'id')::uuid;
 perform public.asset_command(jsonb_build_object('action','ACQUIRE','request_id',gen_random_uuid(),'id',asset,'revision',1,'date',month_value,'payment_mode','ON_ACCOUNT','confirmed',true,'reason','Capitalize tiny rounding edge case'));
 perform public.asset_command(jsonb_build_object('action','DEPRECIATE','request_id',gen_random_uuid(),'id',asset,'revision',2,'month',month_value,'reason','Record zero rounded scheduled month'));
 if not exists(select 1 from public.asset_depreciation_entries where asset_id=asset and amount=0 and journal_id is null) then raise exception 'Zero rounding schedule cannot advance.';end if;
end $test$;
rollback;
