begin;
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values('99000000-0000-0000-0000-000000000001','finite-admin@example.test',now(),'{"full_name":"Finite Admin"}');select public.bootstrap_admin('finite-admin@example.test','Finite Admin');select set_config('request.jwt.claim.sub','99000000-0000-0000-0000-000000000001',true);
do $test$ declare org uuid;category uuid;sid uuid;cash uuid;equity uuid;violation text;rejected boolean:=false;begin
 select id into org from public.organizations where code='SOHOJ';select id into category from public.finance_expense_categories where is_active limit 1;select id into sid from public.staff where profile_id=auth.uid();select id into cash from public.finance_accounts where account_subtype='CASH' and is_active limit 1;select id into equity from public.finance_accounts where account_type='EQUITY' and is_active limit 1;
 if sid is null then insert into public.staff(profile_id,full_name,status,joined_on) values(auth.uid(),'Finite Admin','ACTIVE',current_date) returning id into sid;end if;
 perform public.reimbursement_command(jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'staff_id',sid,'category_id',category,'expense_date',current_date,'amount',1,'description','Valid baseline RPC amount','receipt_reference','VALID-TEST','reason','Verify authorized baseline claim'));
 begin perform public.reimbursement_command(jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'staff_id',sid,'category_id',category,'expense_date',current_date,'amount','NaN','description','Invalid direct RPC amount','receipt_reference','NAN-TEST','reason','Attempt direct nonfinite input'));exception when check_violation then get stacked diagnostics violation=constraint_name;if violation<>'reimbursement_amount_finite' then raise;end if;rejected:=true;end;if not rejected then raise exception 'NaN reimbursement accepted.';end if;
 rejected:=false;begin perform public.finance_post_journal(org,current_date,'MANUAL','FINITE_TEST',gen_random_uuid()::text,'Invalid NaN ledger',auth.uid(),jsonb_build_array(jsonb_build_object('account_id',cash,'debit','NaN','credit',0),jsonb_build_object('account_id',equity,'debit',0,'credit','NaN')));exception when check_violation then get stacked diagnostics violation=constraint_name;if violation<>'ledger_amounts_finite' then raise;end if;rejected:=true;end;if not rejected then raise exception 'NaN journal accepted.';end if;
end $test$;rollback;
