begin;
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) values('96000000-0000-0000-0000-000000000001','procurement-admin@example.test',now(),'{"full_name":"Admin"}'),('96000000-0000-0000-0000-000000000002','procurement-outsider@example.test',now(),'{"full_name":"Outsider"}');
select public.bootstrap_admin('procurement-admin@example.test','Admin');select set_config('request.jwt.claim.sub','96000000-0000-0000-0000-000000000001',true);
do $test$
declare vendor uuid;category uuid;order_value uuid;purchase uuid;payload jsonb;row_value jsonb;journals integer;rejected boolean;
begin
 vendor:=(public.purchase_command(jsonb_build_object('action','CREATE_VENDOR','request_id',gen_random_uuid(),'name','Partial Supply Fixture','reason','Verified operating supplier'))->>'id')::uuid;select id into category from public.finance_expense_categories where is_active limit 1;
 select count(*) into journals from public.general_ledger_journals;
 payload:=jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'vendor_id',vendor,'category_id',category,'description','Ten classroom markers','items',jsonb_build_array(jsonb_build_object('name','Markers','quantity',10,'price',100)),'reason','Order actual classroom consumables');order_value:=(public.procurement_command(payload)->>'id')::uuid;perform public.procurement_command(payload);
 if (select count(*) from public.general_ledger_journals)<>journals then raise exception 'Order created expense before receipt.';end if;
 payload:=jsonb_build_object('action','RECEIVE','id',order_value,'revision',1,'request_id',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('line',1,'quantity',4,'price',100)),'received_on',current_date,'invoice_reference','PART-001','invoice_total',500,'confirmed_received',true,'payment_mode','ON_ACCOUNT','reason','Verified actual partial receipt invoice');
 rejected:=false;begin perform public.procurement_command(payload);exception when others then rejected:=true;end;if not rejected or exists(select 1 from public.procurement_receipts where procurement_receipts.order_id=order_value) then raise exception 'Mismatched invoice accepted or failure left receipt.';end if;
 payload:=payload||jsonb_build_object('request_id',gen_random_uuid(),'invoice_total',400);perform public.procurement_command(payload);perform public.procurement_command(payload);
 row_value:=public.procurement_workspace()->'rows'->0;if row_value->>'status'<>'OPEN' or (row_value->'lines'->0->>'received')::numeric<>4 or (public.supplier_account_statement(vendor)->'summary'->>'payableDue')::numeric<>400 then raise exception 'Partial receipt quantities/payable wrong.';end if;
 if (select count(*) from public.procurement_receipts)<>1 or (select count(*) from public.general_ledger_journals)<>journals+1 then raise exception 'Receipt retry duplicated posting.';end if;
 rejected:=false;begin perform public.procurement_command(payload||jsonb_build_object('request_id',gen_random_uuid()));exception when others then rejected:=true;end;if not rejected then raise exception 'Stale order revision accepted.';end if;

 rejected:=false;begin perform public.procurement_command(payload||jsonb_build_object('request_id',gen_random_uuid(),'revision',2));exception when others then rejected:=true;end;if not rejected or (select count(*) from public.finance_purchases)<>1 then raise exception 'Duplicate supplier invoice accepted or failed atomic receipt left a draft.';end if;
 payload:=payload||jsonb_build_object('request_id',gen_random_uuid(),'revision',2,'items',jsonb_build_array(jsonb_build_object('line',1,'quantity',7,'price',100)),'invoice_total',700,'invoice_reference','PART-002');rejected:=false;begin perform public.procurement_command(payload);exception when others then rejected:=true;end;if not rejected then raise exception 'Over receipt accepted.';end if;
 payload:=payload||jsonb_build_object('request_id',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('line',1,'quantity',6,'price',110)),'invoice_total',660);rejected:=false;begin perform public.procurement_command(payload);exception when others then rejected:=true;end;if not rejected then raise exception 'Invoice price variance without reason accepted.';end if;
 payload:=payload||jsonb_build_object('request_id',gen_random_uuid(),'price_variance_reason','Verified changed supplier price');perform public.procurement_command(payload);
 row_value:=public.procurement_workspace(1,'ALL')->'rows'->0;if row_value->>'status'<>'COMPLETE' or (row_value->'lines'->0->>'received')::numeric<>10 or (public.supplier_account_statement(vendor)->'summary'->>'payableDue')::numeric<>1060 then raise exception 'Final matched receipt failed.';end if;
 rejected:=false;begin update public.procurement_receipts set invoice_total=1;exception when others then rejected:=true;end;if not rejected then raise exception 'Posted receipt mutated.';end if;
 payload:=jsonb_build_object('action','SAVE','request_id',gen_random_uuid(),'vendor_id',vendor,'category_id',category,'description','Close outstanding test','items',jsonb_build_array(jsonb_build_object('name','Markers','quantity',2,'price',100)),'reason','Prepare outstanding closure fixture');order_value:=(public.procurement_command(payload)->>'id')::uuid;
 perform public.procurement_command(jsonb_build_object('action','RECEIVE','id',order_value,'revision',1,'request_id',gen_random_uuid(),'items',jsonb_build_array(jsonb_build_object('line',1,'quantity',1,'price',100)),'received_on',current_date,'invoice_reference','PART-003','invoice_total',100,'confirmed_received',true,'payment_mode','ON_ACCOUNT','reason','Verified one marker receipt'));
 perform public.procurement_command(jsonb_build_object('action','CLOSE','id',order_value,'revision',2,'request_id',gen_random_uuid(),'reason','Remaining delivery cancelled with supplier'));
 if (select status from public.procurement_orders where id=order_value)<>'CLOSED' or (public.supplier_account_statement(vendor)->'summary'->>'payableDue')::numeric<>1160 then raise exception 'Closing commitment changed actual liabilities.';end if;
 if has_function_privilege('anon','public.procurement_command(jsonb)','EXECUTE') then raise exception 'Public procurement exposed.';end if;
end $test$;
select set_config('request.jwt.claim.sub','96000000-0000-0000-0000-000000000002',true);
do $test$ declare rejected boolean:=false;begin begin perform public.procurement_workspace();exception when others then rejected:=true;end;if not rejected then raise exception 'Outsider read orders.';end if;end $test$;
rollback;
