"use client";
import {useRef,useState,useTransition} from "react";
import {useLanguage} from "@/components/providers/language-provider";
export type OperationField={name:string;en:string;bn:string;type?:"text"|"number"|"date"|"month"|"checkbox"|"textarea"|"select";required?:boolean;checked?:boolean;value?:string|number;min?:number;max?:number;step?:string;options?:Array<{id:string;name:string}>};
export function InlineOperation({label,bnLabel,description,bnDescription,fields,values={},action}:{label:string;bnLabel:string;description?:string;bnDescription?:string;fields:OperationField[];values?:Record<string,unknown>;action:(input:unknown)=>Promise<{ok:boolean;message:string}>}){
 const {locale}=useLanguage(),t=(en:string,bn:string)=>locale==="bn"?bn:en;const [open,setOpen]=useState(false),[message,setMessage]=useState("");const [pending,start]=useTransition();const key=useRef({signature:"",id:""});const cls="mt-1 w-full rounded-lg border bg-background p-3";
 return <div className="space-y-3"><button disabled={pending} className="rounded-lg border px-3 py-2" aria-expanded={open} onClick={()=>setOpen(!open)}>{t(label,bnLabel)}</button>{message&&<p role="status" className="text-sm">{message}</p>}{open&&<form className="grid gap-4 rounded-xl border p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),input:Record<string,unknown>={...values};for(const field of fields){const v=String(f.get(field.name)??"");input[field.name]=field.type==="checkbox"?f.has(field.name):field.type==="number"?Number(v):field.type==="month"?`${v}-01`:v;}const signature=JSON.stringify(input);if(key.current.signature!==signature)key.current={signature,id:crypto.randomUUID()};start(async()=>{const r=await action({...input,request_id:key.current.id});setMessage(r.message);if(r.ok){setOpen(false);key.current={signature:"",id:""};}});}}>
 {description&&<p className="sm:col-span-2 text-sm text-muted-foreground">{t(description,bnDescription??description)}</p>}{fields.map(field=><label key={field.name} className={field.type==="textarea"?"sm:col-span-2":""}>{t(field.en,field.bn)}{field.type==="select"?<select name={field.name} className={cls} defaultValue={field.value??""} required={field.required} disabled={pending}><option value="">{t("Choose…","নির্বাচন…")}</option>{field.options?.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select>:field.type==="textarea"?<textarea name={field.name} className={cls} defaultValue={field.value??""} required={field.required} maxLength={1000} disabled={pending}/>:<input className={field.type==="checkbox"?"ml-3":cls} name={field.name} type={field.type??"text"} defaultChecked={field.type==="checkbox"?field.checked:undefined} defaultValue={field.type==="checkbox"?undefined:field.value??""} required={field.required} min={field.min} max={field.max} step={field.step??(field.type==="number"?"0.01":undefined)} maxLength={200} disabled={pending}/>}</label>)}<div className="flex gap-3 sm:col-span-2"><button disabled={pending} className="rounded-lg bg-primary p-3 text-primary-foreground">{pending?t("Saving…","সংরক্ষণ হচ্ছে…"):t("Confirm and save","নিশ্চিত করে সংরক্ষণ")}</button><button type="button" disabled={pending} onClick={()=>setOpen(false)}>{t("Cancel","বাতিল")}</button></div></form>}</div>;
}
