/** Explicit display translations; identifiers and stored values are unchanged. */
const bangla: Record<string, string> = {
  "Student name": "শিক্ষার্থীর নাম",
  "Student full name": "শিক্ষার্থীর পুরো নাম",
  "Student name in Bangla": "শিক্ষার্থীর বাংলা নাম",
  "Guardian name": "অভিভাবকের নাম",
  "Guardian mobile": "অভিভাবকের মোবাইল",
  Mobile: "মোবাইল",
  Email: "ইমেইল",
  "Date of birth": "জন্মতারিখ",
  "Current school": "বর্তমান শিক্ষা প্রতিষ্ঠান",
  "Academic year": "শিক্ষাবর্ষ",
  "Academic group": "বিভাগ",
  Class: "শ্রেণি",
  Programme: "প্রোগ্রাম",
  "Programme offering": "প্রোগ্রাম অফারিং",
  Batch: "ব্যাচ",
  Branch: "শাখা",
  Subject: "বিষয়",
  Classroom: "ক্লাসরুম",
  Teacher: "শিক্ষক",
  "Offering code": "অফারিং কোড",
  "Custom offering title": "আলাদা অফারিং শিরোনাম",
  "Billing cycle": "বিলিং সময়চক্র",
  "Monthly due day": "মাসিক পরিশোধের দিন",
  "Effective date": "কার্যকর হওয়ার তারিখ",
  Code: "কোড",
  Name: "নাম",
  "Amount (BDT)": "টাকার পরিমাণ",
  "Charge type": "ফি-এর ধরন",
  Frequency: "পুনরাবৃত্তির নিয়ম",
  "Publication reason": "প্রকাশের কারণ",
  Reason: "কারণ",
  Status: "অবস্থা",
  Note: "নোট",
  "Sort order": "তালিকার ক্রম",
  Icon: "আইকন",
  "Applications open on": "আবেদন শুরুর তারিখ",
  "Applications close on": "আবেদন শেষের তারিখ",
  "Subjects on this offering": "অফারিং-এর বিষয়সমূহ",
  "Title (English)": "শিরোনাম (ইংরেজি)",
  "Title (Bangla)": "শিরোনাম (বাংলা)",
  "Description (English)": "বর্ণনা (ইংরেজি)",
  "Description (Bangla)": "বর্ণনা (বাংলা)",
  "Eyebrow (English)": "সংক্ষিপ্ত পরিচিতি (ইংরেজি)",
  "Eyebrow (Bangla)": "সংক্ষিপ্ত পরিচিতি (বাংলা)",
  "Public schedule (English)": "প্রকাশ্য সময়সূচি (ইংরেজি)",
  "Public schedule (Bangla)": "প্রকাশ্য সময়সূচি (বাংলা)",
  "Application requirements (English)": "আবেদনের শর্ত (ইংরেজি)",
  "Application requirements (Bangla)": "আবেদনের শর্ত (বাংলা)",
  "Admission policy (English)": "ভর্তির নিয়ম (ইংরেজি)",
  "Admission policy (Bangla)": "ভর্তির নিয়ম (বাংলা)",
  "Target completion date": "সম্পন্ন করার নির্ধারিত তারিখ",
  "Unit / Scope": "পাঠের অংশ / পরিসর",
};
export function localizedFieldLabel(label: string, locale: string) {
  if (locale !== "bn") return label;
  const key = Object.keys(bangla).find(
    (key) => key.toLowerCase() === label.trim().toLowerCase(),
  );
  return key ? bangla[key] : label;
}
