import Link from "next/link";
import {notFound} from "next/navigation";
import {z} from "zod";
import {requirePermission} from "@/modules/platform/auth/erp-context";
import {getReceivables} from "@/modules/finance/receivables/queries";
import {PrintAdmissionButton} from "@/modules/admissions/components/print-button";
import {amountInWords} from "@/lib/academy/money-in-words";
export default async function GuardianStatement({params,searchParams}:{params:Promise<{studentId:string}>;searchParams:Promise<{page?:string}>}){
 await requirePermission("finance.view");const {studentId}=await params;if(!z.string().uuid().safeParse(studentId).success)notFound();const q=await searchParams,page=Math.min(10000,Math.max(1,parseInt(q.page??"1")||1));const data=await getReceivables(page,"","ALL",false,studentId);if(!data.rows.length)notFound();const student=data.rows[0],pageDue=data.rows.reduce((s,r)=>s+r.due,0),overallDue=data.summary.reduce((s,r)=>s+r.amount,0);
 return <div className="space-y-4"><nav className="flex gap-4 print:hidden"><Link href={`/dashboard/finance/receivables?q=${student.student_no}`}>← Back to receivables</Link><PrintAdmissionButton/>{page>1&&<Link href={`?page=${page-1}`}>Previous statement page</Link>}{page*25<data.total&&<Link href={`?page=${page+1}`}>Next statement page</Link>}</nav><style>{`.guardian-statement{max-width:180mm;margin:auto;padding:30mm 5mm 8mm;background:white;color:#111;font:10pt/1.5 Arial,var(--font-bn),sans-serif}.guardian-statement h1{font-size:22pt;font-weight:700;border-bottom:2px solid;padding-bottom:3mm}.guardian-statement table{width:100%;border-collapse:collapse;font-size:9pt}.guardian-statement th,.guardian-statement td{border-bottom:1px solid #aaa;padding:2mm;text-align:right}.guardian-statement th:first-child,.guardian-statement td:first-child{text-align:left}.guardian-statement tr{break-inside:avoid}@media print{body:has(.guardian-statement) *:not(:has(.guardian-statement)):not(.guardian-statement):not(.guardian-statement *){display:none!important}body:has(.guardian-statement) *:has(.guardian-statement){display:block!important;margin:0!important;padding:0!important;max-width:none!important}.guardian-statement{padding:25mm 0 0}@page{size:A4;margin:12mm}}`}</style><article className="guardian-statement"><h1>STUDENT ACCOUNT STATEMENT</h1><p><strong>{student.student_no} · {student.full_name}</strong><br/>Guardian: {student.guardian??"—"} · {student.mobile??"—"}<br/>Current balances as of {data.today} (Bangladesh)<br/>Statement page {page} of {Math.ceil(data.total/25)} · {data.total} invoices in account</p><table><thead><tr>{["Invoice / due","Charges","Reductions","Net fees","Allocated payments","Refunds","Due"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><td>{r.invoice_no}<br/>{r.due_on}</td>{[r.gross,r.credits,r.net,r.paid,r.refunded,r.due].map((v,i)=><td key={i}>{v.toFixed(2)}</td>)}</tr>)}</tbody></table><p><strong>Due on this page:</strong> BDT {pageDue.toFixed(2)}<br/><strong>Total account due across all pages:</strong> BDT {overallDue.toFixed(2)}<br/>{amountInWords(overallDue)}</p><p>Reductions include recorded discounts, scholarships and other fee adjustments. Allocated payments and actual refunds are separate. This statement does not acknowledge new money received and is not a payment receipt. Future invoices are not included.</p></article></div>;
}
