import { z } from "zod";
import { platformClient } from "@/modules/platform/rpc-client";
const choice = z.object({ id: z.string(), name: z.string() });
const schema = z.object({ manager: z.boolean(), canPay: z.boolean(), page: z.number(), total: z.number(), accounts: z.array(choice), assetAccounts: z.array(choice), vendors: z.array(choice), staff: z.array(choice), purchases: z.array(choice), locations: z.array(z.string()), rows: z.array(z.object({ id: z.string(), asset_no: z.string(), name: z.string(), serial_no: z.string().nullable(), location: z.string(), vendor_id: z.string(), source_purchase_id: z.string().nullable(), asset_account_id: z.string(), cost: z.number(), residual: z.number(), life_months: z.number(), acquired_on: z.string(), in_service_on: z.string(), depreciation_start: z.string(), invoice_reference: z.string(), status: z.enum(["DRAFT", "ACTIVE", "INACTIVE", "DISPOSED", "CANCELLED"]), custodian_id: z.string().nullable(), custodian: z.string().nullable(), payable_id: z.string().nullable(), revision: z.number(), depreciated: z.number(), book_value: z.number(), next_month: z.string(), remaining: z.number(), transfer_id: z.string().nullable(), own_custody: z.boolean(), acknowledged: z.boolean(), events: z.array(z.object({ action: z.string(), reason: z.string(), date: z.string(), actor: z.string().nullable(), details: z.string().nullable() })), documents: z.array(z.object({ id: z.string(), name: z.string(), size: z.number(), note: z.string(), date: z.string(), actor: z.string().nullable() })).default([]) })) });
export type AssetData = z.infer<typeof schema>;
export async function getAssets(page: number, status: string, search: string) { const db = await platformClient(); const { data, error } = await db.rpc("asset_workspace", { p_page: page, p_status: status, p_search: search }); if (error)
    throw Error(error.message); const parsed = schema.parse(data); if (!parsed.manager || !parsed.rows.length)
    return parsed; const evidence = await db.rpc("finance_document_batch", { p_type: "ASSET", p_ids: parsed.rows.map(r => r.id) }); if (evidence.error)
    throw Error(evidence.error.message); const docs = z.array(z.object({ entityId: z.string(), documents: z.array(z.unknown()) })).parse(evidence.data); return schema.parse({ ...parsed, rows: parsed.rows.map(r => ({ ...r, documents: docs.find(d => d.entityId === r.id)?.documents ?? [] })) }); }
