import type { ReactNode } from "react";
export type AcknowledgementData={prospectNo?:string|null;studentName?:string;intentLabel?:string;details?:Record<string,string>};
export function AcknowledgementSlip({message,bn=false}:{message:AcknowledgementData;bn?:boolean}){return <>
        <style>{`
.ack-slip{background:#fff;color:#111;max-width:185mm;padding:10mm;margin:auto;border:1px solid #777;font:10pt/1.5 Arial,var(--font-bn),sans-serif}.ack-title{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:5mm}.ack-title h2{font-size:18pt;font-weight:700;margin:0}.ack-title p{font-size:9pt;margin:2mm 0}.ack-badge{border:1px solid #111;padding:2mm;font-size:8pt;align-self:start}.ack-meta{display:grid;grid-template-columns:1fr 1fr;gap:4mm;margin:5mm 0}.ack-meta dt{font-size:8pt;text-transform:uppercase}.ack-meta dd{font-weight:700;margin:1mm 0}.ack-slip table{width:100%;border-collapse:collapse}.ack-slip th,.ack-slip td{border:1px solid #999;padding:3mm;text-align:left;overflow-wrap:anywhere}.ack-slip th{width:30%;font-size:9pt}.ack-next{border:1px solid #111;padding:4mm;margin:6mm 0}.ack-next h3{font-weight:700;margin:0 0 2mm}.ack-slip footer{border-top:1px solid #aaa;padding-top:3mm;font-size:8pt}@media print{body:has(.ack-slip) *:not(:has(.ack-slip)):not(.ack-slip):not(.ack-slip *){display:none!important}body:has(.ack-slip) *:has(.ack-slip){display:block!important;margin:0!important;padding:0!important;max-width:none!important;min-height:0!important}body *{visibility:hidden}.ack-slip,.ack-slip *{visibility:visible}.ack-slip{position:static;border:0;width:100%;padding:0;max-width:none}@page{size:A4;margin:16mm}}
`}</style>
        <article id="interest-acknowledgement-slip" className="ack-slip">
          <header className="ack-title"><div><h2>{bn?"আবেদনের প্রাপ্তি স্বীকারপত্র":"Application acknowledgement"}</h2><p>Sohoj Academy · Public application desk</p></div><span className="ack-badge">RECEIVED · UNVERIFIED</span></header>
          <dl className="ack-meta"><div><dt>Application reference</dt><dd>{message.prospectNo??"Not issued"}</dd></div><div><dt>Submitted (Bangladesh time)</dt><dd>{message.details?.submitted}</dd></div></dl>
          <table><tbody>{[["Student / শিক্ষার্থী",message.studentName],["Guardian / অভিভাবক",message.details?.guardian],["Contact mobile",message.details?.mobile],["Student email",message.details?.email],["Application type",message.intentLabel],["Programme preference",message.details?.programme],["Subject preferences",message.details?.subjects],["Present address",message.details?.address]].map(([label,value])=><tr key={label}><th>{label}</th><td>{value||"Not provided"}</td></tr>)}</tbody></table>
          <section className="ack-next"><h3>Next steps / পরবর্তী ধাপ</h3><p>{bn?"এই রেফারেন্সটি সংরক্ষণ করুন। একাডেমি তথ্য ও পছন্দের প্রোগ্রাম যাচাই করে যোগাযোগ করবে। এটি ভর্তি নিশ্চিতকরণ, শিক্ষার্থী আইডি বা টাকা আদায়ের রসিদ নয়।":"Keep this reference. The academy will verify the details and preferred programme, then contact the guardian. This acknowledgement is not admission confirmation, a Student ID or a payment receipt."}</p></section>
          <footer>System-issued acknowledgement · {message.prospectNo} · No signature, payment or verified admission has been asserted.</footer>
        </article>

</>; }
