import { createAssessment, createNotice, recordPayment } from "@/app/actions/transactions";
import { createFeeStructure, createTeacher } from "@/app/actions/operations";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type O={id:string;name:string};
const Select=({name,items,label,required=false}:{name:string;items:O[];label:string;required?:boolean})=><select name={name} required={required} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="">{label}</option>{items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>;

export function TeacherManager({teachers}:{teachers:{id:string;name:string;mobile:string|null;is_active:boolean}[]}){
 return <Box title="Teachers"><form action={async (fd) => { await createTeacher(fd); }} className="flex gap-2"><Input name="name" placeholder="Teacher name" required/><Input name="mobile" placeholder="Mobile"/><Button>Add Teacher</Button></form><Rows rows={teachers.map(x=>[x.name,x.mobile??"—"])}/></Box>
}
export function FeeManager({years,classes,programs,fees}:{years:O[];classes:O[];programs:O[];fees:{id:string;title:string;amount:number;frequency:string}[]}){
 return <Box title="Fee Structure"><form action={async (fd) => { await createFeeStructure(fd); }} className="grid gap-2 md:grid-cols-3"><Input name="title" placeholder="Monthly Tuition" required/><Select name="academic_year_id" items={years} label="Academic year" required/><Select name="class_id" items={classes} label="Class (optional)"/><Select name="program_id" items={programs} label="Program (optional)"/><Input name="amount" type="number" min="0" placeholder="Amount" required/><Input name="effective_from" type="date" required/><Button className="md:col-span-3">Add Fee Structure</Button></form><Rows rows={fees.map(x=>[x.title,`৳${x.amount} • ${x.frequency}`])}/></Box>
}
export function PaymentManager({students,payments}:{students:{id:string;student_no:string;name:string;enrollments:{id:string}[]|null}[];payments:{id:string;receipt_no:string;amount:number;payment_date:string;students:{name:string;student_no:string}|null}[]}){
 return <Box title="Fee Collection"><form action={async (fd) => { await recordPayment(fd); }} className="grid gap-2 md:grid-cols-3"><select name="student_id" required className="h-9 rounded-md border bg-background px-3 text-sm"><option value="">Student</option>{students.map(x=><option key={x.id} value={x.id}>{x.student_no} — {x.name}</option>)}</select><Input name="amount" type="number" min="1" placeholder="Amount" required/><Input name="payment_date" type="date" required/><select name="method" className="h-9 rounded-md border bg-background px-3 text-sm"><option>CASH</option><option>BANK</option><option>MOBILE BANKING</option></select><Input name="notes" placeholder="Notes"/><Button>Collect & Issue Receipt</Button></form><Rows rows={payments.map(x=>[x.receipt_no,`${x.students?.student_no??""} ${x.students?.name??""} • ৳${x.amount} • ${x.payment_date}`])}/></Box>
}
export function AssessmentManager({years,batches,subjects,assessments}:{years:O[];batches:O[];subjects:O[];assessments:{id:string;title:string;held_on:string;total_marks:number}[]}){
 return <Box title="Assessments"><form action={async (fd) => { await createAssessment(fd); }} className="grid gap-2 md:grid-cols-3"><Input name="title" placeholder="Weekly Test 01" required/><Select name="academic_year_id" items={years} label="Academic year" required/><Select name="batch_id" items={batches} label="Batch" required/><Select name="subject_id" items={subjects} label="Subject"/><Input name="assessment_type" defaultValue="WEEKLY" placeholder="Type"/><Input name="held_on" type="date" required/><Input name="total_marks" type="number" min="1" defaultValue="100" required/><Button>Create Assessment</Button></form><Rows rows={assessments.map(x=>[x.title,`${x.held_on} • ${x.total_marks} marks`])}/></Box>
}
export function NoticeManager({notices}:{notices:{id:string;title:string;audience:string;published_at:string|null}[]}){
 return <Box title="Notices"><form action={async (fd) => { await createNotice(fd); }} className="grid gap-2"><Input name="title" placeholder="Notice title" required/><textarea name="body" required placeholder="Write notice..." className="min-h-24 rounded-md border bg-background p-3 text-sm"/><div className="flex flex-wrap gap-3"><select name="audience" className="h-9 rounded-md border bg-background px-3 text-sm"><option>ALL</option><option>STUDENT</option><option>GUARDIAN</option><option>TEACHER</option></select><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="publish"/> Publish now</label><Button>Create Notice</Button></div></form><Rows rows={notices.map(x=>[x.title,`${x.audience} • ${x.published_at?"Published":"Draft"}`])}/></Box>
}
function Box({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-xl border bg-card p-5"><h2 className="mb-4 text-lg font-semibold">{title}</h2>{children}</section>}
function Rows({rows}:{rows:string[][]}){return <div className="mt-5 divide-y">{rows.length?rows.map((r,i)=><div key={i} className="flex justify-between gap-4 py-2 text-sm"><b>{r[0]}</b><span className="text-right text-muted-foreground">{r[1]}</span></div>):<p className="text-sm text-muted-foreground">No records yet.</p>}</div>}
