import {recordParentCommunication,saveWeeklyMonitoring} from "@/app/actions/transactions";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {Card,CardContent,CardHeader,CardTitle} from "@/components/ui/card";
type Student={id:string;student_no:string;name:string};
type Monitor={id:string;student_id:string;week_start:string;homework_score:number|null;participation_score:number|null;test_score:number|null;remarks:string|null;students:{name:string;student_no:string}|null};
type Comm={id:string;student_id:string;communication_type:string;occurred_at:string;notes:string;next_follow_up:string|null;students:{name:string;student_no:string}|null;guardians:{name:string}|null};
export function ProgressManager({students,records}:{students:Student[];records:Monitor[]}){
 return <Card><CardHeader><CardTitle>Weekly Monitoring</CardTitle></CardHeader><CardContent><form action={saveProgress} className="grid gap-2 md:grid-cols-3"><select name="student_id" required className="h-9 rounded-md border bg-background px-3 text-sm"><option value="">Student</option>{students.map(s=><option key={s.id} value={s.id}>{s.student_no} — {s.name}</option>)}</select><Input name="week_start" type="date" required/><Input name="homework_score" type="number" min="0" max="100" placeholder="Homework /100"/><Input name="participation_score" type="number" min="0" max="100" placeholder="Participation /100"/><Input name="test_score" type="number" min="0" max="100" placeholder="Test /100"/><Input name="remarks" placeholder="Remarks"/><Button className="md:col-span-3">Save Weekly Progress</Button></form><Table headers={["Week","Student","HW","Participation","Test","Remarks"]} rows={records.map(x=>[x.week_start,`${x.students?.student_no??""} ${x.students?.name??""}`,show(x.homework_score),show(x.participation_score),show(x.test_score),x.remarks??"—"])}/></CardContent></Card>
}
export function ParentCommunicationManager({students,records}:{students:Student[];records:Comm[]}){
 return <Card><CardHeader><CardTitle>Parent Communication</CardTitle></CardHeader><CardContent><form action={saveCommunication} className="grid gap-2 md:grid-cols-3"><select name="student_id" required className="h-9 rounded-md border bg-background px-3 text-sm"><option value="">Student</option>{students.map(s=><option key={s.id} value={s.id}>{s.student_no} — {s.name}</option>)}</select><select name="communication_type" className="h-9 rounded-md border bg-background px-3 text-sm"><option>CALL</option><option>MEETING</option><option>SMS</option><option>WHATSAPP</option><option>OTHER</option></select><Input name="next_follow_up" type="date"/><textarea name="notes" required placeholder="Discussion, concern, commitment, next action..." className="min-h-24 rounded-md border bg-background p-3 text-sm md:col-span-3"/><Button className="md:col-span-3">Record Communication</Button></form><Table headers={["Date","Student","Type","Notes","Follow-up"]} rows={records.map(x=>[x.occurred_at.slice(0,10),`${x.students?.student_no??""} ${x.students?.name??""}`,x.communication_type,x.notes,x.next_follow_up??"—"])}/></CardContent></Card>
}
function show(v:number|null){return v===null?"—":String(v)}
function Table({headers,rows}:{headers:string[];rows:string[][]}){return <div className="mt-6 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left">{headers.map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-b">{r.map((v,j)=><td key={j} className="p-3">{v}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="py-8 text-center text-muted-foreground">No records yet.</p>}</div>}
async function saveProgress(fd:FormData):Promise<void>{"use server";await saveWeeklyMonitoring(fd)}
async function saveCommunication(fd:FormData):Promise<void>{"use server";await recordParentCommunication(fd)}
