"use client";
import Link from "next/link";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {useLanguage} from "@/components/providers/language-provider";
import {periodAction} from "./actions";
import type {ReportData} from "./queries";
const money=(n:number)=>`BDT ${n.toLocaleString("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function MonthlyReports({data}:{data:ReportData}){const {locale}=useLanguage();const t=(en:string,bn:string)=>locale==="bn"?bn:en;const router=useRouter();const [view,setView]=useState("profit"),[acting,setActing]=useState(false),[message,setMessage]=useState("");const [pending,start]=useTransition();const key=useRef({signature:"",id:""});
 const filtered=data.accounts.filter(a=>view==="profit"?["REVENUE","CONTRA_REVENUE","EXPENSE"].includes(a.type):view==="balance"?["ASSET","LIABILITY","EQUITY"].includes(a.type):true);
 function csv(){const text=[['Code','Account','Type','Opening debit minus credit','Period debit','Period credit','Closing debit','Closing credit'],...data.accounts.map(a=>[a.code,a.name,a.type,a.opening,a.debit,a.credit,a.endingDebit,a.endingCredit])].map(row=>row.map(v=>{const safe=typeof v==="number"?String(v):String(v).replace(/^[=+@-]/,"'$&");return '"'+safe.replaceAll('"','""')+'"';}).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`trial-balance-${data.month.slice(0,7)}.csv`;a.click();URL.revokeObjectURL(url);}
 return <div className="space-y-5"><form className="flex items-end gap-3 print:hidden" action="/dashboard/finance/reports"><label>{t("Accounting month","হিসাবের মাস")}<input type="month" name="month" className="ml-3 rounded-lg border bg-background p-3" defaultValue={data.month.slice(0,7)} required/></label><button className="rounded-lg border p-3">{t("View reports","রিপোর্ট দেখুন")}</button></form><div className="flex flex-wrap gap-3 print:hidden">{[["profit",t("Profit & loss","লাভ ও ক্ষতি")],["balance",t("Balance sheet","ব্যালান্স শিট")],["trial",t("Trial balance","ট্রায়াল ব্যালান্স")],["cash",t("Cash movement","অর্থের চলাচল")]].map(([value,label])=><button className="rounded-lg border p-3" key={value} aria-pressed={view===value} onClick={()=>setView(value)}>{label}</button>)}<button className="rounded-lg border p-3" onClick={csv}>{t("Export trial balance CSV","ট্রায়াল ব্যালান্স CSV")}</button><button className="rounded-lg border p-3" onClick={()=>window.print()}>{t("Print report","রিপোর্ট প্রিন্ট")}</button></div>
 <article className="monthly-report space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">{view==="profit"?t("Profit & loss","লাভ ও ক্ষতি"):view==="balance"?t("Balance sheet","ব্যালান্স শিট"):view==="trial"?t("Trial balance","ট্রায়াল ব্যালান্স"):t("Cash movement report","অর্থের চলাচলের রিপোর্ট")}</h2><p>{data.month} — {data.through} · BDT · {data.status==="CLOSE"?t("Closed","বন্ধ"):t("Open","খোলা")}</p><p className="text-sm text-muted-foreground">{t("Posted journals by accounting date. Current month can be incomplete. Cash movement groups posted sources and excludes net-zero internal cash/bank transfers.","হিসাবের তারিখ অনুযায়ী পোস্ট করা journal। চলতি মাসের হিসাব অসম্পূর্ণ হতে পারে। অর্থের চলাচল পোস্ট করা source অনুযায়ী; নিট শূন্য internal transfer বাদ।")}</p>
 {view==="profit"&&<div className="grid gap-3 sm:grid-cols-4">{[[t("Revenue","রাজস্ব"),data.revenue],[t("Discounts / reversals","ছাড় / reversal"),data.reductions],[t("Expenses","ব্যয়"),data.expenses],[t("Profit / loss","লাভ / ক্ষতি"),data.profit]].map(([label,n])=><div className="rounded-lg border p-3" key={String(label)}><p>{label}</p><strong>{money(Number(n))}</strong></div>)}</div>}
 {view==="balance"&&<div className="grid gap-3 sm:grid-cols-5">{[[t("Assets","সম্পদ"),data.assets],[t("Liabilities","দায়"),data.liabilities],[t("Posted equity","পোস্ট করা মূলধন"),data.equity],[t("Accumulated unclosed result","পুঞ্জীভূত ফলাফল"),data.retainedResult],[t("Balance difference","ব্যালান্সের পার্থক্য"),data.balanceDifference]].map(([label,n])=><div className="rounded-lg border p-3" key={String(label)}><p>{label}</p><strong>{money(Number(n))}</strong></div>)}</div>}
 {view==="cash"?<><p>{t("Opening cash / bank / mobile","শুরুর নগদ / ব্যাংক / মোবাইল")}: {money(data.cashOpening)}</p><table className="w-full text-sm"><thead><tr><th className="text-left">{t("Posted source","পোস্ট করা source")}</th><th className="text-right">{t("Net movement","নিট পরিবর্তন")}</th></tr></thead><tbody>{data.cashMovements.map((r,i)=><tr key={i} className="border-b"><td className="py-3">{r.type} · {r.source}</td><td className="text-right">{money(r.net)}</td></tr>)}</tbody></table><p className="font-semibold">{t("Closing cash / bank / mobile","শেষ নগদ / ব্যাংক / মোবাইল")}: {money(data.cashClosing)}</p></>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">{t("Code / account","কোড / অ্যাকাউন্ট")}</th>{view==="trial"?<><th>{t("Period debit","মাসের ডেবিট")}</th><th>{t("Period credit","মাসের ক্রেডিট")}</th><th>{t("Closing debit","শেষ ডেবিট")}</th><th>{t("Closing credit","শেষ ক্রেডিট")}</th></>:<th className="text-right">{t("Amount","পরিমাণ")}</th>}</tr></thead><tbody>{filtered.map(a=><tr key={a.id} className="border-b"><td className="p-3">{a.code} · {a.name}</td>{view==="trial"?<><td>{money(a.debit)}</td><td>{money(a.credit)}</td><td>{money(a.endingDebit)}</td><td>{money(a.endingCredit)}</td></>:<td className="text-right">{money(view==="profit"?a.type==="REVENUE"?a.credit-a.debit:a.debit-a.credit:a.type==="ASSET"?a.closing:-a.closing)}</td>}</tr>)}</tbody>{view==="trial"&&<tfoot><tr className="font-semibold"><td className="p-3">{t("Totals","মোট")}</td>{["debit","credit","endingDebit","endingCredit"].map(k=><td key={k}>{money(data.accounts.reduce((sum,a)=>sum+a[k as "debit"|"credit"|"endingDebit"|"endingCredit"],0))}</td>)}</tr></tfoot>}</table></div>}
 <p className="text-xs">{t("Generated","তৈরির সময়")}: {new Date(data.generatedAt).toLocaleString(locale==="bn"?"bn-BD":"en-GB",{timeZone:"Asia/Dhaka"})}</p></article>
 {data.canManage&&<section className="space-y-4 rounded-xl border p-5 print:hidden"><h2 className="font-semibold">{t("Month-end controls","মাস শেষের নিয়ন্ত্রণ")}</h2><p className="text-sm">{t("Verify every active cash/bank/mobile account at month end. Close preserves a snapshot and rejects later posting into this month. Reopen requires a recorded explanation.","মাস শেষে প্রতিটি সক্রিয় নগদ / ব্যাংক / মোবাইল অ্যাকাউন্ট যাচাই করুন। Close snapshot রাখে এবং এই মাসে পরের posting বন্ধ করে। Reopen-এর ব্যাখ্যা রেকর্ড করতে হবে।")}</p><ul className="space-y-2">{data.closeChecks.map(c=><li key={c.id}>{c.matched?"✓":"○"} {c.name} · {c.matched?t("Month-end matched","মাসের শেষ হিসাব মিলেছে"):t("Verified month-end count/statement needed","যাচাইকৃত মাসের শেষ count/statement লাগবে")}</li>)}</ul><Link className="inline-block underline" href="/dashboard/finance/daily-close">{t("Open cash / statement close","নগদ / স্টেটমেন্টের শেষ হিসাব খুলুন")}</Link><button className="ml-4 rounded-lg border p-3" disabled={pending||(!data.canClose&&data.status!=="CLOSE")} onClick={()=>{setActing(!acting);setMessage("");}}>{data.status==="CLOSE"?t("Reopen month","মাস আবার খুলুন"):t("Close month","মাস বন্ধ করুন")}</button>{acting&&<form className="space-y-3" onSubmit={e=>{e.preventDefault();const reason=String(new FormData(e.currentTarget).get("reason"));const values={action:data.status==="CLOSE"?"REOPEN":"CLOSE",month:data.month,preview_token:data.token,reason};const signature=JSON.stringify(values);if(signature!==key.current.signature)key.current={signature,id:crypto.randomUUID()};start(async()=>{const r=await periodAction({...values,request_id:key.current.id});setMessage(r.message);if(r.ok){setActing(false);key.current={signature:"",id:""};router.refresh();}});}}><label className="block"><input type="checkbox" required disabled={pending}/> {t("I reviewed payroll, receipts, refunds, expenses, advances, payables and reconciliations.","বেতন, আদায়, refund, ব্যয়, অগ্রিম, দায় ও reconciliation পর্যালোচনা করেছি।")}</label><label className="block">{t("Explanation","ব্যাখ্যা")}<textarea name="reason" minLength={10} maxLength={1000} required disabled={pending} className="mt-1 w-full rounded-lg border bg-background p-3"/></label><button className="rounded-lg bg-primary p-3 text-primary-foreground" disabled={pending}>{pending?t("Saving…","সংরক্ষণ হচ্ছে…"):t("Confirm period action","মাসের পদক্ষেপ নিশ্চিত করুন")}</button></form>}{message&&<p role="status">{message}</p>}<details><summary className="cursor-pointer">{t("Close / reopen history","বন্ধ / আবার খোলার ইতিহাস")}</summary>{data.events.map((e,i)=><p className="mt-2 text-sm" key={i}>{e.date.slice(0,10)} · {e.actor??"—"} · {e.action} · {e.reason}</p>)}</details></section>}
 <style>{`@media print{body:has(.monthly-report) *:not(:has(.monthly-report)):not(.monthly-report):not(.monthly-report *){display:none!important}body:has(.monthly-report) *:has(.monthly-report){display:block!important;margin:0!important;padding:0!important;max-width:none!important;min-height:0!important}.monthly-report{color:#111!important;background:white!important;border:0!important;font:9pt/1.4 Arial,sans-serif;padding:25mm 0 0!important}.monthly-report .text-muted-foreground{color:#333!important}.monthly-report thead{display:table-header-group}.monthly-report tr{break-inside:avoid}@page{size:A4;margin:14mm}}`}</style>
 </div>;}
