"use client";
import { Fragment,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { StatusBadge } from "@/components/erp/status-badge";
import { RecordStateButton } from "@/components/erp/record-state-button";
import { announceSaved } from "@/components/erp/action-panel";
import { editStaffRecord } from "../edit-actions";
import type { StaffListRow } from "../queries";
export function StaffRegister({rows,canManage}:{rows:StaffListRow[];canManage:boolean}){
 const [editing,setEditing]=useState<string|null>(null),[message,setMessage]=useState("");const [pending,start]=useTransition();const router=useRouter();
 return <section className="overflow-x-auto rounded-2xl border bg-card"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b text-left">{["Staff ID / name","Primary responsibility","Contact","Joined","Status / actions"].map(x=><th className="p-4" key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><Fragment key={row.id}><tr className="border-b"><td className="p-4"><p className="font-semibold">{row.fullName}</p>{row.staffNo}</td><td className="p-4">{row.roleName}</td><td className="p-4">{row.mobile??"—"}<br/>{row.email??"—"}</td><td className="p-4">{row.joinedOn??"—"}</td><td className="p-4"><StatusBadge value={row.status}/>{canManage&&<div className="mt-2 flex gap-2"><button onClick={()=>{setEditing(editing===row.id?null:row.id);setMessage("");}} className="rounded border px-3 py-2">{editing===row.id?"Close editor":"Edit details"}</button><RecordStateButton entity="staff" id={row.id} active={row.status!=="ARCHIVED"}/></div>}</td></tr>{editing===row.id&&<tr><td colSpan={5} className="p-5"><form className="grid gap-4 rounded-xl border p-5 sm:grid-cols-2 lg:grid-cols-3" onSubmit={e=>{e.preventDefault();const values={id:row.id,...Object.fromEntries(new FormData(e.currentTarget))};start(async()=>{try{const result=await editStaffRecord(values);setMessage(result.message);if(result.ok){setEditing(null);announceSaved(result.message);router.refresh();}}catch{setMessage("Connection interrupted. Your entries remain; reload to check the saved record.");}});}}>
 <h3 className="font-semibold sm:col-span-2 lg:col-span-3">Edit {row.fullName}</h3>
 {[['staff_no','Permanent Staff ID',row.staffNo,true],['id','Record ID',row.id,true],['full_name','Full name',row.fullName,false],['mobile','Primary mobile',row.mobile,false],['alternate_mobile','Alternate mobile',row.details.alternate_mobile,false],['email','Email',row.email,!!row.details.profile_id],['address','Full address',row.details.address,false],['emergency_contact_name','Emergency contact',row.details.emergency_contact_name,false],['emergency_contact_mobile','Emergency mobile',row.details.emergency_contact_mobile,false],['joined_on','Joined on',row.joinedOn,false],['left_on','Left on (lifecycle action)',row.details.left_on,true],['role','Responsibility (access setup)',row.roleName,true],['branch_id','Branch assignment',row.details.branch_id,true],['profile_id','Linked account',row.details.profile_id,true],['status','Lifecycle status',row.status,true],['notes','Staff notes',row.details.notes,false]].map(([name,label,value,readOnly])=><label key={String(name)} className="text-sm">{label}{readOnly&&<span className="ml-1 text-xs text-muted-foreground">Read only</span>}<input name={readOnly?undefined:String(name)} defaultValue={String(value??"")} readOnly={Boolean(readOnly)} required={name==="full_name"} type={name==="joined_on"?"date":name==="email"?"email":"text"} className="mt-1 w-full rounded-lg border bg-background p-3 read-only:bg-muted/30"/></label>)}
 <label className="text-sm">Correction reason<input name="reason" required minLength={5} defaultValue="Corrected verified staff details" className="mt-1 w-full rounded-lg border bg-background p-3"/></label>
 <p className="text-xs text-muted-foreground sm:col-span-2 lg:col-span-3">Permanent IDs and account/security assignments are protected. Change linked email in secure account settings; change access responsibilities through Staff access settings.</p>
 {message&&<p role="status" className="sm:col-span-2 lg:col-span-3">{message}</p>}<button disabled={pending} aria-busy={pending} className="rounded-lg bg-primary px-4 py-3 text-primary-foreground">{pending?"Saving…":"Save changes"}</button><button type="button" disabled={pending} onClick={()=>setEditing(null)}>Cancel</button></form></td></tr>}</Fragment>)}</tbody></table></section>;
}
