"use client";
import Link from "next/link";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {useLanguage} from "@/components/providers/language-provider";
import {StatusBadge} from "@/components/erp/status-badge";
import {previewPayroll,payrollAction} from "./actions";
import type {PayrollData,PayrollPreview} from "./queries";
const cls="mt-1 w-full rounded-lg border bg-background p-3";
const money=(n:number)=>`BDT ${n.toLocaleString("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function PayrollRegister({data,page=1}:{data:PayrollData;page?:number}){
 const {locale}=useLanguage();const t=(en:string,bn:string)=>locale==="bn"?bn:en;const router=useRouter();const [creating,setCreating]=useState(false),[pay,setPay]=useState<PayrollData["records"][number]|null>(null),[preview,setPreview]=useState<PayrollPreview|null>(null),[basis,setBasis]=useState<Record<string,unknown>|null>(null),[message,setMessage]=useState("");const [pending,start]=useTransition();const key=useRef({signature:"",id:""});
 function run(values:Record<string,unknown>){const signature=JSON.stringify(values);if(signature!==key.current.signature)key.current={signature,id:crypto.randomUUID()};start(async()=>{const r=await payrollAction({...values,request_id:key.current.id});setMessage(r.message);if(r.ok){setCreating(false);setPay(null);setPreview(null);key.current={signature:"",id:""};router.refresh();}});}
 function review(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),a=Number(f.get("allowance")),c=Number(f.get("correction"));const input={staff_id:f.get("staff_id"),month:`${f.get("month")}-01`,allowances:a>0?[{label:String(f.get("allowance_label")),amount:a}]:[],corrections:c>0?[{kind:String(f.get("correction_kind")),label:String(f.get("correction_note")),amount:c}]:[]};start(async()=>{const r=await previewPayroll(input);if(r.ok){setPreview(r.preview);setBasis(input);setMessage("");}else setMessage(r.message);});}
 return <div className="space-y-5">{message&&<p className="rounded-xl border p-4" role="status">{message}</p>}{data.manager&&<button className="rounded-lg border p-3" disabled={pending} onClick={()=>{setCreating(!creating);setPay(null);setPreview(null);setMessage("");key.current={signature:"",id:""};}}>{t("Prepare monthly payroll","মাসিক বেতন প্রস্তুত করুন")}</button>}
 {creating&&<section className="space-y-4 rounded-2xl border p-5"><h2 className="font-semibold">{t("Review agreed salary and actual work","সম্মত বেতন ও প্রকৃত কাজ পর্যালোচনা")}</h2><p className="text-sm text-muted-foreground">{t("Fixed/hourly payroll only. Revenue-share teaching and referral rewards have separate statements. Fixed base is prorated by calendar days from the later of agreement or joining date; missing attendance never automatically reduces it. Current-month preview is provisional.","শুধু fixed/hourly বেতন। Revenue-share ও রেফারাল বোনাসের হিসাব আলাদা। চুক্তি ও যোগদানের মধ্যে পরের তারিখ থেকে ক্যালেন্ডার দিন অনুযায়ী মূল বেতন হিসাব হয়; উপস্থিতির রেকর্ড না থাকলে স্বয়ংক্রিয়ভাবে কমে না। চলতি মাসের preview অস্থায়ী।")}</p><Link className="inline-block underline" href="/dashboard/staff/operations">{t("Review staff attendance and terms","স্টাফ উপস্থিতি ও শর্ত দেখুন")}</Link>
 <form onSubmit={review} onChange={()=>setPreview(null)} className="grid gap-4 sm:grid-cols-2"><label>{t("Staff","স্টাফ")}<select disabled={pending} className={cls} name="staff_id" required><option value="">{t("Choose…","নির্বাচন করুন…")}</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t("Payroll month","বেতনের মাস")}<input disabled={pending} className={cls} type="month" name="month" required/></label><label>{t("Allowance (BDT, optional)","ভাতা (টাকা, ঐচ্ছিক)")}<input disabled={pending} type="number" name="allowance" step="0.01" min="0" defaultValue="0" className={cls}/></label><label>{t("Allowance purpose","ভাতার কারণ")}<select disabled={pending} className={cls} name="allowance_label">{["Meal allowance","Travel allowance","Extra duty allowance","Other agreed allowance"].map(v=><option key={v}>{v}</option>)}</select></label><label>{t("Earning correction (BDT, optional)","আয়ের সংশোধন (টাকা, ঐচ্ছিক)")}<input disabled={pending} className={cls} type="number" name="correction" step="0.01" min="0" defaultValue="0"/></label><label>{t("Correction type","সংশোধনের ধরন")}<select disabled={pending} name="correction_kind" className={cls}>{["UNPAID_LEAVE","ABSENCE","EARNING_CORRECTION"].map(v=><option key={v}>{v}</option>)}</select></label><label className="sm:col-span-2">{t("Explain the earning correction","আয়ের সংশোধনের ব্যাখ্যা")}<input disabled={pending} name="correction_note" className={cls} maxLength={300}/></label><p className="text-sm text-muted-foreground sm:col-span-2">{t("Corrections reduce remuneration expense. Tax, loan recovery and advance offsets must not be entered here; advance recovery belongs to settlement.","সংশোধন পারিশ্রমিকের ব্যয় কমায়। কর, ঋণ বা অগ্রিম সমন্বয় এখানে দেবেন না; অগ্রিম settlement-এ সমন্বয় হবে।")}</p><button className="rounded-lg border p-3" disabled={pending}>{pending?t("Preparing…","প্রস্তুত হচ্ছে…"):t("Preview payroll","বেতনের preview")}</button><button type="button" disabled={pending} onClick={()=>setCreating(false)}>{t("Cancel","বাতিল")}</button></form>
 {preview&&<div className="space-y-4 rounded-xl border p-4"><h3 className="font-semibold">{preview.number} · {preview.name} · {preview.month.slice(0,7)}</h3><div className="grid gap-3 sm:grid-cols-3">{[[t("Prorated base","দিন অনুযায়ী মূল বেতন"),preview.base],[t("Recorded hourly pay","রেকর্ড অনুযায়ী ঘণ্টার আয়"),preview.hourly],[t("Allowances","ভাতা"),preview.allowanceTotal],[t("Gross remuneration","মোট পারিশ্রমিক"),preview.gross],[t("Earning corrections","আয়ের সংশোধন"),preview.corrections],[t("Net salary payable","নিট প্রাপ্য বেতন"),preview.net]].map(([label,n])=><div className="rounded-lg border p-3" key={String(label)}><p className="text-sm">{label}</p><p className="font-semibold">{money(Number(n))}</p></div>)}</div><p>{t("Hours","ঘণ্টা")}: {preview.hours} · {t("Due","প্রাপ্য তারিখ")}: {preview.dueOn}</p>{preview.canPost?<form onSubmit={e=>{e.preventDefault();run({...basis,action:"POST",preview_token:preview.token,reason:String(new FormData(e.currentTarget).get("reason"))});}} className="space-y-3"><label className="block"><input disabled={pending} type="checkbox" required/> {t("I reviewed the agreed terms, attendance and earning adjustments.","শর্ত, উপস্থিতি ও আয়ের সমন্বয় পর্যালোচনা করেছি।")}</label><label className="block">{t("Posting reason","পোস্ট করার কারণ")}<input disabled={pending} name="reason" className={cls} minLength={5} maxLength={1000} required/></label><button className="rounded-lg bg-primary p-3 text-primary-foreground" disabled={pending}>{pending?t("Posting…","পোস্ট হচ্ছে…"):t("Post salary payable","প্রাপ্য বেতন পোস্ট করুন")}</button></form>:<p>{t("Provisional only. Post after this month ends; earlier money is a staff advance.","এটি অস্থায়ী হিসাব। মাস শেষে পোস্ট করুন; তার আগের টাকা স্টাফের অগ্রিম।")}</p>}</div>}
 </section>}
 {pay&&<form className="grid gap-4 rounded-xl border p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run({action:"SETTLE",id:pay.id,cash:Number(f.get("cash")),advance_offset:Number(f.get("advance_offset")),...(f.get("account_id")?{account_id:String(f.get("account_id"))}:{}),...(f.get("advance_id")?{advance_id:String(f.get("advance_id"))}:{}),reference:String(f.get("reference")),reason:String(f.get("reason"))});}}><h2 className="font-semibold sm:col-span-2">{pay.snapshot.name} · {t("Remaining","বাকি")} {money(pay.net-pay.settled)}</h2><label>{t("Actual cash / bank payment","প্রকৃত নগদ / ব্যাংক পরিশোধ")}<input disabled={pending} name="cash" className={cls} type="number" min="0" step="0.01" max={pay.net-pay.settled} defaultValue="0" required/></label><label>{t("Payment account","পরিশোধের অ্যাকাউন্ট")}<select disabled={pending} name="account_id" className={cls}><option value="">{t("Choose…","নির্বাচন করুন…")}</option>{data.accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>{t("Advance to offset","সমন্বয়ের অগ্রিম")}<select disabled={pending} name="advance_id" className={cls}><option value="">{t("No offset","সমন্বয় নেই")}</option>{data.advances.filter(a=>a.staffId===pay.staff_id).map(a=><option value={a.id} key={a.id}>{a.name} · {money(a.balance)}</option>)}</select></label><label>{t("Advance offset amount","অগ্রিম সমন্বয়ের পরিমাণ")}<input disabled={pending} className={cls} name="advance_offset" type="number" min="0" step="0.01" defaultValue="0" required/></label><label>{t("Payment reference","পরিশোধের রেফারেন্স")}<input disabled={pending} name="reference" className={cls} maxLength={300}/></label><label>{t("Reason","কারণ")}<input disabled={pending} className={cls} name="reason" minLength={5} maxLength={1000} required/></label><div className="flex gap-3 sm:col-span-2"><button className="rounded-lg bg-primary p-3 text-primary-foreground" disabled={pending}>{pending?t("Recording…","রেকর্ড হচ্ছে…"):t("Record settlement","পরিশোধ রেকর্ড করুন")}</button><button type="button" disabled={pending} onClick={()=>setPay(null)}>{t("Cancel","বাতিল")}</button></div></form>}
 <div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left">{[t("Staff / month","স্টাফ / মাস"),t("Net salary","নিট বেতন"),t("Settled incl. offsets","সমন্বয়সহ পরিশোধ"),t("Remaining","বাকি"),t("Status / due","অবস্থা / তারিখ"),t("Actions","পদক্ষেপ")].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{data.records.map(r=><tr key={r.id} className="border-b"><td className="p-3">{r.snapshot.number} · {r.snapshot.name}<p className="text-xs">{r.month.slice(0,7)} · {r.payroll_no}</p></td><td>{money(r.net)}</td><td>{money(r.settled)}</td><td>{money(r.net-r.settled)}</td><td><StatusBadge value={r.status}/><p>{r.due_on}</p></td><td><Link className="block underline" href={`/dashboard/finance/payroll/${r.id}/print`}>{t("View / print payslip","বেতন স্লিপ দেখুন / প্রিন্ট")}</Link>{data.manager&&r.net>r.settled&&<button disabled={pending} className="underline" onClick={()=>{setPay(r);setCreating(false);setMessage("");key.current={signature:"",id:""};}}>{t("Pay / offset advance","পরিশোধ / অগ্রিম সমন্বয়")}</button>}</td></tr>)}</tbody></table>{!data.records.length&&<p className="p-5">{t("No fixed/hourly payroll posted yet. Teaching and referral statements remain separate.","Fixed/hourly বেতন এখনো পোস্ট হয়নি। পাঠদান ও রেফারাল হিসাব আলাদা আছে।")}</p>}</div><nav className="flex gap-4">{page>1&&<Link href={`?page=${page-1}`}>{t("Previous","পেছনে")}</Link>}{page*25<data.total&&<Link href={`?page=${page+1}`}>{t("Next","পরবর্তী")}</Link>}<span>{data.total} {t("payslips","বেতন স্লিপ")}</span></nav></div>;
}
