// Generated from fresh SQL function signatures. Run pnpm db:rpc-types.
// RPC-only client intentionally has no direct table-write contract.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
export type AcademyDatabase = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: {
      current_academy_id: { Args: Record<string, never>; Returns: string };
      can_operate: { Args: { permission: string }; Returns: boolean };
      require_operation: { Args: { permission: string }; Returns: string };
      record_activity: { Args: { action_value: string; entity_value: string; id_value: string; reason_value: string; before_value: Json; after_value: Json; request_value?: string }; Returns: undefined };
      reject_record_delete: { Args: Record<string, never>; Returns: unknown };
      reject_evidence_change: { Args: Record<string, never>; Returns: unknown };
      initialize_academy: { Args: { admin_email: string; admin_name: string }; Returns: string };
      save_person: { Args: { p_input: Json }; Returns: Json };
      search_people: { Args: { p_query?: string; p_page?: number }; Returns: Json };
      set_person_responsibility: { Args: { p_input: Json }; Returns: Json };
      save_directory_entry: { Args: { p_input: Json }; Returns: Json };
      search_directory: { Args: { p_kind: string; p_query?: string; p_page?: number; p_include_inactive?: boolean }; Returns: Json };
      lookup_operation: { Args: { request_value: string; command_value: string; payload_value: Json }; Returns: Json };
      finish_operation: { Args: { request_value: string; command_value: string; payload_value: Json; result_value: Json; entity_value: string; id_value: string; before_value: Json }; Returns: Json };
      check_change_reason: { Args: { reason_value: string }; Returns: undefined };
      save_programme: { Args: { p_input: Json }; Returns: Json };
      save_programme_run: { Args: { p_input: Json }; Returns: Json };
      save_run_fees: { Args: { p_input: Json }; Returns: Json };
      save_teaching_batch: { Args: { p_input: Json }; Returns: Json };
      guard_batch_seat: { Args: Record<string, never>; Returns: unknown };
      list_current_programmes: { Args: { p_division_id?: string; p_query?: string; p_page?: number }; Returns: Json };
      public_current_programmes: { Args: Record<string, never>; Returns: Json };
      save_academic_year: { Args: { p_input: Json }; Returns: Json };
      set_programme_run_active: { Args: { p_input: Json }; Returns: Json };
      programme_run_setup: { Args: { p_run_id: string; p_batch_page?: number }; Returns: Json };
      academy_account_context: { Args: Record<string, never>; Returns: Json };
      academy_setup_choices: { Args: Record<string, never>; Returns: Json };
      person_profile: { Args: { p_person_id: string }; Returns: Json };
      save_person_profile: { Args: { p_input: Json }; Returns: Json };
      set_person_active: { Args: { p_input: Json }; Returns: Json };
      search_programme_definitions: { Args: { p_query?: string; p_page?: number }; Returns: Json };
      public_application_choices: { Args: Record<string, never>; Returns: Json };
      receive_public_enquiry: { Args: { p_request_id: string; p_payload: Json }; Returns: Json };
      search_enquiries: { Args: { p_query?: string; p_page?: number }; Returns: Json };
      find_person_matches: { Args: { p_input: Json }; Returns: Json };
      request_academy_access: { Args: { p_input: Json }; Returns: Json };
      list_access_requests: { Args: { p_page?: number; p_history?: boolean }; Returns: Json };
      review_access_request: { Args: { p_input: Json }; Returns: Json };
      complete_access_setup: { Args: { p_request_id: string }; Returns: Json };
      access_setup_request: { Args: { p_request_id: string }; Returns: Json };
      search_people_by_role: { Args: { p_query?: string; p_page?: number; p_responsibility?: string }; Returns: Json };
      protect_current_account_identity: { Args: Record<string, never>; Returns: unknown };
      search_academic_years: { Args: { p_page?: number }; Returns: Json };
      academic_workspace: { Args: { p_page?: number }; Returns: Json };
      academic_command: { Args: { p_request_id: string; p_payload: Json }; Returns: Json };
      claim_academic_emails: { Args: Record<string, never>; Returns: Json };
      finish_academic_email: { Args: { p_id: string; p_lease: string; p_provider_id: string; p_error: string }; Returns: undefined };
      academic_resource_setup: { Args: Record<string, never>; Returns: Json };
      guard_session_teacher_and_blocks: { Args: Record<string, never>; Returns: unknown };
      save_academic_resource: { Args: { p_request_id: string; p_payload: Json }; Returns: Json };
      academic_resource_register: { Args: { p_page?: number }; Returns: Json };
      academic_session_register: { Args: { p_page?: number }; Returns: Json };
      academic_operation_choices: { Args: { p_section?: string }; Returns: Json };
      academic_settings_register: { Args: { p_section: string; p_page?: number }; Returns: Json };
      assign_staff_identity: { Args: Record<string, never>; Returns: unknown };
      protect_staff_identity: { Args: Record<string, never>; Returns: unknown };
      assign_referrer_identity: { Args: Record<string, never>; Returns: unknown };
      resource_window_covers: { Args: { p_academy: string; p_kind: string; p_resource: string; p_start: string; p_end: string }; Returns: boolean };
      preview_academic_schedule: { Args: { p_payload: Json }; Returns: Json };
      academic_calendar: { Args: { p_from: string; p_through: string; p_page?: number; p_status?: string }; Returns: Json };
      academic_session_detail: { Args: { p_id: string }; Returns: Json };
      academic_routine_register: { Args: { p_page?: number }; Returns: Json };
      manage_academic_routine: { Args: { p_request_id: string; p_payload: Json }; Returns: Json };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
