"use client";
import Link from "next/link";
import { OverviewReturnLink } from "@/components/erp/overview-return-link";
import { useLanguage } from "@/components/providers/language-provider";
import type { AuditPageData } from "./queries";
export function AuditView({data,filters,error}:{data:AuditPageData;filters:Record<string,string>;error?:string}){
 const {locale}=useLanguage();const t=(en:string,bn:string)=>locale==="bn"?bn:en;
 const href=(values:Record<string,string>)=>'/dashboard/governance/audit?'+new URLSearchParams(values);
 const today=data.activity.date;const pages=Math.max(1,Math.ceil(data.total/data.pageSize));
 const box="rounded-lg border bg-background p-2";
 return <div className="space-y-5"><header><OverviewReturnLink/><p className="text-xs text-muted-foreground">{t("Governance","পরিচালনা")}</p><h1 className="mt-1 text-2xl font-bold">{t("Audit Trail","কাজের ইতিহাস")}</h1><p className="mt-2 text-sm text-muted-foreground">{t("See who did what and when. Search by person, role, ID, action, record or reason.","কে, কখন, কী কাজ করেছেন দেখুন। নাম, ভূমিকা, আইডি, কাজ, রেকর্ড বা কারণ দিয়ে খুঁজুন।")}</p></header>
 <section className="grid gap-3 sm:grid-cols-3">{data.activity.admissions!==null&&<Link href={href({from:today,to:today,entity:"ADMISSION",action:"FINALIZE"})} className="rounded-xl border p-4"><p>{t("Admissions completed today","আজ সম্পন্ন ভর্তি")}</p><strong>{data.activity.admissions}</strong></Link>}{data.activity.invoices!==null&&<Link href={href({from:today,to:today,preset:"invoices"})} className="rounded-xl border p-4"><p>{t("Invoices issued today","আজ ইস্যু করা ইনভয়েস")}</p><strong>{data.activity.invoices} · BDT {data.activity.grossIssued?.toFixed(2)}</strong><p className="text-xs text-muted-foreground">{t("Original charges before reductions","ছাড়ের আগের মূল চার্জ")}</p></Link>}{data.activity.collected!==null&&<Link href={href({from:today,to:today,entity:"PAYMENT"})} className="rounded-xl border p-4"><p>{t("Money collected today","আজ টাকা আদায়")}</p><strong>BDT {data.activity.collected.toFixed(2)}</strong><p className="text-xs">{t("Refunds paid","ফেরত দেওয়া টাকা")}: BDT {data.activity.refunds?.toFixed(2)}</p></Link>}</section>
 <p className="text-xs text-muted-foreground">{t("Daily totals use Bangladesh time and actual posted records; filters below apply to the event list.","দৈনিক হিসাব বাংলাদেশ সময় ও পোস্ট করা রেকর্ড থেকে আসে; নিচের ফিল্টার কাজের তালিকার জন্য।")}</p>
 <section className="rounded-xl border p-4"><form className="grid gap-3 sm:grid-cols-3">{filters.preset&&<input type="hidden" name="preset" value={filters.preset}/>}<label className="text-sm">{t("Search name, role, ID or reason","নাম, ভূমিকা, আইডি বা কারণ")}<input name="q" defaultValue={filters.q??""} maxLength={160} className={`${box} mt-1 w-full`}/></label><label className="text-sm">{t("Record type","রেকর্ডের ধরন")}<select name="entity" defaultValue={filters.entity??""} className={`${box} mt-1 w-full`}><option value="">{t("All records","সব রেকর্ড")}</option>{['ADMISSION','PAYMENT','INVOICE','PROSPECT','STAFF','STAFF_ACCESS_REQUEST','REFUND','FEE_PLAN','PROGRAMME_OFFERING'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select></label><label className="text-sm">{t("Action","কাজ")}<input name="action" defaultValue={filters.action??""} list="audit-actions" className={`${box} mt-1 w-full`}/><datalist id="audit-actions">{['CREATE','FINALIZE','BILL','POST','POST_REFUND','VERIFY','CORRECT_DETAILS','SAVE_DISCOUNT'].map(v=><option key={v} value={v}/>)}</datalist></label><label className="text-sm">{t("From","শুরু")}<input type="date" name="from" defaultValue={filters.from??""} className={`${box} mt-1 w-full`}/></label><label className="text-sm">{t("To","শেষ")}<input type="date" name="to" defaultValue={filters.to??""} className={`${box} mt-1 w-full`}/></label><div className="flex items-end gap-2"><button className={box}>{t("Search","খুঁজুন")}</button><Link className={box} href="/dashboard/governance/audit">{t("Clear","মুছুন")}</Link></div></form><div className="mt-3 flex gap-2"><Link className={box} href={href({from:today,to:today})}>{t("Today","আজ")}</Link><Link className={box} href={href({entity:"STAFF_ACCESS_REQUEST"})}>{t("Staff access","স্টাফ প্রবেশাধিকার")}</Link><Link className={box} href={href({entity:"ADMISSION"})}>{t("Admissions","ভর্তি")}</Link></div>{error&&<p role="alert" className="mt-3">{t("Check the date range. Start must be on or before end.","তারিখ যাচাই করুন। শুরুর তারিখ শেষের আগে বা সমান হতে হবে।")}</p>}</section>
 <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[850px] text-sm"><thead><tr className="border-b bg-muted/40 text-left">{[["Time","সময়"],["Action","কাজ"],["Entity","রেকর্ড"],["Person / role / ID","ব্যক্তি / ভূমিকা / আইডি"],["Reason","কারণ"]].map(([en,bn])=><th className="p-3" key={en}>{t(en,bn)}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id} className="border-b align-top"><td className="p-3">{new Date(r.occurred_at).toLocaleString(locale==='bn'?'bn-BD':'en-GB',{timeZone:'Asia/Dhaka'})}</td><td className="p-3">{r.action.replaceAll('_',' ')}</td><td className="p-3"><p>{r.entity_type.replaceAll('_',' ')}</p><p className="mt-1 max-w-52 break-all text-xs text-muted-foreground">{r.entity_id}</p></td><td className="p-3"><p className="font-semibold">{r.actor_name??t(r.actor_profile_id?'Authenticated user':'Public / system','সাইন ইন করা ব্যক্তি / পাবলিক সিস্টেম')}</p><p>{r.actor_role_code??'—'}</p><p className="mt-1 max-w-52 break-all text-xs">{r.actor_staff_no??r.actor_profile_id??'—'}</p></td><td className="max-w-80 p-3">{r.reason??'—'}</td></tr>)}</tbody></table>{!data.rows.length&&<p className="p-5">{t("No matching events.","মিল পাওয়া যায়নি।")}</p>}</div>
 <nav className="flex items-center justify-between" aria-label="Audit pages"><p className="text-sm">{data.total} {t("events","রেকর্ড")} · {t("Page","পৃষ্ঠা")} {data.page}/{pages}</p><div className="flex gap-2">{data.page>1&&<Link className={box} href={href({...filters,page:String(data.page-1)})}>{t("Previous","পেছনে")}</Link>}{data.page<pages&&<Link className={box} href={href({...filters,page:String(data.page+1)})}>{t("Next","পরবর্তী")}</Link>}</div></nav>
 </div>;
}
