"use client";
import {useRef,useState} from "react";
import {useRouter} from "next/navigation";
export type DocumentEvidence={id:string;name:string;size:number;note:string;date:string;actor:string|null};
export function DocumentPanel({entityType,entityId,documents=[]}:{entityType:"PURCHASE"|"EXPENSE"|"REIMBURSEMENT"|"ASSET";entityId:string;documents?:DocumentEvidence[]}){
 const router=useRouter();const [pending,setPending]=useState(false);const [message,setMessage]=useState("");const identity=useRef<{fingerprint:string;id:string}|null>(null);
 async function upload(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(pending)return;const form=e.currentTarget;const body=new FormData(form);const file=body.get("file");if(!(file instanceof File))return;const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await file.arrayBuffer()))).map(x=>x.toString(16).padStart(2,"0")).join("");const fingerprint=JSON.stringify([hash,file.name,body.get("note"),entityId]);if(identity.current?.fingerprint!==fingerprint)identity.current={fingerprint,id:crypto.randomUUID()};body.set("request_id",identity.current!.id);body.set("entity_type",entityType);body.set("entity_id",entityId);setPending(true);try{const response=await fetch("/api/finance/documents",{method:"POST",body});const result=await response.json();setMessage(result.message);if(result.ok){form.reset();identity.current=null;router.refresh();}}catch{setMessage("Could not confirm upload. Keep the selected file and retry unchanged.");}finally{setPending(false);}}
 return <details className="rounded border p-3"><summary className="cursor-pointer">Document evidence · {documents.length} files</summary><div className="space-y-3 pt-3"><p className="text-sm">Private PDF/JPEG/PNG, up to 5 MB each. Recorded evidence is retained; attach a corrected document with an explanation instead of replacing the original.</p>{documents.map(d=><div key={d.id} className="border-b py-2"><a href={`/api/finance/documents/${d.id}`} target="_blank" rel="noopener noreferrer" className="underline">{d.name}</a><p>{d.note}</p><p className="text-sm text-muted-foreground">{d.actor??"Staff"} · {new Date(d.date).toLocaleString()} · {Math.ceil(d.size/1024)} KB</p></div>)}<form onSubmit={upload} className="space-y-2"><fieldset disabled={pending} className="space-y-2"><label className="grid gap-1">Document<input name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/></label><label className="grid gap-1">Evidence note<textarea name="note" required minLength={5} maxLength={1000} className="w-full rounded border bg-background p-2"/></label><button type="submit" className="rounded border px-3 py-2">{pending?"Uploading…":"Attach document"}</button></fieldset></form>{message&&<p role="status">{message}</p>}</div></details>;
}
