"use client";
import {startTransition,useState} from "react";
import {adjustmentAction} from "./adjustment-actions";
export type PurchaseAdjustment={id:string;kind:string;reference:string;date:string;amount:number;credit:number;cash:number;due:number;reason:string};
export function PurchaseAdjustments({purchaseId,total,adjustments,accounts,canPay}:{purchaseId:string;total:number;adjustments:PurchaseAdjustment[];accounts:{id:string;name:string}[];canPay:boolean}){
 const [target,setTarget]=useState<string|null|undefined>();const [pending,setPending]=useState(false);const [notice,setNotice]=useState("");const [request,setRequest]=useState("");const [last,setLast]=useState("");const remaining=total-adjustments.reduce((n,a)=>n+a.amount,0);
 function open(value:string|null){setTarget(value);setRequest(crypto.randomUUID());setLast("");setNotice("");}
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(pending)return;const v=Object.fromEntries(new FormData(e.currentTarget));const input={...v,amount:Number(v.amount),...(target?{action:"COLLECT_REFUND",adjustment_id:target}:{action:"ADJUST",purchase_id:purchaseId,confirmed:v.confirmed==="on",cash_refund:Number(v.cash_refund??0)}),...(v.payment_account_id?{payment_account_id:v.payment_account_id}:{payment_account_id:undefined})};const fingerprint=JSON.stringify(input);const id=last&&last!==fingerprint?crypto.randomUUID():request;setRequest(id);setLast(fingerprint);setPending(true);startTransition(async()=>{try{const r=await adjustmentAction({...input,request_id:id});setNotice(r.message);if(r.ok)setTarget(undefined);}finally{setPending(false);}});}
 return <details className="rounded border p-3"><summary>Returns & expense corrections · {adjustments.length}</summary><div className="space-y-3 pt-3">{adjustments.map(a=><div key={a.id} className="border-b py-2"><p>{a.kind} · {a.reference} · {a.date}</p><p>Reduction BDT {a.amount.toFixed(2)} · payable credit {a.credit.toFixed(2)} · cash refunded {a.cash.toFixed(2)} · refund still due {a.due.toFixed(2)}</p><p>{a.reason}</p>{a.due>0&&canPay&&<button disabled={pending} onClick={()=>open(a.id)}>Collect supplier refund</button>}</div>)}{remaining>0&&<button disabled={pending} onClick={()=>open(null)}>Record return / reduce incorrect expense</button>}{notice&&<p role="status">{notice}</p>}{target!==undefined&&<form key={target??"new"} onSubmit={save} className="space-y-3"><fieldset disabled={pending} className="grid gap-3"><p>{target?"Record an actual supplier refund received.":`Reduce the expense using verified credit/correction evidence. Maximum BDT ${remaining.toFixed(2)}. Unpaid supplier balance is credited first; any paid amount not refunded becomes supplier refund receivable.`}</p>{!target&&<label>Type<select name="kind" className="ml-2 rounded border bg-background p-2"><option value="RETURN">Supplier return / credit note</option><option value="CORRECTION">Correct an overstated expense</option></select></label>}<label>Amount (BDT)<input name="amount" type="number" min="0.01" step="0.01" required className="ml-2 rounded border bg-background p-2"/></label><label>Date<input name="date" type="date" required className="ml-2 rounded border bg-background p-2"/></label><label>Credit note / correction / refund reference<input name="reference" minLength={3} required className="ml-2 rounded border bg-background p-2"/></label>{!target&&canPay&&<label>Cash refund actually received now (BDT)<input name="cash_refund" type="number" min="0" step="0.01" defaultValue="0" className="ml-2 rounded border bg-background p-2"/></label>}{canPay&&<label>Receiving account (required for actual cash refund)<select name="payment_account_id" className="ml-2 rounded border bg-background p-2" defaultValue=""><option value="">No cash received</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}<label>Explanation<textarea name="reason" minLength={10} maxLength={1000} required className="w-full rounded border bg-background p-2"/></label>{!target&&<label><input type="checkbox" name="confirmed" required/>Verified return / correction and supporting evidence</label>}<div className="flex gap-3"><button type="submit">{pending?"Posting…":"Post compensating entry"}</button><button type="button" onClick={()=>setTarget(undefined)}>Close</button></div></fieldset></form>}</div></details>;
}
