"use client";
import {startTransition,useState} from "react";
import Link from "next/link";
import {directoryAction} from "./directory-actions";
import type {DirectoryData} from "./directory-queries";
type Row=DirectoryData["rows"][number];
export function PurchaseDirectory({data,search}:{data:DirectoryData;search:string}){
 const [editing,setEditing]=useState<Row|null|undefined>();const [pending,setPending]=useState(false);const [message,setMessage]=useState<{ok:boolean;message:string}|null>(null);const [request,setRequest]=useState("");const [last,setLast]=useState("");
 function open(row:Row|null){setEditing(row);setMessage(null);setRequest(crypto.randomUUID());setLast("");}
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(pending)return;const values=Object.fromEntries(new FormData(e.currentTarget));const input={...values,kind:data.kind,is_active:values.is_active==="on",...(editing?{id:editing.id,token:editing.token,expected_updated_at:editing.token}:{})};const fingerprint=JSON.stringify(input);const req=last&&last!==fingerprint?crypto.randomUUID():request;setRequest(req);setLast(fingerprint);setPending(true);startTransition(async()=>{try{const result=await directoryAction({...input,request_id:req});setMessage(result);if(result.ok)setEditing(undefined);}finally{setPending(false);}});}
 const label=data.kind==="VENDOR"?"supplier":"expense category";
 return <div className="space-y-4"><div className="flex gap-4"><Link href="?view=directory&kind=VENDOR">Suppliers</Link><Link href="?view=directory&kind=CATEGORY">Expense categories</Link><button disabled={pending} onClick={()=>open(null)}>Create {label}</button></div>
 <p className="text-sm text-muted-foreground">Deactivate records instead of deleting history. Category changes affect future expense postings; previously posted ledger amounts and accounts remain unchanged.</p>
 {message&&<p role={message.ok?"status":"alert"}>{message.message}</p>}
 {editing!==undefined&&<form key={editing?.id??"new"} onSubmit={save} className="space-y-3 rounded border p-5"><h2 className="text-xl">{editing?"Edit":"Create"} {label}</h2><fieldset disabled={pending} className="grid gap-4 md:grid-cols-2"><label className="grid gap-1">Name<input name="name" required minLength={2} maxLength={200} defaultValue={editing?.name} className="rounded border bg-background p-2"/></label>{data.kind==="VENDOR"?<>{(["mobile","email","address","service_category"] as const).map(key=><label className="grid gap-1" key={key}>{key.replace("_"," ")} (optional)<input name={key} type={key==="email"?"email":"text"} defaultValue={editing?.[key]??""} className="rounded border bg-background p-2"/></label>)}{editing&&<p>Permanent supplier ID: {editing.code}</p>}</>:<><label className="grid gap-1">Permanent code<input name="code" required pattern="[A-Z][A-Z0-9_]{1,49}" defaultValue={editing?.code} readOnly={!!editing} className="rounded border bg-background p-2"/></label><label className="grid gap-1">Expense ledger account<select name="expense_account_id" defaultValue={editing?.expense_account_id??""} required className="rounded border bg-background p-2"><option value="">Select account</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name}{a.active?"":" · inactive"}</option>)}</select></label></>}
 <label className="flex items-center gap-2"><input type="checkbox" name="is_active" defaultChecked={editing?.is_active??true}/>Active for new purchases</label><label className="grid gap-1">Reason<textarea name="reason" minLength={5} maxLength={1000} required className="rounded border bg-background p-2"/></label><button type="submit" className="rounded bg-primary p-2 text-primary-foreground">{pending?"Saving…":"Save"}</button><button type="button" onClick={()=>setEditing(undefined)}>Close</button></fieldset></form>}
 <form className="flex gap-3"><input type="hidden" name="view" value="directory"/><input type="hidden" name="kind" value={data.kind}/><input aria-label="Search directory" name="q" maxLength={100} defaultValue={search} className="rounded border bg-background p-2"/><button>Search</button></form>
 <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["ID / name","Contact / account","Status","Action"].map(x=><th key={x} className="p-3 text-left">{x}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.code}<p className="font-semibold">{r.name}</p></td><td className="p-3">{data.kind==="VENDOR"?<>{r.mobile}<p>{r.email}</p><p>{r.address}</p></>:data.accounts.find(a=>a.id===r.expense_account_id)?.name}</td><td className="p-3">{r.is_active?"ACTIVE":"INACTIVE"}</td><td className="p-3"><button disabled={pending} onClick={()=>open(r)}>Edit / {r.is_active?"mark inactive":"reactivate"}</button></td></tr>)}</tbody></table></div><div className="flex justify-between"><p>{data.total} records · page {data.page}</p><div className="flex gap-3">{data.page>1&&<Link href={`?${new URLSearchParams({view:"directory",kind:data.kind,page:String(data.page-1),q:search})}`}>Previous</Link>}{data.page*25<data.total&&<Link href={`?${new URLSearchParams({view:"directory",kind:data.kind,page:String(data.page+1),q:search})}`}>Next</Link>}</div></div></div>;
}
