"use client";
import Link from "next/link";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {useLanguage} from "@/components/providers/language-provider";
import {previewClose,closeAction} from "./actions";
import type {CloseData,ClosePreview} from "./queries";
const cls="mt-1 w-full rounded-lg border bg-background p-3";
const denominations=[1000,500,200,100,50,20,10,5,2,1];
const money=(n:number)=>`BDT ${n.toFixed(2)}`;
export function DailyCloseRegister({data,page}:{data:CloseData;page:number}){
 const {locale}=useLanguage();const t=(en:string,bn:string)=>locale==="bn"?bn:en;const router=useRouter();const [creating,setCreating]=useState(false),[preview,setPreview]=useState<ClosePreview|null>(null),[counts,setCounts]=useState<Record<number,number>>({}),[actual,setActual]=useState(0),[message,setMessage]=useState("");const [review,setReview]=useState<{id:string;action:string}|null>(null);const [pending,start]=useTransition();const key=useRef({signature:"",id:""});
 const physical=denominations.reduce((s,n)=>s+n*(counts[n]??0),0),balance=preview?.subtype==="CASH"?physical:actual;
 function run(values:Record<string,unknown>){const signature=JSON.stringify(values);if(signature!==key.current.signature)key.current={signature,id:crypto.randomUUID()};start(async()=>{const r=await closeAction({...values,request_id:key.current.id});setMessage(r.message);if(r.ok){setCreating(false);setPreview(null);setReview(null);key.current={signature:"",id:""};router.refresh();}});}
 return <div className="space-y-5"><button className="rounded-lg border p-3" disabled={pending} onClick={()=>{setCreating(!creating);setPreview(null);setCounts({});setActual(0);setReview(null);setMessage("");}}>{t("Count cash / match statement","নগদ গণনা / স্টেটমেন্ট মিলান")}</button>{message&&<p className="rounded-xl border p-4" role="status">{message}</p>}
 {creating&&<section className="space-y-4 rounded-2xl border p-5"><form className="grid gap-4 sm:grid-cols-2" onChange={()=>setPreview(null)} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);start(async()=>{const r=await previewClose({account_id:String(f.get("account_id")),date:String(f.get("date"))});if(r.ok){setPreview(r.preview);setCounts({});setActual(0);setMessage("");}else setMessage(r.message);});}}><label>{t("Cash / bank / mobile account","নগদ / ব্যাংক / মোবাইল অ্যাকাউন্ট")}<select disabled={pending} name="account_id" className={cls} required><option value="">{t("Choose…","নির্বাচন করুন…")}</option>{data.accounts.map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><label>{t("Close date (Bangladesh)","হিসাবের তারিখ (বাংলাদেশ)")}<input disabled={pending} name="date" type="date" defaultValue={new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Dhaka",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())} className={cls} required/></label><button disabled={pending} className="rounded-lg border p-3">{pending?t("Loading…","লোড হচ্ছে…"):t("Review ledger balance","Ledger balance দেখুন")}</button><button type="button" disabled={pending} onClick={()=>setCreating(false)}>{t("Cancel","বাতিল")}</button></form>
 {preview&&<form className="space-y-4 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run({action:"COUNT",account_id:preview.accountId,date:preview.date,preview_token:preview.token,actual:balance,...(preview.subtype==="CASH"?{denominations:denominations.map(n=>({value:n,count:counts[n]??0}))}:{}),statement_reference:String(f.get("statement_reference")),variance_note:String(f.get("variance_note")),reason:String(f.get("reason")),...(f.get("handed_to")?{handed_to:String(f.get("handed_to"))}:{})});}}><h2 className="font-semibold">{preview.name} · {preview.date}</h2><div className="grid gap-3 sm:grid-cols-4">{[[t("Opening ledger balance","শুরুর ledger balance"),preview.opening],[t("Debits / receipts","ডেবিট / আদায়"),preview.receipts],[t("Credits / payments","ক্রেডিট / পরিশোধ"),preview.payments],[t("Expected closing balance","প্রত্যাশিত শেষ balance"),preview.expected]].map(([label,n])=><div className="rounded-lg border p-3" key={String(label)}><p className="text-sm">{label}</p><strong>{money(Number(n))}</strong></div>)}</div>
 {preview.subtype==="CASH"?<div className="grid gap-3 sm:grid-cols-5">{denominations.map(n=><label key={n}>BDT {n} ×<input disabled={pending} aria-label={`BDT ${n} count`} className={cls} type="number" min="0" max="1000000" step="1" value={counts[n]??0} onChange={e=>setCounts({...counts,[n]:Number(e.target.value)})} required/></label>)}</div>:<label className="block">{t("Actual statement closing balance (BDT)","স্টেটমেন্টের প্রকৃত শেষ balance (টাকা)")}<input disabled={pending} type="number" step="0.01" className={cls} required value={actual} onChange={e=>setActual(Number(e.target.value))}/></label>}
 <p className="text-lg font-semibold">{t("Actual","প্রকৃত")}: {money(balance)} · {t("Difference","পার্থক্য")}: {money(balance-preview.expected)}</p><div className="grid gap-4 sm:grid-cols-2"><label>{t("Cash count / statement reference","নগদ গণনা / স্টেটমেন্ট রেফারেন্স")}<input disabled={pending} name="statement_reference" className={cls} minLength={3} maxLength={300} required/></label><label>{t("Handed to (optional)","হস্তান্তর গ্রহণকারী (ঐচ্ছিক)")}<select disabled={pending} name="handed_to" className={cls}><option value="">{t("No handover","হস্তান্তর নেই")}</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="sm:col-span-2">{t("Explain any difference","পার্থক্যের ব্যাখ্যা")}<textarea disabled={pending} name="variance_note" className={cls} required={balance!==preview.expected} minLength={balance!==preview.expected?10:undefined} maxLength={1000}/></label><label className="sm:col-span-2">{t("Review / handover note","পর্যালোচনা / হস্তান্তরের নোট")}<textarea disabled={pending} name="reason" className={cls} required minLength={5} maxLength={1000}/></label></div><p className="text-sm text-muted-foreground">{t("This records count evidence; it neither changes the ledger nor locks financial posting. Later backdated postings mark this evidence stale. A difference must be investigated and recounted, not hidden.","এটি গণনার প্রমাণ রাখে; ledger পরিবর্তন বা posting বন্ধ করে না। পরের backdated posting হলে পুরোনো প্রমাণ stale হয়। পার্থক্য তদন্ত করে আবার গণনা করতে হবে, লুকানো যাবে না।")}</p><button disabled={pending} className="rounded-lg bg-primary p-3 text-primary-foreground">{pending?t("Recording…","রেকর্ড হচ্ছে…"):t("Record close evidence","শেষ হিসাবের প্রমাণ রেকর্ড করুন")}</button></form>}
 </section>}
 {review&&<form className="space-y-3 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();run({...review,reason:String(new FormData(e.currentTarget).get("reason"))});}}><h3 className="font-semibold">{review.action}</h3><p className="text-sm">{t("Resolution requires a fresh matching count or statement if there was a difference or the ledger changed. Previous evidence remains intact.","পার্থক্য বা ledger পরিবর্তন থাকলে সমাধানের জন্য নতুন matching count / statement লাগবে। আগের প্রমাণ অক্ষত থাকে।")}</p><label className="block">{t("Investigation / resolution explanation","তদন্ত / সমাধানের ব্যাখ্যা")}<textarea disabled={pending} name="reason" required minLength={5} maxLength={1000} className={cls}/></label><button disabled={pending} className="rounded-lg border p-3">{pending?t("Saving…","সংরক্ষণ হচ্ছে…"):t("Confirm","নিশ্চিত করুন")}</button><button type="button" disabled={pending} onClick={()=>setReview(null)} className="ml-3">{t("Cancel","বাতিল")}</button></form>}
 <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b text-left">{[t("Close / account","শেষ হিসাব / অ্যাকাউন্ট"),t("Expected","প্রত্যাশিত"),t("Actual / difference","প্রকৃত / পার্থক্য"),t("Recorded by / handover","রেকর্ডকারী / হস্তান্তর"),t("Status / actions","অবস্থা / পদক্ষেপ")].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{data.records.map(r=><tr key={r.id} className="border-b align-top"><td className="p-3"><strong>{r.close_no}</strong><p>{r.name} · {r.close_date}</p><details><summary className="cursor-pointer">{t("Evidence and notes","প্রমাণ ও নোট")}</summary><p>{r.statement_reference} · {r.explanation}</p>{r.notes.map((n,i)=><p key={i}>{n.date.slice(0,10)} · {n.action} · {n.reason}</p>)}</details></td><td className="p-3">{money(r.expected)}</td><td className="p-3">{money(r.actual)}<p className={r.variance===0?"text-emerald-600":"text-amber-600"}>{money(r.variance)}</p></td><td className="p-3">{r.actor??"—"}<p>{r.receiver??t("No handover","হস্তান্তর নেই")}</p></td><td className="space-y-2 p-3"><p className={(r.resolution==="RESOLVE"&&!r.resolution_stale)||(!r.stale&&r.variance===0&&r.resolution!=="REOPEN")?"text-emerald-600":"text-amber-600"}>{r.resolution==="RESOLVE"&&!r.resolution_stale?t("Resolved","সমাধান হয়েছে"):r.resolution==="REOPEN"?t("Reopened","পুনরায় খোলা"):r.stale?t("Ledger changed · recount required","Ledger বদলেছে · পুনর্গণনা দরকার"):r.variance===0?t("Matched","মিলেছে"):t("Difference needs investigation","পার্থক্যের তদন্ত প্রয়োজন")}</p>{["NOTE","RESOLVE","REOPEN"].map(a=><button disabled={pending} key={a} className="mr-3 underline" onClick={()=>{setReview({id:r.id,action:a});setCreating(false);setMessage("");key.current={signature:"",id:""};}}>{a==="NOTE"?t("Add note","নোট দিন"):a==="RESOLVE"?t("Resolve","সমাধান"):t("Reopen","আবার খুলুন")}</button>)}</td></tr>)}</tbody></table>{!data.records.length&&<p className="p-5">{t("No close evidence yet.","শেষ হিসাবের প্রমাণ এখনো নেই।")}</p>}</div><nav className="flex gap-4">{page>1&&<Link href={`?page=${page-1}`}>{t("Previous","পেছনে")}</Link>}{page*25<data.total&&<Link href={`?page=${page+1}`}>{t("Next","পরবর্তী")}</Link>}<span>{data.total} {t("records","রেকর্ড")}</span></nav></div>;
}
