import type { ReactNode } from "react";
import { admissionPrintStyles } from "./document-styles";
import { amountInWords } from "@/lib/academy/money-in-words";
type PaperData={discountPercent?:number;discountReason?:string|null;academyRoll?:string|null;additionalDetails?:Record<string,string|null>;number?:string;name?:string;nameBn?:string|null;dateOfBirth?:string|null;gender?:string|null;schoolName?:string|null;schoolRoll?:string|null;guardian?:string;guardianRelationship?:string|null;mobile?:string;alternateMobile?:string|null;guardianAddress?:string|null;offeringName?:string;className?:string;yearName?:string;batchName?:string;studentNo?:string|null;components?:{name:string;amount:number;recurrence:string}[];invoice?:{number:string;total:number;net?:number;due:number;paid:number}|null;receipts?:{number:string;amount:number;method:string;postedAt:string;refunded:number}[]};
export type PaperCatalogue={offerings:{id:string;name:string}[];subjects:{id:string;name:string}[]};
function Field({label,value,wide=false,tall=false}:{label:string;value?:string|null;wide?:boolean;tall?:boolean}){return <div className={`paper-field ${wide?"paper-wide":""} ${tall?"paper-address":""}`}><span>{label}</span><div>{value||"\u00a0"}</div></div>;}
function NameBoxes({label,value}:{label:string;value?:string|null}){const letters=Array.from((value??"").toUpperCase());return <div className="paper-name"><span>{label} · CAPITAL LETTERS / বড় হাতের অক্ষর</span>{letters.length>36?<div className="paper-long-name">{value}</div>:<div className="paper-boxes">{Array.from({length:36},(_,i)=><b key={i}>{letters[i]??"\u00a0"}</b>)}</div>}</div>;}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="paper-section"><h2>{title}</h2>{children}</section>;}
function Header({title,reference,page}:{title:string;reference?:string;page?:string}){return <><div className="paper-letterhead-space" aria-label="Space for preprinted letterhead"/><header className="paper-header"><div><h1>{title}</h1><p>Reference: {reference||"________________________"}</p></div><p>{page}</p></header></>;}
export function AdmissionPaper({data:a={},receiptOnly,academyName:_academyName,catalogue={offerings:[],subjects:[]}}:{data?:PaperData;receiptOnly?:string;academyName?:string;catalogue?:PaperCatalogue}){
 const receipt=a.receipts?.find(r=>r.number===receiptOnly),x=a.additionalDetails??{};
 return <><style>{admissionPrintStyles}</style><article className="admission-paper">
 {!receiptOnly&&<section className="paper-page"><Header title="Admission application / ভর্তি আবেদন" reference={a.number} page="01 / 02"/>
 <p className="paper-note">Tick the relevant choices. Write names in capital letters; Bangla names may be written normally. Office fields are completed by staff. This application alone does not confirm admission.</p>
 <Section title="01 · Student information / শিক্ষার্থীর তথ্য"><NameBoxes label="Student full name (English)" value={a.name}/><div className="paper-grid"><Field label="Name in Bangla" value={a.nameBn} wide/><Field label="Date of birth" value={a.dateOfBirth}/><Field label="Gender" value={a.gender||"□ Female  □ Male  □ Other"}/><Field label="Student mobile (optional)" value={x.student_mobile}/><Field label="Student email (optional)" value={x.student_email}/><Field label="School / college" value={a.schoolName} wide/><Field label="Current class / group" value={a.className}/><Field label="School roll" value={a.schoolRoll}/><Field label="Birth registration (optional)" value={x.birth_registration}/><Field label="Previous exam / result" value={x.previous_result}/></div></Section>
 <Section title="02 · Family and contact / অভিভাবক ও যোগাযোগ"><NameBoxes label="Father’s name (optional)" value={x.father_name}/><NameBoxes label="Mother’s name (optional)" value={x.mother_name}/><NameBoxes label="Primary guardian full name" value={a.guardian}/><div className="paper-grid"><Field label="Relationship" value={a.guardianRelationship||"□ Father □ Mother □ Other"}/><Field label="Guardian mobile" value={a.mobile}/><Field label="Alternate mobile" value={a.alternateMobile}/><Field label="Emergency mobile" value={x.emergency_mobile}/><Field label="Present address: village/road, ward, post, upazila, district" value={a.guardianAddress} wide tall/><Field label="Nearby landmark / special location" value={x.present_landmark} wide/><Field label="Permanent address · □ Same as present address" value={x.permanent_same_as_present==="true"?"☑ Same as present address":x.permanent_address} wide tall/></div></Section>
 <Section title="03 · Programme preferences / পছন্দের প্রোগ্রাম"><div className="paper-options">{catalogue.offerings.length?catalogue.offerings.map(o=><span key={o.id}>□ {o.name}</span>):<span>{a.offeringName||"Programme: __________________________________________"}</span>}</div><div className="paper-options">{catalogue.subjects.map(s=><span key={s.id}>□ {s.name}</span>)}</div><p className="paper-note">Schedule: □ Morning □ Afternoon □ Evening □ Flexible · Placement will be verified by staff.</p><Field label="Learning / health / accessibility support (optional)" value={x.learning_needs} wide/></Section>
 <footer className="paper-footer"><span>{a.number||"Application desk copy"}</span><span>Continue declaration and office record on page 2</span></footer></section>}
 <section className={`paper-page ${receiptOnly?"paper-receipt-only":""}`}><Header title={receiptOnly?"Money receipt / প্রাপ্তি স্বীকারপত্র":"Declaration and office record"} reference={receipt?.number??a.number} page={receiptOnly?undefined:"02 / 02"}/>
 {!receiptOnly&&<><Section title="04 · Declaration and consent / ঘোষণা ও সম্মতি"><p>I confirm the supplied information is accurate to the best of my knowledge. I have reviewed the placement, charges and any discount below. I consent to keeping the student’s academy records and contacting the family for academic support. Unpaid charges remain due; payment receipts acknowledge only money actually received.</p><p className="paper-note">আমি প্রদত্ত তথ্য, ভর্তি ও ফি সংক্রান্ত শর্ত যাচাই করেছি। শিক্ষার্থীর শিক্ষা কার্যক্রম ও প্রয়োজনীয় যোগাযোগের জন্য সম্মতি দিচ্ছি।</p><div className="paper-signatures"><div>Guardian signature / date (required)</div><div>Student signature / date (if able)</div></div></Section>
 <Section title="05 · Office use only / শুধু অফিসের জন্য"><div className="paper-grid"><Field label="Academic year / class" value={a.yearName?`${a.yearName} / ${a.className??""}`:undefined}/><Field label="Batch / class time" value={a.batchName}/><Field label="Verified programme" value={a.offeringName} wide/><Field label="System Student ID" value={a.studentNo}/><Field label="Academy roll (system assigned)" value={a.academyRoll}/><Field label="Source / referrer"/><Field label="Referrer mobile / record ID"/></div><p className="paper-note">□ Identity/contact verified □ Placement checked □ Referral recorded □ Signed original filed</p></Section>
 <Section title="06 · Charges and collection / ফি ও আদায়"><table className="paper-table"><thead><tr><th>Charge</th><th>Frequency</th><th>BDT</th></tr></thead><tbody>{a.components?.length?a.components.map((c,i)=><tr key={i}><td>{c.name}</td><td>{c.recurrence.replaceAll("_"," ")}</td><td>{c.amount.toFixed(2)}</td></tr>):["Tuition","Admission / registration","Exam / materials / other"].map(c=><tr key={c}><td>{c}</td><td>________________</td><td>_______________</td></tr>)}</tbody></table><p className="paper-note">Tuition discount: {[0,5,10,15,20,25,30].map(p=>`${a.discountPercent===p?"☑":"□"} ${p?p+"%":"None"}`).join(" · ")}</p><p className="paper-note">Reason: {a.discountReason?.replaceAll("_"," ")||"□ Hardship □ Sibling □ Merit □ Launch □ Staff family □ Other"}</p><div className="paper-grid"><Field label="Invoice reference" value={a.invoice?.number}/><Field label="Net charges / unpaid balance (BDT)" value={a.invoice?`${(a.invoice.net??a.invoice.total).toFixed(2)} / ${a.invoice.due.toFixed(2)}`:undefined}/><Field label="Money received now (write 0 if unpaid)"/><Field label="Method / transaction reference"/></div><div className="paper-signatures"><div>Recorded / verified by · signature and date</div><div>Academy seal (office use)</div></div></Section></>}
 <section className="paper-receipt"><p className="paper-note">{receipt?"Evidence of actual recorded payment":"DETACH HERE · Give to guardian only when money is received"}</p><h2>Money receipt / প্রাপ্তি স্বীকারপত্র</h2><div className="paper-grid"><Field label="Receipt / date" value={receipt?`${receipt.number} / ${new Date(receipt.postedAt).toLocaleDateString("en-GB",{timeZone:"Asia/Dhaka"})}`:undefined}/><Field label="Student ID / application" value={a.studentNo??a.number}/><Field label="Student / guardian" value={a.name?`${a.name} / ${a.guardian??""}`:undefined} wide/><Field label="Actual amount received (BDT)" value={receipt?.amount.toFixed(2)}/><Field label="Payment method" value={receipt?.method}/><Field label="Amount in words / কথায়" value={receipt?amountInWords(receipt.amount):undefined} wide/><Field label="Current unpaid invoice balance (BDT)" value={a.invoice?.due.toFixed(2)} wide/></div><div className="paper-signatures"><div>Received by / signature / seal</div><div>Guardian acknowledgement (optional)</div></div><p className="paper-note">{receipt?`Original payment retained. Subsequent refunds: BDT ${receipt.refunded.toFixed(2)}.`:"Enter manual collection in ERP once, using this paper receipt reference. No payment means no receipt."}</p></section>
 <footer className="paper-footer"><span>{receipt?.number??a.number??"Keep signed original in student file"}</span><span>{receiptOnly?"Payment evidence":"Office copy · 02 / 02"}</span></footer></section>
 </article></>;
}
