/** Monochrome A4 layout: all essential rules print without background graphics. */
export const admissionPrintStyles = `
.admission-paper{color:#111;background:#fff;width:210mm;max-width:100%;margin:auto;font:10pt/1.35 Arial,"Noto Sans Bengali",sans-serif}
.paper-page{min-height:297mm;padding:12mm 14mm;box-sizing:border-box;background:#fff;margin-bottom:16px;border:1px solid #ccc;position:relative}
.paper-header{display:flex;justify-content:space-between;align-items:start;border-bottom:2px solid #111;padding-bottom:4mm;margin-bottom:4mm;gap:8mm}
.paper-header>div:first-child{padding-left:16mm;position:relative}.paper-header>div:first-child:before{content:"SA";position:absolute;left:0;top:0;border:1.5px solid #111;font:bold 17pt Arial;width:12mm;height:12mm;display:flex;align-items:center;justify-content:center}
.paper-header h1{font-size:20pt;letter-spacing:.4pt;font-weight:800;margin:0;text-transform:uppercase}.paper-header p{margin:1.2mm 0;font-size:8pt}.paper-photo{border:1px solid #777;width:24mm;height:29mm;flex-shrink:0;text-align:center;padding-top:9mm;box-sizing:border-box;font-size:7pt}
.paper-title{font-size:13pt;font-weight:700;margin:0 0 3mm;text-transform:uppercase;letter-spacing:.6pt}.paper-section{margin:4mm 0;break-inside:avoid}.paper-section h2{font-size:9pt;font-weight:700;border-bottom:1px solid #111;border-left:3px solid #111;padding:1.5mm 2.5mm;margin:0 0 2mm;text-transform:uppercase;letter-spacing:.2pt}
.paper-grid{display:grid;grid-template-columns:1fr 1fr;gap:1.5mm 5mm}.paper-field{display:flex;align-items:stretch;min-height:8mm;border:1px solid #aaa}.paper-field span{display:flex;align-items:center;width:42%;flex-shrink:0;padding:1.5mm 2mm;font-size:7.2pt;font-weight:600;border-right:1px solid #aaa;box-sizing:border-box;color:#222}.paper-field>div{flex:1;min-width:0;padding:1.5mm 2mm;font-size:9pt;overflow-wrap:anywhere}.paper-wide{grid-column:1/-1}.paper-wide span{width:25%}
.paper-note{font-size:7.5pt;margin:2mm 0;line-height:1.4}.paper-signatures{display:grid;grid-template-columns:1fr 1fr;gap:9mm;margin-top:9mm}.paper-signatures>div{border-top:1px solid #333;padding-top:1.5mm;font-size:7.5pt}
.paper-page:last-child{font-size:9pt;line-height:1.3}.paper-page:last-child .paper-header h1{font-size:18pt}.paper-page:last-child .paper-section{margin:3mm 0}.paper-page:last-child .paper-field{min-height:7mm}.paper-page:last-child .paper-grid{gap:1.5mm 5mm}.paper-page:last-child .paper-signatures{margin-top:7mm}
.paper-table{width:100%;border-collapse:collapse;font-size:8pt}.paper-table th,.paper-table td{border:1px solid #999;padding:1.5mm 2mm;text-align:left}.paper-table th{font-size:7.5pt;text-transform:uppercase}
.paper-receipt{border:1px solid #777;border-top:2px dashed #333;margin-top:5mm;padding:3mm;break-inside:avoid}.paper-receipt h2{font-size:11pt;font-weight:700;margin:0 0 2mm;text-transform:uppercase}.paper-receipt .paper-field{border:0;border-bottom:1px solid #aaa;min-height:6mm}.paper-receipt .paper-field span{border:0;width:48%;padding-left:0}.paper-footer{border-top:1px solid #777;margin-top:4mm;padding-top:2mm;display:flex;justify-content:space-between;font-size:7pt;color:#333}
@media print{body *{visibility:hidden}.admission-paper,.admission-paper *{visibility:visible}.admission-paper{position:absolute;left:0;top:0;width:100%;max-width:none}.paper-page{min-height:0;height:273mm;padding:0;border:0;margin:0;break-after:page;overflow:visible}.paper-page:last-child{break-after:auto}.paper-section{break-inside:avoid}@page{size:A4;margin:12mm 14mm}}
`;
