/** Black-and-white, two-page A4. Reserve 24mm for the academy's preprinted letterhead. */
export const admissionPrintStyles=`
.admission-paper{--letterhead-space:24mm;color:#111;background:white;width:210mm;max-width:100%;margin:auto;font:9pt/1.35 Arial,var(--font-bn),sans-serif}
.paper-page{box-sizing:border-box;min-height:297mm;padding:8mm 12mm;background:white;margin:0 auto 16px;border:1px solid #ddd}
.paper-letterhead-space{height:var(--letterhead-space)}
.paper-header{display:flex;justify-content:space-between;align-items:start;gap:5mm;border-bottom:2px solid #111;padding:0 0 3mm;margin-bottom:3mm}.paper-header h1{font-size:16pt;line-height:1.2;font-weight:700;margin:0}.paper-header p{font-size:8pt;margin:1mm 0}.paper-section{margin:3mm 0;break-inside:avoid}.paper-section h2{font-size:9pt;font-weight:700;letter-spacing:.15pt;text-transform:uppercase;border-bottom:1px solid #111;padding:1.3mm 0;margin:0 0 2mm}
.paper-grid{display:flex;flex-wrap:wrap;gap:1.5mm 3mm}.paper-grid>.paper-field{width:calc(50% - 1.5mm)}.paper-grid>.paper-wide{width:100%}.paper-field{display:flex;min-height:7mm;border:1px solid #999;box-sizing:border-box}.paper-field>span{width:43%;flex-shrink:0;font-size:7pt;font-weight:600;padding:1.3mm;border-right:1px solid #aaa;box-sizing:border-box}.paper-field>div{flex:1;min-width:0;font-size:8.5pt;padding:1.3mm;overflow-wrap:anywhere}.paper-wide{grid-column:1/-1}.paper-wide>span{width:28%}.paper-address{min-height:13mm}
.paper-name{margin-bottom:2mm}.paper-name>span{display:block;font-size:7pt;font-weight:600;margin-bottom:1mm}.paper-boxes{display:grid;grid-template-columns:repeat(36,1fr);border-left:1px solid #999}.paper-boxes>b{border:1px solid #999;border-left:0;height:6.5mm;font:8pt/6.5mm Arial;text-align:center}.paper-long-name{border:1px solid #999;padding:2mm;font-size:9pt;overflow-wrap:anywhere}
.paper-options{display:flex;flex-wrap:wrap;gap:1.5mm 4mm;font-size:8pt;margin-bottom:2mm}.paper-options>span{display:inline-block}.paper-note{font-size:7.5pt;line-height:1.45;margin:2mm 0}.paper-signatures{display:grid;grid-template-columns:1fr 1fr;gap:10mm;margin-top:6mm}.paper-signatures>div{border-top:1px solid #444;padding-top:1.5mm;font-size:7.5pt}
.paper-table{width:100%;border-collapse:collapse;font-size:8pt}.paper-table th,.paper-table td{border:1px solid #999;padding:1.7mm;text-align:left}.paper-table th{font-size:7pt;text-transform:uppercase}.paper-table td:last-child,.paper-table th:last-child{text-align:right}
.paper-receipt{border-top:2px dashed #333;margin-top:6mm;padding-top:2mm;break-inside:avoid}.paper-receipt h2{font-size:12pt;margin:0 0 3mm;font-weight:700}.paper-footer{display:flex;justify-content:space-between;gap:5mm;border-top:1px solid #aaa;padding-top:2mm;margin-top:4mm;font-size:7pt}.paper-receipt-only{min-height:0}.paper-receipt-only .paper-receipt{border-top:0}
.paper-page:nth-child(2){font-size:8pt;line-height:1.25}.paper-page:nth-child(2) .paper-letterhead-space{height:20mm}.paper-page:nth-child(2) .paper-receipt .paper-note{font-size:6.5pt;line-height:1.2}.paper-page:nth-child(2) .paper-receipt .paper-signatures{margin-top:4mm}.paper-page:nth-child(2) .paper-section{margin:2mm 0}.paper-page:nth-child(2) .paper-section h2{margin-bottom:1.5mm;padding:1mm 0}.paper-page:nth-child(2) .paper-note{margin:1.5mm 0;font-size:7pt}.paper-page:nth-child(2) .paper-field>span{font-size:6.5pt;padding:1mm}.paper-page:nth-child(2) .paper-field>div{padding:1mm;font-size:8pt}.paper-page:nth-child(2) .paper-table td,.paper-page:nth-child(2) .paper-table th{padding:1.2mm}.paper-page:nth-child(2) .paper-footer{margin-top:2mm}.paper-page:nth-child(2) .paper-receipt{margin-top:4mm}
@media print{body:has(.admission-paper) *:not(:has(.admission-paper)):not(.admission-paper):not(.admission-paper *){display:none!important}body:has(.admission-paper) *:has(.admission-paper){display:block!important;margin:0!important;padding:0!important;max-width:none!important;min-height:0!important}body *{visibility:hidden}.admission-paper,.admission-paper *{visibility:visible}.admission-paper{position:static;width:100%;max-width:none}.paper-page{min-height:0;min-height:281mm;padding:0;border:0;margin:0;break-after:page}.paper-page:last-child{break-after:auto}.paper-receipt-only{height:auto}.paper-section{break-inside:avoid}@page{size:A4;margin:8mm 12mm}}
`;
