'use client';
import Link from 'next/link';
import {useRef,useState} from 'react';
import {useRouter} from 'next/navigation';
import {OfferingWorkspace} from './offering-workspace';
import {DirectoryWorkspace} from './directory-workspace';
import {ProgrammesWorkspace} from './programmes-workspace';
import {YearWorkspace} from './year-workspace';
import {useWords,inputClass} from './common';
export type AcademicTab='programmes'|'admissions'|'settings';
export function AcademicsWorkspace({permissions,initialTab,initialSetting}:{permissions:string[];initialTab:AcademicTab;initialSetting:'choices'|'names'|'years'}){
 const t=useWords(),router=useRouter(),panel=useRef<HTMLDivElement>(null),[tab,setTab]=useState(initialTab),[setting,setSetting]=useState(initialSetting),[message,setMessage]=useState('');
 const canAcademics=permissions.includes('academics.view'),canDirectory=permissions.includes('directory.view');
 const tabs=([{id:'programmes',en:'Programmes',bn:'প্রোগ্রাম',allowed:canAcademics},{id:'admissions',en:'Admissions',bn:'ভর্তি',allowed:permissions.includes('people.view')&&canAcademics},{id:'settings',en:'Academic settings',bn:'শিক্ষা সেটিংস',allowed:canDirectory||canAcademics}] as const).filter(x=>x.allowed);
 function canLeave(){if(panel.current?.querySelector('[data-busy="true"]')){setMessage(t('Finish or confirm the running request before changing sections.','চলমান অনুরোধের ফলাফল নিশ্চিত করে তারপর অন্য অংশে যান।'));return false;}return !panel.current?.querySelector('[data-editor][data-dirty="true"]')||window.confirm(t('Discard unsaved changes and switch sections?','অসংরক্ষিত পরিবর্তন বাদ দিয়ে অন্য অংশে যাবেন?'));}
 function change(next:AcademicTab){if(next===tab||!canLeave())return false;setMessage('');setTab(next);router.replace('/dashboard/academics?tab='+next,{scroll:false});return true;}
 return <section className="space-y-5"><header><h1 className="text-3xl font-semibold">{t('Academics','শিক্ষা পরিচালনা')}</h1><p className="mt-2 text-sm text-muted-foreground">{t('Manage programmes, admission and academic choices in one place. Inside each programme, manage its fees, discounts, batches and website applications.','প্রোগ্রাম, ভর্তি ও শিক্ষার প্রয়োজনীয় তালিকা এক জায়গায়। প্রতিটি প্রোগ্রামের ভেতরে ফি, ছাড়, ব্যাচ ও website-এর আবেদন পরিচালনা করুন।')}</p></header><Link className="inline-block rounded-lg border px-4 py-2" href="/dashboard/academics/sessions">{t('Class sessions, classrooms & changes','ক্লাস, classroom ও পরিবর্তন')}</Link><div role="tablist" aria-label={t('Academic work','শিক্ষা পরিচালনার কাজ')} className="flex flex-wrap gap-2 border-b pb-3">{tabs.map(x=><button key={x.id} role="tab" id={'academic-'+x.id} aria-controls="academic-panel" aria-selected={tab===x.id} tabIndex={tab===x.id?0:-1} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const current=tabs.findIndex(item=>item.id===x.id),index=e.key==='Home'?0:e.key==='End'?tabs.length-1:(current+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;const next=tabs[index].id;if(change(next))document.getElementById('academic-'+next)?.focus();}} type="button" className={`rounded-lg px-4 py-2.5 ${tab===x.id?'bg-primary text-primary-foreground':'border hover:bg-muted'}`} onClick={()=>change(x.id)}>{t(x.en,x.bn)}</button>)}</div>{message&&<p role="status">{message}</p>}<div ref={panel} id="academic-panel" role="tabpanel" aria-labelledby={'academic-'+tab}>
 {tab==='programmes'&&canAcademics&&<OfferingWorkspace permissions={permissions}/>}
 {tab==='admissions'&&<article className="space-y-3 rounded-xl border p-5"><h2 className="text-xl font-semibold">{t('Admission desk — next implementation','ভর্তি ডেস্ক — পরবর্তী implementation')}</h2><p>{t('The single-page admission workflow is not available yet. It will handle identity, placement, fees, review, invoice, payment and receipt here. Public applications currently remain in the CRM enquiry queue.','এক পাতায় ভর্তি workflow এখনো চালু হয়নি। পরিচয়, placement, ফি, review, invoice, payment ও receipt এখানেই হবে। Public আবেদন বর্তমানে CRM enquiry queue-তে থাকে।')}</p></article>}
 {tab==='settings'&&<section className="space-y-4"><label className="block text-sm font-medium">{t('What do you want to manage?','কোন তথ্য পরিচালনা করবেন?')}<select className={inputClass} value={setting} onChange={e=>{const value=e.target.value;if(value!=='choices'&&value!=='names'&&value!=='years')return;if(canLeave()){setSetting(value);setMessage('');router.replace('/dashboard/academics?tab=settings&section='+value,{scroll:false});}}}>{canDirectory&&<option value="choices">{t('Schools, subjects & other choices','স্কুল, বিষয় ও অন্যান্য তালিকা')}</option>}{canAcademics&&<option value="names">{t('Programme names','প্রোগ্রামের নাম')}</option>}{canDirectory&&<option value="years">{t('Academic years','শিক্ষাবর্ষ')}</option>}</select></label>{setting==='choices'&&canDirectory&&<DirectoryWorkspace canManage={permissions.includes('directory.manage')}/>} {setting==='names'&&canAcademics&&<ProgrammesWorkspace canManage={permissions.includes('academics.manage')} canCreateDirectory={permissions.includes('directory.manage')}/>} {setting==='years'&&canDirectory&&<YearWorkspace canManage={permissions.includes('directory.manage')} onClose={()=>{setSetting('choices');router.replace('/dashboard/academics?tab=settings&section=choices',{scroll:false});}}/>}</section>}
 </div></section>;
}
