'use client';
import Link from 'next/link';
import {useWords} from './common';
export function AcademicsWorkspace({permissions}:{permissions:string[]}){
 const t=useWords(),manager=permissions.includes('academics.manage')||permissions.includes('directory.manage'),settings=permissions.includes('directory.view')||permissions.includes('academics.manage');
 const items=[
  {href:'/dashboard/academics/settings',en:manager?'1. Prepare academic settings':'Academic reference lists',bn:manager?'১. শিক্ষা সেটিংস প্রস্তুত করুন':'শিক্ষার প্রয়োজনীয় তালিকা',bodyEn:'Review years and subjects, then set classrooms and teachers. Seeded choices can be reused.',bodyBn:'শিক্ষাবর্ষ ও বিষয় যাচাই করুন; তারপর শ্রেণিকক্ষ ও শিক্ষক প্রস্তুত করুন। আগে থেকে দেওয়া তালিকা ব্যবহার করা যাবে।',show:settings},
  {href:'/dashboard/academics/programmes',en:'2. Prepare a programme',bn:'২. প্রোগ্রাম প্রস্তুত করুন',bodyEn:'Choose its academic context. Save standard fees, create a batch, then publish or open applications.',bodyBn:'প্রোগ্রামের তথ্য নির্বাচন করুন। ফি দিন, ব্যাচ তৈরি করুন; তারপর প্রকাশ বা আবেদন খুলুন।',show:permissions.includes('academics.view')},
  {href:'/dashboard/academics/sessions',en:'3. Run classes',bn:'৩. ক্লাস পরিচালনা করুন',bodyEn:'Schedule classes, arrange substitutes or makeup classes, then submit and review teaching reports.',bodyBn:'ক্লাসের সময় ঠিক করুন, বিকল্প শিক্ষক বা অতিরিক্ত ক্লাস দিন; তারপর পাঠদানের প্রতিবেদন জমা ও যাচাই করুন।',show:permissions.includes('academics.view')},
 ];
 return <section className="space-y-5"><header><h1 className="text-3xl font-semibold">{t('Academics','শিক্ষা পরিচালনা')}</h1><p className="mt-2 text-muted-foreground">{t('Choose the task you need. Settings and everyday class work have separate pages.','প্রয়োজনীয় কাজ নির্বাচন করুন। সেটিংস ও দৈনন্দিন ক্লাস পরিচালনার পাতা আলাদা।')}</p></header><div className="grid gap-4 md:grid-cols-3">{items.filter(x=>x.show).map(x=><Link href={x.href} prefetch={false} key={x.href} className="space-y-3 rounded-xl border p-5 hover:bg-muted"><h2 className="font-semibold">{t(x.en,x.bn)}</h2><p className="text-sm text-muted-foreground">{t(x.bodyEn,x.bodyBn)}</p><p className="text-sm font-medium">{t('Open →','খুলুন →')}</p></Link>)}</div><p className="text-sm text-muted-foreground">{manager?t('Already set up? Go directly to Class operation. This start page loads no programme, session or settings register.','প্রস্তুতি শেষ হলে সরাসরি ক্লাস পরিচালনায় যান। শুরু পাতায় প্রোগ্রাম, ক্লাস বা সেটিংসের তালিকা লোড হয় না।'):t('Teaching staff: open Class operation for your assigned classes and reports. Your administrator manages setup.','শিক্ষক হলে ক্লাস পরিচালনায় নিজের ক্লাস ও প্রতিবেদন খুলুন। সেটিংস প্রশাসক পরিচালনা করবেন।')}</p></section>;
}
