'use client';
import { useState } from 'react';
import { directoryListRow,pageSchema,kinds,type DirectoryEntry } from '../schema';
import { useRegister } from './register';
import { Editor,ValueField,ActiveCheck,inputClass,text,useWords,PageControls } from './common';
const directoryPage=pageSchema(directoryListRow);
const labels:Record<typeof kinds[number],[string,string]>={INSTITUTION:['Schools & colleges','স্কুল ও কলেজ'],AREA:['Areas','এলাকা'],RELATIONSHIP:['Guardian relationships','অভিভাবকের সম্পর্ক'],SUBJECT:['Subjects','বিষয়'],MAJOR:['Majors','মেজর'],GROUP:['Academic groups','একাডেমিক বিভাগ'],PROGRAMME_TYPE:['Programme types','প্রোগ্রামের ধরন'],EXPENSE_CATEGORY:['Expense categories','খরচের ধরন'],DISCOUNT_REASON:['Discount reasons','ছাড়ের কারণ'],LEAD_SOURCE:['Application sources','আবেদনের উৎস']};
export function DirectoryWorkspace({canManage,fixedKind,allowedKinds}:{canManage:boolean;fixedKind?:typeof kinds[number];allowedKinds?:readonly (typeof kinds[number])[]}) {
 const t=useWords(),[kind,setKind]=useState<typeof kinds[number]>(fixedKind??allowedKinds?.[0]??'INSTITUTION'),[inactive,setInactive]=useState(false),[editor,setEditor]=useState<DirectoryEntry|'NEW'|null>(null),[notice,setNotice]=useState('');
 const list=useRegister('directory',directoryPage,{kind,includeInactive:inactive}),entry=editor&&editor!=='NEW'?editor:null;
 return <div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-semibold">{fixedKind?t(...labels[fixedKind]):t('Shared choices','প্রয়োজনীয় তালিকা')}</h1>{canManage&&!editor&&<button className="rounded-lg bg-primary px-4 py-2.5 text-primary-foreground" onClick={()=>setEditor('NEW')}>{t('Add record','নতুন যোগ করুন')}</button>}</header>
 <div className="flex flex-wrap gap-4">{!fixedKind&&<select aria-label={t('Directory','তালিকার ধরন')} className="rounded-lg border bg-background p-2" value={kind} disabled={!!editor} onChange={e=>setKind(e.target.value as typeof kinds[number])}>{(allowedKinds??kinds).map(k=><option key={k} value={k}>{t(...labels[k])}</option>)}</select>}{canManage&&<label className="flex items-center gap-2"><input type="checkbox" checked={inactive} onChange={e=>setInactive(e.target.checked)}/>{t('Include inactive records','নিষ্ক্রিয় record দেখুন')}</label>}</div>
 <p className="text-sm text-muted-foreground">{t('Edit or mark inactive. Existing history stays readable. New schools added during intake remain unverified until their source is checked.','সংশোধন বা নিষ্ক্রিয় করুন। পুরোনো তথ্য থাকে। নতুন প্রতিষ্ঠানের নাম উৎস যাচাই হওয়ার আগে unverified থাকবে।')}</p>
 {notice&&<p role="status" className="rounded-lg border p-3">{notice}</p>}
 {editor&&<Editor key={entry?.id??kind} title={t(entry?'Edit record':'New record',entry?'তথ্য সংশোধন':'নতুন তথ্য')} command="directory" onCancel={()=>setEditor(null)} onDone={()=>{setEditor(null);setNotice(t('Directory saved.','তালিকা সংরক্ষিত।'));void list.load();}}
 read={f=>({...(entry?{id:entry.id,revision:entry.revision}:{}),kind,code:entry?.code??'',name:text(f,'name'),name_bn:text(f,'name_bn'),locality:text(f,'locality'),institution_type:text(f,'institution_type'),eiin:text(f,'eiin'),source_url:text(f,'source_url'),verified_on:text(f,'verified_on'),is_verified:f.has('is_verified')&&(!entry||(text(f,'name')===entry.name&&text(f,'locality').toLowerCase()===entry.locality)),sort_order:Number(text(f,'sort_order')),is_active:f.has('is_active'),reason:text(f,'reason')})}>
 <ValueField name="name" label={t('Name','নাম')} value={entry?.name} required maxLength={160}/>
 {kind==='INSTITUTION'&&<ValueField name="locality" label={t('Area (optional)','এলাকা (ঐচ্ছিক)')} value={entry?.locality} maxLength={160}/>}
 <details className="sm:col-span-2 rounded-lg border p-3"><summary className="cursor-pointer">{t('Additional details (optional)','অতিরিক্ত তথ্য (ঐচ্ছিক)')}</summary><div className="mt-3 grid gap-4 sm:grid-cols-2"><ValueField name="name_bn" label={t('Bangla name (optional)','বাংলা নাম (ঐচ্ছিক)')} value={entry?.name_bn} maxLength={160}/>
 {kind==='INSTITUTION'&&<><label className="text-sm">{t('Institution type','প্রতিষ্ঠানের ধরন')}<select name="institution_type" className={inputClass} defaultValue={entry?.institution_type??'SCHOOL'}>{[['SCHOOL','School','স্কুল'],['COLLEGE','College','কলেজ'],['MADRASA','Madrasa','মাদ্রাসা'],['UNIVERSITY','University','বিশ্ববিদ্যালয়'],['OTHER','Other','অন্যান্য']].map(([id,en,bn])=><option key={id} value={id}>{t(en,bn)}</option>)}</select></label><ValueField name="eiin" label={t('EIIN (optional)','EIIN (ঐচ্ছিক)')} value={entry?.eiin} maxLength={6}/>
 <ValueField name="source_url" label={t('Verified source HTTPS URL','যাচাইযোগ্য উৎসের HTTPS URL')} value={entry?.source_url} maxLength={1000}/><ValueField name="verified_on" label={t('Source checked on','উৎস যাচাইয়ের তারিখ')} value={entry?.verified_on} type="date"/><label className="flex items-center gap-2"><input type="checkbox" name="is_verified" defaultChecked={entry?.is_verified}/>{t('Official source verified','প্রাতিষ্ঠানিক উৎস যাচাই করেছি')}</label></>}
 <ValueField name="sort_order" label={t('Display order','প্রদর্শনের ক্রম')} value={entry?.sort_order??0} type="number" step="1"/></div></details><ActiveCheck value={entry?.is_active??true}/><input type="hidden" name="reason" value={entry?'Corrected academic directory details':'Added missing academic directory choice'}/>
 </Editor>}
 <form className="flex gap-3" onSubmit={e=>{e.preventDefault();void list.load(1,list.query);}}><input aria-label={t('Search directory','তালিকা খুঁজুন')} className={inputClass} value={list.query} onChange={e=>list.setQuery(e.target.value)} maxLength={160}/><button disabled={list.loading} className="rounded-lg border px-4">{t('Search','খুঁজুন')}</button></form>
 {list.loading?<p role="status">{t('Loading…','লোড হচ্ছে…')}</p>:list.error?<p role="alert">{t('Search failed.','খোঁজা যায়নি।')} <button className="underline" onClick={()=>void list.load()}>{t('Retry','আবার চেষ্টা')}</button></p>:<div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left">{[t('Name','নাম'),t('Locality / type','এলাকা / ধরন'),t('Status','অবস্থা'),t('Actions','পদক্ষেপ')].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{list.data.rows.map(row=><tr key={row.id} className="border-b"><td className="p-3">{t(row.name,row.name_bn??row.name)}</td><td>{row.locality||'—'} {row.eiin&&`· ${row.eiin}`}</td><td>{row.is_active?t('Active','সক্রিয়'):t('Inactive','নিষ্ক্রিয়')}{kind==='INSTITUTION'&&<p className="text-xs">{row.is_verified?t('Verified source','উৎস যাচাইকৃত'):t('Source needs verification','উৎস যাচাই বাকি')}</p>}</td><td>{canManage&&<button className="underline" onClick={()=>setEditor(row)}>{t('Edit / change status','সংশোধন / অবস্থা পরিবর্তন')}</button>}</td></tr>)}</tbody></table>{!list.data.rows.length&&<p className="p-4">{t('No matching records.','মিল পাওয়া যায়নি।')}</p>}</div>}
 <PageControls page={list.data.page} total={list.data.total} onPage={p=>void list.load(p)}/>
 </div>;
}
