'use client';
import {useState} from 'react';
import type {RunSetup} from '../schema';
import {Editor,Field,ValueField,Reason,inputClass,text,useWords} from './common';
const kinds=['TUITION','ADMISSION','EXAM','MATERIAL','OTHER'] as const;
const labels:Record<string,[string,string]>={TUITION:['Tuition','টিউশন'],ADMISSION:['Admission','ভর্তি'],EXAM:['Exam','পরীক্ষা'],MATERIAL:['Materials','শিক্ষা উপকরণ'],OTHER:['Other charge','অন্য চার্জ']};
type Component={code:string;name:string;amount:number|string;charge_type:typeof kinds[number];recurrence:'PER_CYCLE'|'ONE_TIME'};
export function FeeEditor({setup,onDone,onCancel}:{setup:RunSetup;onDone:()=>void;onCancel:()=>void}){
 const t=useWords(),[components,setComponents]=useState<Component[]>(setup.components.length?setup.components:[{code:'TUITION',name:'Tuition',amount:'',charge_type:'TUITION',recurrence:'PER_CYCLE'},{code:'ADMISSION',name:'Admission fee',amount:0,charge_type:'ADMISSION',recurrence:'ONE_TIME'}]);
 const fees=setup.feeSettings;
 return <Editor title={t(fees?'Edit standard fees & discounts':'Set standard fees & discounts',fees?'নির্ধারিত ফি ও ছাড় সংশোধন':'নির্ধারিত ফি ও ছাড় দিন')} command="fees" onDone={onDone} onCancel={onCancel} read={f=>({run_id:setup.run.id,revision:fees?.revision??0,cycle:text(f,'cycle'),due_day:Number(text(f,'due_day')),allowed_discounts:f.getAll('allowed_discounts').map(Number),components:components.map(c=>({code:c.code,name:text(f,c.code+'_name'),amount:text(f,c.code+'_amount')===''?NaN:Number(text(f,c.code+'_amount')),charge_type:c.charge_type,recurrence:c.recurrence})),reason:text(f,'reason')})}>
 <p className="sm:col-span-2 text-sm">{t('Standard tuition is required. Zero is allowed only when intentional. Optional charges can be removed from the current plan; history is retained.','নির্ধারিত tuition প্রয়োজন। ইচ্ছাকৃত হলে শূন্য দেয়া যায়। ঐচ্ছিক চার্জ বর্তমান plan থেকে সরানো যায়; ইতিহাস থাকবে।')}</p><Field name="cycle" label={t('Billing cycle','বিলের সময়কাল')}><select id="cycle" name="cycle" className={inputClass} defaultValue={fees?.cycle??(setup.run.class_code?'MONTHLY':'COURSE')}>{[['MONTHLY','Monthly','মাসিক'],['TERM','Per term','টার্ম'],['COURSE','Whole course','পুরো কোর্স']].map(([id,en,bn])=><option key={id} value={id}>{t(en,bn)}</option>)}</select></Field><ValueField name="due_day" label={t('Due day (1–28)','শেষ তারিখ (১–২৮)')} type="number" required min={1} max={28} value={fees?.due_day??10}/>
 {components.map((c,index)=><fieldset key={c.code} className="grid gap-3 rounded-lg border p-4 sm:col-span-2 sm:grid-cols-2"><legend className="px-2 text-sm">{t(...labels[c.charge_type])}</legend><ValueField name={c.code+'_name'} label={t('Charge name','চার্জের নাম')} value={c.name} required maxLength={120}/><ValueField name={c.code+'_amount'} label={t('Amount (BDT)','পরিমাণ (টাকা)')} value={c.amount} type="number" required min={0} max={999999999999.99} step="0.01"/>{c.charge_type==='TUITION'?<p className="text-sm">{t('Tuition repeats per billing cycle.','Tuition প্রতি billing cycle-এ প্রযোজ্য।')}</p>:<><label>{t('Type','ধরন')}<select className={inputClass} value={c.charge_type} onChange={e=>{const value=e.target.value as Component['charge_type'];setComponents(old=>old.map((row,i)=>i===index?{...row,charge_type:value}:row));}}>{kinds.filter(k=>k!=='TUITION').map(k=><option key={k} value={k}>{t(...labels[k])}</option>)}</select></label><label>{t('Frequency','কখন প্রযোজ্য')}<select className={inputClass} value={c.recurrence} onChange={e=>setComponents(old=>old.map((row,i)=>i===index?{...row,recurrence:e.target.value as Component['recurrence']}:row))}><option value="ONE_TIME">{t('One time','একবার')}</option><option value="PER_CYCLE">{t('Per billing cycle','প্রতি billing cycle')}</option></select></label><button type="button" className="text-left text-sm underline" onClick={()=>setComponents(old=>old.filter((_,i)=>i!==index))}>{t('Remove from current plan','বর্তমান plan থেকে সরান')}</button></>}</fieldset>)}
 <div className="sm:col-span-2 flex flex-wrap gap-3">{kinds.filter(k=>k!=='TUITION').map(kind=><button key={kind} type="button" disabled={components.length>=20} className="rounded-lg border px-3 py-2 text-sm" onClick={()=>setComponents(old=>[...old,{code:kind+'_'+crypto.randomUUID().slice(0,8).toUpperCase(),name:labels[kind][0],amount:'',charge_type:kind,recurrence:'ONE_TIME'}])}>{t('Add '+labels[kind][0],labels[kind][1]+' যোগ করুন')}</button>)}</div><div className="sm:col-span-2"><p className="mb-2 font-medium">{t('Permitted admission discounts','ভর্তির সময় অনুমোদিত ছাড়')}</p><div className="flex flex-wrap gap-4">{[5,10,15,20,25,30].map(n=><label key={n}><input type="checkbox" name="allowed_discounts" value={n} defaultChecked={fees?.allowed_discounts.includes(n)}/> {n}%</label>)}</div></div><Reason value="Reviewed standard fees and permitted discount choices"/>
 </Editor>;
}
