'use client';
import {useEffect,useState,startTransition} from 'react';
import {fetchSetupChoices} from '../actions';
import {choicesSchema,type SetupChoices,type RunSetup,type Choice} from '../schema';
import type {Json} from '@/types/academy-rpc';
import {Editor,Field,ValueField,Reason,inputClass,text,useMutation,useWords} from './common';
import {DirectoryPicker} from './directory-picker';
const contentLabels:Record<string,[string,string]>={description:['Description','বিবরণ (ইংরেজি)'],schedule:['Schedule','সময়সূচি (ইংরেজি)'],requirements:['Requirements','প্রয়োজনীয় তথ্য (ইংরেজি)'],policy:['Admission policy','ভর্তির নীতি (ইংরেজি)'],description_bn:['Description (Bangla)','বিবরণ (বাংলা)'],schedule_bn:['Schedule (Bangla)','সময়সূচি (বাংলা)'],requirements_bn:['Requirements (Bangla)','প্রয়োজনীয় তথ্য (বাংলা)'],policy_bn:['Admission policy (Bangla)','ভর্তির নীতি (বাংলা)']};
export function OfferingEditor({setup,divisionId,permissions,onDone,onCancel}:{setup:RunSetup|null;divisionId:string;permissions:string[];onDone:(data:Json)=>void;onCancel:()=>void}){
 const t=useWords(),run=setup?.run,[choices,setChoices]=useState<SetupChoices|null>(null),[error,setError]=useState(''),[division,setDivision]=useState(run?.division_id??divisionId),[year,setYear]=useState(run?.academic_year_id??''),[classCode,setClassCode]=useState(run?.class_code??''),[start,setStart]=useState(run?.starts_on??''),[end,setEnd]=useState(run?.ends_on??''),[subjects,setSubjects]=useState<(Choice & {is_active?:boolean})[]>(setup?.subjects??[]),[yearOpen,setYearOpen]=useState(false),[yearName,setYearName]=useState(''),[yearStart,setYearStart]=useState(''),[yearEnd,setYearEnd]=useState('');
 const locked=setup?.contextLocked??false,canDirectory=permissions.includes('directory.manage'),canManage=permissions.includes('academics.manage');
 function load(){setError('');startTransition(async()=>{try{const result=await fetchSetupChoices();setChoices(result);if(!division&&result.divisions.length)setDivision(result.divisions[0].id);}catch{setError(t('Setup choices failed to load. Retry.','Setup তালিকা লোড হয়নি। আবার চেষ্টা করুন।'));}});}
 useEffect(()=>{load();},[]);
 const yearMutation=useMutation('year',data=>{const saved=choicesSchema.shape.years.element.parse(data);setChoices(old=>old?{...old,years:[saved,...old.years.filter(y=>y.id!==saved.id)]}:old);setYear(saved.id);setStart(saved.starts_on);setEnd(saved.ends_on);setYearOpen(false);});
 const divisionCode=choices?.divisions.find(d=>d.id===division)?.code,isTraining=divisionCode==='TRAINING';
 const allowedClasses=choices?.classes.filter(c=>divisionCode==='SCHOOL'?['PLAY','NURSERY','KG',...Array.from({length:8},(_,i)=>`CLASS_${i+1}`)].includes(c.code):divisionCode==='COACHING'?['CLASS_9','CLASS_10','CLASS_11','CLASS_12'].includes(c.code):false)??[];
 function selectYear(id:string){setYear(id);if(!run){const value=choices?.years.find(y=>y.id===id);if(value){setStart(value.starts_on);setEnd(value.ends_on);}}}
 if(!choices)return <section className="rounded-xl border p-5"><p role="status">{error||t('Loading setup choices…','Setup তালিকা লোড হচ্ছে…')}</p>{error&&<button type="button" className="underline" onClick={load}>{t('Retry','আবার চেষ্টা')}</button>}<button type="button" onClick={onCancel} className="ml-4 underline">{t('Cancel','বাতিল')}</button></section>;
 return <Editor title={t(run?'Edit programme':'Create programme',run?'প্রোগ্রাম সংশোধন':'প্রোগ্রাম তৈরি')} command="run" onDone={onDone} onCancel={onCancel} read={f=>({...run?{id:run.id,revision:run.revision}:{},programme_id:locked?run!.programme_id:text(f,'programme_id'),division_id:division,campus_id:locked?run!.campus_id:text(f,'campus_id'),academic_year_id:isTraining?'':year,class_code:isTraining?'':classCode,code:text(f,'code'),title:text(f,'title'),starts_on:start,ends_on:end,guardian_rule:text(f,'guardian_rule'),is_active:run?f.has('is_active'):true,website_visible:!!run&&f.has('website_visible'),applications_open:!!run&&f.has('applications_open'),application_opens_on:text(f,'application_opens_on'),application_closes_on:text(f,'application_closes_on'),subject_ids:subjects.map(s=>s.id),public_content:Object.fromEntries(['description','schedule','requirements','policy','description_bn','schedule_bn','requirements_bn','policy_bn'].map(k=>[k,text(f,k)])),reason:text(f,'reason')})}>
 <div className="space-y-4 sm:col-span-2"><p className="text-sm">{t('Choose the programme name, operation, dates, class and subjects. Save, then set fees and batches here. Code and display title are optional.','প্রোগ্রামের নাম, পরিচালনা, তারিখ, ক্লাস ও বিষয় নির্বাচন করুন। সংরক্ষণ করে এখানেই ফি ও ব্যাচ দিন। Code ও আলাদা নাম ঐচ্ছিক।')}</p>{locked&&<p className="rounded-lg border p-3 text-sm">{t('Placement history exists: context is locked. Create another programme for a different academic placement.','Placement history আছে: context বদলানো যাবে না। আলাদা শিক্ষার placement-এর জন্য নতুন প্রোগ্রাম তৈরি করুন।')}</p>}<fieldset disabled={locked} className="grid gap-4 sm:grid-cols-2"><Field name="division_id" label={t('Operation','পরিচালনা')}><select name="division_id" id="division_id" className={inputClass} value={division} required onChange={e=>{setDivision(e.target.value);setClassCode('');setYear('');}}>{choices.divisions.map(d=><option key={d.id} value={d.id}>{t(d.name,d.nameBn)}</option>)}</select></Field><Field name="campus_id" label={t('Campus','ক্যাম্পাস')}><select name="campus_id" id="campus_id" className={inputClass} required defaultValue={run?.campus_id??choices.campuses[0]?.id}>{choices.campuses.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field name="programme_id" label={t('Programme name','প্রোগ্রামের নাম')}><DirectoryPicker name="programme_id" kind="PROGRAMME" initial={run?{id:run.programme_id,name:setup!.programmeName}:null} canCreate={canManage}/></Field>
 {!isTraining&&<><Field name="academic_year_id" label={t('Academic year','শিক্ষাবর্ষ')}><select name="academic_year_id" id="academic_year_id" className={inputClass} required value={year} onChange={e=>selectYear(e.target.value)}><option value="">{t('Select year','শিক্ষাবর্ষ নির্বাচন')}</option>{choices.years.filter(y=>y.is_active||y.id===year).map(y=><option key={y.id} value={y.id}>{y.name}{!y.is_active?t(' · inactive',' · নিষ্ক্রিয়'):''}</option>)}</select></Field><Field name="class_code" label={t('Class','ক্লাস')}><select name="class_code" id="class_code" className={inputClass} value={classCode} required onChange={e=>setClassCode(e.target.value)}><option value="">{t('Select class','ক্লাস নির্বাচন')}</option>{allowedClasses.map(c=><option key={c.code} value={c.code}>{t(c.name,c.nameBn)}</option>)}</select></Field></>}
 </fieldset>{isTraining&&<p className="text-sm">{t('Training uses course dates. School class/year are not required.','Training কোর্সের তারিখ ব্যবহার করে। School class/year প্রয়োজন নেই।')}</p>}
 {!isTraining&&!locked&&canDirectory&&<div data-busy={yearMutation.pending||yearMutation.uncertain}><button type="button" className="underline text-sm" onClick={()=>setYearOpen(!yearOpen)}>{t('Missing year? Create here','শিক্ষাবর্ষ নেই? এখানেই তৈরি করুন')}</button>{yearOpen&&<fieldset disabled={yearMutation.pending||yearMutation.uncertain} className="mt-3 grid gap-3 rounded-lg border p-3 sm:grid-cols-3"><label>{t('Year name','শিক্ষাবর্ষের নাম')}<input value={yearName} onChange={e=>{setYearName(e.target.value);if(/^\d{4}$/.test(e.target.value)){setYearStart(e.target.value+'-01-01');setYearEnd(e.target.value+'-12-31');}}} maxLength={80} className={inputClass}/></label><label>{t('Starts','শুরু')}<input type="date" className={inputClass} value={yearStart} onChange={e=>setYearStart(e.target.value)}/></label><label>{t('Ends','শেষ')}<input type="date" className={inputClass} value={yearEnd} onChange={e=>setYearEnd(e.target.value)}/></label><button type="button" disabled={!yearName||!yearStart||!yearEnd} className="underline" onClick={()=>yearMutation.submit({name:yearName,starts_on:yearStart,ends_on:yearEnd,is_active:true,reason:'Created missing academic year during offering setup'})}>{yearMutation.pending?t('Saving…','সংরক্ষণ হচ্ছে…'):t('Save & select year','সংরক্ষণ করে নির্বাচন')}</button></fieldset>}{yearMutation.error&&<p role="alert">{t(yearMutation.error.message,'শিক্ষাবর্ষের নাম ও তারিখ যাচাই করুন। Input রাখা হয়েছে।')}</p>}{yearMutation.uncertain&&<button type="button" onClick={yearMutation.retry}>{t('Retry unchanged year request','একই শিক্ষাবর্ষের অনুরোধ আবার পাঠান')}</button>}</div>}
 </div>
 <ValueField name="code" label={t('Operational code (optional)','পরিচালনার code (ঐচ্ছিক)')} value={run?.code} maxLength={80}/><ValueField name="title" label={t('Title override (optional; otherwise generated)','আলাদা নাম (ঐচ্ছিক; না দিলে স্বয়ংক্রিয়)')} value={run?.title} maxLength={240}/>
 <Field name="starts_on" label={t('Classes start','ক্লাস শুরু')}><input id="starts_on" name="starts_on" required type="date" value={start} onChange={e=>setStart(e.target.value)} className={inputClass}/></Field><Field name="ends_on" label={t('Classes end','ক্লাস শেষ')}><input id="ends_on" name="ends_on" required type="date" min={start} value={end} onChange={e=>setEnd(e.target.value)} className={inputClass}/></Field>
 <Field name="guardian_rule" label={t('Guardian requirement','অভিভাবকের প্রয়োজন')}><select id="guardian_rule" name="guardian_rule" className={inputClass} defaultValue={run?.guardian_rule??(isTraining?'OPTIONAL':'MINOR_REQUIRED')}><option value="MINOR_REQUIRED">{t('Required for minors','অপ্রাপ্তবয়স্ক হলে প্রয়োজন')}</option><option value="REQUIRED">{t('Required for everyone','সবার জন্য প্রয়োজন')}</option><option value="OPTIONAL">{t('Optional','ঐচ্ছিক')}</option></select></Field>
 <div className="sm:col-span-2 space-y-3"><p className="font-medium">{t('Subjects — select; create if missing','বিষয় — নির্বাচন করুন; না থাকলে তৈরি')}</p><DirectoryPicker name="add_subject" kind="SUBJECT" canCreate={canDirectory} onSelect={c=>setSubjects(old=>old.some(s=>s.id===c.id)?old:[...old,c])}/><div className="flex flex-wrap gap-4">{subjects.map(s=><label key={s.id} className="flex items-center gap-2"><input type="checkbox" checked onChange={()=>setSubjects(old=>old.filter(c=>c.id!==s.id))}/>{t(s.name,s.nameBn??s.name_bn??s.name)}{s.is_active===false&&<span className="text-xs text-amber-600">{t('Inactive — uncheck or reactivate in directory','নিষ্ক্রিয় — tick সরান অথবা directory-তে সক্রিয় করুন')}</span>}</label>)}</div><p className="text-xs">{t('Uncheck a subject to remove it from current selection. Historical links remain.','বর্তমান তালিকা থেকে সরাতে tick তুলে দিন। পুরোনো সম্পর্ক থাকবে।')}</p></div>
 {run?<><label><input type="checkbox" name="is_active" defaultChecked={run.is_active}/> {t('Operationally active','পরিচালনায় সক্রিয়')}</label><label><input type="checkbox" name="website_visible" defaultChecked={run.website_visible}/> {t('Visible on website','Website-এ দৃশ্যমান')}</label><label><input type="checkbox" name="applications_open" defaultChecked={run.applications_open}/> {t('Accept applications — fees and batch required','আবেদন গ্রহণ — ফি ও ব্যাচ প্রয়োজন')}</label></>:<p className="sm:col-span-2 text-sm">{t('Save first, configure standard fees and a batch, then publish/open applications.','আগে সংরক্ষণ, এরপর নির্ধারিত ফি ও ব্যাচ তৈরি করে প্রকাশ/আবেদন খুলুন।')}</p>}
 <ValueField name="application_opens_on" label={t('Applications open (optional)','আবেদন শুরু (ঐচ্ছিক)')} type="date" value={run?.application_opens_on}/><ValueField name="application_closes_on" label={t('Applications close (optional)','আবেদন শেষ (ঐচ্ছিক)')} type="date" value={run?.application_closes_on}/>
 <details className="sm:col-span-2 rounded-lg border p-3"><summary className="cursor-pointer font-medium">{t('Website copy — English & Bangla','Website-এর লেখা — ইংরেজি ও বাংলা')}</summary><div className="mt-3 grid gap-4 sm:grid-cols-2">{(['description','schedule','requirements','policy'] as const).flatMap(k=>[k,k+'_bn']).map(k=><Field key={k} name={k} label={t(...contentLabels[k])}><textarea id={k} name={k} rows={k.startsWith('description')?3:2} className={inputClass} defaultValue={String(run?.public_content[k]??'')} maxLength={k.startsWith('description')?3000:k.startsWith('schedule')?500:1000}/></Field>)}</div></details><Reason value="Reviewed offering context, subjects and public information"/>
 </Editor>;
}
