'use client';
import {useState} from 'react';
import {fetchRunSetup} from '../actions';
import {pageSchema,runListRow,type RunSetup} from '../schema';
import {useRegister} from './register';
import {Editor,ValueField,ActiveCheck,Reason,text,inputClass,useWords,PageControls} from './common';
const pages=pageSchema(runListRow);
export function OfferingWorkspace({permissions}:{permissions:string[]}){
 const t=useWords(),list=useRegister('runs',pages),[setup,setSetup]=useState<RunSetup|null>(null),[editor,setEditor]=useState<'run'|'fees'|'batches'|null>(null),[batchId,setBatchId]=useState<string|null>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false);
 const canManage=permissions.includes('academics.manage'),canFees=permissions.includes('fees.manage');
 async function open(id:string,section:typeof editor){setLoading(true);setNotice('');try{setSetup(await fetchRunSetup(id));setEditor(section);setBatchId(null);}catch{setNotice(t('Setup could not be loaded. Retry.','Setup লোড হয়নি। আবার চেষ্টা করুন।'));}finally{setLoading(false);}}
 function done(){setEditor(null);setSetup(null);setBatchId(null);setNotice(t('Saved. Current setup updated; previous records remain intact.','সংরক্ষিত। বর্তমান setup হালনাগাদ হয়েছে; পুরোনো record থাকে।'));void list.load();}
 const run=setup?.run,fees=setup?.feeSettings,batch=setup?.batches.find(b=>b.id===batchId);
 return <section className="space-y-5"><h1 className="text-2xl font-semibold">{t('Programme offerings','পরিচালিত প্রোগ্রাম')}</h1><p className="text-sm text-muted-foreground">{t('Starter dates and fees are editable defaults. Review them before publishing. Spoken English starts at zero: set its actual fee before opening applications.','Starter তারিখ ও ফি পরিবর্তনযোগ্য defaults। প্রকাশের আগে যাচাই করুন। Spoken English-এর ফি শূন্য রাখা হয়েছে—আবেদন খোলার আগে প্রকৃত ফি দিন।')}</p>{notice&&<p role="status" className="rounded-lg border p-3">{notice}</p>}
 {editor==='run'&&run&&setup&&<Editor title={t('Edit offering & website','Offering ও website সংশোধন')} command="run" onCancel={()=>setEditor(null)} onDone={done} read={f=>({id:run.id,revision:run.revision,programme_id:run.programme_id,division_id:run.division_id,campus_id:run.campus_id,academic_year_id:run.academic_year_id??'',class_code:run.class_code??'',code:text(f,'code'),title:text(f,'title'),starts_on:text(f,'starts_on'),ends_on:text(f,'ends_on'),guardian_rule:run.guardian_rule,is_active:f.has('is_active'),website_visible:f.has('website_visible'),applications_open:f.has('applications_open'),application_opens_on:text(f,'application_opens_on'),application_closes_on:text(f,'application_closes_on'),subject_ids:setup.subjectIds,public_content:{description:text(f,'description'),schedule:text(f,'schedule'),requirements:text(f,'requirements'),policy:text(f,'policy'),description_bn:String(run.public_content.description_bn??''),schedule_bn:String(run.public_content.schedule_bn??''),requirements_bn:String(run.public_content.requirements_bn??''),policy_bn:String(run.public_content.policy_bn??'')},reason:text(f,'reason')})}>
 <ValueField name="code" label={t('Code','কোড')} value={run.code}/><ValueField name="title" label={t('Display title','প্রদর্শনের নাম')} value={run.title}/><ValueField name="starts_on" label={t('Classes start','ক্লাস শুরু')} value={run.starts_on} type="date" required/><ValueField name="ends_on" label={t('Classes end','ক্লাস শেষ')} value={run.ends_on} type="date" required/>
 <ActiveCheck value={run.is_active}/><label><input type="checkbox" name="website_visible" defaultChecked={run.website_visible}/> {t('Website visible — fees and dates reviewed','Website visible — ফি ও তারিখ যাচাই করেছি')}</label><label><input type="checkbox" name="applications_open" defaultChecked={run.applications_open}/> {t('Accept applications','আবেদন গ্রহণ করুন')}</label><ValueField name="application_opens_on" label={t('Applications open from (optional)','আবেদন শুরু (ঐচ্ছিক)')} value={run.application_opens_on} type="date"/><ValueField name="application_closes_on" label={t('Applications close on (optional)','আবেদন শেষ (ঐচ্ছিক)')} value={run.application_closes_on} type="date"/>
 {(['description','schedule','requirements','policy'] as const).map(key=><ValueField key={key} name={key} label={t({description:'Description',schedule:'Schedule',requirements:'Requirements',policy:'Admission policy'}[key],{description:'বিবরণ',schedule:'সময়সূচি',requirements:'প্রয়োজনীয় তথ্য',policy:'ভর্তি নীতি'}[key])} value={String(run.public_content[key]??'')} maxLength={key==='description'?3000:key==='schedule'?500:1000}/>)}<Reason/>
 </Editor>}
 {editor==='fees'&&run&&setup&&<Editor title={t('Edit fees & discount choices','ফি ও ছাড়ের অপশন সংশোধন')} command="fees" onCancel={()=>setEditor(null)} onDone={done} read={f=>({run_id:run.id,revision:fees?.revision??0,cycle:text(f,'cycle'),due_day:Number(text(f,'due_day')),allowed_discounts:f.getAll('allowed_discounts').map(Number),components:setup.components.map(c=>({code:c.code,name:text(f,c.id+'_name'),amount:Number(text(f,c.id+'_amount')),charge_type:c.charge_type,recurrence:c.recurrence})),reason:text(f,'reason')})}>
 <label>{t('Billing cycle','বিলের সময়কাল')}<select name="cycle" className={inputClass} defaultValue={fees?.cycle??'MONTHLY'}>{[['MONTHLY','Monthly','মাসিক'],['TERM','Per term','টার্ম'],['COURSE','Whole course','সম্পূর্ণ কোর্স']].map(([id,en,bn])=><option key={id} value={id}>{t(en,bn)}</option>)}</select></label><ValueField name="due_day" label={t('Due day (1–28)','শেষ তারিখ (১–২৮)')} value={fees?.due_day??10} type="number" min={1} max={28} required/>
 {setup.components.map(c=><div className="grid gap-3 sm:col-span-2 sm:grid-cols-2" key={c.id}><ValueField name={c.id+'_name'} label={t('Charge name','চার্জের নাম')} value={c.name} required/><ValueField name={c.id+'_amount'} label={t('Amount (BDT)','পরিমাণ (টাকা)')} value={c.amount} type="number" min={0} step="0.01" required/></div>)}<div className="sm:col-span-2"><p>{t('Permitted discounts','অনুমোদিত ছাড়')}</p><div className="flex flex-wrap gap-4">{[5,10,15,20,25,30].map(n=><label key={n}><input type="checkbox" name="allowed_discounts" value={n} defaultChecked={fees?.allowed_discounts.includes(n)}/> {n}%</label>)}</div></div><Reason/>
 </Editor>}
 {editor==='batches'&&setup&&run&&<section className="space-y-4 rounded-xl border p-4"><h2>{t('Batches','ব্যাচ')}</h2>{batch?<Editor title={t('Edit batch','ব্যাচ সংশোধন')} command="batch" onCancel={()=>setBatchId(null)} onDone={done} read={f=>({id:batch.id,revision:batch.revision,run_id:run.id,code:batch.code,name:text(f,'name'),capacity:Number(text(f,'capacity')),is_active:f.has('is_active'),reason:text(f,'reason')})}><ValueField name="name" label={t('Batch name','ব্যাচের নাম')} value={batch.name} required/><ValueField name="capacity" label={t('Capacity','আসন')} value={batch.capacity} type="number" min={Math.max(1,batch.occupied)} max={200} required/><ActiveCheck value={batch.is_active}/><Reason/></Editor>:<><table className="w-full text-sm"><tbody>{setup.batches.map(b=><tr key={b.id} className="border-t"><td className="py-3">{b.name}</td><td>{b.occupied}/{b.capacity}</td><td>{b.is_active?t('Active','সক্রিয়'):t('Inactive','নিষ্ক্রিয়')}</td><td>{canManage&&<button className="underline" onClick={()=>setBatchId(b.id)}>{t('Edit','সংশোধন')}</button>}</td></tr>)}</tbody></table><PageControls page={setup.batchPage} total={setup.batchTotal} onPage={p=>{setLoading(true);void fetchRunSetup(run.id,p).then(setSetup).catch(()=>setNotice(t('Could not load batches.','ব্যাচ লোড হয়নি।'))).finally(()=>setLoading(false));}}/><button onClick={()=>setEditor(null)}>{t('Close','বন্ধ')}</button></>}</section>}
 <form className="flex gap-3" onSubmit={e=>{e.preventDefault();void list.load(1,list.query);}}><input aria-label={t('Search offerings','Offering খুঁজুন')} className={inputClass} value={list.query} onChange={e=>list.setQuery(e.target.value)} maxLength={160}/><button disabled={list.loading} className="rounded-lg border px-4">{t('Search','খুঁজুন')}</button></form>
 {list.loading||loading?<p role="status">{t('Loading…','লোড হচ্ছে…')}</p>:list.error?<p role="alert">{t('Load failed.','লোড হয়নি।')} <button onClick={()=>void list.load()}>{t('Retry','আবার চেষ্টা')}</button></p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>{t('Offering','Offering')}</th><th>{t('Division / class','বিভাগ / ক্লাস')}</th><th>{t('Website / intake','Website / আবেদন')}</th><th>{t('Actions','পদক্ষেপ')}</th></tr></thead><tbody>{list.data.rows.map(r=><tr key={r.id} className="border-t"><td className="py-3">{r.title}<p className="text-xs">{r.code}</p></td><td>{r.division_name} · {r.class_code??'—'}</td><td>{r.website_visible?t('Visible','দৃশ্যমান'):t('Hidden','অপ্রকাশিত')} · {r.applications_open?t('Open','খোলা'):t('Closed','বন্ধ')}</td><td className="space-x-3">{canManage&&<button disabled={!!editor} className="underline" onClick={()=>void open(r.id,'run')}>{t('Edit / publish','সংশোধন / প্রকাশ')}</button>}{canFees&&<button disabled={!!editor} className="underline" onClick={()=>void open(r.id,'fees')}>{t('Fees','ফি')}</button>}<button disabled={!!editor} className="underline" onClick={()=>void open(r.id,'batches')}>{t('Batches','ব্যাচ')}</button></td></tr>)}</tbody></table>{!list.data.rows.length&&<p>{t('No offerings. Apply the starter migration.','Offering নেই। Starter migration চালান।')}</p>}</div>}
 <PageControls page={list.data.page} total={list.data.total} onPage={p=>void list.load(p)}/>
 </section>;
}
