'use client';
import Link from 'next/link';
import {useRef,useState,startTransition} from 'react';
import {useOperationScope} from './operation-scope';
import {fetchRunSetup} from '../actions';
import {pageSchema,runListRow,runRow,type RunSetup} from '../schema';
import {useRegister} from './register';
import {inputClass,useWords,PageControls} from './common';
import {OfferingEditor} from './offering-editor';
import {FeeEditor} from './fee-editor';
import {BatchEditor} from './batch-editor';
const pages=pageSchema(runListRow);
type Section='new'|'run'|'fees'|'batches'|'website'|null;
export function OfferingWorkspace({permissions,area='run'}:{permissions:string[];area:'run'|'fees'|'batches'|'website'}){
 const t=useWords(),scope=useOperationScope(),list=useRegister('runs',pages,{division:scope.division||undefined}),[setup,setSetup]=useState<RunSetup|null>(null),[editor,setEditor]=useState<Section>(null),[batchId,setBatchId]=useState<string|'NEW'|null>(null),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false),generation=useRef(0);
 const canManage=permissions.includes('academics.manage'),canFees=permissions.includes('fees.manage');
 function open(id:string,section:Section,page=1,message=''){const sequence=++generation.current;setLoading(true);setNotice(message);startTransition(async()=>{try{const value=await fetchRunSetup(id,page);if(sequence===generation.current){setSetup(value);setEditor(section);setBatchId(null);}}catch{if(sequence===generation.current)setNotice(t('Setup could not be loaded. Retry.','Setup লোড হয়নি। আবার চেষ্টা করুন।'));}finally{if(sequence===generation.current)setLoading(false);}});}
 function close(){generation.current++;setEditor(null);setBatchId(null);setLoading(false);}
 function saved(next:Section=null){const message=t('Saved. Setup updated; history retained.','সংরক্ষিত। Setup হালনাগাদ হয়েছে; ইতিহাস থাকবে।');close();setNotice(message);void list.load();if(setup&&next)open(setup.run.id,next,1,message);}
 const run=setup?.run,feeReady=!!setup?.feeSettings,editing=!!editor||loading;
 return <section className="space-y-5"><header className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-semibold">{t({run:'Programme offerings',fees:'Standard fees',batches:'Batches',website:'Website & applications'}[area],{run:'Programme offerings',fees:'নির্ধারিত ফি',batches:'ব্যাচ',website:'Website ও আবেদন'}[area])}</h1><p className="mt-2 text-sm text-muted-foreground">{t('Set context → fees & discounts → batch → publish/open applications. Choose a dedicated work area above.','Context → ফি ও ছাড় → ব্যাচ → প্রকাশ/আবেদন খুলুন। উপরে প্রয়োজনীয় কাজের পৃথক পেজ নির্বাচন করুন।')}</p></div><div className="flex flex-wrap gap-2">{canManage&&area==='run'&&<button type="button" disabled={editing||!scope.division} className="rounded-lg bg-primary px-4 py-2.5 text-primary-foreground" onClick={()=>{setSetup(null);setEditor('new');setNotice('');}}>{t('Create programme offering','Programme offering তৈরি')}</button>}</div></header><p className="text-xs text-muted-foreground">{t('Programme list follows the selected operation. People and shared directory records remain academy-wide. Starter fees are editable defaults; review before publishing.','প্রোগ্রাম তালিকা নির্বাচিত পরিচালনা অনুযায়ী। People ও shared directory একাডেমিজুড়ে একই। Starter ফি পরিবর্তনযোগ্য—প্রকাশের আগে যাচাই করুন।')}</p>{notice&&<p role="status" className="rounded-lg border p-3">{notice}</p>}

 {editor==='new'&&<OfferingEditor key="NEW" setup={null} divisionId={scope.division} permissions={permissions} onCancel={close} onDone={data=>{runRow.parse(data);close();void list.load();setNotice(t('Offering saved. Next: open Standard fees, then Batches.','Offering সংরক্ষিত। পরের কাজ: নির্ধারিত ফি, এরপর ব্যাচ।'));}}/>}
 {(editor==='run'||editor==='website')&&setup&&<OfferingEditor key={setup.run.id+'_'+setup.run.revision} publication={editor==='website'} setup={setup} divisionId={scope.division} permissions={permissions} onCancel={close} onDone={()=>saved()}/>}
 {editor==='fees'&&setup&&<FeeEditor key={setup.run.id+'_'+(setup.feeSettings?.revision??0)} setup={setup} onCancel={close} onDone={()=>saved()}/>}
 {editor==='batches'&&setup&&run&&<section className="space-y-4 rounded-xl border p-5"><header className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{t('Batches','ব্যাচ')} · {run.title}</h2><p className="text-sm">{t('Once fees and an active batch are ready, edit the programme to publish or open applications.','ফি ও active batch প্রস্তুত হলে প্রোগ্রাম edit করে প্রকাশ বা আবেদন খুলুন।')}</p></div>{!batchId&&<button type="button" onClick={close}>{t('Close','বন্ধ')}</button>}</header>{!feeReady&&<p className="rounded-lg border p-3">{t('Save standard fees before creating a batch.','ব্যাচ তৈরির আগে নির্ধারিত ফি সংরক্ষণ করুন।')}{canFees&&<Link prefetch={false} className="ml-3 underline" href="/dashboard/academics/fees">{t('Open standard fees','নির্ধারিত ফি খুলুন')}</Link>}</p>}
 {batchId?<BatchEditor key={batchId} setup={setup} batchId={batchId==='NEW'?null:batchId} onCancel={()=>setBatchId(null)} onDone={()=>saved('batches')}/>:<>{canManage&&<button type="button" disabled={!feeReady||!run.is_active||loading} className="rounded-lg border px-4 py-2" onClick={()=>setBatchId('NEW')}>{t('Create batch','ব্যাচ তৈরি')}</button>}<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>{t('Batch','ব্যাচ')}</th><th>{t('Enrollment / seats','ভর্তি / আসন')}</th><th>{t('Status','অবস্থা')}</th><th>{t('Actions','পদক্ষেপ')}</th></tr></thead><tbody>{setup.batches.map(b=><tr key={b.id} className="border-t"><td className="py-3">{b.name}<p className="text-xs">{b.code}</p></td><td>{b.occupied}/{b.capacity}</td><td>{b.is_active?t('Active','সক্রিয়'):t('Inactive','নিষ্ক্রিয়')}</td><td>{canManage&&<button type="button" disabled={loading||!run.is_active} className="underline" onClick={()=>setBatchId(b.id)}>{t('Edit / mark inactive','সংশোধন / নিষ্ক্রিয়')}</button>}</td></tr>)}</tbody></table>{!setup.batches.length&&<p className="py-3">{t('No batch yet. Create the first batch above.','ব্যাচ নেই। উপরের button দিয়ে প্রথম ব্যাচ তৈরি করুন।')}</p>}</div><PageControls page={setup.batchPage} total={setup.batchTotal} onPage={p=>open(run.id,'batches',p)}/>{canManage&&feeReady&&setup.batches.some(b=>b.is_active)&&<Link prefetch={false} href="/dashboard/academics/website" className="inline-block rounded-lg bg-primary px-4 py-2 text-primary-foreground">{t('Next: publish / open applications','পরের ধাপ: প্রকাশ / আবেদন খুলুন')}</Link>}</>}
 </section>}
 <form className="flex gap-3" onSubmit={e=>{e.preventDefault();void list.load(1,list.query);}}><input aria-label={t('Search programmes','প্রোগ্রাম খুঁজুন')} className={inputClass} value={list.query} onChange={e=>list.setQuery(e.target.value)} maxLength={160}/><button disabled={list.loading} className="rounded-lg border px-4">{t('Search','খুঁজুন')}</button></form>
 {list.loading||loading?<p role="status">{t('Loading…','লোড হচ্ছে…')}</p>:list.error?<p role="alert">{t('Load failed.','লোড হয়নি।')} <button onClick={()=>void list.load()} className="underline">{t('Retry','আবার চেষ্টা')}</button></p>:<div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="text-left">{[t('Programme','প্রোগ্রাম'),t('Operation / class','পরিচালনা / ক্লাস'),t('Status / website / intake','অবস্থা / website / আবেদন'),t('Actions','পদক্ষেপ')].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{list.data.rows.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-medium">{r.title}<p className="font-normal text-xs text-muted-foreground">{r.programme_name} · {r.code}</p></td><td>{r.division_name} · {r.class_code??t('Course dates','কোর্সের তারিখ')}</td><td><span className={`rounded-full border px-2 py-1 text-xs ${r.is_active?'border-green-500/50 text-green-600':'text-muted-foreground'}`}>{r.is_active?t('Active','সক্রিয়'):t('Inactive','নিষ্ক্রিয়')}</span><p className="mt-2 text-xs">{r.website_visible?t('Visible','দৃশ্যমান'):t('Hidden','অপ্রকাশিত')} · {r.applications_open?t('Open','খোলা'):t('Closed','বন্ধ')}</p></td><td className="space-x-3 p-3">{(area==='fees'?canFees:canManage)&&<button disabled={editing} type="button" className="rounded-lg border px-3 py-2" onClick={()=>open(r.id,area)}>{t(area==='website'?'Manage website':area==='fees'?'Edit fees':area==='batches'?'Manage batches':'Edit offering',area==='website'?'Website পরিচালনা':area==='fees'?'ফি সংশোধন':area==='batches'?'ব্যাচ পরিচালনা':'Offering সংশোধন')}</button>}</td></tr>)}</tbody></table>{!list.data.rows.length&&<p className="p-4">{t('No matching programmes. Create a programme or change the operation/search.','প্রোগ্রাম পাওয়া যায়নি। প্রোগ্রাম তৈরি করুন অথবা পরিচালনা/search বদলান।')}</p>}</div>}
 <PageControls page={list.data.page} total={list.data.total} onPage={p=>void list.load(p)}/>
 </section>;
}
