'use client';
import { useState } from 'react';
import { fetchPerson } from '../actions';
import { pageSchema,personListRow,type Person,responsibilities } from '../schema';
import { Editor,Reason,ValueField,Field,inputClass,text,useWords,PageControls } from './common';
import { DirectoryPicker } from './directory-picker';
import { useRegister } from './register';
const peoplePage=pageSchema(personListRow);
export function PeopleWorkspace({permissions}:{permissions:string[]}) {
 const t=useWords(),list=useRegister('people',peoplePage),[editor,setEditor]=useState<Person|'NEW'|null>(null),[notice,setNotice]=useState(''),[loadingPerson,setLoadingPerson]=useState(false),[statusPerson,setStatusPerson]=useState<{id:string;revision:number;is_active:boolean}|null>(null);
 const manage=permissions.includes('people.manage'),directoryCreate=permissions.includes('directory.manage');
 async function edit(id:string){setLoadingPerson(true);setNotice('');try{setEditor(await fetchPerson(id));}catch{setNotice(t('Could not load this person. Retry.','ব্যক্তির তথ্য লোড হয়নি। আবার চেষ্টা করুন।'));}finally{setLoadingPerson(false);}}
 const person=editor&&editor!=='NEW'?editor:null;
 const labels:Record<typeof responsibilities[number],[string,string]>={STUDENT:['Student','শিক্ষার্থী'],GUARDIAN:['Guardian','অভিভাবক'],STAFF:['Staff','স্টাফ'],TEACHER:['Teacher','শিক্ষক'],REFERRER:['Referrer','রেফারার']};
 return <div className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">{t('People','ব্যক্তি ও পরিচয়')}</h1><p className="mt-1 text-sm text-muted-foreground">{t('One identity, several responsibilities. Shared family mobile numbers are allowed.','একটি পরিচয়, একাধিক দায়িত্ব। পরিবারের একই মোবাইল ব্যবহার করা যায়।')}</p></div>{manage&&!editor&&<button className="rounded-lg bg-primary px-4 py-2.5 text-primary-foreground" onClick={()=>setEditor('NEW')}>{t('Add person','ব্যক্তি যোগ করুন')}</button>}</header>
 {notice&&<p role="status" className="rounded-lg border p-3">{notice}</p>}
 {statusPerson&&<Editor title={t(statusPerson.is_active?'Mark inactive':'Reactivate',statusPerson.is_active?'নিষ্ক্রিয় করুন':'আবার সক্রিয় করুন')} command="personActive" onCancel={()=>setStatusPerson(null)} onDone={()=>{setStatusPerson(null);setNotice(t('Status saved.','অবস্থা সংরক্ষিত।'));void list.load();}} read={f=>({id:statusPerson.id,revision:statusPerson.revision,is_active:!statusPerson.is_active,reason:text(f,'reason')})}><p>{t('Existing history is retained. Active placements must be closed before deactivation.','পুরোনো তথ্য থাকবে। সক্রিয় ভর্তি থাকলে আগে সেটি বন্ধ করতে হবে।')}</p><Reason/></Editor>}
 {editor&&<Editor key={person?.id??'NEW'} title={t(person?'Edit person':'New person',person?'তথ্য সংশোধন':'নতুন ব্যক্তি')} command="person" onCancel={()=>setEditor(null)} onDone={()=>{setEditor(null);setNotice(t('Person saved. Responsibilities do not grant login access.','তথ্য সংরক্ষিত। দায়িত্ব নির্বাচন login access দেয় না।'));void list.load();}}
 read={f=>({...(person?{id:person.id,revision:person.revision}:{}),full_name:text(f,'full_name'),full_name_bn:text(f,'full_name_bn'),mobile:text(f,'mobile'),email:text(f,'email'),date_of_birth:text(f,'date_of_birth'),
 present_address:{line:text(f,'present_address.line'),locality:text(f,'present_address.locality')},permanent_address:{line:text(f,'permanent_address.line'),locality:text(f,'permanent_address.locality')},same_address:f.has('same_address'),responsibilities:f.getAll('responsibilities').map(String),reason:text(f,'reason')})}>
 <ValueField name="full_name" label={t('Full name','পূর্ণ নাম')} value={person?.full_name} required maxLength={160}/><ValueField name="full_name_bn" label={t('Bangla name (optional)','বাংলা নাম (ঐচ্ছিক)')} value={person?.full_name_bn} maxLength={160}/>
 <ValueField name="mobile" label={t('Mobile (optional)','মোবাইল (ঐচ্ছিক)')} type="tel" value={person?.mobile} maxLength={11}/><ValueField name="email" label={t('Email (optional)','ইমেইল (ঐচ্ছিক)')} type="email" value={person?.email} maxLength={200}/>
 <ValueField name="date_of_birth" label={t('Date of birth (optional)','জন্মতারিখ (ঐচ্ছিক)')} type="date" value={person?.date_of_birth}/>
 <div className="sm:col-span-2"><p className="mb-2 text-sm font-medium">{t('Responsibilities — choose all applicable','দায়িত্ব — প্রযোজ্যগুলো নির্বাচন করুন')}</p><div className="flex flex-wrap gap-4">{responsibilities.map(role=><label key={role} className="flex items-center gap-2 text-sm"><input type="checkbox" name="responsibilities" value={role} defaultChecked={person?.responsibilities.includes(role)}/>{t(...labels[role])}</label>)}</div><p className="mt-2 text-xs text-muted-foreground">{t('Teacher also includes Staff. Account permissions are configured separately.','Teacher হলে Staff-ও যুক্ত হবে। Account permissions আলাদাভাবে নির্ধারিত হয়।')}</p></div>
 <Field name="present_address.line" label={t('Present address','বর্তমান ঠিকানা')}><textarea id="present_address.line" className={inputClass} name="present_address.line" defaultValue={String(person?.present_address.line??'')} rows={3} maxLength={500}/></Field>
 <div><ValueField name="present_address.locality" label={t('Special locality / landmark','বিশেষ এলাকা / পরিচিত স্থান')} value={String(person?.present_address.locality??'')} maxLength={160}/><p className="mt-2 text-xs">{t('Select an area to fill this locality, or type a specific landmark.','এলাকা নির্বাচন করে পূরণ করুন, অথবা নির্দিষ্ট স্থান লিখুন।')}</p><DirectoryPicker name="present_area" kind="AREA" canCreate={directoryCreate} onSelect={c=>{const element=document.getElementById('present_address.locality');if(element instanceof HTMLInputElement){element.value=c.name;element.dispatchEvent(new Event('change',{bubbles:true}));}}}/></div>
 <label className="flex items-center gap-2 sm:col-span-2"><input type="checkbox" name="same_address" defaultChecked={!person}/>{t('Permanent address is the same as present address','স্থায়ী ঠিকানা বর্তমান ঠিকানার মতো')}</label>
 <ValueField name="permanent_address.line" label={t('Permanent address (if different)','স্থায়ী ঠিকানা (আলাদা হলে)')} value={String(person?.permanent_address.line??'')} maxLength={500}/><ValueField name="permanent_address.locality" label={t('Permanent locality','স্থায়ী এলাকার নাম')} value={String(person?.permanent_address.locality??'')} maxLength={160}/>
 <Reason/>{person&&<p className="text-sm text-muted-foreground">{t('Permanent identity','স্থায়ী পরিচয়')}: P-{person.person_no} · {t('Status','অবস্থা')}: {person.is_active?t('Active','সক্রিয়'):t('Inactive','নিষ্ক্রিয়')}</p>}
 </Editor>}
 <form className="flex gap-3" onSubmit={e=>{e.preventDefault();void list.load(1,list.query);}}><input aria-label={t('Search name, person number or mobile','নাম, পরিচিতি নম্বর বা মোবাইল খুঁজুন')} className={inputClass} value={list.query} onChange={e=>list.setQuery(e.target.value)} maxLength={160}/><button disabled={list.loading} className="rounded-lg border px-4">{t('Search','খুঁজুন')}</button></form>
 {list.loading||loadingPerson?<p role="status">{t('Loading…','লোড হচ্ছে…')}</p>:list.error?<p role="alert">{t('Search failed.','খোঁজা যায়নি।')} <button onClick={()=>void list.load()} className="underline">{t('Retry','আবার চেষ্টা')}</button></p>:<div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left">{[t('Person / name','পরিচয় / নাম'),t('Mobile','মোবাইল'),t('Email','ইমেইল'),t('Status','অবস্থা'),t('Actions','পদক্ষেপ')].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{list.data.rows.map(p=><tr key={p.id} className="border-b"><td className="p-3"><strong>{p.full_name}</strong><p className="text-xs">P-{p.person_no}</p></td><td>{p.mobile??'—'}</td><td>{p.email??'—'}</td><td>{p.is_active?t('Active','সক্রিয়'):t('Inactive','নিষ্ক্রিয়')}</td><td>{manage&&<button onClick={()=>void edit(p.id)} className="underline">{t('Edit details & responsibilities','তথ্য ও দায়িত্ব সংশোধন')}</button>}{manage&&<button className="ml-3 underline" onClick={()=>setStatusPerson(p)}>{t(p.is_active?'Mark inactive':'Reactivate',p.is_active?'নিষ্ক্রিয় করুন':'সক্রিয় করুন')}</button>}</td></tr>)}</tbody></table>{!list.data.rows.length&&<p className="p-4">{t('No matching people.','মিল পাওয়া যায়নি।')}</p>}</div>}
 <PageControls page={list.data.page} total={list.data.total} onPage={p=>void list.load(p)}/>
 </div>;
}
