'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useState,type ReactNode} from 'react';
import {LayoutDashboard,UsersRound,GraduationCap,Settings2,MessagesSquare,PanelLeftClose,PanelLeftOpen,ArrowLeft} from 'lucide-react';
import {useWords} from './common';
import {navigation,currentRoute} from '../navigation';
import {OperationScope,useOperationScope} from './operation-scope';
type Props={name:string;academyName:string;permissions:string[];divisions:{id:string;name:string;nameBn:string;code:string}[];children:ReactNode};
const icons=[LayoutDashboard,MessagesSquare,UsersRound,GraduationCap,Settings2];
function Shell({name,academyName,permissions,children}:Props){
 const t=useWords(),path=usePathname(),active=currentRoute(path),[collapsed,setCollapsed]=useState(false),[mobileOpen,setMobileOpen]=useState(false),scope=useOperationScope();
 const groups=navigation.map((g,index)=>({...g,index,items:g.items.filter(i=>!i.permission||(i.permission==='academic.workspace'?permissions.includes('academics.view')||permissions.includes('directory.view'):permissions.includes(i.permission)))})).filter(g=>g.items.length);
 const menu=(compact=false)=><>{groups.map(group=>{const Icon=icons[group.index];return <section key={group.group[0]} className="space-y-1 py-3"><p className={`px-3 pb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground ${compact?'sr-only':''}`}>{t(group.group[0],group.group[1])}</p>{group.items.map(item=><Link key={item.href} href={item.href} onClick={()=>setMobileOpen(false)} title={t(item.label[0],item.label[1])} aria-current={active?.href===item.href?'page':undefined} className={`flex min-h-11 items-center gap-3 rounded-lg px-3 py-2 text-sm ${active?.href===item.href?'bg-primary text-primary-foreground':'hover:bg-muted'}`}><Icon className="size-5 shrink-0" aria-hidden="true"/><span className={compact?'sr-only':''}>{t(item.label[0],item.label[1])}</span></Link>)}</section>;})}<p className={`px-3 text-xs text-muted-foreground ${compact?'sr-only':''}`}>{t('Finance and admission workspace follow the implementation plan.','Finance ও admission workspace implementation plan অনুযায়ী পরের ধাপ।')}</p></>;
 return <div className="min-h-screen bg-background text-foreground"><aside className={`fixed inset-y-0 left-0 z-30 hidden flex-col border-r bg-card p-3 lg:flex ${collapsed?'w-20':'w-64'}`}><Link href="/dashboard" className="px-3 py-5 font-bold" aria-label={academyName}>{collapsed?'SA':academyName}</Link><nav aria-label={t('ERP navigation','ERP মেনু')} className="flex-1 overflow-y-auto">{menu(collapsed)}</nav><button type="button" onClick={()=>setCollapsed(!collapsed)} className="rounded-lg border p-3" aria-label={t(collapsed?'Expand sidebar':'Collapse sidebar',collapsed?'মেনু বড় করুন':'মেনু ছোট করুন')}>{collapsed?<PanelLeftOpen className="size-5"/>:<PanelLeftClose className="size-5"/>}</button></aside><div className={collapsed?'lg:pl-20':'lg:pl-64'}><header className="sticky top-0 z-20 border-b bg-background/95 px-4 py-3 backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs text-muted-foreground">{t('Digital Campus','ডিজিটাল ক্যাম্পাস')}</p><p className="font-semibold">{active?t(active.label[0],active.label[1]):t('Workspace','কর্মক্ষেত্র')}</p></div><div className="flex flex-wrap items-center gap-3"><label className="text-sm">{t('Operation','পরিচালনা')}<select aria-label={t('Operation filter','পরিচালনার ফিল্টার')} value={scope.division} onChange={e=>scope.setDivision(e.target.value)} className="ml-2 rounded-lg border bg-background p-2"><option value="">{t('All operations','সব পরিচালনা')}</option>{scope.divisions.map(d=><option key={d.id} value={d.id}>{t(d.name,d.nameBn)}</option>)}</select></label><span className="text-sm">{name}</span></div></div><details className="mt-3 lg:hidden" open={mobileOpen} onToggle={e=>setMobileOpen(e.currentTarget.open)}><summary className="cursor-pointer rounded-lg border px-3 py-2 text-sm">{t('Navigation','মেনু খুলুন')}</summary><nav aria-label={t('Mobile ERP navigation','মোবাইল ERP মেনু')} className="max-h-[65vh] overflow-auto py-2">{menu()}</nav></details></header><main className="mx-auto max-w-6xl space-y-5 p-4 md:p-6">{path!=='/dashboard'&&<Link href="/dashboard" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:underline"><ArrowLeft className="size-4"/>{t('Back to dashboard','ড্যাশবোর্ডে ফিরুন')}</Link>}{children}</main></div></div>;
}
export function WorkspaceShell(props:Props){return <OperationScope divisions={props.divisions}><Shell {...props}/></OperationScope>;}
