'use client';
import {useCallback,useEffect,useRef,useState,useTransition} from 'react';
import {fetchAcademicYears} from '../actions';
import type {AcademicYear} from '../schema';
import {Editor,ValueField,ActiveCheck,Reason,PageControls,text,useWords} from './common';
export function YearWorkspace({canManage,onClose}:{canManage:boolean;onClose?:()=>void}){
 const initialized=useRef(false);
 const t=useWords(),[pending,start]=useTransition(),[rows,setRows]=useState<AcademicYear[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[editor,setEditor]=useState<AcademicYear|'NEW'|null>(null),[message,setMessage]=useState('');
 const load=useCallback((next=page)=>{start(async()=>{try{const result=await fetchAcademicYears(next);setRows(result.rows);setPage(next);setTotal(result.total);}catch{setMessage(t('Years could not be loaded. Retry.','বছরের তালিকা লোড হয়নি। আবার চেষ্টা করুন।'));}});},[page,start,t]);
 useEffect(()=>{if(initialized.current)return;initialized.current=true;load(1);},[load]);
 const year=editor&&editor!=='NEW'?editor:null;
 return <section className="space-y-4 rounded-xl border p-5"><header className="flex justify-between gap-3"><div><h2 className="text-xl font-semibold">{t('Academic years','শিক্ষাবর্ষ')}</h2><p className="text-sm">{t('Several years may be active together. Training uses course dates without a school year.','একাধিক শিক্ষাবর্ষ একসঙ্গে সক্রিয় থাকতে পারে। Training-এর জন্য school year নয়, কোর্সের তারিখ ব্যবহার হবে।')}</p></div>{onClose&&<button disabled={!!editor} type="button" onClick={onClose}>{t('Close','বন্ধ')}</button>}</header>{message&&<p role="status">{message}</p>}
 {canManage&&!editor&&<button type="button" onClick={()=>setEditor('NEW')} className="rounded-lg border px-4 py-2">{t('Create academic year','শিক্ষাবর্ষ তৈরি')}</button>}
 {editor&&<Editor key={year?.id??'NEW'} title={t(year?'Edit academic year':'Create academic year',year?'শিক্ষাবর্ষ সংশোধন':'শিক্ষাবর্ষ তৈরি')} command="year" onCancel={()=>setEditor(null)} onDone={()=>{setEditor(null);setMessage(t('Year saved.','শিক্ষাবর্ষ সংরক্ষিত।'));load();}} read={f=>({...year?{id:year.id,revision:year.revision}:{},name:text(f,'name'),starts_on:text(f,'starts_on'),ends_on:text(f,'ends_on'),is_active:f.has('is_active'),reason:text(f,'reason')})}><ValueField name="name" label={t('Year name','শিক্ষাবর্ষের নাম')} value={year?.name} required maxLength={80}/><ValueField name="starts_on" label={t('Starts on','শুরু')} value={year?.starts_on} type="date" required/><ValueField name="ends_on" label={t('Ends on','শেষ')} value={year?.ends_on} type="date" required/><ActiveCheck value={year?.is_active??true}/><Reason value="Reviewed academic year dates and availability"/></Editor>}
 {pending?<p role="status">{t('Loading…','লোড হচ্ছে…')}</p>:<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>{t('Name','নাম')}</th><th>{t('Dates','তারিখ')}</th><th>{t('Status','অবস্থা')}</th><th>{t('Actions','পদক্ষেপ')}</th></tr></thead><tbody>{rows.map(y=><tr key={y.id} className="border-t"><td className="py-3">{y.name}</td><td>{y.starts_on} → {y.ends_on}</td><td>{y.is_active?t('Active','সক্রিয়'):t('Inactive','নিষ্ক্রিয়')}</td><td>{canManage&&<button disabled={!!editor} type="button" className="underline" onClick={()=>setEditor(y)}>{t('Edit / mark inactive','সংশোধন / নিষ্ক্রিয়')}</button>}</td></tr>)}</tbody></table></div>}<PageControls page={page} total={total} onPage={load}/><button type="button" disabled={pending||!!editor} onClick={()=>load()} className="underline">{t('Refresh','আবার দেখুন')}</button></section>;
}
