'use client';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {z} from 'zod';
import {useWords,inputClass} from '@/modules/academy/components/common';
import {OperationForm} from '@/modules/academics/operation-form';
import {loadAccessSettings,saveAccessSettings} from './permission-actions';
const role=z.object({code:z.string(),permissions:z.array(z.string()),revision:z.number()});
const account=z.object({id:z.string(),display_name:z.string(),email:z.string().nullable(),staff_id:z.string().nullable(),is_active:z.boolean(),revision:z.number(),roles:z.array(z.string()),workspaces:z.array(z.string())});
const schema=z.object({roles:z.array(role),divisions:z.array(z.object({id:z.string(),name:z.string(),nameBn:z.string()})),rows:z.array(account),page:z.number(),total:z.number()});
const permissions=[['admissions.view','View admissions','ভর্তি দেখুন'],['admissions.manage','Prepare and confirm admissions','ভর্তি প্রস্তুত ও নিশ্চিত করুন'],['billing.view','View student bills and receipts','শিক্ষার্থীর বিল ও রসিদ দেখুন'],['billing.manage','Record payments and billing adjustments','আদায় ও বিল সংশোধন করুন'],['people.view','View people and applications','পরিচয় ও আবেদন দেখুন'],['people.manage','Edit people','পরিচয় সংশোধন'],['directory.view','View shared academic choices','শিক্ষার তালিকা দেখুন'],['directory.manage','Edit shared academic choices','শিক্ষার তালিকা সংশোধন'],['academics.view','View academic work','শিক্ষা পরিচালনা দেখুন'],['academics.manage','Schedule and manage classes','ক্লাস পরিকল্পনা ও পরিচালনা'],['academics.teach','Record own attendance and submit class work','নিজ ক্লাসের উপস্থিতি ও প্রতিবেদন জমা'],['academics.review','Approve or return teaching reports (with class management)','শিক্ষকের প্রতিবেদন অনুমোদন বা ফেরত (ক্লাস পরিচালনাসহ)'],['fees.manage','Manage standard fees','নির্ধারিত ফি পরিচালনা'],['activity.view','View activity evidence','কাজের ইতিহাস দেখুন']];
export function PermissionSettings({initial}:{initial:unknown}){
 const t=useWords(),router=useRouter(),[data,setData]=useState(()=>schema.parse(initial)),[editor,setEditor]=useState<{kind:'ROLE'|'ACCOUNT';id:string}|null>(null),[query,setQuery]=useState(''),[pending,start]=useTransition(),[message,setMessage]=useState('');
 const selectedRole=data.roles.find(x=>x.code===editor?.id),selectedAccount=data.rows.find(x=>x.id===editor?.id);
 function refresh(page=data.page){start(async()=>{try{setData(schema.parse(await loadAccessSettings(query,page)));setMessage('');}catch{setMessage(t('Access settings could not be loaded. Retry.','প্রবেশাধিকারের তথ্য আসেনি। আবার চেষ্টা করুন।'));}});}
 return <section className="space-y-5"><h1 className="text-2xl font-semibold">{t('Roles, permissions & workspaces','দায়িত্ব, অনুমতি ও কর্মক্ষেত্র')}</h1><p>{t('First set what each role can do; then assign verified accounts to roles and workspaces. Teacher viewing stays limited to assigned classes unless you explicitly grant management access. Administrator recovery access is protected.','আগে দায়িত্ব অনুযায়ী কাজের অনুমতি দিন; তারপর যাচাইকৃত account-এর দায়িত্ব ও কর্মক্ষেত্র নির্ধারণ করুন। পরিচালনার অনুমতি আলাদা করে না দিলে শিক্ষক শুধু নিজের ক্লাস দেখবেন। প্রশাসকের recovery access সুরক্ষিত।')}</p>{message&&<p role="status">{message}</p>}<div className="grid gap-3 sm:grid-cols-2">{data.roles.map(r=><article key={r.code} className="rounded-xl border p-4"><h2 className="font-semibold">{r.code}</h2><ul className="my-3 space-y-1 text-sm">{permissions.filter(p=>r.permissions.includes(p[0])).map(p=><li key={p[0]}>{t(p[1],p[2])}</li>)}</ul>{r.code==='ADMIN'?<p className="text-sm">{t('Protected administrator access','সুরক্ষিত প্রশাসকের অনুমতি')}</p>:<button disabled={!!editor||pending} className="cursor-pointer rounded-lg border px-3 py-2" onClick={()=>setEditor({kind:'ROLE',id:r.code})}>{t('Edit permissions','অনুমতি সংশোধন')}</button>}</article>)}</div>
 {editor?.kind==='ROLE'&&selectedRole&&<OperationForm reasonOptions={[t('Configured responsibilities for academy operations','একাডেমি পরিচালনার দায়িত্ব নির্ধারণ করেছি'),t('Updated verified account access','যাচাইকৃত account প্রবেশাধিকার সংশোধন করেছি')]} title={t(`Permissions — ${selectedRole.code}`,`অনুমতি — ${selectedRole.code}`)} save={saveAccessSettings} onCancel={()=>setEditor(null)} onSaved={async()=>{setEditor(null);refresh();router.refresh();}} serialize={fd=>({action:'ROLE',role:selectedRole.code,revision:selectedRole.revision,permissions:fd.getAll('permissions').map(String),reason:String(fd.get('reason'))})}>{permissions.map(([code,en,bn])=><label key={code} className="flex cursor-pointer items-start gap-2"><input name="permissions" type="checkbox" value={code} defaultChecked={selectedRole.permissions.includes(code)}/><span>{t(en,bn)}</span></label>)}</OperationForm>}
 <h2 className="text-xl font-semibold">{t('Verified accounts','যাচাইকৃত account')}</h2><form className="flex gap-3" onSubmit={e=>{e.preventDefault();refresh(1);}}><input className={inputClass} value={query} maxLength={160} aria-label={t('Find account','Account খুঁজুন')} placeholder={t('Name, email or staff number','নাম, ইমেইল বা স্টাফ নম্বর')} onChange={e=>setQuery(e.target.value)} disabled={!!editor||pending}/><button disabled={!!editor||pending} className="cursor-pointer rounded-lg border px-4">{pending?t('Loading…','তথ্য আসছে…'):t('Search','খুঁজুন')}</button></form>
 <div className="overflow-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr>{[t('Person','ব্যক্তি'),t('Roles','দায়িত্ব'),t('Workspaces','কর্মক্ষেত্র'),t('Account access','Account প্রবেশাধিকার')].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{data.rows.map(a=><tr className="border-t" key={a.id}><td className="p-3">{a.display_name}<p>{a.staff_id}</p><p>{a.email}</p></td><td>{a.roles.join(' · ')}</td><td>{a.roles.includes('ADMIN')?t('All workspaces','সব কর্মক্ষেত্র'):data.divisions.filter(d=>a.workspaces.includes(d.id)).map(d=>t(d.name,d.nameBn)).join(' · ')||t('Not assigned','নির্ধারণ করা হয়নি')}</td><td>{a.is_active?t('Enabled','সক্রিয়'):t('Disabled','নিষ্ক্রিয়')} {!a.roles.includes('ADMIN')&&<button disabled={!!editor||pending} className="ml-2 cursor-pointer rounded-lg border px-3 py-2" onClick={()=>setEditor({kind:'ACCOUNT',id:a.id})}>{t('Edit access','প্রবেশাধিকার সংশোধন')}</button>}</td></tr>)}</tbody></table></div>
 {editor?.kind==='ACCOUNT'&&selectedAccount&&<OperationForm reasonOptions={[t('Configured responsibilities for academy operations','একাডেমি পরিচালনার দায়িত্ব নির্ধারণ করেছি'),t('Updated verified account access','যাচাইকৃত account প্রবেশাধিকার সংশোধন করেছি')]} title={t(`Access — ${selectedAccount.display_name}`,`প্রবেশাধিকার — ${selectedAccount.display_name}`)} save={saveAccessSettings} onCancel={()=>setEditor(null)} onSaved={async()=>{setEditor(null);refresh();router.refresh();}} serialize={fd=>({action:'ACCOUNT',id:selectedAccount.id,revision:selectedAccount.revision,roles:fd.getAll('roles').map(String),workspaces:fd.getAll('workspaces').map(String),active:fd.has('active'),reason:String(fd.get('reason'))})}><fieldset><legend>{t('Responsibilities','দায়িত্ব')}</legend>{data.roles.filter(r=>r.code!=='ADMIN').map(r=><label key={r.code} className="my-2 flex gap-2"><input name="roles" type="checkbox" value={r.code} defaultChecked={selectedAccount.roles.includes(r.code)}/>{r.code}</label>)}</fieldset><fieldset><legend>{t('Allowed workspaces','অনুমোদিত কর্মক্ষেত্র')}</legend>{data.divisions.map(d=><label key={d.id} className="my-2 flex gap-2"><input name="workspaces" type="checkbox" value={d.id} defaultChecked={selectedAccount.workspaces.includes(d.id)}/>{t(d.name,d.nameBn)}</label>)}</fieldset><label className="flex gap-2"><input type="checkbox" name="active" defaultChecked={selectedAccount.is_active}/>{t('Account enabled','Account সক্রিয়')}</label></OperationForm>}
 <div className="flex gap-4"><button className="cursor-pointer rounded-lg border px-3 py-2" disabled={!!editor||pending||data.page===1} onClick={()=>refresh(data.page-1)}>{t('Previous','আগের')}</button><span>{data.page} · {data.total}</span><button className="cursor-pointer rounded-lg border px-3 py-2" disabled={!!editor||pending||data.page*25>=data.total} onClick={()=>refresh(data.page+1)}>{t('Next','পরের')}</button></div></section>;
}
