'use client';
import {useState,useTransition,type FormEvent} from 'react';
import {requestAccess} from './actions';
import {roles} from './schema';
import {inputClass,useWords} from '@/modules/academy/components/common';
export function AccessRequestForm(){const t=useWords(),[pending,start]=useTransition(),[sent,setSent]=useState(false),[message,setMessage]=useState('');
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const input=Object.fromEntries(new FormData(e.currentTarget));start(async()=>{try{const result=await requestAccess(input);setSent(result.ok);setMessage(result.ok?t('Request received. The academy will verify your identity and responsibilities, then send account setup instructions.','অনুরোধ গ্রহণ করা হয়েছে। একাডেমি পরিচয় ও দায়িত্ব যাচাই করে account চালুর নির্দেশনা পাঠাবে।'):t(result.message,'নাম, ইমেইল ও প্রয়োজনীয় তথ্য যাচাই করুন অথবা পরে আবার চেষ্টা করুন।'));}catch{setMessage(t('Could not confirm submission. Retry with the same details.','অনুরোধ নিশ্চিত হয়নি। একই তথ্য দিয়ে আবার চেষ্টা করুন।'));}});}
 return <form onSubmit={submit} className="space-y-4">{!sent&&<fieldset disabled={pending} className="space-y-4"><label className="block">{t('Full name','পূর্ণ নাম')}<input name="full_name" required minLength={2} maxLength={160} className={inputClass}/></label><label className="block">{t('Personal login email','নিজস্ব login ইমেইল')}<input name="email" type="email" required maxLength={200} className={inputClass}/></label><label className="block">{t('Mobile (optional; shared contacts allowed)','মোবাইল (ঐচ্ছিক; একই যোগাযোগ ব্যবহার করা যায়)')}<input name="mobile" type="tel" pattern="01[3-9][0-9]{8}" maxLength={11} className={inputClass}/></label><label className="block">{t('Requested responsibility','যে দায়িত্বের জন্য আবেদন')}<select name="requested_role" required defaultValue="" className={inputClass}><option value="">{t('Choose role','দায়িত্ব নির্বাচন করুন')}</option>{roles.map(r=><option key={r} value={r}>{t({ADMIN:'Administrator',OPERATOR:'Operator',TEACHER:'Teacher',ACCOUNTANT:'Accountant',REFERRER:'Referrer'}[r],{ADMIN:'প্রশাসক',OPERATOR:'অপারেটর',TEACHER:'শিক্ষক',ACCOUNTANT:'হিসাবরক্ষক',REFERRER:'রেফারার'}[r])}</option>)}</select></label><label className="block">{t('Why do you need access?','কেন প্রবেশাধিকার প্রয়োজন?')}<textarea name="purpose" required minLength={5} maxLength={500} rows={3} className={inputClass}/></label><input name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/><button className="w-full rounded-xl bg-primary p-3 text-primary-foreground" disabled={pending}>{pending?t('Submitting…','পাঠানো হচ্ছে…'):t('Request account access','প্রবেশাধিকারের অনুরোধ পাঠান')}</button></fieldset>}{message&&<p role="status" className="rounded-xl border p-4">{message}</p>}</form>;
}
