'use client';
import {useEffect,useRef,useState,useTransition} from 'react';
import Link from 'next/link';
import {listRequests,reviewRequest,sendSetup} from './actions';
import {roles,type AccessRequest} from './schema';
import {findPersonMatches} from '@/modules/academy/actions';
import {personListRow} from '@/modules/academy/schema';
import type {z} from 'zod';
import {inputClass,text,useWords,PageControls} from '@/modules/academy/components/common';
export function RequestWorkspace(){
 const t=useWords(),[pending,start]=useTransition(),[rows,setRows]=useState<AccessRequest[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[history,setHistory]=useState(false),[selected,setSelected]=useState<AccessRequest|null>(null),[matches,setMatches]=useState<z.infer<typeof personListRow>[]>([]),[message,setMessage]=useState(''),[loadingMatches,setLoadingMatches]=useState(false),[matchFailed,setMatchFailed]=useState(false),generation=useRef(0),requestToken=useRef(crypto.randomUUID());
 function load(next=page,all=history){start(async()=>{try{const value=await listRequests(next,all);setRows(value.rows);setPage(next);setTotal(value.total);}catch{setMessage(t('Requests could not be loaded. Retry.','অনুরোধ লোড হয়নি। আবার চেষ্টা করুন।'));}});}
 useEffect(()=>{load(1,false);},[]);
 function choose(row:AccessRequest){setSelected(row);setMatches([]);setMessage('');setLoadingMatches(true);setMatchFailed(false);requestToken.current=crypto.randomUUID();const seq=++generation.current;start(async()=>{try{const found=await findPersonMatches({full_name:row.full_name,mobile:row.mobile??'',email:row.email});if(seq===generation.current)setMatches(found);}catch{if(seq===generation.current)setMatchFailed(true);}finally{if(seq===generation.current)setLoadingMatches(false);}});}
 function setup(id:string){start(async()=>{try{const result=await sendSetup(id);setMessage(t(result.message,result.ok?'Account access প্রস্তুত। নতুন account হলে নিরাপদ নির্দেশনা পাঠানো হয়েছে; আগের account হলে sign in বা password recovery ব্যবহার করুন।':'Account setup সম্পন্ন হয়নি। Configuration ও অনুরোধ যাচাই করে আবার চেষ্টা করুন।'));load();}catch{setMessage(t('Setup could not be confirmed. Retry safely; the existing account is reused.','Account setup নিশ্চিত হয়নি। আবার চেষ্টা করুন; আগের account ব্যবহার হবে।'));}});}
 return <section className="space-y-5"><h1 className="text-2xl font-semibold">{t('Account access requests','প্রবেশাধিকারের অনুরোধ')}</h1><p>{t('Verify the person, link an existing identity or create it once, choose access, then send secure setup instructions. Requested roles do not grant permissions.','পরিচয় যাচাই করে আগের পরিচয় link করুন অথবা একবার তৈরি করুন। অনুমোদিত দায়িত্ব দিয়ে নিরাপদ নির্দেশনা পাঠান। আবেদনের দায়িত্ব নিজে থেকে access দেয় না।')}</p><Link href="/dashboard/settings" className="text-sm underline">{t('Account configuration guide','Account configuration নির্দেশনা')}</Link><label className="block"><input type="checkbox" checked={history} onChange={e=>{setHistory(e.target.checked);load(1,e.target.checked);}}/> {t('Include completed and declined requests','সম্পন্ন ও বাতিল অনুরোধসহ দেখুন')}</label>{message&&<p role="status" className="rounded-lg border p-3">{message}</p>}
 {selected&&<form key={selected.id} className="space-y-4 rounded-xl border p-5" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={id:selected.id,revision:selected.revision,request_id:requestToken.current,decision:text(f,'decision'),role:text(f,'role'),person_id:selected.person_id??(text(f,'person_id')||undefined),new_identity_confirmed:f.has('new_identity_confirmed'),reason:text(f,'reason')};start(async()=>{try{const result=await reviewRequest(payload);setMessage(t(result.message,result.ok?'যাচাই সংরক্ষিত। এখন account setup নির্দেশনা পাঠান।':'নির্বাচন যাচাই করুন। অনুরোধ বদলে গেলে তালিকা refresh করুন।'));if(result.ok){setSelected(null);load();}}catch{setMessage(t('Review could not be confirmed. Retry unchanged.','যাচাই নিশ্চিত হয়নি। একই তথ্য দিয়ে আবার চেষ্টা করুন।'));}});}}><h2 className="font-semibold">{selected.full_name} · {selected.email}</h2><p className="text-sm">{selected.purpose}</p><fieldset disabled={pending||loadingMatches} className="space-y-4"><label className="block">{t('Permitted login role','অনুমোদিত login দায়িত্ব')}<select name="role" className={inputClass} defaultValue={selected.approved_role??selected.requested_role}>{roles.map(r=><option key={r} value={r}>{r}</option>)}</select></label>{selected.person_id?<p>{t('Identity already linked. Retries reuse the same person.','পরিচয় link করা আছে। পুনরায় চেষ্টা করলে একই পরিচয় থাকবে।')}</p>:<><label className="block">{t('Existing identity','আগের পরিচয়')}<select name="person_id" className={inputClass} defaultValue=""><option value="">{t('New person after verification','যাচাইয়ের পর নতুন পরিচয়')}</option>{matches.filter(m=>m.is_active).map(m=><option key={m.id} value={m.id}>{m.full_name} · P-{m.person_no} · {m.mobile??'—'} · {m.email??'—'}</option>)}</select></label><p className="text-sm">{loadingMatches?t('Checking identities…','পরিচয় খোঁজা হচ্ছে…'):matchFailed?t('Matching failed. Check the People directory before creating a new identity.','মিল খোঁজা যায়নি। নতুন পরিচয়ের আগে People তালিকা যাচাই করুন।'):t(`${matches.length} possible matches. Shared contacts are never merged automatically.`,`${matches.length}টি সম্ভাব্য মিল। একই যোগাযোগের record স্বয়ংক্রিয়ভাবে একত্র হবে না।`)}</p><Link href="/dashboard/people" target="_blank" className="underline text-sm">{t('Check People in a new tab','নতুন tab-এ People যাচাই করুন')}</Link><label className="flex gap-2 text-sm"><input type="checkbox" name="new_identity_confirmed"/>{t('I checked existing identities; this is a different person if creating new.','আগের পরিচয় যাচাই করেছি; নতুন তৈরি করলে এটি আলাদা ব্যক্তি।')}</label></>}
 <label className="block">{t('Verification reason','যাচাইয়ের কারণ')}<select name="reason" required className={inputClass}><option value="Verified identity, contact ownership and required responsibilities">{t('Verified identity, email ownership and responsibilities','পরিচয়, ইমেইলের মালিকানা ও দায়িত্ব যাচাই করেছি')}</option><option value="Declined after identity and responsibility review">{t('Declined after review','যাচাইয়ের পর বাতিল')}</option></select></label><label>{t('Decision','সিদ্ধান্ত')}<select name="decision" className={inputClass}><option value="VERIFY">{t('Verify','যাচাই করুন')}</option><option value="DECLINE">{t('Decline','বাতিল করুন')}</option></select></label><div className="flex gap-3"><button disabled={pending} className="rounded-lg bg-primary px-4 py-2 text-primary-foreground">{pending?t('Saving…','সংরক্ষণ হচ্ছে…'):t('Save review','যাচাই সংরক্ষণ')}</button><button type="button" className="underline" onClick={()=>{generation.current++;setSelected(null);}}>{t('Cancel','বাতিল')}</button></div></fieldset></form>}
 <div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left">{[t('Person / contact','পরিচয় / যোগাযোগ'),t('Requested role','আবেদনের দায়িত্ব'),t('Status','অবস্থা'),t('Actions','পদক্ষেপ')].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b"><td className="p-3">{r.full_name}<p>{r.email}</p><p>{r.mobile??'—'}</p></td><td>{r.requested_role}</td><td>{r.status}</td><td className="p-3">{['NEW','VERIFIED'].includes(r.status)&&<button disabled={pending} className="mr-3 underline" onClick={()=>choose(r)}>{t('Review','যাচাই')}</button>}{r.status==='VERIFIED'&&<button disabled={pending} className="underline" onClick={()=>setup(r.id)}>{t('Enable account / send setup','Account চালু / নির্দেশনা পাঠান')}</button>}{r.status==='INVITED'&&<span>{t('Awaiting first sign-in','প্রথম sign-in-এর অপেক্ষায়')}</span>}{r.status==='ACTIVE'&&<span>{t('Account active','Account সক্রিয়')}</span>}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-4">{t('No requests in this queue.','এই তালিকায় অনুরোধ নেই।')}</p>}</div><button type="button" disabled={pending} onClick={()=>load()} className="underline">{pending?t('Loading…','লোড হচ্ছে…'):t('Refresh','আবার দেখুন')}</button><PageControls page={page} total={total} onPage={p=>load(p)}/></section>;
}
