'use client';
import {bangladeshToday} from '@/modules/academics/class-time';
import Link from 'next/link';
import {useState,useTransition} from 'react';
import {z} from 'zod';
import {inputClass,PageControls,useWords} from '@/modules/academy/components/common';
import {loadAcademicCalendar} from './actions';
const schema=z.object({page:z.number(),pageSize:z.number(),total:z.number(),from:z.string(),through:z.string(),sessions:z.array(z.object({id:z.string(),batch_name:z.string(),subject_name:z.string(),teacher_name:z.string(),room_name:z.string(),starts_at:z.string(),ends_at:z.string(),status:z.string()})),closures:z.array(z.object({date:z.string(),name:z.string()}))});
export function CalendarDesk({initial}:{initial:unknown}){
 const t=useWords(),[data,setData]=useState(()=>schema.parse(initial)),[filter,setFilter]=useState({from:data.from,through:data.through,status:''}),[pending,start]=useTransition(),[message,setMessage]=useState('');
 function load(page=1,next=filter){start(async()=>{setMessage('');try{setData(schema.parse(await loadAcademicCalendar(next.from,next.through,page,next.status)));setFilter(next);}catch(error){setMessage(error instanceof Error?error.message:t('Calendar could not load.','ক্যালেন্ডার আসেনি।'));}});}
 function range(days:number){const from=bangladeshToday(),end=new Date(from+'T00:00:00Z');end.setUTCDate(end.getUTCDate()+days-1);load(1,{from,through:end.toISOString().slice(0,10),status:''});}
 return <section className="space-y-5"><h1 className="text-3xl font-semibold">{t('Class calendar','ক্লাস ক্যালেন্ডার')}</h1><p>{t('Choose a date range, then open a class to work on it. All times are Bangladesh time.','তারিখসীমা দিন; তারপর ক্লাস খুলে কাজ করুন। সব সময় বাংলাদেশ সময়।')}</p><div className="flex gap-3">{[1,7,30].map(days=><button key={days} disabled={pending} className="cursor-pointer rounded-lg border px-4 py-2" onClick={()=>range(days)}>{days===1?t('Today','আজ'):t(`Next ${days} days`,`আগামী ${days} দিন`)}</button>)}</div>
 <form className="flex flex-wrap items-end gap-3 rounded-xl border p-4" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);load(1,{from:String(fd.get('from')),through:String(fd.get('through')),status:String(fd.get('status'))});}} key={JSON.stringify(filter)}><label>{t('From','শুরু')}<input required type="date" name="from" defaultValue={filter.from} className={inputClass}/></label><label>{t('Through · maximum 32 days','শেষ · সর্বোচ্চ ৩২ দিন')}<input required type="date" name="through" defaultValue={filter.through} className={inputClass}/></label><label>{t('Status','অবস্থা')}<select name="status" className={inputClass} defaultValue={filter.status}><option value="">{t('All','সব')}</option>{['SCHEDULED','SUBMITTED','RETURNED','APPROVED','CANCELLED'].map(x=><option key={x}>{x}</option>)}</select></label><button disabled={pending} className="cursor-pointer rounded-lg bg-primary px-4 py-2 text-primary-foreground">{pending?t('Loading…','তথ্য আসছে…'):t('Show classes','ক্লাস দেখুন')}</button></form>
 {message&&<p role="alert" className="rounded-lg border p-3">{message}</p>}{data.closures.length>0&&<aside className="rounded-lg border p-3"><h2 className="font-semibold">{t('Closed dates','বন্ধের দিন')}</h2>{data.closures.map(x=><p key={x.date}>{x.date} · {x.name}</p>)}</aside>}
 <div className="overflow-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr>{[t('Date / time','তারিখ / সময়'),t('Batch / subject','ব্যাচ / বিষয়'),t('Teacher / room','শিক্ষক / শ্রেণিকক্ষ'),t('Status','অবস্থা'),t('Action','পদক্ষেপ')].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{data.sessions.map(x=><tr key={x.id} className="border-t"><td className="p-3">{new Date(x.starts_at).toLocaleString(t('en-GB','bn-BD'),{timeZone:'Asia/Dhaka'})}–{new Date(x.ends_at).toLocaleTimeString(t('en-GB','bn-BD'),{timeZone:'Asia/Dhaka',hour:'2-digit',minute:'2-digit'})}</td><td>{x.batch_name}<p>{x.subject_name}</p></td><td>{x.teacher_name}<p>{x.room_name}</p></td><td>{x.status}</td><td className="p-3"><Link className="cursor-pointer rounded-lg border px-3 py-2 hover:bg-muted" prefetch={false} href={`/dashboard/academics/sessions/${x.id}`}>{t('Open class','ক্লাস খুলুন')}</Link></td></tr>)}</tbody></table>{!data.sessions.length&&<p className="p-4">{t('No classes in this date range.','এই তারিখসীমায় ক্লাস নেই।')}</p>}</div><PageControls page={data.page} total={data.total} onPage={load}/>
 </section>;
}
