'use client';
import Link from 'next/link';
import {useState,useTransition} from 'react';
import {z} from 'zod';
import {inputClass,PageControls,useWords} from '@/modules/academy/components/common';
import {searchAcademy} from '@/modules/academy/actions';
import {loadPlacements,savePlacement} from './actions';
import {OperationForm} from './operation-form';
const schema=z.object({page:z.number(),total:z.number(),batches:z.array(z.object({id:z.string(),name:z.string()})),rows:z.array(z.object({id:z.string(),person_id:z.string(),name:z.string(),revision:z.number(),starts_on:z.string(),ends_before:z.string().nullable()}))});
type Row=z.infer<typeof schema>['rows'][number];
export function PlacementDesk({initial,batchId}:{initial:unknown;batchId:string}){
 const t=useWords(),[data,setData]=useState(()=>schema.parse(initial)),[form,setForm]=useState<{action:'ENROLL'|'TRANSFER'|'CLOSE';row?:Row}|null>(null),[students,setStudents]=useState<{id:string;full_name:string}[]>([]),[pending,start]=useTransition(),[message,setMessage]=useState('');
 async function reload(page=data.page){setData(schema.parse(await loadPlacements(batchId,page)));}
 return <section className="space-y-5"><h1 className="text-3xl font-semibold">{t('Batch enrollment','ব্যাচে শিক্ষার্থী')}</h1><Link href="/dashboard/academics/batches" prefetch={false} className="cursor-pointer underline">{t('← Back to batches','← ব্যাচের তালিকা')}</Link><p>{t('Place an existing student, transfer within the same offering, or close enrollment. Effective dates preserve old attendance. For a new student, use Admissions.','আগের শিক্ষার্থীকে ব্যাচে দিন, একই offering-এর ব্যাচ বদলান অথবা enrollment বন্ধ করুন। কার্যকর তারিখ অনুযায়ী আগের attendance থাকবে। নতুন শিক্ষার্থীর জন্য ভর্তি ব্যবহার করুন।')}</p>{!form&&<button className="cursor-pointer rounded-lg border px-4 py-2" onClick={()=>setForm({action:'ENROLL'})}>{t('Enroll an existing student','আগের শিক্ষার্থীকে ব্যাচে দিন')}</button>}{message&&<p role="status">{message}</p>}
 {form&&<><form onSubmit={e=>{e.preventDefault();const query=String(new FormData(e.currentTarget).get('query')??'');start(async()=>{try{const result=await searchAcademy('people',{query,page:1,responsibility:'STUDENT'});setStudents(result.rows.filter(p=>p.is_active) as {id:string;full_name:string}[]);setMessage(t('Choose a matching existing student.','মিল পাওয়া আগের শিক্ষার্থী নির্বাচন করুন।'));}catch(error){setMessage(error instanceof Error?error.message:'Search failed.');}});}} hidden={form.action!=='ENROLL'} className="flex gap-3"><input name="query" className={inputClass} placeholder={t('Search student name / mobile','শিক্ষার্থীর নাম / মোবাইল খুঁজুন')}/><button disabled={pending} className="cursor-pointer rounded-lg border px-4 py-2">{pending?t('Searching…','খোঁজা হচ্ছে…'):t('Search','খুঁজুন')}</button></form>
 <OperationForm title={t('Change placement','ব্যাচের দায়িত্ব পরিবর্তন')} reasonOptions={['Confirmed student placement','Transferred after discussion with guardian','Closed enrollment after verification']} save={savePlacement} onCancel={()=>setForm(null)} onSaved={async()=>{setForm(null);await reload();setMessage(t('Placement saved; past attendance remains intact.','ব্যাচের তথ্য সংরক্ষিত; আগের attendance থাকবে।'));}} serialize={fd=>({action:form.action,personId:form.row?.person_id??String(fd.get('personId')),batchId:form.action==='TRANSFER'?String(fd.get('batchId')):batchId,fromDate:String(fd.get('fromDate')),revision:form.row?.revision})}>
 {form.row?<p>{form.row.name}</p>:<label>{t('Existing student','আগের শিক্ষার্থী')}<select name="personId" required className={inputClass} defaultValue=""><option value="">{t('Search, then select…','খুঁজে নির্বাচন করুন…')}</option>{students.map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select></label>}{form.action==='TRANSFER'&&<label>{t('New batch in this offering','এই offering-এর নতুন ব্যাচ')}<select required name="batchId" className={inputClass} defaultValue=""><option value="">{t('Select…','নির্বাচন করুন…')}</option>{data.batches.filter(x=>x.id!==batchId).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label>}<label>{t('Effective from date','কার্যকর তারিখ')}<input name="fromDate" type="date" required className={inputClass}/></label><p className="text-sm">{t('Closing excludes attendance from this date onward. The date must be after any already recorded attendance.','বন্ধ করার তারিখ থেকে attendance তালিকায় থাকবে না। তারিখটি আগে নেওয়া attendance-এর পরে হতে হবে।')}</p></OperationForm></>}
 <table className="w-full text-left text-sm"><thead><tr>{[t('Student','শিক্ষার্থী'),t('From','শুরু'),t('Closed from','বন্ধের তারিখ'),t('Action','পদক্ষেপ')].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.rows.map(x=><tr key={x.id} className="border-t"><td className="py-3">{x.name}</td><td>{x.starts_on}</td><td>{x.ends_before??t('Open','চলমান')}</td><td>{!x.ends_before&&<div className="flex gap-2">{(['TRANSFER','CLOSE'] as const).map(action=><button key={action} disabled={!!form||pending} className="cursor-pointer rounded-lg border px-3 py-2" onClick={()=>setForm({action,row:x})}>{action==='TRANSFER'?t('Transfer','ব্যাচ বদলান'):t('Close','বন্ধ করুন')}</button>)}</div>}</td></tr>)}</tbody></table><PageControls page={data.page} total={data.total} onPage={page=>start(async()=>{try{await reload(page);}catch(error){setMessage(error instanceof Error?error.message:'Could not load placement.');}})}/>
 </section>;
}
