'use client';
import {useState} from 'react';
import type {RunSetup} from '@/modules/academy/schema';
import {inputClass,useWords} from '@/modules/academy/components/common';
import {saveAcademicPlan} from './actions';
import {OperationForm} from './operation-form';
export function PlanEditor({setup,batchId,onDone,onCancel}:{setup:RunSetup;batchId?:string;onDone:()=>void;onCancel:()=>void}){
 const t=useWords(),batch=setup.batches.find(b=>b.id===batchId),[days,setDays]=useState<number[]>(batch?.planned_slots.length?batch.planned_slots.map(x=>x.weekday):setup.run.default_weekdays),[different,setDifferent]=useState(!!batch?.planned_slots.some(x=>x.start!==batch.planned_slots[0].start||x.end!==batch.planned_slots[0].end));
 const names=[t('Sunday','রবিবার'),t('Monday','সোমবার'),t('Tuesday','মঙ্গলবার'),t('Wednesday','বুধবার'),t('Thursday','বৃহস্পতিবার'),t('Friday','শুক্রবার'),t('Saturday','শনিবার')];
 return <OperationForm title={batch?t('Batch default days & times','ব্যাচের সাধারণ দিন ও সময়'):t('Programme default teaching days','প্রোগ্রামের সাধারণ ক্লাসের দিন')} save={saveAcademicPlan} onSaved={async()=>onDone()} onCancel={onCancel} reasonOptions={['Confirmed default teaching days and times','Corrected the planned timetable']} serialize={fd=>({target:batch?'BATCH':'RUN',id:batch?.id??setup.run.id,revision:batch?.revision??setup.run.revision,weekdays:days,slots:batch?days.map(weekday=>({weekday,start:String(fd.get(different?`start-${weekday}`:'start')),end:String(fd.get(different?`end-${weekday}`:'end'))})):[]})}>
 <p className="md:col-span-2">{setup.run.title}{batch?` · ${batch.name}`:''} — {t('Defaults are planning only. Routine assigns subject, teacher and room and checks bookings. Existing sessions stay unchanged.','এটি শুধু পরিকল্পনা। রুটিনে বিষয়, শিক্ষক ও শ্রেণিকক্ষ বরাদ্দ ও booking যাচাই হবে। আগের ক্লাস বদলাবে না।')}</p><div className="flex flex-wrap gap-3 md:col-span-2">{names.map((name,index)=><label key={index}><input type="checkbox" checked={days.includes(index)} onChange={e=>setDays(e.target.checked?[...days,index].sort((a,b)=>a-b):days.filter(x=>x!==index))}/> {name}</label>)}</div><p>{days.length} {t('days per week','দিন/সপ্তাহ')}</p>
 {batch&&days.length>0&&<><label><input type="checkbox" checked={different} onChange={e=>setDifferent(e.target.checked)}/> {t('Different times by weekday','দিনভেদে আলাদা সময়')}</label>{different?days.map(weekday=><div key={weekday} className="grid grid-cols-2 gap-3 rounded-lg border p-3"><p className="col-span-2">{names[weekday]}</p><label>{t('Starts','শুরু')}<input required type="time" name={`start-${weekday}`} defaultValue={batch.planned_slots.find(x=>x.weekday===weekday)?.start??''} className={inputClass}/></label><label>{t('Ends','শেষ')}<input required type="time" name={`end-${weekday}`} defaultValue={batch.planned_slots.find(x=>x.weekday===weekday)?.end??''} className={inputClass}/></label></div>):<><label>{t('Default starts','সাধারণ শুরুর সময়')}<input required name="start" type="time" defaultValue={batch.planned_slots[0]?.start??''} className={inputClass}/></label><label>{t('Default ends','সাধারণ শেষের সময়')}<input required name="end" type="time" defaultValue={batch.planned_slots[0]?.end??''} className={inputClass}/></label></>}</>}
 {!days.length&&<p className="text-sm">{t('No default days selected. Saving clears the default plan; scheduled classes remain.','সাধারণ দিন নির্বাচন করা নেই। Save করলে default পরিকল্পনা মুছবে; তৈরি ক্লাস থাকবে।')}</p>}
 </OperationForm>;
}
