'use client';
import {useState,useTransition} from 'react';
import {z} from 'zod';
import {inputClass,useWords} from '@/modules/academy/components/common';
import {loadAcademicResources,saveAcademicResource} from './actions';
import {OperationForm} from './operation-form';
const qualification=z.object({teacher_id:z.string(),subject_id:z.string(),is_active:z.boolean(),revision:z.number()});
const block=z.object({id:z.string(),resource_kind:z.enum(['TEACHER','ROOM']),resource_id:z.string(),starts_at:z.string(),ends_at:z.string(),is_active:z.boolean(),revision:z.number(),reason:z.string()});
const register=z.object({qualifications:z.array(qualification),blocks:z.array(block),blockTotal:z.number()});
type Choice={id:string;name:string};
function local(value:string){return new Date(new Date(value).getTime()+6*3600000).toISOString().slice(0,16);}
export function ResourceRegister({teachers,subjects,rooms}:{teachers:Choice[];subjects:Choice[];rooms:Choice[]}){
 const t=useWords(),[data,setData]=useState<z.infer<typeof register>|null>(null),[page,setPage]=useState(1),[pending,startTransition]=useTransition(),[message,setMessage]=useState('');
 const [edit,setEdit]=useState<{action:'QUALIFICATION';row?:z.infer<typeof qualification>}|{action:'BLOCK';row?:z.infer<typeof block>}|null>(null);
 const [kind,setKind]=useState<'TEACHER'|'ROOM'>('TEACHER'),[teacher,setTeacher]=useState(''),[subject,setSubject]=useState('');
 async function reload(next=page){setData(register.parse(await loadAcademicResources(next)));setPage(next);}
 function open(){startTransition(async()=>{try{await reload();setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Could not load resources.');}});}
 const name=(id:string,list:Choice[])=>list.find(x=>x.id===id)?.name??t('Inactive identity','নিষ্ক্রিয় পরিচয়');
 const q=data?.qualifications.find(x=>x.teacher_id===teacher&&x.subject_id===subject);
 return <section className="space-y-4 rounded-xl border p-4"><header className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-semibold">{t('Teacher qualifications & unavailable dates','শিক্ষকের বিষয় যোগ্যতা ও অনুপলব্ধ সময়')}</h2><button disabled={pending||!!edit} className="rounded-lg border px-4 py-2" onClick={open}>{pending?t('Loading…','তথ্য আসছে…'):data?t('Refresh','Refresh'):t('Open register','তালিকা খুলুন')}</button></header>{message&&<p role="status">{message}</p>}{data&&<>
 <div className="flex gap-3"><button disabled={!!edit||pending} onClick={()=>{setTeacher('');setSubject('');setEdit({action:'QUALIFICATION'});}}>{t('Assign subject','বিষয় নির্ধারণ')}</button><button disabled={!!edit||pending} onClick={()=>{setKind('TEACHER');setEdit({action:'BLOCK'});}}>{t('Add unavailable period','অনুপলব্ধ সময় যোগ করুন')}</button></div>
 {edit&&<OperationForm key={edit.action+(edit.row&&'id'in edit.row?edit.row.id:teacher+subject)} title={edit.action==='QUALIFICATION'?t('Verify subject qualification','বিষয়ের যোগ্যতা যাচাই'):t('Unavailable period','অনুপলব্ধ সময়')} reasonOptions={edit.action==='QUALIFICATION'?['Verified subject teaching qualification','Removed subject teaching qualification']:['Teacher leave confirmed','Classroom maintenance confirmed','Unavailable period corrected','Resource available again']} save={saveAcademicResource} onSaved={async()=>{await reload();setEdit(null);}} onCancel={()=>setEdit(null)} serialize={fd=>edit.action==='QUALIFICATION'?{action:'QUALIFICATION',teacherId:teacher,subjectId:subject,revision:q?.revision??0,active:fd.get('active')==='on'}:{action:'BLOCK',...(edit.row?{id:edit.row.id,revision:edit.row.revision}:{}),kind,resourceId:String(fd.get('resourceId')),start:new Date(String(fd.get('start'))+'+06:00').toISOString(),end:new Date(String(fd.get('end'))+'+06:00').toISOString(),active:fd.get('active')==='on'}}>
 {edit.action==='QUALIFICATION'?<><label>{t('Teacher','শিক্ষক')}<select required className={inputClass} value={teacher} onChange={e=>setTeacher(e.target.value)} disabled={!!edit.row}><option value="">Select…</option>{teachers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>{t('Subject','বিষয়')}<select required className={inputClass} value={subject} onChange={e=>setSubject(e.target.value)} disabled={!!edit.row}><option value="">Select…</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><input key={q?.revision??'new'} name="active" type="checkbox" defaultChecked={q?.is_active??true}/> {t('Qualified for future classes','পরবর্তী ক্লাসের জন্য যোগ্য')}</label></>:<><label>{t('Resource type','ধরন')}<select className={inputClass} value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="TEACHER">Teacher</option><option value="ROOM">Classroom</option></select></label><label>{t('Resource','শিক্ষক বা classroom')}<select key={kind} required name="resourceId" className={inputClass} defaultValue={edit.row?.resource_id??''}><option value="">Select…</option>{(kind==='TEACHER'?teachers:rooms).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>{t('From · Bangladesh time','শুরু · বাংলাদেশ সময়')}<input name="start" required type="datetime-local" className={inputClass} defaultValue={edit.row?local(edit.row.starts_at):undefined}/></label><label>{t('Until · Bangladesh time','শেষ · বাংলাদেশ সময়')}<input name="end" required type="datetime-local" className={inputClass} defaultValue={edit.row?local(edit.row.ends_at):undefined}/></label><label><input name="active" type="checkbox" defaultChecked={edit.row?.is_active??true}/> {t('Unavailable','ব্যবহার করা যাবে না')}</label></>}
 </OperationForm>}
 <details open><summary>{t('Subject assignments','বিষয়ের দায়িত্ব')}</summary><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Teacher</th><th>Subject</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.qualifications.map(x=><tr key={x.teacher_id+x.subject_id} className="border-t"><td className="p-2">{name(x.teacher_id,teachers)}</td><td>{name(x.subject_id,subjects)}</td><td>{x.is_active?'Active':'Inactive'}</td><td><button disabled={!!edit||pending} onClick={()=>{setTeacher(x.teacher_id);setSubject(x.subject_id);setEdit({action:'QUALIFICATION',row:x});}}>{t('Edit / inactive','সম্পাদনা / নিষ্ক্রিয়')}</button></td></tr>)}</tbody></table></div></details>
 <details><summary>{t('Unavailable periods','অনুপলব্ধ সময়')}</summary>{data.blocks.map(x=><article key={x.id} className="flex flex-wrap justify-between gap-3 border-t py-3"><p>{name(x.resource_id,x.resource_kind==='TEACHER'?teachers:rooms)} · {new Date(x.starts_at).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'})} – {new Date(x.ends_at).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'})} · {x.is_active?'Unavailable':'Inactive'}</p><button disabled={!!edit||pending} onClick={()=>{setKind(x.resource_kind);setEdit({action:'BLOCK',row:x});}}>{t('Edit / inactive','সম্পাদনা / নিষ্ক্রিয়')}</button></article>)}<div className="flex gap-3"><button disabled={pending||!!edit||page===1} onClick={()=>startTransition(async()=>{try{await reload(page-1);}catch{setMessage('Could not load the page.');}})}>Previous</button><span>Page {page}</span><button disabled={pending||!!edit||page*25>=data.blockTotal} onClick={()=>startTransition(async()=>{try{await reload(page+1);}catch{setMessage('Could not load the page.');}})}>Next</button></div></details>
 </>}</section>;
}
