'use client';
import {useState} from 'react';
import {z} from 'zod';
import {inputClass,useWords} from '@/modules/academy/components/common';
import {loadClassWork,saveClassWork} from './actions';
import {OperationForm} from './operation-form';
import {localClassTime} from './class-time';
const status=z.enum(['PRESENT','ABSENT','LATE','EXCUSED']);
const schema=z.object({manage:z.boolean(),canEdit:z.boolean(),session:z.object({id:z.string(),revision:z.number(),status:z.string(),report:z.string().nullable(),review_note:z.string().nullable(),actual_start:z.string().nullable(),actual_end:z.string().nullable(),starts_at:z.string(),ends_at:z.string(),homework:z.string(),homework_due_on:z.string().nullable(),assessment_kind:z.string(),assessment_note:z.string()}),roster:z.array(z.object({id:z.string(),name:z.string(),personNo:z.number()})),attendance:z.array(z.object({personId:z.string(),status,note:z.string().nullable()}))});
export function SessionWork({initial,onSaved}:{initial:unknown;onSaved?:()=>void}){
 const t=useWords(),[data,setData]=useState(()=>schema.parse(initial)),[open,setOpen]=useState(false),[mode,setMode]=useState<'DRAFT'|'SUBMIT'>('DRAFT'),[marks,setMarks]=useState<Record<string,string>>(()=>Object.fromEntries(schema.parse(initial).attendance.map(x=>[x.personId,x.status]))),[message,setMessage]=useState('');
 const s=data.session;
 const labels={PRESENT:t('Present','উপস্থিত'),ABSENT:t('Absent','অনুপস্থিত'),LATE:t('Late','দেরিতে এসেছে'),EXCUSED:t('Excused','অনুমতিতে অনুপস্থিত')};
 return <section className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">{t('Attendance & class work','উপস্থিতি ও ক্লাসের কাজ')}</h2><p>{t('Student attendance, teaching time and staff presence are separate records. Only approved actual teaching time counts in the teaching-hours report.','শিক্ষার্থীর উপস্থিতি, পাঠদানের সময় ও স্টাফ উপস্থিতি আলাদা record। অনুমোদিত actual সময়ই teaching-hours report-এ গণনা হবে।')}</p>{s.review_note&&<p className="rounded-lg border p-3">{t('Review note','যাচাইয়ের মন্তব্য')}: {s.review_note}</p>}{message&&<p role="status">{message}</p>}
 {data.canEdit&&!open&&<button className="cursor-pointer rounded-lg bg-primary px-4 py-2 text-primary-foreground" onClick={()=>setOpen(true)}>{t('Take attendance / prepare report','উপস্থিতি নিন / প্রতিবেদন প্রস্তুত করুন')}</button>}
 {open&&<OperationForm key={s.revision} title={t('Record class work','ক্লাসের কাজ লিখুন')} reasonOptions={['Recorded actual attendance and class work','Corrected class report after review']} save={saveClassWork} onCancel={()=>setOpen(false)} onSaved={async()=>{setOpen(false);setData(schema.parse(await loadClassWork(s.id)));setMessage(mode==='SUBMIT'?t('Submitted. An administrator will review your work.','জমা হয়েছে। প্রশাসক কাজ যাচাই করবেন।'):t('Draft saved. Return here to finish and submit.','খসড়া সংরক্ষিত। এখান থেকেই শেষ করে জমা দিন।'));onSaved?.();}} serialize={fd=>({action:mode,id:s.id,revision:s.revision,attendance:data.roster.filter(p=>marks[p.id]).map(p=>({personId:p.id,status:marks[p.id],note:String(fd.get(`note-${p.id}`)??'')})),report:String(fd.get('report')??''),homework:String(fd.get('homework')??''),homeworkDueOn:String(fd.get('homeworkDueOn')??''),assessmentKind:String(fd.get('assessmentKind')??'NONE'),assessmentNote:String(fd.get('assessmentNote')??''),actualStart:fd.get('actualStart')?new Date(String(fd.get('actualStart'))+'+06:00').toISOString():null,actualEnd:fd.get('actualEnd')?new Date(String(fd.get('actualEnd'))+'+06:00').toISOString():null})}>
 <div className="md:col-span-2"><button className="mb-3 cursor-pointer rounded-lg border px-3 py-2" type="button" onClick={()=>setMarks(Object.fromEntries(data.roster.map(p=>[p.id,'PRESENT'])))}>{t('Mark all present; then adjust exceptions','সবাই উপস্থিত; ব্যতিক্রমগুলো বদলান')}</button><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>{t('Student','শিক্ষার্থী')}</th><th>{t('Attendance','উপস্থিতি')}</th><th>{t('Optional note','ঐচ্ছিক মন্তব্য')}</th></tr></thead><tbody>{data.roster.map(p=><tr key={p.id} className="border-t"><td className="p-2">{p.name}</td><td><select aria-label={t(`Attendance for ${p.name}`,`${p.name}-এর উপস্থিতি`)} required={mode==='SUBMIT'} value={marks[p.id]??''} className={inputClass} onChange={e=>setMarks({...marks,[p.id]:e.target.value})}><option value="">{t('Select…','নির্বাচন করুন…')}</option>{Object.entries(labels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></td><td><input name={`note-${p.id}`} maxLength={500} className={inputClass} defaultValue={data.attendance.find(x=>x.personId===p.id)?.note??''}/></td></tr>)}</tbody></table></div>{!data.roster.length&&<p className="text-sm">{t('No students enrolled for this class date. Ask the administrator to check dated batch enrollment.','এই ক্লাসের তারিখে ভর্তি শিক্ষার্থী নেই। প্রশাসককে তারিখসহ batch enrollment যাচাই করতে বলুন।')}</p>}</div>
 <label>{t('What was taught','কী শেখানো হয়েছে')}<textarea name="report" className={inputClass} required={mode==='SUBMIT'} minLength={mode==='SUBMIT'?3:undefined} maxLength={10000} defaultValue={s.report??''}/></label><label>{t('Homework (optional)','বাড়ির কাজ (ঐচ্ছিক)')}<textarea name="homework" className={inputClass} maxLength={3000} defaultValue={s.homework}/></label><label>{t('Homework due date','বাড়ির কাজ জমার তারিখ')}<input name="homeworkDueOn" type="date" className={inputClass} defaultValue={s.homework_due_on??''}/></label><label>{t('Assessment type','মূল্যায়নের ধরন')}<select name="assessmentKind" className={inputClass} defaultValue={s.assessment_kind}>{[['NONE',t('None','নেই')],['CLASS_TEST',t('Class test','ক্লাস পরীক্ষা')],['QUIZ',t('Quiz','কুইজ')],['PRACTICE',t('Practice','অনুশীলন')],['MODEL_TEST',t('Model test','মডেল টেস্ট')]].map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><label>{t('Assessment note (optional)','মূল্যায়নের মন্তব্য (ঐচ্ছিক)')}<textarea name="assessmentNote" className={inputClass} maxLength={3000} defaultValue={s.assessment_note}/></label><label>{t('Actual start · Bangladesh time','প্রকৃত শুরু · বাংলাদেশ সময়')}<input name="actualStart" type="datetime-local" required={mode==='SUBMIT'} className={inputClass} defaultValue={s.actual_start?localClassTime(s.actual_start):''}/></label><label>{t('Actual end · Bangladesh time','প্রকৃত শেষ · বাংলাদেশ সময়')}<input name="actualEnd" type="datetime-local" required={mode==='SUBMIT'} className={inputClass} defaultValue={s.actual_end?localClassTime(s.actual_end):''}/></label><label>{t('Save as','সংরক্ষণের ধরন')}<select className={inputClass} value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="DRAFT">{t('Draft — finish later','খসড়া — পরে শেষ করবো')}</option><option value="SUBMIT">{t('Submit for admin review','প্রশাসকের যাচাইয়ের জন্য জমা')}</option></select></label>
 </OperationForm>}
 {!open&&<><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>{t('Student','শিক্ষার্থী')}</th><th>{t('Attendance','উপস্থিতি')}</th><th>{t('Note','মন্তব্য')}</th></tr></thead><tbody>{data.roster.map(p=>{const a=data.attendance.find(x=>x.personId===p.id);return <tr key={p.id} className="border-t"><td className="p-2">{p.name}</td><td>{a?labels[a.status]:t('Not recorded','রেকর্ড হয়নি')}</td><td>{a?.note??'—'}</td></tr>;})}</tbody></table></div><dl className="grid gap-3 md:grid-cols-2"><div><dt>{t('Teaching report','পাঠদানের প্রতিবেদন')}</dt><dd className="whitespace-pre-wrap">{s.report??'—'}</dd></div><div><dt>{t('Homework / due date','বাড়ির কাজ / জমার তারিখ')}</dt><dd>{s.homework||'—'} {s.homework_due_on}</dd></div><div><dt>{t('Assessment','মূল্যায়ন')}</dt><dd>{s.assessment_kind} · {s.assessment_note||'—'}</dd></div><div><dt>{t('Actual start / end','প্রকৃত শুরু / শেষ')}</dt><dd>{s.actual_start?localClassTime(s.actual_start):'—'} → {s.actual_end?localClassTime(s.actual_end):'—'}</dd></div></dl></>}
 </section>;
}
