'use client';
import Link from 'next/link';
import {ResourceRegister} from './resource-register';
import {useState,useTransition} from 'react';
import {z} from 'zod';
import {loadAcademicDesk,saveAcademicOperation} from './actions';
import {inputClass} from '@/modules/academy/components/common';
const choice=z.object({id:z.string(),name:z.string()});
const session=z.object({id:z.string(),batch_id:z.string(),subject_id:z.string(),teacher_id:z.string(),room_id:z.string(),starts_at:z.string(),ends_at:z.string(),status:z.string(),revision:z.number(),batch_name:z.string(),subject_name:z.string(),teacher_name:z.string(),room_name:z.string(),report:z.string().nullable(),actual_start:z.string().nullable(),actual_end:z.string().nullable()});
const schema=z.object({manage:z.boolean(),rooms:z.array(choice.extend({capacity:z.number(),is_active:z.boolean(),revision:z.number()})),batches:z.array(choice),teachers:z.array(choice),subjects:z.array(choice),sessions:z.array(session),total:z.number(),resources:z.object({windows:z.array(z.object({id:z.string(),resource_kind:z.string(),resource_id:z.string(),weekday:z.number(),starts:z.string(),ends:z.string(),is_active:z.boolean()})),closures:z.array(z.object({id:z.string(),closed_on:z.string(),name:z.string(),is_active:z.boolean()})),contacts:z.array(z.object({id:z.string(),name:z.string(),email:z.string(),is_active:z.boolean()}))}).optional(),queue:z.array(z.object({id:z.string(),recipient:z.string(),status:z.string(),attempts:z.number(),last_error:z.string().nullable()}))});
type Session=z.infer<typeof session>;
function local(value:string){return new Date(new Date(value).getTime()+6*3600000).toISOString().slice(0,16);}
export function SessionDesk({initial}:{initial:unknown}){
 const [data,setData]=useState(()=>schema.parse(initial)),[page,setPage]=useState(1),[form,setForm]=useState<{action:string;item?:Session;room?:z.infer<typeof schema>['rooms'][number];contactId?:string}|null>(null),[message,setMessage]=useState(''),[pending,startTransition]=useTransition(),[token,setToken]=useState<string|null>(null);
 function open(next:typeof form){if(pending)return;setForm(next);setToken(crypto.randomUUID());setMessage('');}
 function refresh(next=page){startTransition(async()=>{try{setData(schema.parse(await loadAcademicDesk(next)));setPage(next);}catch(e){setMessage(e instanceof Error?e.message:'Could not reload.');}});}
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),values=Object.fromEntries(fd),action=form!.action;const payload:Record<string,unknown>={...values,action};if(form?.contactId)payload.id=form.contactId;if(form?.item){payload.id=form.item.id;payload.revision=form.item.revision;}if(form?.room){payload.id=form.room.id;payload.revision=form.room.revision;payload.active=values.active==='on';}if(action==='ROUTINE')payload.weekdays=fd.getAll('weekdays').map(Number);if(['WINDOW','CLOSURE'].includes(action))payload.active=values.active==='on';if(action==='CONTACT')payload.consent=values.consent==='on';for(const key of ['start','end','actualStart','actualEnd'])if(values[key])payload[key]=new Date(String(values[key])+'+06:00').toISOString();startTransition(async()=>{try{const result=await saveAcademicOperation({requestId:token!,payload});setMessage(result.message);if(result.ok){setForm(null);setToken(null);setData(schema.parse(await loadAcademicDesk(page)));}}catch{setMessage('The response could not be confirmed. Retry unchanged input to safely confirm the same request.');}});}
 const picker=(name:string,label:string,options:z.infer<typeof choice>[],value?:string)=><label className="block">{label}<select name={name} required defaultValue={value??''} className={inputClass}><option value="">Select…</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>;
 const field=(name:string,label:string,type='text',value?:string)=><label className="block">{label}<input className={inputClass} name={name} type={type} required defaultValue={value}/></label>;
 return <section className="space-y-5"><Link href="/dashboard/academics">← Academics</Link><h1 className="text-3xl font-semibold">Class sessions</h1><p>Bangladesh time · dated classes, changes and teaching reports.</p>{data.manage&&<div className="flex flex-wrap gap-3">{[['CREATE','Schedule class'],['ROOM','Create classroom'],['CONTACT','Add notification contact'],['WINDOW','Weekly availability'],['CLOSURE','Holiday / closure'],['ROUTINE','Create weekly classes']].map(([action,label])=><button disabled={pending} className="rounded-lg border px-4 py-2" key={action} onClick={()=>open({action})}>{label}</button>)}</div>}{message&&<p role="status">{message}</p>}
 {form&&<form key={token} onSubmit={submit} className="space-y-4 rounded-xl border p-5" data-editor data-busy={pending} data-dirty="true"><h2 className="text-xl font-semibold">{form.action.replaceAll('_',' ')} {form.item?.batch_name}</h2><fieldset disabled={pending} className="grid gap-4 md:grid-cols-2">
 {form.action==='ROOM'&&<>{field('name','Room name','text',form.room?.name)}{field('capacity','Seats','number',String(form.room?.capacity??12))}{form.room&&<label><input name="active" type="checkbox" defaultChecked={form.room.is_active}/> Available for new classes</label>}</>}
 {form.action==='CONTACT_INACTIVE'&&<p>Stop future class emails for this contact. Messages already queued remain in the history.</p>}
 {form.action==='CONTACT'&&<>{picker('batchId','Batch',data.batches)}{field('name','Guardian / adult contact name')}{field('email','Verified email','email')}<label><input required name="consent" type="checkbox"/> Agreed to receive class updates</label></>}
 {['CREATE','CHANGE','MAKEUP','ROUTINE'].includes(form.action)&&<>{picker('batchId','Batch',data.batches,form.item?.batch_id)}{picker('subjectId','Subject',data.subjects,form.item?.subject_id)}{picker('teacherId','Teacher / substitute',data.teachers,form.item?.teacher_id)}{picker('roomId','Classroom',data.rooms.filter(x=>x.is_active),form.item?.room_id)}{form.action==='ROUTINE'?<>{field('startsOn','From date','date')}{field('endsOn','Through date (maximum 32 days)','date')}{field('startTime','Start time','time')}{field('endTime','End time','time')}<div>{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=><label className="mr-3" key={day}><input type="checkbox" name="weekdays" value={i}/>{day}</label>)}</div></>:<>{field('start','Starts (Bangladesh)','datetime-local',form.item?local(form.item.starts_at):undefined)}{field('end','Ends (Bangladesh)','datetime-local',form.item?local(form.item.ends_at):undefined)}</>}</>}
 {form.action==='WINDOW'&&<><label>Resource type<select className={inputClass} name="kind"><option>ROOM</option><option>TEACHER</option></select></label>{picker('resourceId','Room or teacher',[...data.rooms,...data.teachers])}<label>Weekday<select className={inputClass} name="weekday">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=><option value={i} key={day}>{day}</option>)}</select></label>{field('startTime','Available from','time')}{field('endTime','Available until','time')}<label><input name="active" type="checkbox" defaultChecked/> Available (uncheck same window to deactivate)</label></>}
 {form.action==='CLOSURE'&&<>{field('date','Closed date','date')}{field('name','Holiday / closure name')}<label><input name="active" type="checkbox" defaultChecked/> Closed (uncheck same date to reopen)</label></>}
 {form.action==='SUBMIT'&&<>{field('actualStart','Actual start','datetime-local',local(form.item!.starts_at))}{field('actualEnd','Actual end','datetime-local',local(form.item!.ends_at))}<label>What was taught<textarea name="report" required className={inputClass} defaultValue={form.item?.report??''}/></label></>}
 <label>Reason<select name="reason" required className={inputClass}><option value="">Select…</option>{['Scheduled agreed class','Teacher unavailable; substitute confirmed','Room unavailable; replacement confirmed','Rescheduled with affected participants','Class cancelled due to absence','Makeup arranged for cancelled class','Teaching report completed','Verified completed teaching report','Return report for correction','Confirmed room availability and capacity','Verified email and notification consent','Confirmed weekly resource availability','Confirmed holiday or reopening','Created agreed weekly timetable','Removed notification consent'].map(x=><option key={x}>{x}</option>)}</select></label></fieldset><button disabled={pending} className="rounded-lg bg-primary px-4 py-2 text-primary-foreground">{pending?'Saving…':'Confirm'}</button> <button type="button" disabled={pending} onClick={()=>open(null)}>Cancel</button></form>}
 <div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{['Class / time','Teacher / room','Status','Actions'].map(x=><th className="p-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{data.sessions.map(s=><tr key={s.id} className="border-t"><td className="p-3">{s.batch_name} · {s.subject_name}<br/>{new Date(s.starts_at).toLocaleString('en-GB',{timeZone:'Asia/Dhaka'})} – {new Date(s.ends_at).toLocaleTimeString('en-GB',{timeZone:'Asia/Dhaka'})}{s.report&&<details><summary>Teaching report</summary>{s.report}<br/>Actual: {s.actual_start} – {s.actual_end}</details>}</td><td>{s.teacher_name}<br/>{s.room_name}</td><td>{s.status}</td><td className="space-x-3">{(data.manage?(s.status==='SUBMITTED'?['APPROVE','RETURN']:s.status==='CANCELLED'?['MAKEUP']:['SCHEDULED','RETURNED'].includes(s.status)?['CHANGE','CANCEL']:[]):['SCHEDULED','RETURNED'].includes(s.status)?['SUBMIT']:[]).map(action=><button disabled={pending} key={action} onClick={()=>open({action,item:s})}>{action==='CHANGE'?'Edit / reschedule':action}</button>)}</td></tr>)}</tbody></table></div><div className="flex gap-4"><button disabled={pending||page===1} onClick={()=>refresh(page-1)}>Previous</button><span>Page {page} · {data.total} classes</span><button disabled={pending||page*25>=data.total} onClick={()=>refresh(page+1)}>Next</button><button disabled={pending} onClick={()=>refresh()}>Refresh</button></div>
 {data.manage&&<><ResourceRegister teachers={data.teachers} subjects={data.subjects} rooms={data.rooms}/><details><summary>Availability, holidays & notification contacts</summary>{data.resources?.windows.map(w=><p key={w.id}>{w.resource_kind} · {[...data.rooms,...data.teachers].find(x=>x.id===w.resource_id)?.name} · weekday {w.weekday} · {w.starts}–{w.ends} · {w.is_active?'Available':'Inactive'}</p>)}{data.resources?.closures.map(c=><p key={c.id}>{c.closed_on} · {c.name} · {c.is_active?'Closed':'Reopened'}</p>)}{data.resources?.contacts.map(c=><p key={c.id}>{c.name} · {c.email} · {c.is_active?'Active':'Inactive'} {c.is_active&&<button disabled={pending} onClick={()=>{open({action:'CONTACT_INACTIVE',contactId:c.id});}}>Mark inactive</button>}</p>)}</details><details><summary>Classrooms</summary>{data.rooms.map(room=><div key={room.id} className="flex gap-4 py-2">{room.name} · {room.capacity} seats · {room.is_active?'Active':'Inactive'}<button disabled={pending} onClick={()=>open({action:'ROOM',room})}>Edit / inactive</button></div>)}</details><details><summary>Email queue · latest 25</summary><p>Accepted means accepted by the email provider; inbox delivery is not confirmed.</p>{data.queue.map(q=><p key={q.id}>{q.recipient} · {q.status} · {q.attempts} attempts {q.last_error}</p>)}</details></>}
 </section>;
}
