'use client';
import {useState,useTransition} from 'react';
import {z} from 'zod';
import {inputClass,PageControls,useWords} from '@/modules/academy/components/common';
import {loadAcademicChoices,loadAcademicSettings,saveAcademicOperation,saveAcademicWindows} from './actions';
import {OperationForm} from './operation-form';
export type SettingsRegisterKind='ROOMS'|'WINDOWS'|'CLOSURES'|'CONTACTS'|'EMAILS';
const rowSchema=z.object({id:z.string(),name:z.string().optional(),capacity:z.number().optional(),is_active:z.boolean().optional(),revision:z.number().optional(),resource_kind:z.enum(['TEACHER','ROOM']).optional(),resource_id:z.string().optional(),resource_name:z.string().nullable().optional(),weekday:z.number().optional(),starts:z.string().optional(),ends:z.string().optional(),closed_on:z.string().optional(),batch_id:z.string().optional(),batch_name:z.string().optional(),email:z.string().optional(),recipient:z.string().optional(),status:z.string().optional(),attempts:z.number().optional(),last_error:z.string().nullable().optional()});
const pageSchema=z.object({rows:z.array(rowSchema),page:z.number(),total:z.number(),pageSize:z.number()});
const choice=z.object({id:z.string(),name:z.string()});
const choicesSchema=z.object({teachers:z.array(choice),rooms:z.array(choice),batches:z.array(choice)});
type Row=z.infer<typeof rowSchema>;
export function SettingsRegister({kind,initial}:{kind:SettingsRegisterKind;initial:unknown}){
 const t=useWords(),[data,setData]=useState(()=>pageSchema.parse(initial)),[form,setForm]=useState<{row?:Row;inactive?:boolean}|null>(null),[choices,setChoices]=useState<z.infer<typeof choicesSchema>>({teachers:[],rooms:[],batches:[]}),[resourceKind,setResourceKind]=useState<'TEACHER'|'ROOM'>('TEACHER'),[pending,startTransition]=useTransition(),[message,setMessage]=useState('');
 const days=[t('Sunday','রবিবার'),t('Monday','সোমবার'),t('Tuesday','মঙ্গলবার'),t('Wednesday','বুধবার'),t('Thursday','বৃহস্পতিবার'),t('Friday','শুক্রবার'),t('Saturday','শনিবার')];
 async function reload(page=data.page){setData(pageSchema.parse(await loadAcademicSettings(kind,page)));}
 function open(next:{row?:Row;inactive?:boolean}){if(form||pending)return;setMessage('');if(next.row?.resource_kind)setResourceKind(next.row.resource_kind);startTransition(async()=>{try{if(kind==='WINDOWS'&&!next.row)setChoices(choicesSchema.parse(await loadAcademicChoices('AVAILABILITY')));if(kind==='CONTACTS'&&!next.inactive&&!next.row)setChoices(choicesSchema.parse(await loadAcademicChoices('CONTACTS')));setForm(next);}catch{setMessage(t('Could not load the form choices. Retry.','নির্বাচনের তালিকা আসেনি। আবার চেষ্টা করুন।'));}});}
 function field(name:string,label:string,type='text',value?:string|number){return <label>{label}<input name={name} type={type} required className={inputClass} defaultValue={value}/></label>;}
 const row=form?.row;
 function serialize(fd:FormData):Record<string,unknown>{
  const active=fd.has('active');
  if(kind==='ROOMS')return{action:'ROOM',...(row?{id:row.id,revision:row.revision}:{}),name:String(fd.get('name')),capacity:Number(fd.get('capacity')),active};
  if(kind==='WINDOWS')return{...(row?{id:row.id,revision:row.revision}:{}),kind:row?.resource_kind??resourceKind,resourceId:row?.resource_id??String(fd.get('resourceId')),weekdays:fd.getAll('weekdays').map(Number),startTime:String(fd.get('startTime')),endTime:String(fd.get('endTime')),active};
  if(kind==='CLOSURES')return{action:'CLOSURE',date:row?.closed_on??String(fd.get('date')),name:String(fd.get('name')),active};
  if(form?.inactive)return{action:'CONTACT_INACTIVE',id:row!.id};
  return{action:'CONTACT',batchId:row?.batch_id??String(fd.get('batchId')),name:String(fd.get('name')),email:row?.email??String(fd.get('email')),consent:fd.has('consent')};
 }
 const addLabels={ROOMS:t('Create classroom','শ্রেণিকক্ষ তৈরি'),WINDOWS:t('Add weekly availability','সাপ্তাহিক সময় যোগ করুন'),CLOSURES:t('Add holiday / closure','ছুটি বা বন্ধের দিন যোগ করুন'),CONTACTS:t('Add notification contact','বার্তা পাওয়ার ঠিকানা যোগ করুন'),EMAILS:''};
 return <section className="space-y-4"><div className="flex gap-3">{kind!=='EMAILS'&&<button disabled={!!form||pending} onClick={()=>open({})} className="rounded-lg border px-4 py-2">{addLabels[kind]}</button>}<button disabled={!!form||pending} onClick={()=>startTransition(async()=>{try{await reload();}catch{setMessage(t('Could not refresh the list. Retry.','তালিকা আসেনি। আবার চেষ্টা করুন।'));}})} className="rounded-lg border px-4 py-2">{pending?t('Loading…','তথ্য আসছে…'):t('Refresh','আবার দেখুন')}</button></div>{message&&<p role="status">{message}</p>}
 {form&&<OperationForm title={row?t('Update record','তথ্য পরিবর্তন'):addLabels[kind]} save={kind==='WINDOWS'?saveAcademicWindows:saveAcademicOperation} onSaved={async()=>{setForm(null);try{await reload();setMessage(t('Saved. Use the next-step link above when ready.','সংরক্ষিত। প্রস্তুত হলে উপরের পরের কাজের লিংক ব্যবহার করুন।'));}catch{setMessage(t('Saved, but the list could not refresh. Use Refresh before the next action.','সংরক্ষিত; তালিকা refresh হয়নি। পরের কাজের আগে আবার দেখুন বোতাম ব্যবহার করুন।'));}}} onCancel={()=>setForm(null)} serialize={serialize} reasonOptions={kind==='ROOMS'?['Confirmed room availability and capacity']:kind==='WINDOWS'?['Confirmed weekly resource availability']:kind==='CLOSURES'?['Confirmed holiday or reopening']:form.inactive?['Removed notification consent']:['Verified email and notification consent']}>
 {kind==='ROOMS'&&<>{field('name',t('Classroom name','শ্রেণিকক্ষের নাম'),'text',row?.name)}{field('capacity',t('Seats','আসন'),'number',row?.capacity??12)}<label><input name="active" type="checkbox" defaultChecked={row?.is_active??true}/> {t('Active for new classes','নতুন ক্লাসের জন্য সক্রিয়')}</label></>}
 {kind==='WINDOWS'&&<>{row?<p>{row.resource_name}</p>:<><label>{t('Resource type','ধরন')}<select className={inputClass} value={resourceKind} onChange={e=>setResourceKind(e.target.value as typeof resourceKind)}><option value="TEACHER">{t('Teacher','শিক্ষক')}</option><option value="ROOM">{t('Classroom','শ্রেণিকক্ষ')}</option></select></label><label>{t('Select resource','শিক্ষক বা শ্রেণিকক্ষ নির্বাচন')}<select key={resourceKind} required name="resourceId" className={inputClass} defaultValue=""><option value="">{t('Select…','নির্বাচন করুন…')}</option>{(resourceKind==='TEACHER'?choices.teachers:choices.rooms).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label></>}<div className="flex flex-wrap gap-3 md:col-span-2">{row?<label>{t('Weekday','দিন')}<select name="weekdays" defaultValue={row.weekday} className={inputClass}>{days.map((day,index)=><option key={day} value={index}>{day}</option>)}</select></label>:days.map((day,index)=><label key={index}><input type="checkbox" name="weekdays" value={index}/> {day}</label>)}</div>{field('startTime',t('From · Bangladesh time','শুরু · বাংলাদেশ সময়'),'time',row?.starts)}{field('endTime',t('Until · Bangladesh time','শেষ · বাংলাদেশ সময়'),'time',row?.ends)}<label><input name="active" type="checkbox" defaultChecked={row?.is_active??true}/> {t('Available','ব্যবহারযোগ্য')}</label><p className="text-sm">{t('Select all applicable weekdays once. Existing class coverage is checked before reducing or deactivating a window.','প্রযোজ্য সব দিন একবারে নির্বাচন করুন। সময় কমানো বা বন্ধ করার আগে তৈরি ক্লাসের availability যাচাই হবে।')}</p></>}
 {kind==='CLOSURES'&&<>{row?<p>{row.closed_on}</p>:field('date',t('Date','তারিখ'),'date')}{field('name',t('Holiday / closure name','ছুটি বা বন্ধের কারণ'),'text',row?.name)}<label><input name="active" type="checkbox" defaultChecked={row?.is_active??true}/> {t('Academy closed on this date','এই দিনে একাডেমি বন্ধ')}</label></>}
 {kind==='CONTACTS'&&(form.inactive?<p>{row?.name} · {row?.email} — {t('Stop future class messages.','পরবর্তী ক্লাসের বার্তা বন্ধ করুন।')}</p>:<>{row?<p>{row.batch_name} · {row.email}</p>:<><label>{t('Batch','ব্যাচ')}<select name="batchId" required className={inputClass} defaultValue=""><option value="">{t('Select…','নির্বাচন করুন…')}</option>{choices.batches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{field('email',t('Verified email','যাচাইকৃত ইমেইল'),'email')}</>}{field('name',t('Guardian / adult name','অভিভাবক বা প্রাপ্তবয়স্কের নাম'),'text',row?.name)}<label><input required type="checkbox" name="consent"/> {t('Agreed to receive class updates','ক্লাসের বার্তা পেতে সম্মতি দিয়েছেন')}</label></>)}
 </OperationForm>}
 {kind==='EMAILS'&&<p className="text-sm text-muted-foreground">{t('Accepted means accepted by the provider; inbox delivery is not confirmed.','গ্রহণ করেছে মানে ইমেইল সেবা গ্রহণ করেছে; প্রাপকের কাছে পৌঁছানো নিশ্চিত নয়।')}</p>}
 <div className="overflow-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">{t('Record','তথ্য')}</th><th>{t('Status','অবস্থা')}</th>{kind!=='EMAILS'&&<th>{t('Action','পদক্ষেপ')}</th>}</tr></thead><tbody>{data.rows.map(x=><tr className="border-t" key={x.id}><td className="p-3">{kind==='ROOMS'?`${x.name} · ${x.capacity} ${t('seats','আসন')}`:kind==='WINDOWS'?`${x.resource_name} · ${days[x.weekday!]} · ${x.starts}–${x.ends}`:kind==='CLOSURES'?`${x.closed_on} · ${x.name}`:kind==='CONTACTS'?`${x.name} · ${x.batch_name} · ${x.email}`:<>{x.recipient} · {x.attempts} {t('attempts','বার চেষ্টা')}{x.last_error&&<p className="text-xs">{x.last_error}</p>}</>}</td><td>{kind==='EMAILS'?x.status:x.is_active?t('Active','সক্রিয়'):t('Inactive','নিষ্ক্রিয়')}</td>{kind!=='EMAILS'&&<td className="space-x-3 p-3"><button disabled={!!form||pending} onClick={()=>open({row:x})} className="underline">{t('Edit / status','সম্পাদনা / অবস্থা')}</button>{kind==='CONTACTS'&&x.is_active&&<button disabled={!!form||pending} onClick={()=>open({row:x,inactive:true})} className="underline">{t('Mark inactive','নিষ্ক্রিয়')}</button>}</td>}</tr>)}</tbody></table>{!data.rows.length&&<p className="p-4">{t('No records yet. Use the create button above when needed.','এখনো তথ্য নেই। প্রয়োজন হলে উপরের তৈরি বোতাম ব্যবহার করুন।')}</p>}</div><PageControls page={data.page} total={data.total} onPage={page=>startTransition(async()=>{try{await reload(page);}catch{setMessage(t('Could not load the page.','পাতাটি লোড হয়নি।'));}})}/>
 </section>;
}
