'use client';
import {useState,useTransition} from 'react';
import {z} from 'zod';
import {inputClass,useWords} from '@/modules/academy/components/common';
import {loadTeachingHours} from './actions';
const schema=z.array(z.object({id:z.string(),name:z.string(),classes:z.number(),approved_hours:z.number()}));
export function TeachingHours({initial,from,through}:{initial:unknown;from:string;through:string}){
 const t=useWords(),[rows,setRows]=useState(()=>schema.parse(initial)),[message,setMessage]=useState(''),[pending,start]=useTransition();
 return <section className="space-y-5"><h1 className="text-3xl font-semibold">{t('Verified teaching hours','যাচাইকৃত পাঠদানের সময়')}</h1><p>{t('Approved actual hours only. Cancelled, draft and unapproved classes do not count. This is workload evidence, not salary or staff attendance.','শুধু অনুমোদিত actual সময়। বাতিল, খসড়া ও যাচাই বাকি ক্লাস গণনা হবে না। এটি workload-এর record; বেতন বা স্টাফ উপস্থিতি নয়।')}</p><form className="flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);start(async()=>{try{setRows(schema.parse(await loadTeachingHours(String(fd.get('from')),String(fd.get('through')))));setMessage('');}catch(error){setMessage(error instanceof Error?error.message:'Could not load hours.');}});}}><label>{t('From','শুরু')}<input required name="from" type="date" defaultValue={from} className={inputClass}/></label><label>{t('Through','শেষ')}<input required name="through" type="date" defaultValue={through} className={inputClass}/></label><button disabled={pending} className="cursor-pointer rounded-lg bg-primary px-4 py-2 text-primary-foreground">{pending?t('Loading…','তথ্য আসছে…'):t('Show hours','সময় দেখুন')}</button></form>{message&&<p role="alert">{message}</p>}<table className="w-full text-left text-sm"><thead><tr><th>{t('Teacher','শিক্ষক')}</th><th>{t('Approved classes','অনুমোদিত ক্লাস')}</th><th>{t('Actual hours','প্রকৃত সময় (ঘণ্টা)')}</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="py-3">{x.name}</td><td>{x.classes}</td><td>{x.approved_hours}</td></tr>)}</tbody></table>{!rows.length&&<p>{t('No approved teaching hours in this range.','এই তারিখসীমায় অনুমোদিত পাঠদানের সময় নেই।')}</p>}</section>;
}
