'use client';
import Link from 'next/link';
import {z} from 'zod';
import {useWords} from '@/modules/academy/components/common';
const item=z.object({id:z.string(),batch_name:z.string(),subject_name:z.string(),room_name:z.string(),starts_at:z.string(),ends_at:z.string(),status:z.string()});
const schema=z.object({today:z.array(item),returned:z.array(item),todayTotal:z.number(),returnedTotal:z.number()});
export function TeacherAgenda({initial}:{initial:unknown}){
 const t=useWords(),data=schema.parse(initial),rows=[...data.today,...data.returned.filter(x=>!data.today.some(y=>y.id===x.id))];
 return <section className="space-y-5"><h1 className="text-3xl font-semibold">{t('My teaching desk','আমার ক্লাসের কাজ')}</h1><p>{t('Open today’s class to take attendance and submit your report. Returned reports need your correction.','আজকের ক্লাস খুলে উপস্থিতি নিন ও প্রতিবেদন জমা দিন। ফেরত দেওয়া প্রতিবেদনে সংশোধন প্রয়োজন।')}</p><div className="flex flex-wrap gap-3">{[['/dashboard/academics/sessions',t('All assigned classes','সব দায়িত্বের ক্লাস')],['/dashboard/academics/calendar',t('My calendar','আমার ক্যালেন্ডার')],['/dashboard/academics/teaching-hours',t('My approved teaching hours','আমার অনুমোদিত পাঠদানের সময়')]].map(([href,label])=><Link prefetch={false} key={href} href={href} className="cursor-pointer rounded-lg border px-4 py-2 hover:bg-muted">{label}</Link>)}</div><p>{t('Classes today','আজকের ক্লাস')}: {data.todayTotal} · {t('Reports to correct','সংশোধনের প্রতিবেদন')}: {data.returnedTotal}</p><div className="space-y-3">{rows.map(x=><Link href={`/dashboard/academics/sessions/${x.id}`} prefetch={false} className="block cursor-pointer rounded-xl border p-4 hover:bg-muted" key={x.id}><h2 className="font-semibold">{x.batch_name} · {x.subject_name}</h2><p>{new Date(x.starts_at).toLocaleString(t('en-GB','bn-BD'),{timeZone:'Asia/Dhaka'})} — {x.room_name}</p><p className={x.status==='RETURNED'?'text-amber-600':'text-muted-foreground'}>{x.status==='RETURNED'?t('Correction requested — open report','সংশোধন প্রয়োজন — প্রতিবেদন খুলুন'):x.status}</p></Link>)}{!rows.length&&<p>{t('No class today or report needing correction. Open All assigned classes for other dates.','আজকের ক্লাস বা সংশোধনের প্রতিবেদন নেই। অন্য দিন দেখতে সব দায়িত্বের ক্লাস খুলুন।')}</p>}</div>{(data.todayTotal>25||data.returnedTotal>25)&&<p>{t('Showing up to 25 per queue. Open the calendar or assigned classes for more.','প্রতি তালিকায় সর্বোচ্চ ২৫টি। আরও দেখতে ক্যালেন্ডার বা দায়িত্বের ক্লাস খুলুন।')}</p>}</section>;
}
