"use client";
import Link from "next/link";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {useLanguage} from "@/components/providers/language-provider";
import {StatusBadge} from "@/components/erp/status-badge";
import {taskAction} from "./task-actions";
import type {TaskData} from "./tasks";
import type {WorkData} from "./queries";
const input="mt-1 w-full rounded-lg border bg-background p-3";
type Row=TaskData["tasks"][number];
export function TaskRegister({data,people,admin=false,history,page,month}:{data:TaskData;people:WorkData["people"];admin?:boolean;history:boolean;page:number;month:string}){
 const {locale}=useLanguage();const t=(en:string,bn:string)=>locale==="bn"?bn:en;const router=useRouter();const [action,setAction]=useState<string|null>(null),[row,setRow]=useState<Row|null>(null),[message,setMessage]=useState("");const [pending,start]=useTransition();const request=useRef({signature:"",id:""});
 const prefix=admin?"/dashboard/staff/operations":"/dashboard/my-work";
 const url=(h:boolean,p=1)=>`${prefix}?month=${month.slice(0,7)}${admin&&data.staffId?`&person=${data.staffId}`:""}&tasksView=${h?"history":"queue"}&tasksPage=${p}#assigned-work`;
 function open(a:string,r:Row|null){setAction(a);setRow(r);setMessage("");request.current={signature:"",id:""};}
 function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const values:Record<string,unknown>={...Object.fromEntries(new FormData(e.currentTarget)),action,...(row?{id:row.id}:{})};const signature=JSON.stringify(values);if(signature!==request.current.signature)request.current={signature,id:crypto.randomUUID()};values.request_id=request.current.id;
 start(async()=>{const result=await taskAction(values);setMessage(result.message);if(result.ok){setAction(null);setRow(null);request.current={signature:"",id:""};router.refresh();}});}
 const assignment=action==="CREATE"||action==="EDIT";const report=action==="REPORT"||action==="SUBMIT";
 return <section id="assigned-work" className="space-y-4 rounded-2xl border p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">{t("Assigned work","নির্ধারিত কাজ")}</h2>{admin&&<button disabled={pending} className="rounded-lg border p-3" onClick={()=>open("CREATE",null)}>{t("Assign task","কাজ দিন")}</button>}</div>
 <div className="grid gap-3 sm:grid-cols-5">{[[t("Open","বাকি"),data.stats.open],[t("Awaiting acceptance","গ্রহণের অপেক্ষায়"),data.stats.review],[t("Completed","সম্পন্ন"),data.stats.completed],[t("Blocked","বাধাগ্রস্ত"),data.stats.blocked],[t("Overdue","সময় পেরিয়েছে"),data.stats.overdue]].map(([label,n])=><div className="rounded-lg border p-3" key={String(label)}><p className="text-sm">{label}</p><p className="text-xl font-semibold">{n}</p></div>)}</div><p className="text-sm text-muted-foreground">{t("Progress is the assignee's report. 100% submission becomes completed after admin acceptance; percentages do not automatically alter pay.","অগ্রগতি দায়িত্বপ্রাপ্ত ব্যক্তির রিপোর্ট। ১০০% জমা প্রশাসক গ্রহণ করলে সম্পন্ন হয়; এই শতাংশ অনুযায়ী বেতন স্বয়ংক্রিয়ভাবে পরিবর্তন হয় না।")}</p>
 <nav className="flex gap-4"><Link aria-current={!history?"page":undefined} href={url(false)}>{t("Current tasks","চলমান কাজ")}</Link><Link aria-current={history?"page":undefined} href={url(true)}>{t("Completed / cancelled","সম্পন্ন / বাতিল")}</Link></nav>
 {message&&<p role="status" className="rounded-lg border p-3">{message}</p>}
 {action&&<form onSubmit={save} key={`${action}:${row?.id??"new"}`} className="grid gap-4 rounded-xl border p-5 sm:grid-cols-2"><h3 className="font-semibold sm:col-span-2">{action.replaceAll("_"," ")} {row?.title}</h3>{assignment&&<><label>{t("Responsible staff","দায়িত্বপ্রাপ্ত স্টাফ")}<select name="staff_id" className={input} defaultValue={row?.staff_id??data.staffId??""} required>{people.filter(p=>action!=="EDIT"||p.id===row?.staff_id).map(p=><option key={p.id} value={p.id}>{p.number} · {p.name}</option>)}</select></label><label>{t("Task title","কাজের নাম")}<input name="title" className={input} required minLength={3} maxLength={160} defaultValue={row?.title??""}/></label><label>{t("Due date","শেষ করার তারিখ")}<input name="due_on" type="date" className={input} required defaultValue={row?.due_on??""}/></label><label>{t("Instructions","নির্দেশনা")}<textarea name="instructions" className={input} maxLength={4000} defaultValue={row?.instructions??""}/></label></>}
 {report&&<>{action==="REPORT"&&<label>{t("Reported progress (0–99%)","রিপোর্ট করা অগ্রগতি (০–৯৯%)")}<input name="progress" type="number" min="0" max="99" className={input} defaultValue={Math.min(row?.progress??0,99)} required/></label>}<label>{t("What is blocking completion? (optional)","শেষ করতে কী বাধা আছে? (ঐচ্ছিক)")}<textarea name="blocker" className={input} maxLength={2000} defaultValue={row?.blocker??""}/></label>{action==="SUBMIT"&&<p className="sm:col-span-2">{t("Submit completed work (100%) for administrative acceptance.","সম্পন্ন কাজ (১০০%) প্রশাসকের গ্রহণের জন্য জমা দিন।")}</p>}</>}
 <label className="sm:col-span-2">{t("Work note / explanation","কাজের নোট / ব্যাখ্যা")}<textarea name="reason" className={input} required minLength={5} maxLength={1000}/></label><div className="flex gap-3 sm:col-span-2"><button disabled={pending} className="rounded-lg bg-primary p-3 text-primary-foreground">{pending?t("Saving…","সংরক্ষণ হচ্ছে…"):t("Confirm","নিশ্চিত করুন")}</button><button type="button" disabled={pending} onClick={()=>setAction(null)}>{t("Cancel","বাতিল")}</button></div></form>}
 <div className="overflow-x-auto"><table className="w-full min-w-[640px] text-sm"><thead><tr className="border-b text-left">{[t("Task / instructions","কাজ / নির্দেশনা"),t("Due","শেষ তারিখ"),t("Progress","অগ্রগতি"),t("Status","অবস্থা"),t("Actions","পদক্ষেপ")].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{data.tasks.map(r=><tr className="border-b align-top" key={r.id}><td className="p-3"><p className="font-semibold">{r.title}</p><details className="mt-2"><summary className="cursor-pointer">{t("Instructions and notes","নির্দেশনা ও নোট")}</summary><p className="whitespace-pre-wrap">{r.instructions||"—"}</p>{r.blocker&&<p>{t("Blocker","বাধা")}: {r.blocker}</p>}{r.review_note&&<p>{t("Admin response","প্রশাসকের মন্তব্য")}: {r.review_note}</p>}</details></td><td className="p-3">{r.due_on}</td><td className="p-3"><p>{r.progress}%</p><progress className="w-24" value={r.progress} max={100} aria-label={`${r.title}: ${r.progress}%`}/></td><td className="p-3"><StatusBadge value={r.status}/></td><td className="space-y-2 p-3">{r.staff_id===data.ownStaffId&&["OPEN","IN_PROGRESS"].includes(r.status)&&<><button disabled={pending} className="block underline" onClick={()=>open("REPORT",r)}>{t("Update progress","অগ্রগতি জানান")}</button><button disabled={pending} className="block underline" onClick={()=>open("SUBMIT",r)}>{t("Submit completion","সম্পন্ন কাজ জমা দিন")}</button></>}{admin&&["OPEN","IN_PROGRESS"].includes(r.status)&&<button disabled={pending} className="block underline" onClick={()=>open("EDIT",r)}>{t("Edit","সম্পাদনা")}</button>}{admin&&r.status==="SUBMITTED"&&<><button disabled={pending} className="block underline" onClick={()=>open("ACCEPT",r)}>{t("Accept completion","সম্পন্ন কাজ গ্রহণ")}</button><button disabled={pending} className="block underline" onClick={()=>open("RETURN",r)}>{t("Return with reason","কারণসহ ফেরত")}</button></>}{admin&&!["COMPLETED","CANCELLED"].includes(r.status)&&<button disabled={pending} className="block underline" onClick={()=>open("CANCEL",r)}>{t("Cancel assignment","দায়িত্ব বাতিল")}</button>}</td></tr>)}</tbody></table>{!data.tasks.length&&<p className="p-4">{t("No tasks in this view.","এই তালিকায় কাজ নেই।")}</p>}</div><nav className="flex gap-4">{page>1&&<Link href={url(history,page-1)}>{t("Previous","পেছনে")}</Link>}{page*25<data.total&&<Link href={url(history,page+1)}>{t("Next","পরবর্তী")}</Link>}<span>{data.total} {t("tasks","কাজ")}</span></nav></section>;
}
