"use client";
import Link from "next/link";
import {useRef,useState,useTransition} from "react";
import {useRouter} from "next/navigation";
import {useLanguage} from "@/components/providers/language-provider";
import {StatusBadge} from "@/components/erp/status-badge";
import {workforceAction} from "./actions";
import type {WorkData} from "./queries";
const cls="mt-1 w-full rounded-lg border bg-background p-3";
export function WorkWorkspace({data,page,admin=false}:{data:WorkData;page:number;admin?:boolean}){
 const {locale}=useLanguage();const t=(en:string,bn:string)=>locale==="bn"?bn:en;const router=useRouter();const [form,setForm]=useState<"attendance"|"terms"|null>(null);const [editing,setEditing]=useState<WorkData["records"][number]|null>(null);const [status,setStatus]=useState("PRESENT");const [message,setMessage]=useState("");const [pending,start]=useTransition();const request=useRef({signature:"",id:""});
 const prefix=admin?"/dashboard/staff/operations":"/dashboard/my-work";
 const url=(p:number)=>`${prefix}?month=${data.month.slice(0,7)}&page=${p}${admin&&data.staffId?`&person=${data.staffId}`:""}`;
 function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const values:Record<string,unknown>=Object.fromEntries(new FormData(e.currentTarget));values.action=form==="attendance"?"RECORD_ATTENDANCE":"SAVE_TERMS";values.staff_id=data.staffId;
 if(form==="attendance"&&status==="PRESENT"){for(const key of ["started_at","ended_at"])values[key]=`${values[key]}:00+06:00`;}
 const signature=JSON.stringify(values);if(request.current.signature!==signature)request.current={signature,id:crypto.randomUUID()};values.request_id=request.current.id;
 start(async()=>{const r=await workforceAction(values);setMessage(r.message);if(r.ok){setForm(null);setEditing(null);request.current={signature:"",id:""};router.refresh();}});}
 function localTime(value:string|null){return value?new Date(new Date(value).getTime()+6*3600000).toISOString().slice(0,16):"";}
 return <div className="space-y-5"><form className="flex flex-wrap items-end gap-3" action={prefix}>{admin&&<label>{t("Staff member","স্টাফ")}<select name="person" className={cls} defaultValue={data.staffId??""} required><option value="">{t("Choose staff…","স্টাফ নির্বাচন করুন…")}</option>{data.people.map(p=><option value={p.id} key={p.id}>{p.number} · {p.name}</option>)}</select></label>}<label>{t("Month","মাস")}<input type="month" name="month" required defaultValue={data.month.slice(0,7)} className={cls}/></label><button className="rounded-lg border p-3">{t("View records","রেকর্ড দেখুন")}</button></form>
 {message&&<p role="status" className="rounded-xl border p-4">{message}</p>}
 {!data.staffId?<p>{t("No active staff identity linked. Ask the administrator to verify your identity.","সক্রিয় স্টাফ পরিচয় যুক্ত নেই। প্রশাসককে পরিচয় যাচাই করতে বলুন।")}</p>:<><h2 className="text-xl font-semibold">{data.name}</h2><div className="grid gap-3 sm:grid-cols-4">{[[t("Recorded present days","রেকর্ড করা উপস্থিত দিন"),data.presentDays],[t("Recorded hours after breaks","বিরতি বাদে রেকর্ড করা ঘণ্টা"),data.hours],[t("Recorded pay / referral cash last month","গত মাসের রেকর্ডকৃত পারিশ্রমিক / রেফারাল পরিশোধ"),`BDT ${data.previousMonthPaid.toLocaleString()}`],[t("Scheduled next pay date","পরবর্তী নির্ধারিত বেতন তারিখ"),data.scheduledPayDate??t("Not configured","নির্ধারণ করা হয়নি")]].map(([label,value])=><div key={String(label)} className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="text-xl font-semibold">{value}</p></div>)}</div>
 <section className="space-y-2 rounded-xl border p-5"><h3 className="font-semibold">{t("Current compensation agreement","বর্তমান পারিশ্রমিকের শর্ত")}</h3>{data.terms?<><p>{data.terms.model.replaceAll("_"," ")} · {t("Effective","কার্যকর")} {data.terms.effective_from}</p><p>{t("Monthly base","মাসিক মূল বেতন")}: BDT {data.terms.monthly_base.toLocaleString()} · {t("Hourly rate","প্রতি ঘণ্টার হার")}: BDT {data.terms.hourly_rate.toLocaleString()}</p><p>{t("Recorded hourly estimate for this month","এই মাসের রেকর্ড অনুযায়ী ঘণ্টাভিত্তিক আনুমানিক আয়")}: BDT {data.hourlyEstimate.toLocaleString()}</p></>:<p>{t("Terms have not been configured; no salary amount is assumed.","শর্ত নির্ধারণ করা হয়নি; কোনো বেতনের পরিমাণ অনুমান করা হচ্ছে না।")}</p>}<p className="text-sm text-muted-foreground">{t("Estimates and scheduled dates are not approved salary or payment confirmations. Post agreed fixed/hourly payroll in Payroll & payslips. Revenue-share earnings use approved teaching workload, not these daily hours.","আনুমানিক আয় ও নির্ধারিত তারিখ অনুমোদিত বেতন বা পরিশোধের প্রমাণ নয়। সম্মত fixed/hourly বেতন Payroll & payslips থেকে পোস্ট করা যায়। Revenue-share আয় অনুমোদিত পাঠদানের কাজ অনুযায়ী, এই দৈনিক ঘণ্টা অনুযায়ী নয়।")}</p>{!admin&&<Link href="/dashboard/referrals" className="inline-block underline">{t("Referral and approved teaching financial statement →","রেফারাল ও অনুমোদিত পাঠদানের আর্থিক হিসাব →")}</Link>}<Link href="/dashboard/finance/payroll" className="ml-4 inline-block underline">{t("Payroll & payslips →","বেতন ও স্লিপ →")}</Link></section>
 {admin&&<div className="flex gap-3"><button disabled={pending} className="rounded-lg border p-3" onClick={()=>{setForm(form==="attendance"?null:"attendance");setEditing(null);setStatus("PRESENT");}}>{t("Record staff attendance","স্টাফ উপস্থিতি রেকর্ড করুন")}</button><button disabled={pending} className="rounded-lg border p-3" onClick={()=>{setForm(form==="terms"?null:"terms");setEditing(null);}}>{t("Edit compensation terms","পারিশ্রমিকের শর্ত সম্পাদনা")}</button></div>}
 {form&&<form key={`${form}:${editing?.id??"new"}`} onSubmit={submit} className="grid gap-4 rounded-xl border p-5 sm:grid-cols-2"><h3 className="font-semibold sm:col-span-2">{form==="attendance"?t("Actual attendance evidence","প্রকৃত উপস্থিতির রেকর্ড"):t("Agreed terms","সম্মত পারিশ্রমিকের শর্ত")}</h3>{form==="attendance"?<><label>{t("Work date","কাজের তারিখ")}<input type="date" name="work_date" required defaultValue={editing?.work_date??data.month} className={cls}/></label><label>{t("Status","অবস্থা")}<select name="status" value={status} onChange={e=>setStatus(e.target.value)} className={cls}>{["PRESENT","ABSENT","LEAVE","HOLIDAY"].map(v=><option key={v}>{v}</option>)}</select></label>{status==="PRESENT"&&<><label>{t("Started (Bangladesh time)","শুরু (বাংলাদেশ সময়)")}<input className={cls} type="datetime-local" name="started_at" required defaultValue={localTime(editing?.started_at??null)}/></label><label>{t("Ended (Bangladesh time)","শেষ (বাংলাদেশ সময়)")}<input className={cls} type="datetime-local" name="ended_at" required defaultValue={localTime(editing?.ended_at??null)}/></label><label>{t("Break minutes","বিরতি মিনিট")}<input className={cls} name="break_minutes" type="number" min="0" max="1440" defaultValue={editing?.break_minutes??0} required/></label></>}{status!=="PRESENT"&&<input type="hidden" name="break_minutes" value="0"/>}</>:<><label>{t("Model","ধরন")}<select name="model" className={cls} defaultValue={data.terms?.model??"REVENUE_SHARE"}>{["FIXED","HOURLY","REVENUE_SHARE","HYBRID"].map(v=><option key={v}>{v}</option>)}</select></label>{[["monthly_base",t("Monthly base (BDT)","মাসিক মূল বেতন (টাকা)"),data.terms?.monthly_base??0],["hourly_rate",t("Hourly rate (BDT)","প্রতি ঘণ্টা (টাকা)"),data.terms?.hourly_rate??0],["pay_day",t("Pay day (1–28)","বেতন দিন (১–২৮)"),data.terms?.pay_day??10]].map(([name,label,value])=><label key={String(name)}>{label}<input name={String(name)} className={cls} type="number" min={name==="pay_day"?1:0} max={name==="pay_day"?28:undefined} step={name==="pay_day"?1:"0.01"} defaultValue={value} required/></label>)}<label>{t("Effective from","কার্যকর তারিখ")}<input className={cls} type="date" name="effective_from" defaultValue={data.terms?.effective_from??data.month} required/></label></>}
 <label className="sm:col-span-2">{t("Reason / correction explanation","কারণ / সংশোধনের ব্যাখ্যা")}<input name="reason" className={cls} minLength={5} maxLength={1000} required/></label><div className="flex gap-3 sm:col-span-2"><button disabled={pending} className="rounded-lg bg-primary p-3 text-primary-foreground">{pending?t("Saving…","সংরক্ষণ হচ্ছে…"):t("Save","সংরক্ষণ করুন")}</button><button type="button" disabled={pending} onClick={()=>setForm(null)}>{t("Cancel","বাতিল")}</button></div></form>}
 <div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left">{[t("Date","তারিখ"),t("Status","অবস্থা"),t("Start / end","শুরু / শেষ"),t("Hours","ঘণ্টা"),t("Reason","কারণ"),""].map((h,i)=><th key={i} className="p-3">{h}</th>)}</tr></thead><tbody>{data.records.map(r=><tr key={r.id} className="border-b"><td className="p-3">{r.work_date}</td><td><StatusBadge value={r.status}/></td><td>{r.started_at?new Date(r.started_at).toLocaleTimeString(locale==="bn"?"bn-BD":"en-GB",{timeZone:"Asia/Dhaka",hour:"2-digit",minute:"2-digit"}):"—"} / {r.ended_at?new Date(r.ended_at).toLocaleTimeString("en-GB",{timeZone:"Asia/Dhaka",hour:"2-digit",minute:"2-digit"}):"—"}</td><td>{r.hours}</td><td>{r.reason}</td><td>{admin&&<button disabled={pending} onClick={()=>{setEditing(r);setForm("attendance");setStatus(r.status);}}>{t("Correct","সংশোধন")}</button>}</td></tr>)}</tbody></table>{!data.records.length&&<p className="p-4">{t("No attendance recorded for this month. Missing records do not mean absent.","এই মাসের উপস্থিতি রেকর্ড হয়নি। রেকর্ড না থাকা মানে অনুপস্থিত নয়।")}</p>}</div><nav className="flex gap-4">{page>1&&<Link href={url(page-1)}>{t("Previous","পেছনে")}</Link>}{page*25<data.total&&<Link href={url(page+1)}>{t("Next","পরবর্তী")}</Link>}<span>{data.total} {t("records","রেকর্ড")}</span></nav></>}
 </div>;
}
