'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {OperationForm} from '@/modules/academics/operation-form';
import {inputClass,useWords} from '@/modules/academy/components/common';
import {studentBillingCommand} from './actions';
import type {AdmissionCase,StudentInvoice} from './contracts';
export function StudentBillingDesk({admission:a,invoices,manage}:{admission:AdmissionCase;invoices:StudentInvoice[];manage:boolean}){
 const t=useWords(),router=useRouter(),[editor,setEditor]=useState<{invoice?:StudentInvoice;action:string}|null>(null),today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Dhaka'}).format(new Date());
 const labels:Record<string,[string,string]>={PAYMENT:['Receive payment','টাকা গ্রহণ করুন'],DISCOUNT:['Give discount','ছাড় দিন'],SCHOLARSHIP:['Give scholarship','বৃত্তি দিন'],REFUND:['Refund collected money','গৃহীত টাকা ফেরত দিন'],NEXT_INVOICE:['Create next tuition bill','পরের টিউশন বিল তৈরি করুন']};
 return <section id="billing" className="space-y-4 rounded-xl border p-5"><h2 className="text-xl font-semibold">{t('Student billing & receipts','শিক্ষার্থীর বিল ও রসিদ')}</h2><p>{t('An invoice is an amount payable. Record a payment only when money is received. Discounts are shown separately.','বিল হলো পরিশোধযোগ্য টাকা। টাকা পাওয়ার পরই payment লিখুন। ছাড় আলাদা দেখানো হয়।')}</p><p className="text-lg font-semibold">{t('Total due','মোট বকেয়া')}: BDT {invoices.reduce((sum,i)=>sum+i.balance.due,0).toFixed(2)}</p>{manage&&a.fee_snapshot?.cycle!=='COURSE'&&<button className="cursor-pointer rounded-lg border px-3 py-2" onClick={()=>setEditor({action:'NEXT_INVOICE'})}>{t(...labels.NEXT_INVOICE)}</button>}<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{['Invoice / cycle','Net charges','Collected','Due','Actions'].map((h,n)=><th className="p-3 text-left" key={h}>{t(h,['বিল / চক্র','নিট ফি','গৃহীত','বকেয়া','কাজ'][n])}</th>)}</tr></thead><tbody>{invoices.map(i=><tr key={i.id} className="border-t"><td className="p-3">INV-{String(i.invoice_no).padStart(6,'0')}<br/>{i.period_start}</td><td className="p-3">{i.balance.net.toFixed(2)}<br/>{t('Discount','ছাড়')} {(i.discount+i.balance.reductions).toFixed(2)}</td><td className="p-3">{(i.balance.paid-i.balance.refunded).toFixed(2)}</td><td className="p-3"><span className={i.balance.due===0?'text-green-600':'text-amber-600'}>{i.balance.due.toFixed(2)}</span></td><td className="p-3"><div className="flex flex-wrap gap-2"><Link className="cursor-pointer rounded border px-3 py-2" href={`/dashboard/academics/admissions/${a.id}/print?invoice=${i.id}`}>{t('Print invoice','বিল প্রিন্ট')}</Link>{manage&&['PAYMENT','DISCOUNT','SCHOLARSHIP','REFUND'].map(action=><button key={action} className="cursor-pointer rounded border px-3 py-2 disabled:opacity-50" disabled={action==='REFUND'?i.balance.paid<=i.balance.refunded:i.balance.due<=0} onClick={()=>setEditor({invoice:i,action})}>{t(...labels[action])}</button>)}</div></td></tr>)}</tbody></table></div>
 {editor&&<OperationForm key={`${editor.action}-${editor.invoice?.id}`} title={t(...labels[editor.action])} reasonOptions={[t('Confirmed with the student or guardian','শিক্ষার্থী বা অভিভাবকের সঙ্গে নিশ্চিত করেছি')]} save={studentBillingCommand} onSaved={async()=>{setEditor(null);router.refresh();}} onCancel={()=>setEditor(null)} serialize={fd=>({action:editor.action,admissionId:a.id,invoiceId:editor.invoice?.id,amount:Number(fd.get('amount')),method:String(fd.get('method')??''),reference:String(fd.get('reference')??''),receivedOn:String(fd.get('receivedOn')??''),paymentId:String(fd.get('paymentId')??''),periodStart:String(fd.get('periodStart')??'')})}>
 {editor.action==='NEXT_INVOICE'?<p>{a.fee_snapshot?.cycle==='MONTHLY'?t('The next calendar month is selected automatically. One-time charges do not repeat.','পরের মাস স্বয়ংক্রিয়ভাবে নির্বাচিত হবে। এককালীন ফি পুনরায় আসে না।'):t('Choose the next term start.','পরের term-এর শুরু নির্বাচন করুন।')}</p>:<label>{t('Amount (BDT)','টাকা (BDT)')}<input required name="amount" type="number" min="0.01" step="0.01" className={inputClass}/></label>}
 {editor.action==='NEXT_INVOICE'&&a.fee_snapshot?.cycle==='TERM'&&<label>{t('Next term starts','পরের term শুরু')}<input name="periodStart" type="date" required className={inputClass}/></label>}
 {editor.action==='PAYMENT'&&<><label>{t('Money received on','টাকা গ্রহণের দিন')}<input required name="receivedOn" type="date" max={today} defaultValue={today} className={inputClass}/></label><label>{t('Payment method','পদ্ধতি')}<select name="method" className={inputClass}><option value="CASH">{t('Cash','নগদ')}</option><option value="BANK">{t('Bank','ব্যাংক')}</option><option value="MOBILE_BANKING">{t('Mobile banking','মোবাইল ব্যাংকিং')}</option></select></label><label>{t('Transaction / manual receipt reference','লেনদেন / হাতে লেখা রসিদের নম্বর')}<input name="reference" maxLength={160} className={inputClass}/></label></>}
 {editor.action==='REFUND'&&<label>{t('Original receipt','মূল রসিদ')}<select name="paymentId" required className={inputClass}><option value="">{t('Choose…','নির্বাচন করুন…')}</option>{editor.invoice?.payments.map(p=><option key={p.id} value={p.id}>RCPT-{p.receipt_no} · {p.amount.toFixed(2)} · {p.received_on}</option>)}</select></label>}
 </OperationForm>}
 {invoices.map(i=><details key={i.id} className="rounded-lg border p-3"><summary className="cursor-pointer">INV-{i.invoice_no} · {t('Charges, payment receipts & adjustments','ফি, টাকা গ্রহণের রসিদ ও পরিবর্তন')}</summary><ul className="space-y-2 py-3">{i.lines.map(l=><li key={l.code}>{l.name}: {l.amount.toFixed(2)} · {t('Discount','ছাড়')}: {l.discount.toFixed(2)}</li>)}{i.payments.map(p=><li key={p.id}>RCPT-{p.receipt_no} · {p.received_on} · BDT {p.amount.toFixed(2)} · {p.method} <Link className="cursor-pointer underline" href={`/dashboard/academics/admissions/${a.id}/print?receipt=${p.id}`}>{t('Print receipt','রসিদ প্রিন্ট')}</Link></li>)}{i.adjustments.map(x=><li key={x.id}>{x.kind} · BDT {x.amount.toFixed(2)} · {x.reason}</li>)}</ul></details>)}
 </section>;
}
