'use client';
import Link from 'next/link';
import {useState} from 'react';
import {useWords} from '@/modules/academy/components/common';
import {AdmissionDraftForm} from './draft-form';
import type {AdmissionCase,AdmissionOptions} from './contracts';
export function AdmissionCaseDesk({initial:a,options,permissions}:{initial:AdmissionCase;options?:AdmissionOptions;permissions:string[]}){
 const t=useWords(),[edit,setEdit]=useState(false);
 return <section className="space-y-5"><Link href="/dashboard/academics/admissions" className="cursor-pointer rounded-lg border px-3 py-2">{t('← Admissions','← ভর্তির তালিকা')}</Link><header><h1 className="text-2xl font-semibold">ADM-{String(a.admission_no).padStart(6,'0')} · {String(a.details.studentName??t('Draft','খসড়া'))}</h1><p>{a.runTitle??'—'} · {a.batchName??'—'} · {a.studentNumber??t('Student ID issued on confirmation','নিশ্চিত হলে Student ID')}</p></header>{a.enquiry&&<details className="rounded-xl border p-4"><summary className="cursor-pointer">{t('Original public preferences — unverified','ওয়েবসাইটের মূল পছন্দ — যাচাই হয়নি')}</summary><pre className="mt-3 whitespace-pre-wrap break-words text-sm">{JSON.stringify(a.enquiry,null,2)}</pre></details>}<div className="rounded-xl border p-5"><h2 className="font-semibold">{t('Next: verify details and placement','পরের কাজ: তথ্য ও ভর্তি নির্বাচন যাচাই')}</h2><p>{t('Save the verified student/guardian details, programme, batch, standard charges and source. No student, enrollment or invoice is created by a draft.','শিক্ষার্থী/অভিভাবক, প্রোগ্রাম, ব্যাচ, ফি ও উৎস যাচাই করে সংরক্ষণ করুন। খসড়া দিয়ে Student, enrollment বা বিল তৈরি হয় না।')}</p>{permissions.includes('admissions.manage')&&a.status==='DRAFT'&&<button className="mt-3 cursor-pointer rounded-lg bg-primary px-4 py-2 text-primary-foreground" onClick={()=>setEdit(!edit)}>{t(edit?'Close details':'Verify / edit application',edit?'তথ্য বন্ধ করুন':'আবেদন যাচাই / সংশোধন')}</button>}</div>{edit&&options&&<AdmissionDraftForm initial={a} options={options} canCreate={permissions.includes('directory.manage')} onCancel={()=>setEdit(false)}/>}<dl className="grid gap-3 rounded-xl border p-5 sm:grid-cols-2"><div><dt>{t('Guardian / contact','অভিভাবক / যোগাযোগ')}</dt><dd>{String(a.details.guardianName??'—')} · {String(a.details.guardianMobile??a.details.studentMobile??'—')}</dd></div><div><dt>{t('Status','অবস্থা')}</dt><dd>{a.status}</dd></div></dl><section className="rounded-xl border p-5"><h2 className="font-semibold">{t('Standard charges','নির্ধারিত ফি')}</h2><ul>{a.fee_snapshot?.components.map(c=><li key={c.code}>{c.name} · BDT {c.amount.toFixed(2)}</li>)}</ul><p>{t('Tuition discount','টিউশন ছাড়')}: {a.discount_percent}% · {a.discount_reason??'—'}</p></section></section>;
}
