import {z} from 'zod';
export const feeSchema=z.object({revision:z.number(),cycle:z.enum(['MONTHLY','TERM','COURSE']),dueDay:z.number(),allowedDiscounts:z.array(z.number()),components:z.array(z.object({code:z.string(),name:z.string(),amount:z.number(),type:z.string(),recurrence:z.string()}))});
export const optionsSchema=z.object({runs:z.array(z.object({id:z.string(),title:z.string(),code:z.string(),class_code:z.string().nullable(),guardian_rule:z.string(),starts_on:z.string(),ends_on:z.string(),fees:feeSchema.nullable()})),batches:z.array(z.object({id:z.string(),name:z.string(),capacity:z.number(),occupied:z.number(),slots:z.array(z.object({weekday:z.number(),start:z.string(),end:z.string()}))})),referrers:z.array(z.object({id:z.string(),name:z.string(),mobile:z.string().nullable()}))});
export const caseSchema=z.object({id:z.string(),admission_no:z.number(),run_id:z.string().nullable(),batch_id:z.string().nullable(),enquiry_id:z.string().nullable(),details:z.record(z.string(),z.unknown()),fee_snapshot:feeSchema.nullable(),discount_percent:z.number(),discount_reason:z.string().nullable(),status:z.enum(['DRAFT','ADMITTED','CANCELLED']),revision:z.number(),runTitle:z.string().nullable(),batchName:z.string().nullable(),studentNumber:z.string().nullable(),roll_no:z.number().nullable(),student_id:z.string().nullable(),enquiry:z.record(z.string(),z.unknown()).nullable()});
export type AdmissionCase=z.infer<typeof caseSchema>;
export type AdmissionOptions=z.infer<typeof optionsSchema>;
export const registerSchema=z.object({page:z.number(),total:z.number(),rows:z.array(z.object({id:z.string(),admission_no:z.number(),name:z.string().nullable(),programme:z.string().nullable(),batch:z.string().nullable(),student_number:z.string().nullable(),status:z.string(),created_at:z.string(),roll_no:z.number().nullable()}))});
export const personSchema=z.object({id:z.string(),full_name:z.string(),full_name_bn:z.string().nullable(),mobile:z.string().nullable(),email:z.string().nullable(),date_of_birth:z.string().nullable(),present_address:z.record(z.string(),z.unknown()),permanent_address:z.record(z.string(),z.unknown()),student_no:z.number().nullable()});
export type AdmissionPerson=z.infer<typeof personSchema>;
