'use client';
import {useRef,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {OperationForm} from '@/modules/academics/operation-form';
import {DirectoryPicker} from '@/modules/academy/components/directory-picker';
import {inputClass,useWords} from '@/modules/academy/components/common';
import {AdmissionPersonPicker} from './person-picker';
import {admissionOptions,saveAdmissionDraft} from './actions';
import type {AdmissionCase,AdmissionOptions,AdmissionPerson} from './contracts';
export function AdmissionDraftForm({initial,options,enquiryId,prefill={},canCreate,onCancel}:{initial?:AdmissionCase;options:AdmissionOptions;enquiryId?:string;prefill?:Record<string,unknown>;canCreate:boolean;onCancel:()=>void}){
 const t=useWords(),router=useRouter(),[data,setData]=useState(initial?.details??prefill),[choices,setChoices]=useState(options),[run,setRun]=useState(initial?.run_id??''),[batch,setBatch]=useState(initial?.batch_id??''),[query,setQuery]=useState(''),[queryPage,setQueryPage]=useState(1),[pending,start]=useTransition(),[message,setMessage]=useState(''),savedId=useRef('');
 const current=choices.runs.find(x=>x.id===run),value=(key:string)=>String(data[key]??''),set=(key:string,v:string|boolean)=>setData(previous=>({...previous,[key]:v}));
 function search(next=1,selected=run){start(async()=>{try{setChoices(await admissionOptions(query,next,selected||undefined));setQueryPage(next);setMessage('');}catch{setMessage(t('Could not load programme/batch choices. Retry before saving.','প্রোগ্রাম/ব্যাচ আসেনি। সংরক্ষণের আগে আবার চেষ্টা করুন।'));}});}
 function choosePerson(p:AdmissionPerson,kind:'student'|'guardian'){
  if(kind==='student')setData(previous=>({...previous,studentId:p.id,studentName:p.full_name,studentNameBn:p.full_name_bn??'',studentMobile:p.mobile??'',studentEmail:p.email??'',dateOfBirth:p.date_of_birth??'',presentAddress:String(p.present_address.line??''),landmark:String(p.present_address.locality??''),newStudentConfirmed:false}));
  else setData(previous=>({...previous,guardianId:p.id,guardianName:p.full_name,guardianMobile:p.mobile??'',newGuardianConfirmed:false}));
 }
 function textField(key:string,en:string,bn:string,type='text',max=160){return <label className="block text-sm">{t(en,bn)}<input name={key} type={type} value={value(key)} onChange={e=>set(key,e.target.value)} maxLength={max} className={inputClass}/></label>;}
 return <div className="space-y-3">{message&&<p role="alert">{message}</p>}<OperationForm title={t(initial?'Edit admission draft':'Student application',initial?'ভর্তির খসড়া সংশোধন':'শিক্ষার্থীর আবেদন')} reasonOptions={[t('Entered details with student/guardian present','শিক্ষার্থী/অভিভাবকের উপস্থিতিতে তথ্য নিয়েছি'),t('Entered the signed paper application','স্বাক্ষরিত কাগজের আবেদন থেকে তথ্য নিয়েছি'),t('Corrected and verified the application','আবেদনের তথ্য যাচাই ও সংশোধন করেছি')]} save={async input=>{if(pending)return{ok:false,message:t('Wait for the choices to finish loading.','তালিকা আসা পর্যন্ত অপেক্ষা করুন।')};const result=await saveAdmissionDraft(input);if(result.ok&&result.id)savedId.current=result.id;return result;}} onSaved={async()=>{if(initial){router.refresh();onCancel();}else router.push('/dashboard/academics/admissions/'+savedId.current);}} onCancel={onCancel} serialize={fd=>({id:initial?.id,revision:initial?.revision,runId:run,batchId:batch,enquiryId:initial?.enquiry_id??enquiryId,details:{...data,schoolId:String(fd.get('schoolId')??''),schoolName:String(fd.get('schoolId_label')??''),relationshipId:String(fd.get('relationshipId')??''),guardianRelationship:String(fd.get('relationshipId_label')??''),discountReasonId:String(fd.get('discountReasonId')??'')},discountPercent:Number(fd.get('discountPercent')??0),discountReason:String(fd.get('discountReasonId_label')??'')})}>
 <section className="space-y-3 md:col-span-2"><h4 className="font-semibold">{t('1. Verified programme & batch','১. সঠিক প্রোগ্রাম ও ব্যাচ')}</h4><p className="text-sm">{t('Drafts can be incomplete. Staff choose the correct placement independently of public preferences.','খসড়া অসম্পূর্ণ থাকতে পারে। ওয়েবসাইটের পছন্দ থেকে স্বাধীনভাবে সঠিক ভর্তি নির্বাচন করুন।')}</p><div className="flex gap-2"><input className={inputClass} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('Search offerings','Offering খুঁজুন')} maxLength={160}/><button type="button" disabled={pending} className="cursor-pointer rounded-lg border px-3" onClick={()=>search(1,'')}>{pending?t('Loading…','তথ্য আসছে…'):t('Search','খুঁজুন')}</button><button type="button" disabled={pending||queryPage===1} onClick={()=>search(queryPage-1,'')}>{t('Previous','আগের')}</button><button type="button" disabled={pending||choices.runs.length<25} onClick={()=>search(queryPage+1,'')}>{t('Next','পরের')}</button></div><div className="grid gap-3 md:grid-cols-2"><label>{t('Programme offering','Programme offering')}<select className={inputClass} value={run} disabled={pending} onChange={e=>{setRun(e.target.value);setBatch('');search(1,e.target.value);}}><option value="">{t('Choose…','নির্বাচন করুন…')}</option>{choices.runs.map(r=><option key={r.id} value={r.id}>{r.title} · {r.class_code??t('Training','প্রশিক্ষণ')} {!r.fees?' · '+t('Set fees first','আগে ফি দিন'):''}</option>)}</select></label><label>{t('Batch','ব্যাচ')}<select className={inputClass} value={batch} disabled={pending||!run} onChange={e=>setBatch(e.target.value)}><option value="">{t('Choose batch…','ব্যাচ নির্বাচন…')}</option>{choices.batches.map(b=><option key={b.id} value={b.id} disabled={b.occupied>=b.capacity&&b.id!==initial?.batch_id}>{b.name} · {b.capacity-b.occupied} {t('seats free','আসন খালি')} · {b.slots.map(s=>`${t(['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][s.weekday],['রবি','সোম','মঙ্গল','বুধ','বৃহস্পতি','শুক্র','শনি'][s.weekday])} ${s.start}–${s.end}`).join(', ')}</option>)}</select></label></div>{textField('enrollmentDate','Enrollment starts on','ভর্তি কার্যকর হবে','date')}</section>
 <section className="space-y-3 md:col-span-2"><h4 className="font-semibold">{t('2. Student identity','২. শিক্ষার্থীর পরিচয়')}</h4><AdmissionPersonPicker onSelect={p=>choosePerson(p,'student')}/>{value('studentId')&&<p>{t('Existing identity selected. Student ID will be reused.','আগের পরিচয় নির্বাচিত। একই Student ID থাকবে।')} <button type="button" onClick={()=>{set('studentId','');}} className="underline">{t('Use a different new person','আলাদা নতুন ব্যক্তি')}</button></p>}<div className="grid gap-3 md:grid-cols-2">{textField('studentName','Student full name','শিক্ষার্থীর পূর্ণ নাম')}{textField('studentNameBn','Bangla name (optional)','বাংলা নাম (ঐচ্ছিক)')}{textField('studentMobile','Student mobile (optional)','শিক্ষার্থীর মোবাইল (ঐচ্ছিক)','tel',11)}{textField('studentEmail','Student email (optional)','শিক্ষার্থীর ইমেইল (ঐচ্ছিক)','email',200)}{textField('dateOfBirth','Date of birth','জন্মতারিখ','date')}<label>{t('Gender','লিঙ্গ')}<select value={value('gender')} className={inputClass} onChange={e=>set('gender',e.target.value)}><option value="">{t('Not provided','উল্লেখ নেই')}</option>{['Female','Male','Other'].map(v=><option value={v} key={v}>{t(v,{Female:'নারী',Male:'পুরুষ',Other:'অন্যান্য'}[v]??v)}</option>)}</select></label><div><p>{t('School / college (optional)','স্কুল / কলেজ (ঐচ্ছিক)')}</p><DirectoryPicker name="schoolId" kind="INSTITUTION" canCreate={canCreate} initial={value('schoolId')?{id:value('schoolId'),name:value('schoolName')}:null}/></div>{textField('schoolRoll','School roll (optional)','স্কুলের রোল (ঐচ্ছিক)', 'text',40)}</div>{!value('studentId')&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={!!data.newStudentConfirmed} onChange={e=>set('newStudentConfirmed',e.target.checked)}/>{t('I checked existing identities; this is a new/different person.','আগের পরিচয় যাচাই করেছি; এটি নতুন/আলাদা ব্যক্তি।')}</label>}</section>
 <section className="space-y-3 md:col-span-2"><h4 className="font-semibold">{t('3. Guardian & address','৩. অভিভাবক ও ঠিকানা')}</h4><p className="text-sm">{current?.guardian_rule==='OPTIONAL'?t('Adult course: guardian is optional; provide the student’s own contact.','প্রাপ্তবয়স্ক কোর্স: অভিভাবক ঐচ্ছিক; নিজের যোগাযোগ দিন।'):t('A guardian is required for school/minor students. Reuse the same guardian for siblings.','স্কুল/অপ্রাপ্তবয়স্ক শিক্ষার্থীর অভিভাবক প্রয়োজন। সহোদরের জন্য একই অভিভাবক ব্যবহার করুন।')}</p><AdmissionPersonPicker onSelect={p=>choosePerson(p,'guardian')}/><div className="grid gap-3 md:grid-cols-2">{textField('guardianName','Guardian full name','অভিভাবকের পূর্ণ নাম')}{textField('guardianMobile','Guardian mobile','অভিভাবকের মোবাইল','tel',11)}<div><p>{t('Relationship','সম্পর্ক')}</p><DirectoryPicker name="relationshipId" kind="RELATIONSHIP" canCreate={canCreate} initial={value('relationshipId')?{id:value('relationshipId'),name:value('guardianRelationship')}:null}/></div>{value('guardianId')&&<button type="button" className="underline" onClick={()=>set('guardianId','')}>{t('Use a different new guardian','আলাদা নতুন অভিভাবক')}</button>}</div>{!value('guardianId')&&value('guardianName')&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={!!data.newGuardianConfirmed} onChange={e=>set('newGuardianConfirmed',e.target.checked)}/>{t('I checked existing identities; this guardian is a new/different person.','আগের পরিচয় যাচাই করেছি; এই অভিভাবক নতুন/আলাদা ব্যক্তি।')}</label>}<label className="block">{t('Present address','বর্তমান ঠিকানা')}<textarea className={inputClass} rows={3} maxLength={500} value={value('presentAddress')} onChange={e=>set('presentAddress',e.target.value)}/></label>{textField('landmark','Nearby landmark / location','নিকটস্থ পরিচিত স্থান') }<label className="flex gap-2"><input type="checkbox" checked={!!data.sameAddress} onChange={e=>set('sameAddress',e.target.checked)}/>{t('Permanent address is the same','স্থায়ী ঠিকানা একই')}</label>{!data.sameAddress&&<label className="block">{t('Permanent address (if different)','স্থায়ী ঠিকানা (আলাদা হলে)')}<textarea className={inputClass} maxLength={500} value={value('permanentAddress')} onChange={e=>set('permanentAddress',e.target.value)}/></label>}<details><summary className="cursor-pointer">{t('Additional family / support details','পরিবার / সহায়তার অতিরিক্ত তথ্য')}</summary><div className="grid gap-3 md:grid-cols-2">{textField('fatherName','Father’s name (optional)','পিতার নাম (ঐচ্ছিক)')}{textField('motherName','Mother’s name (optional)','মাতার নাম (ঐচ্ছিক)')}{textField('emergencyMobile','Emergency mobile (optional)','জরুরি মোবাইল (ঐচ্ছিক)','tel',11)}{textField('learningNeeds','Learning / health support (optional)','শিক্ষা / স্বাস্থ্য সহায়তা (ঐচ্ছিক)','text',500)}</div></details></section>
 <section className="space-y-3 md:col-span-2"><h4 className="font-semibold">{t('4. Fees & source','৪. ফি ও উৎস')}</h4>{current?.fees&&<ul className="space-y-1 text-sm">{current.fees.components.map(c=><li key={c.code}>{c.name} · {c.recurrence==='PER_CYCLE'?t('Per cycle','প্রতি চক্র'):t('One time','এককালীন')} · BDT {c.amount.toFixed(2)}</li>)}</ul>}<div className="grid gap-3 md:grid-cols-2"><label>{t('Tuition discount','টিউশন ছাড়')}<select name="discountPercent" className={inputClass} defaultValue={initial?.discount_percent??0}><option value="0">{t('No discount','ছাড় নেই')}</option>{current?.fees?.allowedDiscounts.map(n=><option value={n} key={n}>{n}%</option>)}</select></label><div><p>{t('Discount reason (if discount given)','ছাড়ের কারণ (ছাড় দিলে)')}</p><DirectoryPicker name="discountReasonId" kind="DISCOUNT_REASON" canCreate={canCreate} initial={value('discountReasonId')?{id:value('discountReasonId'),name:initial?.discount_reason??''}:null}/></div><label>{t('Referral source','রেফারেল উৎস')}<select className={inputClass} value={value('referrerId')} onChange={e=>{set('referrerId',e.target.value);set('sourceVerified',true);}}><option value="">{t('Organic — no referrer','নিজ উদ্যোগে — রেফারার নেই')}</option>{choices.referrers.map(p=><option value={p.id} key={p.id}>{p.name} · {p.mobile??'—'}</option>)}</select></label><label className="flex items-center gap-2"><input type="checkbox" checked={!!data.sourceVerified} onChange={e=>set('sourceVerified',e.target.checked)}/>{t('I verified this source with the applicant','আবেদনকারীর সঙ্গে এই উৎস নিশ্চিত করেছি')}</label></div></section>
 </OperationForm></div>;
}
