'use client';
import Link from 'next/link';
import {useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {useWords,inputClass} from '@/modules/academy/components/common';
import {admissionOptions,admissionRegister} from './actions';
import {registerSchema,type AdmissionOptions} from './contracts';
import {AdmissionDraftForm} from './draft-form';
export function AdmissionRegister({initial,canManage,canCreate,prefill,enquiryId,initialOptions}:{initial:unknown;canManage:boolean;canCreate:boolean;prefill?:Record<string,unknown>;enquiryId?:string;initialOptions?:AdmissionOptions}){
 const t=useWords(),router=useRouter(),[data,setData]=useState(()=>registerSchema.parse(initial)),[query,setQuery]=useState(''),[status,setStatus]=useState('DRAFT'),[options,setOptions]=useState(initialOptions??null),[pending,start]=useTransition(),[message,setMessage]=useState('');
 function load(page=1,next=status){start(async()=>{try{setData(await admissionRegister(query,page,next));setMessage('');}catch{setMessage(t('Could not load admissions. Retry.','ভর্তির তালিকা আসেনি। আবার চেষ্টা করুন।'));}});}
 function begin(){start(async()=>{try{setOptions(await admissionOptions());setMessage('');}catch{setMessage(t('Could not prepare the application. Retry.','আবেদন প্রস্তুত হয়নি। আবার চেষ্টা করুন।'));}});}
 return <section className="space-y-5"><header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-semibold">{t('Admissions','ভর্তি')}</h1><p className="mt-2 text-sm">{t('Application → review → admission & invoice → payment/receipt. Complete a case on one page.','আবেদন → যাচাই → ভর্তি ও বিল → payment/রসিদ। একই পাতায় একটি ভর্তি শেষ করুন।')}</p></div>{canManage&&<button disabled={pending||!!options} className="cursor-pointer rounded-lg bg-primary px-4 py-3 text-primary-foreground" onClick={begin}>{pending?t('Preparing…','প্রস্তুত হচ্ছে…'):t('New / existing student admission','নতুন / পুরোনো শিক্ষার্থীর ভর্তি')}</button>}</header><div className="flex flex-wrap gap-3"><Link className="cursor-pointer rounded-lg border px-4 py-2" href="/dashboard/enquiries">{t('Start from public application','ওয়েবসাইটের আবেদন থেকে শুরু')}</Link><Link className="cursor-pointer rounded-lg border px-4 py-2" href="/dashboard/academics/admissions/blank">{t('Print blank application','ফাঁকা ভর্তি ফরম ছাপান')}</Link></div>{message&&<p role="alert">{message}</p>}{options&&<AdmissionDraftForm options={options} prefill={prefill} enquiryId={enquiryId} canCreate={canCreate} onCancel={()=>{setOptions(null);if(enquiryId)router.replace('/dashboard/academics/admissions');}}/>}
 {!options&&<><div className="flex flex-wrap gap-3">{[['DRAFT','In progress','চলমান'],['ADMITTED','Completed','সম্পন্ন'],['CANCELLED','Cancelled','বাতিল']].map(([code,en,bn])=><button type="button" disabled={pending} key={code} onClick={()=>{setStatus(code);load(1,code);}} className={`cursor-pointer rounded-lg border px-4 py-2 ${status===code?'bg-primary text-primary-foreground':''}`}>{t(en,bn)}</button>)}</div><form className="flex gap-3" onSubmit={e=>{e.preventDefault();load();}}><input className={inputClass} maxLength={160} aria-label={t('Find student or guardian mobile','শিক্ষার্থীর নাম বা অভিভাবকের মোবাইল')} value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={pending} className="cursor-pointer rounded-lg border px-4">{pending?t('Loading…','তথ্য আসছে…'):t('Search','খুঁজুন')}</button></form><div className="overflow-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr>{[t('Application / student','আবেদন / শিক্ষার্থী'),t('Programme / batch','প্রোগ্রাম / ব্যাচ'),t('Status','অবস্থা'),t('Action','পদক্ষেপ')].map(x=><th className="p-3" key={x}>{x}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id} className="border-t"><td className="p-3">ADM-{String(r.admission_no).padStart(6,'0')} · {r.name??t('Unnamed draft','নামহীন খসড়া')}<p>{r.student_number}{r.roll_no?' · '+t('Roll','রোল')+' '+r.roll_no:''}</p></td><td>{r.programme??'—'}<p>{r.batch}</p></td><td><span className={`rounded-full border px-2 py-1 ${r.status==='ADMITTED'?'border-green-500/50 text-green-600':r.status==='CANCELLED'?'text-red-600':'text-amber-600'}`}>{r.status==='ADMITTED'?t('Admitted','ভর্তি সম্পন্ন'):r.status==='DRAFT'?t('Draft','খসড়া'):t('Cancelled','বাতিল')}</span></td><td><Link prefetch={false} className="inline-block cursor-pointer rounded-lg border px-3 py-2" href={'/dashboard/academics/admissions/'+r.id}>{t('Open case','ভর্তি খুলুন')}</Link></td></tr>)}</tbody></table>{!data.rows.length&&<p className="p-4">{t('No matching cases. Start an admission above.','এই তালিকায় ভর্তি নেই। উপরে নতুন ভর্তি শুরু করুন।')}</p>}</div><nav className="flex items-center gap-4"><button className="cursor-pointer rounded-lg border px-3 py-2" disabled={pending||data.page===1} onClick={()=>load(data.page-1)}>{t('Previous','আগের')}</button><span>{data.page} · {data.total}</span><button className="cursor-pointer rounded-lg border px-3 py-2" disabled={pending||data.page*25>=data.total} onClick={()=>load(data.page+1)}>{t('Next','পরের')}</button></nav></>}
 </section>;
}
