alter table public.finance_cost_centres add column offering_id uuid references public.programme_offerings(id), add column revision integer not null default 1;
create unique index cost_centre_name on public.finance_cost_centres(organization_id,lower(btrim(name))) where is_active;
create table public.finance_budgets(id uuid primary key default gen_random_uuid(),centre_id uuid not null references public.finance_cost_centres(id),month date not null check(extract(day from month)=1),revenue_target numeric(14,2) not null check(revenue_target>=0 and revenue_target<>'NaN'::numeric),expense_limit numeric(14,2) not null check(expense_limit>=0 and expense_limit<>'NaN'::numeric),cash_in numeric(14,2) not null check(cash_in>=0 and cash_in<>'NaN'::numeric),cash_out numeric(14,2) not null check(cash_out>=0 and cash_out<>'NaN'::numeric),revision integer not null default 1,actor_id uuid not null references public.profiles(id),reason text not null,unique(centre_id,month));
create table public.finance_line_allocations(id uuid primary key default gen_random_uuid(),line_id uuid not null references public.general_ledger_lines(id),allocation jsonb not null,event_order bigint generated always as identity unique,actor_id uuid not null references public.profiles(id),reason text not null,created_at timestamptz not null default now());
create index latest_line_allocation on public.finance_line_allocations(line_id,event_order desc);
alter table public.finance_cost_centres enable row level security;alter table public.finance_budgets enable row level security;alter table public.finance_line_allocations enable row level security;
revoke all on public.finance_cost_centres,public.finance_budgets,public.finance_line_allocations from public,anon,authenticated;
create trigger centre_no_delete before delete on public.finance_cost_centres for each row execute function public.prevent_permanent_record_delete();
create trigger budget_no_delete before delete on public.finance_budgets for each row execute function public.prevent_permanent_record_delete();
create trigger allocation_immutable before update or delete on public.finance_line_allocations for each row execute function public.prevent_permanent_record_delete();
create function public.finance_planning_command(p_input jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
declare actor uuid:=auth.uid();req uuid:=(p_input->>'request_id')::uuid;why text:=btrim(p_input->>'reason');key public.admission_command_keys;org uuid;c public.finance_cost_centres;b public.finance_budgets;l public.general_ledger_lines;j public.general_ledger_journals;mon date;oldval jsonb;rid uuid;res jsonb;a jsonb;part_amount numeric;total_value numeric:=0;alloc jsonb:=coalesce(p_input->'allocations','[]'::jsonb);existing bigint;kind text;
begin
 if actor is null or not public.has_permission('accounting.period.manage') or not exists(select 1 from public.profiles where id=actor and status='ACTIVE') then raise exception 'Financial planning management permission required.';end if;
 if req is null or coalesce(length(why),0) not between 5 and 1000 then raise exception 'Request identity and explanation required.';end if;
 perform pg_advisory_xact_lock(hashtextextended(req::text,0));select * into key from public.admission_command_keys where request_id=req;if found then if key.actor_id<>actor or key.payload<>p_input then raise exception 'Request identity conflict.';end if;return key.result;end if;
 select id into org from public.organizations where code='SOHOJ' and is_active;
 if p_input->>'action' in('SAVE_CENTRE','SET_ACTIVE') then
  if nullif(p_input->>'id','') is not null then select * into c from public.finance_cost_centres where id=(p_input->>'id')::uuid and organization_id=org for update;if c.id is null or c.revision is distinct from (p_input->>'revision')::int then raise exception 'Centre changed. Refresh before editing.';end if;oldval:=to_jsonb(c);end if;
  if p_input->>'action'='SET_ACTIVE' then
   if c.id is null or p_input->>'is_active' is null then raise exception 'Select centre and active state.';end if;
   update public.finance_cost_centres set is_active=(p_input->>'is_active')::boolean,revision=revision+1 where id=c.id returning * into c;
  else
   if nullif(p_input->>'offering_id','') is not null and not exists(select 1 from public.programme_offerings where id=(p_input->>'offering_id')::uuid and organization_id=org) then raise exception 'Choose an academy offering.';end if;
   if c.id is null then insert into public.finance_cost_centres(organization_id,code,name,offering_id) values(org,'CC-'||substr(gen_random_uuid()::text,1,12),btrim(p_input->>'name'),nullif(p_input->>'offering_id','')::uuid) returning * into c;
   else update public.finance_cost_centres set name=btrim(p_input->>'name'),offering_id=nullif(p_input->>'offering_id','')::uuid,revision=revision+1 where id=c.id returning * into c;end if;
  end if;rid:=c.id;res:=to_jsonb(c);
 elsif p_input->>'action'='SAVE_BUDGET' then
  mon:=(p_input->>'month')::date;
  if mon is null or extract(day from mon)<>1 then raise exception 'Choose a budget month.';end if;
  perform pg_advisory_xact_lock_shared(hashtextextended('finance-period:'||mon::text,37));
  if (select action from public.finance_period_events where month=mon order by event_order desc limit 1)='CLOSE' then raise exception 'Budget month is closed.';end if;
  select * into c from public.finance_cost_centres where id=(p_input->>'centre_id')::uuid and organization_id=org and is_active for update;if not found then raise exception 'Select an active centre.';end if;
  select * into b from public.finance_budgets where centre_id=c.id and month=mon for update;oldval:=to_jsonb(b);
  if b.id is not null and b.revision is distinct from (p_input->>'revision')::int then raise exception 'A budget exists or changed. Open Edit budget.';end if;
  foreach kind in array array['revenue_target','expense_limit','cash_in','cash_out'] loop part_amount:=(p_input->>kind)::numeric;if part_amount is null or part_amount<0 or part_amount='NaN'::numeric or part_amount<>round(part_amount,2) then raise exception 'Budget values must be nonnegative finite two-decimal amounts.';end if;end loop;
  if b.id is null then insert into public.finance_budgets(centre_id,month,revenue_target,expense_limit,cash_in,cash_out,actor_id,reason) values(c.id,mon,(p_input->>'revenue_target')::numeric,(p_input->>'expense_limit')::numeric,(p_input->>'cash_in')::numeric,(p_input->>'cash_out')::numeric,actor,why) returning * into b;
  else update public.finance_budgets set revenue_target=(p_input->>'revenue_target')::numeric,expense_limit=(p_input->>'expense_limit')::numeric,cash_in=(p_input->>'cash_in')::numeric,cash_out=(p_input->>'cash_out')::numeric,actor_id=actor,reason=why,revision=revision+1 where id=b.id returning * into b;end if;rid:=b.id;res:=to_jsonb(b);
 elsif p_input->>'action'='ALLOCATE' then
  select ll.* into l from public.general_ledger_lines ll join public.general_ledger_journals jj on jj.id=ll.journal_id where ll.id=(p_input->>'line_id')::uuid and jj.organization_id=org and jj.status='POSTED';
  if l.id is null then raise exception 'Posted line unavailable.';end if;
  select * into j from public.general_ledger_journals where id=l.journal_id;mon:=date_trunc('month',j.journal_date)::date;
  perform pg_advisory_xact_lock_shared(hashtextextended('finance-period:'||mon::text,37));
  if (select action from public.finance_period_events where month=mon order by event_order desc limit 1)='CLOSE' then raise exception 'Allocation month is closed. Reopen with evidence before management-account changes.';end if;
  perform 1 from public.general_ledger_lines where id=l.id for update;
  if not exists(select 1 from public.finance_accounts where id=l.account_id and account_type in('REVENUE','CONTRA_REVENUE','EXPENSE')) then raise exception 'Allocate income/expense lines only.';end if;
  select event_order,allocation into existing,oldval from public.finance_line_allocations where line_id=l.id order by event_order desc limit 1;
  if coalesce(existing,0) is distinct from (p_input->>'expected_order')::bigint then raise exception 'Allocation changed. Review its latest distribution.';end if;
  if jsonb_typeof(alloc)<>'array' or jsonb_array_length(alloc)>10 then raise exception 'Choose up to ten split centres.';end if;
  for a in select value from jsonb_array_elements(alloc) loop
   part_amount:=(a->>'amount')::numeric;
   if part_amount is null or part_amount<=0 or part_amount='NaN'::numeric or part_amount<>round(part_amount,2) or not exists(select 1 from public.finance_cost_centres where id=(a->>'centre_id')::uuid and organization_id=org and is_active) then raise exception 'Each allocation requires an active centre and positive finite amount.';end if;total_value:=total_value+part_amount;
  end loop;
  if total_value>abs(l.debit-l.credit) or (select count(*) from jsonb_array_elements(alloc))<>(select count(distinct value->>'centre_id') from jsonb_array_elements(alloc)) then raise exception 'No duplicate centres; total must fit the posted line.';end if;
  insert into public.finance_line_allocations(line_id,allocation,actor_id,reason) values(l.id,alloc,actor,why) returning id into rid;res:=jsonb_build_object('id',rid,'line',l.id,'allocations',alloc);
 else raise exception 'Unknown planning action.';end if;
 insert into public.audit_events(actor_profile_id,entity_type,entity_id,action,reason,before_data,after_data,correlation_id) values(actor,'FINANCE_PLANNING',rid::text,p_input->>'action',why,oldval,res,req);
 res:=jsonb_build_object('id',rid,'message','Planning evidence saved. Posted ledger amounts remain unchanged.');insert into public.admission_command_keys(request_id,actor_id,payload,result) values(req,actor,p_input,res);return res;
end $$;
revoke all on function public.finance_planning_command(jsonb) from public,anon;
grant execute on function public.finance_planning_command(jsonb) to authenticated;
create function public.finance_planning_workspace(p_month date default null,p_page integer default 1) returns jsonb language plpgsql stable security definer set search_path='' as $$
declare mon date:=coalesce(p_month,date_trunc('month',now() at time zone 'Asia/Dhaka')::date);org uuid;centres jsonb;lines jsonb;unassigned numeric;cash numeric;burn numeric;planned_cash numeric;
begin
 if auth.uid() is null or not public.has_permission('accounting.view') or not exists(select 1 from public.profiles where id=auth.uid() and status='ACTIVE') then raise exception 'Accounting permission required.';end if;
 if mon is null or extract(day from mon)<>1 or p_page is null or p_page not between 1 and 10000 then raise exception 'Invalid month or page.';end if;select id into org from public.organizations where code='SOHOJ' and is_active;
 with posted as(select l.id,l.debit-l.credit signed,a.account_type,coalesce(al.allocation,case when l.cost_centre_id is not null then jsonb_build_array(jsonb_build_object('centre_id',l.cost_centre_id,'amount',abs(l.debit-l.credit))) else '[]'::jsonb end) allocation from public.general_ledger_lines l join public.general_ledger_journals j on j.id=l.journal_id join public.finance_accounts a on a.id=l.account_id left join lateral(select allocation from public.finance_line_allocations where line_id=l.id order by event_order desc limit 1)al on true where j.organization_id=org and j.status='POSTED' and j.journal_date>=mon and j.journal_date<mon+interval '1 month' and a.account_type in('REVENUE','CONTRA_REVENUE','EXPENSE')),
 allocated as(select (v->>'centre_id')::uuid centre_id,sum(case when p.account_type in('REVENUE','CONTRA_REVENUE') then -(v->>'amount')::numeric*sign(p.signed) else 0 end) revenue,sum(case when p.account_type='EXPENSE' then (v->>'amount')::numeric*sign(p.signed) else 0 end) expense from posted p cross join lateral jsonb_array_elements(coalesce(p.allocation,'[]'::jsonb))v group by v->>'centre_id')
 select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'name',c.name,'offering_id',c.offering_id,'revision',c.revision,'is_active',c.is_active,'revenue',coalesce(a.revenue,0),'expense',coalesce(a.expense,0),'profit',coalesce(a.revenue,0)-coalesce(a.expense,0),'budget',to_jsonb(b)) order by c.name),'[]'::jsonb) into centres from (select * from public.finance_cost_centres where organization_id=org order by name,id limit 25 offset (p_page-1)*25)c left join allocated a on a.centre_id=c.id left join public.finance_budgets b on b.centre_id=c.id and b.month=mon where c.organization_id=org;
 select coalesce(jsonb_agg(to_jsonb(x)),'[]'::jsonb) into lines from(select l.id,j.journal_date,j.description,j.source_type,a.name account,a.account_type,l.debit-l.credit signed,coalesce(al.event_order,0) expected_order,coalesce(al.allocation,case when l.cost_centre_id is not null then jsonb_build_array(jsonb_build_object('centre_id',l.cost_centre_id,'amount',abs(l.debit-l.credit))) else '[]'::jsonb end) allocations from public.general_ledger_lines l join public.general_ledger_journals j on j.id=l.journal_id join public.finance_accounts a on a.id=l.account_id left join lateral(select event_order,allocation from public.finance_line_allocations where line_id=l.id order by event_order desc limit 1)al on true where j.organization_id=org and j.status='POSTED' and j.journal_date>=mon and j.journal_date<mon+interval '1 month' and a.account_type in('REVENUE','CONTRA_REVENUE','EXPENSE') order by j.journal_date desc,l.id limit 25 offset (p_page-1)*25)x;
 select coalesce(sum(abs(l.debit-l.credit)-coalesce((select sum((v->>'amount')::numeric) from public.finance_line_allocations al cross join lateral jsonb_array_elements(al.allocation)v where al.id=(select id from public.finance_line_allocations where line_id=l.id order by event_order desc limit 1)),case when l.cost_centre_id is not null and not exists(select 1 from public.finance_line_allocations where line_id=l.id) then abs(l.debit-l.credit) else 0 end)),0) into unassigned from public.general_ledger_lines l join public.general_ledger_journals j on j.id=l.journal_id join public.finance_accounts a on a.id=l.account_id where j.organization_id=org and j.status='POSTED' and j.journal_date>=mon and j.journal_date<mon+interval '1 month' and a.account_type in('REVENUE','CONTRA_REVENUE','EXPENSE');
 select coalesce(sum(public.finance_account_balance(a.id,(now() at time zone 'Asia/Dhaka')::date)),0) into cash from public.finance_accounts a where a.organization_id=org and a.account_subtype in('CASH','BANK','MOBILE_BANK');
 select coalesce(sum(b.cash_out-b.cash_in),0),coalesce(sum(b.cash_in-b.cash_out),0) into burn,planned_cash from public.finance_budgets b join public.finance_cost_centres c on c.id=b.centre_id where c.organization_id=org and b.month=mon;
 return jsonb_build_object('month',mon,'canManage',public.has_permission('accounting.period.manage'),'centres',centres,'lines',lines,'unallocated',unassigned,'cashAvailableToday',cash,'plannedCashMovement',planned_cash,'runwayMonths',case when burn>0 then round(cash/burn,2) else null end,
 'centreChoices',(select coalesce(jsonb_agg(jsonb_build_object('id',x.id,'name',x.name,'is_active',x.is_active)),'[]'::jsonb) from(select id,name,is_active from public.finance_cost_centres where organization_id=org order by is_active desc,name,id limit 200)x),
 'total',greatest((select count(*) from public.finance_cost_centres where organization_id=org),(select count(*) from public.general_ledger_lines l join public.general_ledger_journals j on j.id=l.journal_id join public.finance_accounts a on a.id=l.account_id where j.organization_id=org and j.status='POSTED' and j.journal_date>=mon and j.journal_date<mon+interval '1 month' and a.account_type in('REVENUE','CONTRA_REVENUE','EXPENSE'))),
 'offerings',(select coalesce(jsonb_agg(jsonb_build_object('id',x.id,'name',x.name||' · '||x.code)),'[]'::jsonb) from(select id,name,code from public.programme_offerings where organization_id=org order by code limit 200)x));
end $$;
revoke all on function public.finance_planning_workspace(date,integer) from public,anon;
grant execute on function public.finance_planning_workspace(date,integer) to authenticated;
