"use client";
import { useLanguage } from "@/components/providers/language-provider";
import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { StatusBadge } from "@/components/erp/status-badge";
import { referrerAction } from "./actions";
import type { ReferrerWorkspace } from "./queries";
const input="mt-1 min-h-11 w-full rounded-lg border bg-background px-3";
const money=(n:number)=>`BDT ${n.toLocaleString("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function ReferrerRegister({data}:{data:ReferrerWorkspace}){
 const {locale}=useLanguage();const t=(en:string,bn:string)=>locale==="bn"?bn:en;
 const router=useRouter();const [editing,setEditing]=useState<string|null>(null),[pay,setPay]=useState(false),[message,setMessage]=useState("");const [pending,start]=useTransition();const request=useRef("");const signature=useRef("");
 const person=data.people.find(p=>p.id===editing);const outstanding=data.earned-data.settled;
 function run(values:Record<string,unknown>){const nextSignature=JSON.stringify(values);if(!request.current||signature.current!==nextSignature){request.current=crypto.randomUUID();signature.current=nextSignature;}start(async()=>{const result=await referrerAction({...values,request_id:request.current});setMessage(locale==="bn" && "messageBn" in result ? String(result.messageBn):result.message);if(result.ok){request.current="";setEditing(null);setPay(false);router.refresh();}});}
 function open(id:string){request.current="";setEditing(id);setMessage("");}
 return <div className="space-y-5">
 {message&&<p role="status" className="rounded-xl border p-4">{message}</p>}
 <section className="rounded-2xl border p-5 space-y-3"><h2 className="font-semibold">{t("Compensation terms","পারিশ্রমিকের নিয়ম")}</h2><p>{t("Acquisition reward","শিক্ষার্থী আনার বোনাস")}: <strong>{data.policy.acquisitionPercent??"—"}%</strong> {t("of actual net tuition collected for the first qualifying billing month, once per student.","প্রথম প্রযোজ্য বিলিং মাসের আদায়কৃত নিট টিউশনের, প্রতি শিক্ষার্থীর জন্য একবার।")}</p><p className="text-sm text-muted-foreground">{t("Discounts and scholarships reduce the basis. Admission, exam and material fees are excluded. Refunds adjust earned rewards. Each student's recorded rate remains attached to their reward contract.","ছাড় ও বৃত্তি বাদ দিয়ে হিসাব হয়। ভর্তি, পরীক্ষা ও উপকরণ ফি অন্তর্ভুক্ত নয়। ফেরতের কারণে বোনাস সমন্বয় হয়। শিক্ষার্থীর নির্ধারিত হার তার বোনাস রেকর্ডে থাকে।")}</p>{data.teacher&&<><p>{t("Teaching pool","পাঠদানের তহবিল")}: <strong>{data.policy.teachingPoolPercent??"—"}%</strong> · {t("review limit","পর্যালোচনার সীমা")} {data.policy.teachingReviewMaxPercent??"—"}%. {t("The pool is divided by approved teaching workload; it is not the percentage each teacher receives individually.","অনুমোদিত পাঠদানের কাজ অনুযায়ী এই তহবিল ভাগ হয়; এটি প্রত্যেক শিক্ষকের ব্যক্তিগত হার নয়।")}</p><p>{t("Teacher referral retention bonuses","শিক্ষকের রেফার করা শিক্ষার্থী ধরে রাখার বোনাস")}: 3 {t("months","মাস")} {data.policy.retention3Percent??"—"}% · 6 {t("months","মাস")} {data.policy.retention6Percent??"—"}%. {t("Based on the qualifying month's net collection after continuous active, paid enrollment. Growth adjustments require an academy decision; they are not automatic.","টানা সক্রিয় ও পরিশোধিত ভর্তি থাকলে সংশ্লিষ্ট মাসের নিট আদায়ের ওপর হিসাব হয়। প্রবৃদ্ধির সমন্বয় একাডেমির সিদ্ধান্ত অনুযায়ী, স্বয়ংক্রিয় নয়।")}</p></>}</section>
 {data.manager&&data.ownReferrerId&&<Link className="inline-block underline" href="/dashboard/referrals">{t("My referral statement","আমার রেফারাল হিসাব")}</Link>}
 {!data.selected&&<p className="rounded-xl border p-5">{t("No linked referral identity yet. Ask the administrator to verify your account link. No other person's referrals are shown.","এখনো রেফারাল পরিচয় যুক্ত হয়নি। প্রশাসককে অ্যাকাউন্টের সংযোগ যাচাই করতে বলুন। অন্য ব্যক্তির রেফারাল দেখানো হয় না।")}</p>}
 {data.manager&&<section className="rounded-2xl border p-5"><div className="flex justify-between"><h2 className="font-semibold">{t("Referrer directory","রেফারার তালিকা")}</h2><button className="rounded-lg border px-4 py-2" onClick={()=>open("new")}>{t("Create referrer","রেফারার তৈরি করুন")}</button></div>
 <div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Name / identity</th><th>Contact</th><th>Account</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.people.map(p=><tr className="border-b" key={p.id}><td className="py-3"><Link className="font-semibold underline" href={`/dashboard/referrals?person=${p.id}`}>{p.name}</Link><p className="text-xs text-muted-foreground">{p.staffId?t("Staff","স্টাফ"):t("External referrer","বাইরের রেফারার")}{p.relationship?` · ${p.relationship}`:""}</p></td><td>{p.mobile??"—"}<br/>{p.email??"—"}</td><td>{p.profileId?"Linked account":"Not linked"}</td><td><StatusBadge value={p.active?"ACTIVE":"INACTIVE"}/></td><td className="space-x-2"><button onClick={()=>open(p.id)}>Edit</button><button disabled={pending} onClick={()=>{request.current="";run({action:"SET_ACTIVE",id:p.id,active:!p.active,reason:p.active?"Marked referrer inactive for new use":"Reactivated verified referrer identity"});}}>{p.active?"Mark inactive":"Reactivate"}</button>{p.email&&p.active&&!p.profileId&&<button disabled={pending} onClick={()=>{request.current="";run({action:"INVITE",id:p.id,reason:"Verified referrer identity and account email"});}}>{pending?t("Sending…","পাঠানো হচ্ছে…"):t("Send account setup","অ্যাকাউন্ট চালুর নির্দেশনা পাঠান")}</button>}</td></tr>)}</tbody></table></div>
 {editing&&<form key={editing} className="mt-5 grid gap-4 rounded-xl border p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();run({action:"SAVE",...(person?{id:person.id}:{}),...Object.fromEntries(new FormData(e.currentTarget))});}}>
 <h3 className="font-semibold sm:col-span-2">{person?"Edit referrer":"New referrer"}</h3>
 {[['name','Full name',person?.name],['mobile','Mobile (optional)',person?.mobile],['email','Verified account email',person?.email],['relationship','Relationship / occupation',person?.relationship],['notes','Contact notes',person?.notes]].map(([name,label,value])=><label key={name} className="text-sm">{label}<input name={name!} defaultValue={value??""} required={name==="name"} type={name==="email"?"email":"text"} readOnly={name==="email"&&!!person?.profileId} className={input}/></label>)}
 <label className="text-sm">Correction reason<input name="reason" required minLength={5} defaultValue="Verified referral contact details" className={input}/></label>
 <div className="flex gap-3 sm:col-span-2"><button disabled={pending} className="rounded-lg bg-primary px-4 py-2 text-primary-foreground">{pending?"Saving…":"Save referrer"}</button><button type="button" disabled={pending} onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 </section>}
 {data.selected&&<><h2 className="text-xl font-semibold">{data.name}</h2><div className="grid gap-3 sm:grid-cols-3">{[["Earned after corrections",data.earned],["Actually settled",data.settled],[outstanding<0?"Recovery / future offset":"Outstanding reward",Math.abs(outstanding)]].map(([label,n])=><div key={String(label)} className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{money(Number(n))}</p></div>)}</div>
 {data.manager&&outstanding>0&&<button className="rounded-lg border px-4 py-2" onClick={()=>{request.current="";setPay(!pay);}}>Record referrer payment</button>}
 {pay&&<form className="grid gap-4 rounded-xl border p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run({action:"SETTLE",id:data.selected,amount:Number(f.get("amount")),account_id:String(f.get("account_id")),reference:String(f.get("reference")),reason:String(f.get("reason"))});}}><label>Actual amount paid<input className={input} name="amount" type="number" min="0.01" step="0.01" max={outstanding} required/></label><label>Cash / bank<select className={input} name="account_id" required><option value="">Choose…</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Payment reference<input name="reference" className={input}/></label><label>Reason<input name="reason" className={input} required minLength={5} defaultValue="Paid verified referral reward"/></label><button disabled={pending}>{pending?"Recording…":"Record actual payment"}</button><button type="button" disabled={pending} onClick={()=>setPay(false)}>Cancel</button></form>}
 <section className="overflow-x-auto rounded-2xl border p-4"><h3 className="mb-3 font-semibold">{t("Referred students","রেফার করা শিক্ষার্থী")}</h3>{!data.students.length&&<p className="mb-3 text-sm">{t("No referred admissions recorded yet.","এখনো রেফার করা ভর্তি রেকর্ড হয়নি।")}</p>}<table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b text-left"><th>Student / programme</th><th>Status</th><th>Discounts / scholarships</th><th>Net tuition collected</th><th>Acquisition reward</th></tr></thead><tbody>{data.students.map(s=><tr className="border-b align-top" key={s.id}><td className="py-4"><p className="font-semibold">{s.name} · {s.studentNo??s.number}</p><p className="text-xs">{s.programme}</p><details className="mt-2"><summary className="cursor-pointer">Collections ({s.collections.length})</summary><ul className="mt-2 space-y-2">{s.collections.map(c=><li key={c.receipt}>{new Date(c.receivedOn).toLocaleDateString("en-GB")} · {c.receipt} · {money(c.allocated)} · billing {c.billingPeriod}</li>)}</ul></details></td><td className="py-4"><StatusBadge value={s.status}/></td><td className="py-4">{s.discountPercent}% admission discount<br/>{money(s.discountAmount)} total reductions</td><td className="py-4">{money(s.netTuition)}</td><td className="py-4">{money(s.reward)}<br/><span className="text-xs">{s.rate??"—"}% · first qualifying billing month</span></td></tr>)}</tbody></table></section>
 {data.teacher&&<section className="space-y-4 rounded-2xl border p-5"><h3 className="font-semibold">{t("Teaching and retention account","পাঠদান ও রিটেনশনের হিসাব")}</h3><div className="grid gap-3 sm:grid-cols-4">{[[t("Approved earnings","অনুমোদিত আয়"),data.teachingEarned],[t("Settled including advance offsets","অগ্রিম সমন্বয়সহ পরিশোধ"),data.teachingSettled],[t("Outstanding compensation","বকেয়া পারিশ্রমিক"),data.teachingEarned-data.teachingSettled],[t("Unsettled advances","অসমন্বিত অগ্রিম"),data.advanceOutstanding]].map(([label,n])=><div key={String(label)} className="rounded-xl border p-3"><p className="text-sm">{label}</p><p className="font-semibold">{money(Number(n))}</p></div>)}</div><p className="text-sm text-muted-foreground">{t("Approved runs only. Acquisition rewards appear separately above and are not counted twice. Pending calculations do not constitute payable earnings.","শুধু অনুমোদিত হিসাব দেখানো হয়। শিক্ষার্থী আনার বোনাস উপরে আলাদা দেখানো হয়েছে, দুবার গণনা হয়নি। অপেক্ষমাণ হিসাব এখনো প্রাপ্য আয় নয়।")}</p><details><summary className="cursor-pointer">{t("Earnings details","আয়ের বিবরণ")} ({data.teachingLines.length})</summary>{data.teachingLines.map(l=><div key={l.id} className="border-b py-3 text-sm"><p>{l.run} · {l.from} — {l.to} · {l.type.replaceAll("_"," ")} · <strong>{money(l.amount)}</strong></p>{l.netTuition!==null&&<p>{t("Net tuition basis","নিট টিউশনের ভিত্তি")}: {money(l.netTuition)} · {t("Pool","তহবিল")}: {l.poolPercent}% · {t("Approved sessions","অনুমোদিত ক্লাস")}: {l.approvedSessions}/{l.batchApprovedSessions}</p>}</div>)}</details><details><summary className="cursor-pointer">{t("Payments and advance offsets","পরিশোধ ও অগ্রিম সমন্বয়")} ({data.teachingPayments.length})</summary>{data.teachingPayments.map((p,i)=><p className="py-3 text-sm" key={i}>{p.date.slice(0,10)} · {p.run} · {t("Cash / bank paid","নগদ / ব্যাংকে পরিশোধ")} {money(p.cash)} · {t("Advance offset","অগ্রিম সমন্বয়")} {money(p.advanceOffset)} · {p.reference??"—"}</p>)}</details></section>}
 <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Reward calculation history</summary>{data.entries.map(e=><p className="mt-3 text-sm" key={e.id}>{new Date(e.date).toLocaleString("en-GB")} · {money(e.amount)} {e.amount<0?"correction":"accrual"} · {e.rate}% of {money(e.collected)} net tuition</p>)}</details>
 <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Settlement history</summary>{data.settlements.map((s,i)=><p className="mt-3 text-sm" key={i}>{new Date(s.date).toLocaleString("en-GB")} · {money(s.amount)} · {s.reference??"Office cash record"}</p>)}</details>
 </>}
 </div>;
}
