"use client";
import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { StatusBadge } from "@/components/erp/status-badge";
import { referrerAction } from "./actions";
import type { ReferrerWorkspace } from "./queries";
const input="mt-1 min-h-11 w-full rounded-lg border bg-background px-3";
const money=(n:number)=>`BDT ${n.toLocaleString("en-BD",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function ReferrerRegister({data}:{data:ReferrerWorkspace}){
 const router=useRouter();const [editing,setEditing]=useState<string|null>(null),[pay,setPay]=useState(false),[message,setMessage]=useState("");const [pending,start]=useTransition();const request=useRef("");const signature=useRef("");
 const person=data.people.find(p=>p.id===editing);const outstanding=data.earned-data.settled;
 function run(values:Record<string,unknown>){const nextSignature=JSON.stringify(values);if(!request.current||signature.current!==nextSignature){request.current=crypto.randomUUID();signature.current=nextSignature;}start(async()=>{const result=await referrerAction({...values,request_id:request.current});setMessage(result.message);if(result.ok){request.current="";setEditing(null);setPay(false);router.refresh();}});}
 function open(id:string){request.current="";setEditing(id);setMessage("");}
 return <div className="space-y-5">
 {message&&<p role="status" className="rounded-xl border p-4">{message}</p>}
 {data.manager&&<section className="rounded-2xl border p-5"><div className="flex justify-between"><h2 className="font-semibold">Referrer directory</h2><button className="rounded-lg border px-4 py-2" onClick={()=>open("new")}>Create referrer</button></div>
 <div className="mt-4 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="py-3">Name / identity</th><th>Contact</th><th>Account</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.people.map(p=><tr className="border-b" key={p.id}><td className="py-3"><Link className="font-semibold underline" href={`/dashboard/referrals?person=${p.id}`}>{p.name}</Link><p className="text-xs text-muted-foreground">{p.staffId?"Staff":"External referrer"} · {p.relationship}</p></td><td>{p.mobile??"—"}<br/>{p.email??"—"}</td><td>{p.profileId?"Linked account":"Not linked"}</td><td><StatusBadge value={p.active?"ACTIVE":"INACTIVE"}/></td><td className="space-x-2"><button onClick={()=>open(p.id)}>Edit</button><button disabled={pending} onClick={()=>{request.current="";run({action:"SET_ACTIVE",id:p.id,active:!p.active,reason:p.active?"Marked referrer inactive for new use":"Reactivated verified referrer identity"});}}>{p.active?"Mark inactive":"Reactivate"}</button>{p.email&&p.active&&<button disabled={pending} onClick={()=>{request.current="";run({action:"INVITE",id:p.id,reason:"Verified referrer identity and account email"});}}>{pending?"Working…":"Send account setup"}</button>}</td></tr>)}</tbody></table></div>
 {editing&&<form key={editing} className="mt-5 grid gap-4 rounded-xl border p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();run({action:"SAVE",...(person?{id:person.id}:{}),...Object.fromEntries(new FormData(e.currentTarget))});}}>
 <h3 className="font-semibold sm:col-span-2">{person?"Edit referrer":"New referrer"}</h3>
 {[['name','Full name',person?.name],['mobile','Mobile (optional)',person?.mobile],['email','Verified account email',person?.email],['relationship','Relationship / occupation',person?.relationship],['notes','Contact notes',person?.notes]].map(([name,label,value])=><label key={name} className="text-sm">{label}<input name={name!} defaultValue={value??""} required={name==="name"} type={name==="email"?"email":"text"} readOnly={name==="email"&&!!person?.profileId} className={input}/></label>)}
 <label className="text-sm">Correction reason<input name="reason" required minLength={5} defaultValue="Verified referral contact details" className={input}/></label>
 <div className="flex gap-3 sm:col-span-2"><button disabled={pending} className="rounded-lg bg-primary px-4 py-2 text-primary-foreground">{pending?"Saving…":"Save referrer"}</button><button type="button" disabled={pending} onClick={()=>setEditing(null)}>Cancel</button></div></form>}
 </section>}
 {data.selected&&<><h2 className="text-xl font-semibold">{data.name}</h2><div className="grid gap-3 sm:grid-cols-3">{[["Earned after corrections",data.earned],["Actually settled",data.settled],[outstanding<0?"Recovery / future offset":"Outstanding reward",Math.abs(outstanding)]].map(([label,n])=><div key={String(label)} className="rounded-xl border p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-xl font-semibold">{money(Number(n))}</p></div>)}</div>
 {data.manager&&outstanding>0&&<button className="rounded-lg border px-4 py-2" onClick={()=>{request.current="";setPay(!pay);}}>Record referrer payment</button>}
 {pay&&<form className="grid gap-4 rounded-xl border p-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run({action:"SETTLE",id:data.selected,amount:Number(f.get("amount")),account_id:String(f.get("account_id")),reference:String(f.get("reference")),reason:String(f.get("reason"))});}}><label>Actual amount paid<input className={input} name="amount" type="number" min="0.01" step="0.01" max={outstanding} required/></label><label>Cash / bank<select className={input} name="account_id" required><option value="">Choose…</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Payment reference<input name="reference" className={input}/></label><label>Reason<input name="reason" className={input} required minLength={5} defaultValue="Paid verified referral reward"/></label><button disabled={pending}>{pending?"Recording…":"Record actual payment"}</button><button type="button" disabled={pending} onClick={()=>setPay(false)}>Cancel</button></form>}
 <section className="overflow-x-auto rounded-2xl border p-4"><h3 className="mb-3 font-semibold">Referred students</h3><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b text-left"><th>Student / programme</th><th>Status</th><th>Discounts / scholarships</th><th>Net tuition collected</th><th>Acquisition reward</th></tr></thead><tbody>{data.students.map(s=><tr className="border-b align-top" key={s.id}><td className="py-4"><p className="font-semibold">{s.name} · {s.studentNo??s.number}</p><p className="text-xs">{s.programme}</p><details className="mt-2"><summary className="cursor-pointer">Collections ({s.collections.length})</summary><ul className="mt-2 space-y-2">{s.collections.map(c=><li key={c.receipt}>{new Date(c.receivedOn).toLocaleDateString("en-GB")} · {c.receipt} · {money(c.allocated)} · billing {c.billingPeriod}</li>)}</ul></details></td><td className="py-4"><StatusBadge value={s.status}/></td><td className="py-4">{s.discountPercent}% admission discount<br/>{money(s.discountAmount)} total reductions</td><td className="py-4">{money(s.netTuition)}</td><td className="py-4">{money(s.reward)}<br/><span className="text-xs">{s.rate??"—"}% · first qualifying billing month</span></td></tr>)}</tbody></table></section>
 <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Reward calculation history</summary>{data.entries.map(e=><p className="mt-3 text-sm" key={e.id}>{new Date(e.date).toLocaleString("en-GB")} · {money(e.amount)} {e.amount<0?"correction":"accrual"} · {e.rate}% of {money(e.collected)} net tuition</p>)}</details>
 <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Settlement history</summary>{data.settlements.map((s,i)=><p className="mt-3 text-sm" key={i}>{new Date(s.date).toLocaleString("en-GB")} · {money(s.amount)} · {s.reference??"Office cash record"}</p>)}</details>
 </>}
 </div>;
}
