"use client";
import {CounterHistoryPanel} from "./history-panel";
import Link from "next/link";
import {useEffect,useRef,useState,useTransition} from "react";
import {useLanguage} from "@/components/providers/language-provider";
import {counterAction} from "./actions";
import type {CounterData} from "./queries";
const cls="mt-1 block w-full rounded-lg border bg-background p-2";
type Panel={action:"CREATE"|"EDIT"|"OPEN"|"CLOSE"|"RECEIVE";counter?:CounterData["records"][number];shift?:CounterData["records"][number]["shifts"][number]};
export function CounterRegister({data,page,resumeCloseId,onTransfer,pendingCounterIds=[],returnCounterIds,onAction,foreignPanelOpen=false}:{data:CounterData;page:number;resumeCloseId?:string;onTransfer?:(action:"TOPUP"|"RETURN",counter:CounterData["records"][number])=>void;pendingCounterIds?:string[];returnCounterIds?:string[];onAction?:()=>void;foreignPanelOpen?:boolean}){
 const {locale}=useLanguage(),t=(en:string,bn:string)=>locale==="bn"?bn:en;
 const [panel,setPanel]=useState<Panel|null>(()=>{const c=data.records.find(c=>c.id===resumeCloseId);return c&&data.manager?{action:"CLOSE",counter:c}:null;}),[message,setMessage]=useState(""),[pending,start]=useTransition();const retry=useRef({signature:"",id:""});const formRef=useRef<HTMLFormElement>(null);useEffect(()=>{if(panel)formRef.current?.scrollIntoView({behavior:"smooth",block:"start"});},[panel]);
 useEffect(()=>{if(foreignPanelOpen)setPanel(null);},[foreignPanelOpen]);
 const choose=(p:Panel)=>{onAction?.();setPanel(p);setMessage("");retry.current={signature:"",id:""};};
 const cash=data.accounts.filter(a=>a.kind==="CASH"&&!a.registered);
 return <div className="space-y-5"><p className="text-muted-foreground">{t("Each counter uses a separate cash ledger account. Opening float is a real transfer, not income. Assign a cashier, receive the opening count, then reconcile before closing. Closing keeps the remaining cash in this counter account.","প্রতিটি কাউন্টারের নগদ হিসাব আলাদা। প্রারম্ভিক টাকা প্রকৃত হিসাব-স্থানান্তর; আয় নয়। দায়িত্ব দিন, শুরুতে গ্রহণ নিশ্চিত করুন এবং বন্ধের আগে নগদ মিলান। বন্ধের পর অবশিষ্ট নগদ ওই কাউন্টার হিসাবেই থাকবে।")}</p><div className="flex flex-wrap gap-4"><Link className="underline" href="/dashboard/help/finance#counters">{t("Guided workflow","কাজের নির্দেশিকা")}</Link>{data.manager&&<><Link className="underline" href="/dashboard/finance/daily-close">{t("Count and reconcile cash","নগদ গণনা ও মিল")}</Link><Link className="underline" href="/dashboard/finance/accounting">{t("Create a cash ledger account","নগদ হিসাব তৈরি করুন")}</Link><button disabled={pending} className="rounded-lg border p-2" onClick={()=>choose({action:"CREATE"})}>{t("Register counter","কাউন্টার নিবন্ধন")}</button></>}</div>{message&&<p role="status" className="rounded border p-3">{message}</p>}
 {panel&&<form ref={formRef} key={`${panel.action}:${panel.counter?.id??panel.shift?.id??"new"}`} className="grid gap-4 rounded-xl border p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const values:Record<string,unknown>={action:panel.action,reason:String(f.get("reason"))};if(panel.counter)values.counter_id=panel.counter.id;if(panel.shift)values.shift_id=panel.shift.id;
 if(panel.action==="CREATE"){values.name=f.get("name");if(f.get("account_id"))values.account_id=f.get("account_id");}if(panel.action==="EDIT"){values.name=f.get("name");values.revision=panel.counter!.revision;values.is_active=f.get("active")==="on";}if(panel.action==="OPEN"){values.staff_id=f.get("staff_id");values.amount=Number(f.get("amount"));if(f.get("source_account_id"))values.source_account_id=f.get("source_account_id");}if(panel.action==="RECEIVE"){values.outcome=f.get("outcome");values.amount=Number(f.get("amount"));}if(panel.action==="CLOSE")values.close_id=f.get("close_id");const signature=JSON.stringify(values);if(retry.current.signature!==signature)retry.current={signature,id:crypto.randomUUID()};start(async()=>{const r=await counterAction({...values,request_id:retry.current.id});setMessage(r.ok?t("Saved successfully.","সফলভাবে সংরক্ষিত হয়েছে।"):r.message);if(r.ok){setPanel(null);retry.current={signature:"",id:""};}});
 }}><h2 className="font-semibold sm:col-span-2">{panel.counter?.name??panel.shift?.cashier??t("New cash counter","নতুন নগদ কাউন্টার")} · {panel.action}</h2>
 {["CREATE","EDIT"].includes(panel.action)&&<label>{t("Counter name","কাউন্টারের নাম")}<input disabled={pending} className={cls} name="name" required minLength={3} maxLength={120} defaultValue={panel.counter?.name}/></label>}
 {panel.action==="CREATE"&&<label>{t("Dedicated cash account","আলাদা নগদ হিসাব")}<select disabled={pending} className={cls} name="account_id"><option value="">{t("Create a new cash account automatically","নতুন নগদ হিসাব স্বয়ংক্রিয়ভাবে তৈরি করুন")}</option>{cash.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>}
 {panel.action==="EDIT"&&<label><input disabled={pending} type="checkbox" name="active" defaultChecked={panel.counter?.is_active}/> {t("Active for new shifts","নতুন দায়িত্বের জন্য সক্রিয়")}</label>}
 {panel.action==="OPEN"&&<><label>{t("Cashier","দায়িত্বপ্রাপ্ত কর্মী")}<select disabled={pending} className={cls} name="staff_id" required><option value="">{t("Choose…","নির্বাচন করুন…")}</option>{data.people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{t("Additional opening money (0 to reuse remaining cash)","অতিরিক্ত প্রারম্ভিক টাকা (আগের নগদ ব্যবহার করলে ০)")}<input disabled={pending} className={cls} type="number" step="0.01" min="0" name="amount" defaultValue="0" required/></label><label>{t("Source account when adding money","টাকা যোগ করলে উৎস হিসাব")}<select disabled={pending} className={cls} name="source_account_id"><option value="">{t("No transfer","স্থানান্তর নেই")}</option>{data.accounts.filter(a=>a.id!==panel.counter!.account_id).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></label><p className="text-sm sm:col-span-2">{t("Record only money physically delivered. Opening count includes cash already in this account plus this transfer. Use this counter's account/payment method for subsequent transactions.","শুধু প্রকৃত দেওয়া টাকা লিখুন। শুরুতে গ্রহণের অঙ্কে আগের নগদ ও নতুন স্থানান্তর যোগ হবে। পরের লেনদেনে এই কাউন্টারের হিসাব/অর্থ গ্রহণের মাধ্যম ব্যবহার করুন।")}</p></>}
 {panel.action==="RECEIVE"&&<><label>{t("Actual opening count","প্রকৃত প্রারম্ভিক গণনা")}<input disabled={pending} className={cls} type="number" min="0" step="0.01" name="amount" defaultValue={panel.shift?.opening_balance} required/></label><label>{t("Outcome","ফলাফল")}<select disabled={pending} className={cls} name="outcome"><option value="RECEIVED">{t("Count matches — received","গণনা মিলেছে — গ্রহণ করেছি")}</option><option value="DISPUTED">{t("Disputed","অমিল")}</option></select></label></>}
 {panel.action==="CLOSE"&&<><Link className="underline sm:col-span-2" href={`/dashboard/finance/daily-close?accountId=${panel.counter!.account_id}&returnTo=${encodeURIComponent("/dashboard/finance/counters?close="+panel.counter!.id+"&page="+page)}`}>{t("Record fresh cash count and return here","নতুন নগদ গণনা করে এখানে ফিরুন")}</Link><label>{t("Today's matching count evidence","আজকের মিলে যাওয়া গণনার প্রমাণ")}<select disabled={pending} className={cls} name="close_id" required><option value="">{t("Choose…","নির্বাচন করুন…")}</option>{panel.counter!.counts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>}
 <label className="sm:col-span-2">{t("Reason / verification note","কারণ / যাচাইয়ের নোট")}<input disabled={pending} className={cls} name="reason" required minLength={5} maxLength={1000} list="counter-reasons"/><datalist id="counter-reasons"><option value={t("Verified counter setup and cash account","কাউন্টার ও নগদ হিসাব যাচাই করেছি")}/><option value={t("Assigned responsibility and delivered opening funds","দায়িত্ব নির্ধারণ ও প্রারম্ভিক টাকা দিয়েছি")}/><option value={t("Counted and received the opening cash","গণনা করে প্রারম্ভিক নগদ গ্রহণ করেছি")}/><option value={t("Reviewed matching cash count and closed duty","মিলে যাওয়া নগদ গণনা যাচাই করে দায়িত্ব বন্ধ করেছি")}/></datalist></label><label className="sm:col-span-2"><input disabled={pending} type="checkbox" required/> {t("I verified the account, person and actual money.","হিসাব, ব্যক্তি ও প্রকৃত টাকা যাচাই করেছি।")}</label><div className="flex gap-4 sm:col-span-2"><button disabled={pending} aria-busy={pending} className="rounded-lg bg-primary p-3 text-primary-foreground">{pending?t("Saving…","সংরক্ষণ হচ্ছে…"):t("Save","সংরক্ষণ")}</button><button disabled={pending} type="button" onClick={()=>setPanel(null)}>{t("Cancel","বাতিল")}</button></div></form>}
 <div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr>{[t("Counter / cash account","কাউন্টার / নগদ হিসাব"),t("Duty and opening money","দায়িত্ব ও প্রারম্ভিক টাকা"),t("Status / actions","অবস্থা / পদক্ষেপ")].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{data.records.map(c=>{const shift=c.shifts.find(s=>!s.closed_at);return <tr key={c.id} className="border-t align-top"><td className="p-3"><strong>{c.name}</strong><p>{c.account}</p>{pendingCounterIds.includes(c.id)&&<p className="text-amber-600">{t("Additional cash receipt pending — transactions paused","অতিরিক্ত নগদ গ্রহণ বাকি — লেনদেন বন্ধ")}</p>}<CounterHistoryPanel counter={c.id}/></td><td className="p-3">{shift?<><p>{shift.cashier} · {shift.work_date}</p><p>{t("Opening","প্রারম্ভিক")}: {shift.opening_balance.toFixed(2)} · {t("Added","যোগ")}: {shift.float_amount.toFixed(2)}</p><p className={shift.outcome==="RECEIVED"?"text-emerald-600":"text-amber-600"}>{shift.outcome??t("Awaiting receipt","গ্রহণের অপেক্ষায়")}</p>{shift.can_receive&&<button disabled={pending} className="underline" onClick={()=>choose({action:"RECEIVE",shift})}>{t("Count / receive","গণনা / গ্রহণ")}</button>}</>:t("No open duty","চালু দায়িত্ব নেই")}</td><td className="space-y-3 p-3"><p>{c.is_active?t("Active","সক্রিয়"):t("Inactive","নিষ্ক্রিয়")}</p>{data.manager&&<>{onTransfer&&shift?.outcome==="RECEIVED"&&!pendingCounterIds.includes(c.id)&&<button disabled={pending} className="mr-3 underline" onClick={()=>{setPanel(null);onTransfer("TOPUP",c);}}>{t("Add cash","নগদ যোগ")}</button>}{onTransfer&&!shift&&c.shifts.length>0&&(!returnCounterIds||returnCounterIds.includes(c.id))&&<button disabled={pending} className="mr-3 underline" onClick={()=>{setPanel(null);onTransfer("RETURN",c);}}>{t("Return / deposit cash","নগদ ফেরত / জমা")}</button>}<button disabled={pending} className="mr-3 underline" onClick={()=>choose({action:"EDIT",counter:c})}>{t("Edit / status","সম্পাদনা / অবস্থা")}</button>{c.is_active&&!shift&&<button disabled={pending} className="underline" onClick={()=>choose({action:"OPEN",counter:c})}>{t("Assign / open duty","দায়িত্ব / শুরু")}</button>}{shift&&<button disabled={pending} className="underline" onClick={()=>choose({action:"CLOSE",counter:c})}>{t("Close reconciled duty","মিলে যাওয়া দায়িত্ব বন্ধ")}</button>}</>}</td></tr>;})}</tbody></table>{!data.records.length&&<p className="p-4">{t("No cash counters available.","কোনো নগদ কাউন্টার নেই।")}</p>}</div><nav className="flex gap-4">{page>1&&<Link href={`?page=${page-1}`}>{t("Previous","পেছনে")}</Link>}{page*25<data.total&&<Link href={`?page=${page+1}`}>{t("Next","পরবর্তী")}</Link>}<span>{data.total} {t("counters","কাউন্টার")}</span></nav></div>;
}
