"use client";
import Link from "next/link";
import {useEffect,useRef,useState,useTransition} from "react";
import {useLanguage} from "@/components/providers/language-provider";
import {CounterRegister} from "./register";
import {counterTransferAction} from "./transfer-actions";
import type {CounterData} from "./queries";
import type {TransferData} from "./transfer-queries";
const cls="mt-1 block w-full rounded-lg border bg-background p-2";
type Panel={action:"TOPUP"|"RETURN"|"RECEIVE";counter?:CounterData["records"][number];transfer?:TransferData["records"][number]};
export function CounterWorkspace({data,transfers,page,transfersPage,pendingOnly=false,resumeCloseId,resumeReturnId,actorId}:{data:CounterData;transfers:TransferData;page:number;transfersPage:number;pendingOnly?:boolean;resumeCloseId?:string;resumeReturnId?:string;actorId:string}){
 const {locale}=useLanguage(),t=(en:string,bn:string)=>locale==="bn"?bn:en;
 const [panel,setPanel]=useState<Panel|null>(()=>{const c=data.records.find(x=>x.id===resumeReturnId);return c&&data.manager?{action:"RETURN",counter:c}:null;}),[pending,start]=useTransition(),[message,setMessage]=useState("");const retry=useRef({signature:"",id:""}),formRef=useRef<HTMLFormElement>(null);
 useEffect(()=>{if(panel)formRef.current?.scrollIntoView({behavior:"smooth",block:"start"});},[panel]);
 function draftKey(counterId:string){return `erp:counter-return:${actorId}:${counterId}`;}
 useEffect(()=>{if(panel?.action!=="RETURN"||panel.counter?.id!==resumeReturnId||!formRef.current)return;try{const raw=sessionStorage.getItem(draftKey(panel.counter!.id));if(!raw)return;const draft=JSON.parse(raw) as Record<string,unknown>;for(const key of ["amount","account_id","reference","reason"]){const field=formRef.current.elements.namedItem(key);if(typeof draft[key]==="string"&&(field instanceof HTMLInputElement||field instanceof HTMLSelectElement))field.value=draft[key] as string;}}catch{/* Storage is optional; never post a draft automatically. */}},[panel,resumeReturnId,actorId]);
 function saveReturnDraft(){if(panel?.action!=="RETURN"||!formRef.current)return;const form=new FormData(formRef.current),draft:Record<string,string>={};for(const key of ["amount","account_id","reference","reason"])draft[key]=String(form.get(key)??"");try{sessionStorage.setItem(draftKey(panel.counter!.id),JSON.stringify(draft));}catch{}}
 function choose(p:Panel){setPanel(p);setMessage("");retry.current={signature:"",id:""};}
 const balance=panel?.counter?transfers.balances.find(x=>x.id===panel.counter!.id)?.amount??0:0;
 return <div className="space-y-6"><CounterRegister data={data} page={page} resumeCloseId={resumeCloseId} pendingCounterIds={transfers.pendingCounterIds} returnCounterIds={transfers.balances.filter(x=>x.amount>0).map(x=>x.id)} onAction={()=>setPanel(null)} foreignPanelOpen={panel!==null} onTransfer={(action,counter)=>choose({action,counter})}/>
 {message&&<p role="status" className="rounded-xl border p-3">{message}</p>}
 {panel&&<form ref={formRef} key={`${panel.action}:${panel.counter?.id??panel.transfer?.id}`} className="grid scroll-mt-24 gap-4 rounded-xl border bg-card p-5 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const values:Record<string,unknown>={action:panel.action,amount:Number(f.get("amount")),reason:String(f.get("reason"))};if(panel.action==="RECEIVE"){values.transfer_id=panel.transfer!.id;values.outcome=f.get("outcome");}else{values.counter_id=panel.counter!.id;values.other_account_id=f.get("account_id");values.reference=String(f.get("reference"));values.actual_confirmed=f.get("actual_confirmed")==="on";if(panel.action==="RETURN")values.close_id=f.get("close_id");}const signature=JSON.stringify(values);if(retry.current.signature!==signature)retry.current={signature,id:crypto.randomUUID()};start(async()=>{const r=await counterTransferAction({...values,request_id:retry.current.id});setMessage(r.ok?t("Transfer evidence saved.","স্থানান্তরের প্রমাণ সংরক্ষিত হয়েছে।"):r.message);if(r.ok){if(panel.action==="RETURN")try{sessionStorage.removeItem(draftKey(panel.counter!.id));}catch{}setPanel(null);retry.current={signature:"",id:""};}});}}>
 <h2 className="font-semibold sm:col-span-2">{panel.counter?.name??panel.transfer?.counter} · {panel.action==="TOPUP"?t("Add cash during duty","চালু দায়িত্বে নগদ যোগ"):panel.action==="RETURN"?t("Return/deposit actual cash","প্রকৃত নগদ ফেরত / জমা"):t("Receive additional cash","অতিরিক্ত নগদ গ্রহণ")}</h2>
 <p className="text-sm text-muted-foreground sm:col-span-2">{panel.action==="RECEIVE"?t(`Count only this delivery of BDT ${panel.transfer!.amount.toFixed(2)}, not the whole counter balance.`, `শুধু এই ${panel.transfer!.amount.toFixed(2)} টাকার সরবরাহ গুনুন; পুরো কাউন্টারের স্থিতি নয়।`):t(`Counter ledger balance: BDT ${balance.toFixed(2)}. Transfer only money actually delivered/received; this does not create income or expense.`,`কাউন্টারের হিসাবভুক্ত স্থিতি: ${balance.toFixed(2)} টাকা। শুধু প্রকৃত দেওয়া/পাওয়া টাকা স্থানান্তর করুন; এতে আয় বা ব্যয় তৈরি হয় না।`)}</p>
 <label>{panel.action==="RECEIVE"?t("Actual received count","প্রকৃত গ্রহণের গণনা"):t("Actual transfer amount (BDT)","প্রকৃত স্থানান্তরের অঙ্ক (টাকা)")}<input disabled={pending} className={cls} type="number" name="amount" min={panel.action==="RECEIVE"?0:0.01} max={panel.action==="RETURN"?balance:undefined} step="0.01" required defaultValue={panel.action==="RECEIVE"?panel.transfer!.amount:panel.action==="RETURN"?balance:undefined}/></label>
 {panel.action==="RECEIVE"?<label>{t("Outcome","ফলাফল")}<select disabled={pending} className={cls} name="outcome"><option value="RECEIVED">{t("Received — count matches","গ্রহণ করেছি — গণনা মিলেছে")}</option><option value="DISPUTED">{t("Disputed — requires investigation","অমিল — তদন্ত প্রয়োজন")}</option></select></label>:<><label>{panel.action==="TOPUP"?t("Funded source account","টাকা থাকা উৎস হিসাব"):t("Main receiving/deposit account","মূল গ্রহণ / জমার হিসাব")}<select disabled={pending} className={cls} name="account_id" required><option value="">{t("Choose…","নির্বাচন করুন…")}</option>{data.accounts.filter(a=>!a.registered&&a.id!==panel.counter!.account_id).map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>{t("Unique receipt / deposit reference","স্বতন্ত্র গ্রহণ / জমার রেফারেন্স")}<input disabled={pending} name="reference" className={cls} required minLength={3} maxLength={120}/></label><label className="sm:col-span-2"><input disabled={pending} type="checkbox" name="actual_confirmed" required/> {t("The money was physically delivered/received or the deposit was verified.","টাকা বাস্তবে দেওয়া/পাওয়া হয়েছে অথবা জমা যাচাই করেছি।")}</label></>}
 {panel.action==="RETURN"&&<><Link onClick={saveReturnDraft} className="underline sm:col-span-2" href={`/dashboard/finance/daily-close?accountId=${panel.counter!.account_id}&returnTo=${encodeURIComponent(`/dashboard/finance/counters?cashReturn=${panel.counter!.id}&page=${page}&transfersPage=${transfersPage}`)}`}>{t("Count current cash and return to this form","বর্তমান নগদ গুনে এই ফর্মে ফিরুন")}</Link><label>{t("Fresh matching count evidence","নতুন মিলে যাওয়া গণনার প্রমাণ")}<select disabled={pending} name="close_id" className={cls} required><option value="">{t("Choose…","নির্বাচন করুন…")}</option>{panel.counter!.counts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></>}
 <label className="sm:col-span-2">{t("Verification / reason","যাচাই / কারণ")}<input disabled={pending} className={cls} name="reason" minLength={5} maxLength={1000} required list="counter-transfer-reasons"/><datalist id="counter-transfer-reasons"><option value={t("Verified additional cash delivery to assigned cashier","নির্ধারিত কর্মীর অতিরিক্ত নগদ সরবরাহ যাচাই করেছি")}/><option value={t("Counted and received all additional cash","সব অতিরিক্ত নগদ গুনে গ্রহণ করেছি")}/><option value={t("Reconciled counter cash and verified main-account receipt","কাউন্টারের নগদ মিলিয়ে মূল হিসাবে গ্রহণ যাচাই করেছি")}/></datalist></label><div className="flex gap-4 sm:col-span-2"><button disabled={pending} aria-busy={pending} className="rounded-lg bg-primary p-3 text-primary-foreground">{pending?t("Saving…","সংরক্ষণ হচ্ছে…"):t("Save transfer evidence","স্থানান্তরের প্রমাণ সংরক্ষণ")}</button><button disabled={pending} type="button" onClick={()=>setPanel(null)}>{t("Cancel","বাতিল")}</button></div></form>}
 <section id="counter-transfers" className="scroll-mt-24 space-y-3"><div className="flex gap-4"><Link className={!pendingOnly?"font-semibold underline":"underline"} href={`?page=${page}&transfersPage=1#counter-transfers`}>{t("All transfers","সকল স্থানান্তর")}</Link><Link className={pendingOnly?"font-semibold underline":"underline"} href={`?page=${page}&transfersPage=1&pending=1#counter-transfers`}>{t("Awaiting receipt / disputed","গ্রহণ বাকি / অমিল")}</Link></div><h2 className="text-lg font-semibold">{t("Cash top-ups and returns","অতিরিক্ত নগদ ও ফেরতের ইতিহাস")}</h2><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr>{[t("Counter / time","কাউন্টার / সময়"),t("Transfer","স্থানান্তর"),t("Evidence","প্রমাণ"),t("Status / action","অবস্থা / পদক্ষেপ")].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{transfers.records.map(r=><tr key={r.id} className="border-t align-top"><td className="p-3">{r.counter}<p>{new Date(r.created_at).toLocaleString(locale==="bn"?"bn-BD":"en-BD",{timeZone:"Asia/Dhaka"})}</p><p>{r.cashier}</p></td><td className="p-3">{r.kind==="TOPUP"?t("Additional cash","অতিরিক্ত নগদ"):t("Cash returned","নগদ ফেরত")} · {r.amount.toFixed(2)}<p>{r.source} → {r.destination}</p></td><td className="p-3">{r.reference}<p>{r.actor} · {r.reason}</p><details><summary className="cursor-pointer">{t("Receipt history","গ্রহণের ইতিহাস")}</summary>{r.receipts.map((x,i)=><p key={i}>{x.outcome} · {x.amount.toFixed(2)} · {x.note}</p>)}</details></td><td className="p-3"><p className={["RECEIVED","RETURNED"].includes(r.outcome)?"text-emerald-600":"text-amber-600"}>{r.outcome==="RECEIVED"?t("Received","গৃহীত"):r.outcome==="RETURNED"?t("Returned / deposited","ফেরত / জমা হয়েছে"):r.outcome==="DISPUTED"?t("Disputed","অমিল"):t("Awaiting receipt","গ্রহণের অপেক্ষায়")}</p>{r.can_receive&&<button disabled={pending} className="underline" onClick={()=>choose({action:"RECEIVE",transfer:r})}>{t("Count / receive","গণনা / গ্রহণ")}</button>}</td></tr>)}</tbody></table>{!transfers.records.length&&<p className="p-4">{t("No top-up or return recorded yet.","অতিরিক্ত টাকা বা ফেরতের রেকর্ড নেই।")}</p>}</div><nav className="flex gap-4">{transfersPage>1&&<Link href={`?page=${page}&transfersPage=${transfersPage-1}${pendingOnly?"&pending=1":""}#counter-transfers`}>{t("Previous transfers","আগের স্থানান্তর")}</Link>}{transfersPage*25<transfers.total&&<Link href={`?page=${page}&transfersPage=${transfersPage+1}${pendingOnly?"&pending=1":""}#counter-transfers`}>{t("Next transfers","পরের স্থানান্তর")}</Link>}<span>{transfers.total} {t("records","রেকর্ড")}</span></nav></section></div>;
}
