"use client";
import { useRef,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { collectStudentPayment } from "./collection-actions";
import { finishWorkflow } from "@/modules/platform/navigation/workflow-return";
export function CollectionForm({admissionId,invoiceId,due,methods}:{admissionId:string;invoiceId:string;due:number;methods:{id:string;name:string}[]}){
 const router=useRouter();const [message,setMessage]=useState(""),[adjustment,setAdjustment]=useState(0),[received,setReceived]=useState(0),[pending,start]=useTransition();const request=useRef<{signature:string;id:string}|null>(null);
 return <details className="rounded-xl border p-4" data-action-panel><summary className="cursor-pointer font-semibold">Collect payment / give discount or scholarship</summary><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const values={admission_id:admissionId,invoice_id:invoiceId,amount:received,payment_method_id:String(f.get("method")??"")||undefined,external_reference:String(f.get("reference")??""),adjustment_amount:adjustment,adjustment_category:String(f.get("category")) as "DISCOUNT"|"SCHOLARSHIP",adjustment_reason:String(f.get("adjustment_reason")??""),reason:"Recorded verified student collection and fee adjustment"};const signature=JSON.stringify(values);if(request.current?.signature!==signature)request.current={signature,id:crypto.randomUUID()};start(async()=>{try{const r=await collectStudentPayment({...values,request_id:request.current!.id});setMessage(r.message);if(r.ok){request.current=null;setReceived(0);setAdjustment(0);finishWorkflow(router);}}catch{setMessage("Connection interrupted. Reload the account before retrying; a payment may already have saved.");}});}}>
 <p className="text-sm text-muted-foreground sm:col-span-2">Current due: BDT {due.toFixed(2)}. Reductions apply to this invoice's unpaid tuition only, within the operating rule limits.</p>
 <label className="text-sm">Discount / scholarship amount (BDT)<input type="number" min="0" step="0.01" max={due} value={adjustment} onChange={e=>setAdjustment(Number(e.target.value))} className="mt-1 w-full rounded border bg-background p-3"/></label>
 <label className="text-sm">Reduction type<select name="category" className="mt-1 w-full rounded border bg-background p-3"><option value="DISCOUNT">Discount</option><option value="SCHOLARSHIP">Scholarship</option></select></label>
 {adjustment>0&&<label className="text-sm sm:col-span-2">Why granted?<input name="adjustment_reason" required minLength={5} className="mt-1 w-full rounded border bg-background p-3" list={`discount-reasons-${invoiceId}`}/><datalist id={`discount-reasons-${invoiceId}`}><option value="Verified financial hardship"/><option value="Awarded merit scholarship"/><option value="Verified sibling discount"/><option value="Authorized student support"/></datalist></label>}
 <label className="text-sm">Money actually received (BDT)<input type="number" min="0" step="0.01" max={Math.max(due-adjustment,0)} value={received} onChange={e=>setReceived(Number(e.target.value))} className="mt-1 w-full rounded border bg-background p-3"/></label>
 <label className="text-sm">Payment method<select name="method" required={received>0} className="mt-1 w-full rounded border bg-background p-3"><option value="">No money received</option>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>
 <label className="text-sm sm:col-span-2">Paper receipt / transaction reference (optional)<input name="reference" maxLength={120} className="mt-1 w-full rounded border bg-background p-3"/></label>
 <p className="text-sm sm:col-span-2">After reduction and this payment, due: BDT {Math.max(due-adjustment-received,0).toFixed(2)}. A receipt is issued only for money received.</p>
 {message&&<p role="status" className="sm:col-span-2">{message}</p>}<button disabled={pending||(received===0&&adjustment===0)} aria-busy={pending} className="rounded-lg bg-primary px-4 py-3 text-primary-foreground disabled:opacity-50">{pending?"Recording…":"Reviewed — save collection / adjustment"}</button>
 </form></details>;
}
